### ISSUE TITLE
German Landing page advertises 4.0 as the next big thing

### ISSUE THREAD

**Issue by martrapp** [withastro/docs#10066]
### 📚 Subject area/topic

Banner at the top of the landing page

### 📋 Page(s) affected (or suggested, for new content)

https://docs.astro.build/de/getting-started/

### 📋 Description of content that is out-of-date or incorrect

![image](https://github.com/user-attachments/assets/a688555f-fdf0-476a-9eaf-e0d7288b4db3)
Other languages favor 5.0 ;-)

**Comment by ArmandPhilippot** [comment]
v4 is also advertised on:
* [Italian version](https://docs.astro.build/it/getting-started/)
* [Russian version](https://docs.astro.build/ru/getting-started/)
* [Japanese version](https://docs.astro.build/ja/getting-started/)

I don't know if we should just remove the banner using `i18nIgnore` or if we have active contributors available to update those pages (maybe @trueberryless for the german version, if you have time).

**Comment by trueberryless** [comment]
Sure, I'll update the german version right away!👍

**Comment by trueberryless** [comment]
German version PR done, thanks for pinging me and giving me the chance @ArmandPhilippot !

**Comment by sarah11918** [comment]
Welp... v4 docs are what they are now. 😅 

No worries, we'll have a shiny new banner advertising v5 soon enough!

We're going to be doing "let's find all the outdated pages" tomorrow on Talking and Doc'ing, AND we'll be doing v5 prep like landing page banners, so this should get taken care of tomorrow! Thank you for flagging, Martin!

**Comment by trueberryless** [comment]
> We're going to be doing "let's find all the outdated pages" tomorrow on Talking and Doc'ing, AND we'll be doing v5 prep like landing page banners, so this should get taken care of tomorrow! Thank you for flagging, Martin!

Unfortunately I won't be there, but you could use Yan's new script for finding the outdated pages: https://github.com/withastro/docs/pull/10111

I looked into it and it is awesome🎉
