### ISSUE TITLE
Move our community recipes to Astro Tips!

### ISSUE THREAD

**Issue by sarah11918** [withastro/docs#10092]
### 📋 Explain your issue

Some great first PRs available here!

The task is to go through every [community recipe link in Astro Docs](https://docs.astro.build/en/community-resources/content/#recipes-and-guides) and, if it's still working/valid, then submit it to the [Astro Tips `resources` collection](https://github.com/astrolicious/astro-tips.dev/tree/main/src/content/resources) so that these show up on [their fancy external resources tips page](https://astro-tips.dev/external-resources/)!

Steps:

1. Choose a link in the list of [external community recipes in Astro Docs](https://docs.astro.build/en/community-resources/content/#recipes-and-guides).
2. Verify it doesn't already exist in the [Astro Tips external resources collection](https://astro-tips.dev/external-resources/)
3. Verify the link still works and the content looks helpful. (No need to go through the entire recipe yourself, just use your best judgement as to whether you think it looks like a resource that could help someone.) This will be a judgment call, and some posts there may seem quite out of date/unhelpful (e.g. a resource for setting up old, legacy content collections). Only continue with posts you believe are still helpful/relevant.
4. Make a PR to Astro Tips to [add a `.json` collection entry to the `resources` collection](https://github.com/astrolicious/astro-tips.dev/tree/main/src/content/resources) for this link, following their format, like this example:

```
{
  "tags": ["images"],
  "title": "Astro + PhotoSwipe",
  "link": "https://dev.to/petrovicz/astro-photoswipe-549a",
  "updated": "2024-04-04"
}
```

**BONUS:** Don't stop there!!

1. We also have A TON of content posted in our monthly showcase roundup blog posts that have never been added as tips /recipes anywhere!! We would also welcome you finding and adding any appropriate content from these 13 Astro blog posts, ([Oct 2023](https://astro.build/blog/whats-new-october-2023/)  through to [October 2024](https://astro.build/blog/whats-new-october-2024/) with November coming up soon...) which are all of the URL format `https://astro.build/blog/whats-new-october-2023/`

2. Anything you wrote, or read, that you think belongs there!

I'm sure it's fine to add multiple files in the same PR, but please do communicate/check carefully in case several people are adding files at the same time. For example, you might choose to leave a comment here saying, "I'll do all the Astro DB links!" or "I did all the Astro DB links!" to help avoid duplicate work.

Thanks to anyone who wants to get involved, and I'll close this issue when I'm confident that all links that should be submitted to Astro Tips have been completed!

**Comment by leabs** [comment]
I'll do AOS!

**Comment by Newman5** [comment]
I'll take the RSS section - https://docs.astro.build/en/community-resources/content/#rss

**Comment by hkbertoson** [comment]
Ill do Markdown. https://docs.astro.build/en/community-resources/content/#markdown

Sections remaining
CSS
Authentication
~~RSS~~
Images
Editor Tooling
Markdown
Performance
Utilities
Animation
Internationalization and Localization
Astro DB
API Endpoints

**Comment by Newman5** [comment]
I'll do Astro DB and API Endpoints

**Comment by Newman5** [comment]
I'll do CSS - https://docs.astro.build/en/community-resources/content/#css

and Authentication


Sections remaining

~~CSS~~
Authentication

Images
Editor Tooling

Performance
Utilities
Animation
Internationalization and Localization

**Comment by sarah11918** [comment]
> NO Sections remaining. All Done.

I leave you alone for a couple of days and this happens??!?!

Wonderful job everyone, especially @Newman5 ! Really appreciate everyone helping out!
