### ISSUE TITLE
Expand styling guide in Components

### ISSUE THREAD

**Issue by lostra01** [withastro/docs#1012]
When using `define:vars` in a `<style>` tag for a component that is re-used on a page multiple times, the different variables of the components will be overwritten with the last component's variables.

`styled.astro`
```jsx
---
const { background } = Astro.props;
---

<div class="styled"></div>

<style define:vars={{background}}>
    .styled {
        height: 40px;
        width: 40px;
        background-color: var(--background);
    }
</style>
```

`index.astro`
```jsx
---
import StyledComponent from './styled.astro';
---

<StyledComponent background="blue" />
<StyledComponent background="red" />
<StyledComponent background="green" />
```

In the example above, all the components end up being green.

The documentation needs to be updated to explicitly state that `define:vars` will be overwritten if the component is re-used on the same page.

The documentation also needs to be updated to provide examples on how to go around this default functionality and let users re-use the same component multiple times with different styling.

I will gladly update the documentation and provide such examples. Creating the issue to see if the direction we should go in is common.

@sarah11918 @delucis

**Comment by sarah11918** [comment]
Thanks @lostra01 , my first thought is: I know in the past (admittedly, maybe long ago past!) we had *other* situations where if you had multiple components (even without `define:vars`), they would all end up using the same attribute props.

So firstly, can you give a quick thought or a quick play with some code  to see whether this is not *exclusively* a `define:vars` issue, (even if it is a `define:vars` issue). Can you find any other common situation in which this is happening? If there are n situations where reusing a component with different props is going to cause them all to just use the last one's props, I'd rather document *that* behaviour as a thing itself to wach out for, and this is one example of that.

I also do think this *might* be verging on something for the troubleshooting page, leaving a link on the main Docs page which is mostly to show basic usage and not things that are closer to edge cases, or behaviours that might later be fixed/changed. I don't know yet.

Don't get me wrong, I think wanting to reuse multiple components with different props is common enough for this not to be as rare as an "edge case" for sure! But depending on how much "screen real estate" it takes to both explain the problem and show a "workaround," and whether or not this is behaviour that might eventually be fixed at the code level, I *might* prefer a link to something in Troubleshooting. I'll probably "know it when I see it!"  😉
