### ISSUE TITLE
Update recipes/dynamically-importing-images/ to Astro 5

### ISSUE THREAD

**Issue by tordans** [withastro/docs#10141]
I am using the technique described in https://docs.astro.build/en/recipes/dynamically-importing-images/ with Keystatic (following the Keystatic guide https://keystatic.com/docs/recipes/astro-images).

With Astro 5, I am getting the `MissingImageDimension` https://docs.astro.build/en/reference/errors/missing-image-dimension/ error. However, when I add `inferSize` I get a type error

```ts
Type '{ class: string; src: Promise<{ default: ImageMetadata; }>; alt: string; loading: "lazy"; inferSize: true; }' is not assignable to type 'IntrinsicAttributes & Props'.
  Types of property 'src' are incompatible.ts(2322)
```

I consider the technique in this guide to be equal to importing images from source.
In this mindset I expect this to work without explicit width/height.
It did in Astro 4, it is broken in Astro 5.

**Comment by sarah11918** [comment]
Thanks! Just checking whether this is a *docs* issue (docs need to be updated) or whether this is a bug that was introduced.

cc @Princesseuh @ascorbic

**Comment by Princesseuh** [comment]
Hard to say without seeing your code. do you have a reproduction?

**Comment by tordans** [comment]
Thanks a lot for the quick input!
I am still debugging and working on a reproduction. But will close for now because it looks like the issue is something else. Will open if it is indeed this topic, but it looks like that is working as before.
