### ISSUE TITLE
Welcome Component still links to /blog/astro-5-beta/ instead of /blog/astro-5/

### ISSUE THREAD

**Issue by idkgene** [withastro/docs#10150]
### 📚 Subject area/topic

Create Astro App

### 📋 Page(s) affected (or suggested, for new content)

[Astro 5 Beta Page](https://astro.build/blog/astro-5-beta/) & [Astro 5 Page](https://astro.build/blog/astro-5/)

### 📋 Description of content that is out-of-date or incorrect

Welcome Component still links to /astro-5-beta and should(?) link to /astro-5

### 🖥️ Reproduction in StackBlitz (if reporting incorrect content or code samples)

I think video would be faster, yet if needed I can make a SB repro (I hope I created the issue in the right place, sorry in advance). 

I guess this component not working as expected (https://github.com/withastro/astro/blob/52c8f98b749550ee47536ad2d55163456a644ca6/examples/basics/src/components/Welcome.astro)

https://github.com/user-attachments/assets/44b82430-490d-4771-974e-f03a5124ba66

**Comment by TheOtterlord** [comment]
Thanks for letting us know. The link has been updated, but our examples didn't sync :sweat_smile: This should be fixed shortly
