### ISSUE TITLE
Using Zod's `refine` with `image()` for content collections

### ISSUE THREAD

**Issue by ArmandPhilippot** [withastro/docs#10151]
### 📚 Subject area/topic

Guides

### 📋 Page(s) affected (or suggested, for new content)

https://docs.astro.build/en/guides/content-collections/#zod-schema-methods
https://docs.astro.build/en/guides/images/#images-in-content-collections

### 📋 Description of content that is out-of-date or incorrect

We have two contradictory pages about the use of `refine()` with `image()` while using content collections.

* In the Content Collections guide, we say that we can't use `refine()` with `image()`
```
Notably, performing custom validation checks on images using image().refine() is unsupported.
```
* In images we show an example using `refine()` with `image()`
```
    cover: image().refine((img) => img.width >= 1080, {
      message: "Cover image must be at least 1080 pixels wide!",
    }),
```

Which one is correct?

We currently have two users on Discord trying to use that:
* https://discord.com/channels/830184174198718474/830184175176122389/1313605574856015933
* https://discord.com/channels/830184174198718474/1313516892027093082

And it seems that doesn't work. So I guess the Content Collections guide is correct, but I'd like a confirmation before making any update.

**Comment by sarah11918** [comment]
I believe it's correct that it's NOT supported. Platform was in fact discussing this today. 

So, let's update the examples to not show using it!

**Comment by ArmandPhilippot** [comment]
I was going to say that maybe this should be mentioned in the v5 upgrade guide, but [it already is](https://docs.astro.build/en/guides/upgrade-to/v5/#breaking-changes-to-legacy-content-and-data-collections):
```
image().refine() is not supported. If you need to validate the properties of an image you will need to do this at runtime in your page or component.
```
I should have checked there. Thanks for the confirmation! I'm going to update the example.
