### ISSUE TITLE
Show how to resolved the "A dynamic SSR route cannot be defined more than once." warning

### ISSUE THREAD

**Issue by tordans** [withastro/docs#10168]
### 📚 Subject area/topic

SSR Dynamic Routes

### 📋 Suggested page

https://docs.astro.build/en/guides/routing/#dynamic-routes

### 📋 General description or bullet points (if proposing new content)

With Astro 5, I am getting this warning
```
09:52:13 [WARN] [router] The route "/massnahmen/[slug]" is defined in both "src/pages/massnahmen/[slug].astro" and "src/pages/massnahmen/[townslug].astro" using SSR mode. A dynamic SSR route cannot be defined more than once.
09:52:13 [WARN] [router] A collision will result in an hard error in following versions of Astro.
```

I am looking for docs that explain the recommended way to work around this issue.

I only found this workaround from 2022 https://github.com/withastro/astro/issues/3621 which would still work, I guess, but I am hoping for something more build in than that…

### 🖥️ Reproduction of code samples in StackBlitz

I have two collection that have different schema and render different pages.
Up until Astro 4 this worked perfectly fine…
- https://github.com/FixMyBerlin/nudafa/blob/main/src/pages/massnahmen/%5Btownslug%5D.astro#L10-L16
- https://github.com/FixMyBerlin/nudafa/blob/main/src/pages/massnahmen/%5Bslug%5D.astro#L14-L20

TBH, I don't quite get why Astro would prevent me from doing this. With Collections, I can make sure that content is well defined. I would understand a build error that throws if in fact one route overwrites a existing file… but why make us use workarounds like https://github.com/withastro/astro/issues/3621 which only make our pages-components-structure more complex.

**Comment by sarah11918** [comment]
Hi! The section that describes this behaviour is the [Route Priority Order](https://docs.astro.build/en/guides/routing/#route-priority-order) docs, which did [have some changes to it in v5](/en/guides/upgrade-to/v5/#route-priority-order-for-injected-routes-and-redirects) and might be causing the different behaviour in your project.

As you can see from Matthew's response in the issue linked, this is the use we support, and we have recently updated this feature and documentation to align with the new supported use. So I'm closing this as not a documentation issue because our documentation is current and aligns with specific design choices that have recently been made, and the use we support. It's unfortunately not supported to have two files such as the ones you linked that would cause a route collision, and some other design choice would be necessary. How different people might choose to resolve that is up to them, but we do document that this would occur, and we have a warning that explains that this is a problem. But if you'd like to propose that something should work differently, you can leave feedback in the Discord feedback channel or use the Roadmap RFC process!

**Comment by tordans** [comment]
@sarah11918 could you reopen this because there are some things not aligned:

**Docs https://docs.astro.build/en/guides/routing/#route-priority-order are IMO outdated**

The docs at https://docs.astro.build/en/guides/routing/#route-priority-order explain that multiple routes can create the same page … and which page "wins". BUT https://docs.astro.build/en/guides/upgrade-to/v5/#route-priority-order-for-injected-routes-and-redirects and the error I linked shows a warning in those cases
> In the event of route collisions, where two routes of equal route priority attempt to build the same URL, Astro will log a warning identifying the conflicting routes.

=> I think https://docs.astro.build/en/guides/routing/#route-priority-order need to be updated to Astro 5 to show that this is now a "Warning" case in some situations and will be an error case in Astro 6.

Right now the docs sound like "this is a fine and solved, you just need to know what you are doing".

**Add a link to the error message**

With https://docs.astro.build/en/guides/routing/#route-priority-order being updated, this page could be used to guide users from the error message to somewhere to learn more.

> …
> 09:52:13 [WARN] [router] A collision will result in an hard error in following versions of Astro. Learn more https://docs.astro.build/en/guides/routing/#route-priority-order

**Workaround undocumented**

The workaround documented at https://github.com/withastro/astro/issues/3621#issuecomment-1160578639 is IMO out of date or at least not ideal for content collections. The custom `props: 'page'` is not needed because any collection will provide it's own `collection` property automatically. Below is the code I am using ATM.

> How different people might choose to resolve that is up to them

I have to say I was hoping for a more open response here. You are changing the way things work with the warning and you are planning on making it an error. The Astro docs do such a great job to guide users to good solutions for certain issues that it feels wrong to leave them alone with this. Well, at least we have the code documented here, now, for users to maybe find…


```astro
---
export const prerender = true

import PageMassnahmenMeasure from '@components/page_massnahmen/PageMassnahmenMeasure.astro'
import PageMassnahmenMeasuretown from '@components/page_massnahmen/PageMassnahmenMeasuretown.astro'
import { getCollection, type CollectionEntry } from 'astro:content'

type Page = {
  params: { slug: string }
  props: CollectionEntry<'measures'> | CollectionEntry<'measuretowns'>
}

export async function getStaticPaths() {
  const pages: Page[] = []

  const measures = await getCollection('measures')
  measures.forEach((entry) =>
    pages.push({
      params: { slug: entry.id },
      props: entry,
    }),
  )

  const towns = await getCollection('measuretowns')
  towns.forEach((entry) =>
    pages.push({
      params: { slug: entry.id },
      props: entry,
    }),
  )

  return pages
}

type Props = Page['props']
const { collection } = Astro.props
---

{collection === 'measures' ? <PageMassnahmenMeasure {...Astro.props} /> : null}
{collection === 'measuretowns' ? <PageMassnahmenMeasuretown {...Astro.props} /> : null}
```
