### ISSUE TITLE
Add additional (optional) step for GitHub Pages deployment on custom domain

### ISSUE THREAD

**Issue by JulianCataldo** [withastro/docs#1016]
# Possible improvement

[For GH Pages doc'](https://docs.astro.build/en/guides/deploy/github/)

It might be beneficial for user to know how to set-up a custom domain, it's not totally obvious, and there are handful ways of doing this (I can detail others ways if required, it can be environment dependent).

The simplest one:  
`CNAME` file can be added in `./public` with
`sub.mydomain.com` as content.

That way, GH Pages action will detect it in root `./dist` after build, and will setup the correct custom destination domain. 
When setting this initially via web GUI, custom domain is reseted to default GH user domain (user.github.io) each time you deploy.  
The CNAME trick prevents this undesirable behavior, without touching to GH workflow or npm/node scripts.

**Comment by sarah11918** [comment]
Thanks for mentioning this, @JulianCataldo ! I know these GH Pages instructions have been a bit of a thorn in our sides for a while now... 

Would you like to make a PR for this? I do agree that in particular GH Pages isn't always intuitive for Astro projects, so I think this could be a helpful addition. And yes, let's go with the simplest one. 😉  

It doesn't have to be overly complicated. If you would like to PR just the basic steps or outline, we can always write from that to conform to the rest of docs style etc. if you make sure to check "allow Maintainers to make edits" and take the rest of the work off your hands.

**Comment by Pukimaa** [comment]
I also made a new comment on the PR #1110

**Comment by sarah11918** [comment]
Hm... this didn't seem to get closed with the merged PR! Thanks everyone for all the contributions to this issue and PR!  🥳
