### ISSUE TITLE
📘 DOC: Disable bundling hashes 

### ISSUE THREAD

**Issue by coelmay** [withastro/docs#102]
Under Styling & CSS [Bundling](https://docs.astro.build/en/guides/styling/#bundling) it mentions
> All styles are hashed according to their contents (the hashes only change if the contents do!)

This is (I presume) fine with most services. With Netlify as per [[Support Guide] Making the most of Netlify’s CDN cache](https://answers.netlify.com/t/support-guide-making-the-most-of-netlifys-cdn-cache/127) hashes break caching.
> Perhaps your build framework is trying to be helpful. Gatsby for instance uses asset fingerprinted filenames intentionally, which breaks Netlify’s usual caching.

In order to eliminate the hashes I did find it is possible to disable this via a setting in `vite.config.js` as originally read [here](https://github.com/vitejs/vite/issues/378#issuecomment-768816653) with official documentation [here](https://vitejs.dev/config/#build-rollupoptions)
```javascript
export default {
  build: {
    rollupOptions: {
      output: {
        // Disable hashes for CSS files.
        assetFileNames: `assets/[name].[ext]`
        // These may also work, though haven't tested
        // entryFileNames: `assets/[name].js`,
        // chunkFileNames: `assets/[name].js`,
      }
    }
  }
}
```
I can confirm the `assetFileNames` setting is honoured in Astro (unsure about the `entryFileNames` and `chunkFileNames` as I haven't a project to test these on currently) and think it worth adding this to official documentation for those who (like me) may wish to remove hashes.

**Comment by sarah11918** [comment]
@JuanM04 You seem like a person to ask about this! Would you consider this an issue that can be closed? Or, is there something about this you'd suggest working into the new docs with our new configuration? Maybe here? https://docs.astro.build/en/guides/styling/#advanced

**Comment by sarah11918** [comment]
Excellent, thanks for your feedback, @JuanM04 . I will close this issue as something not to include in the official docs.

@coelmay Perhaps this is something you'd be interested in writing about yourself, maybe a blog post!

**Comment by coelmay** [comment]
I've moved on from this. Happy to let this disappear into the great abyss that is the Internet.

**Comment by ADTC** [comment]
And in the great abyss of the internet, I have explored far and wide to find this gem!

Perhaps a nod to this issue in the docs wouldn't hurt. However, given that this is a Rollup configuration that's [well-documented in Rollup's docs](https://rollupjs.org/configuration-options/#output-assetfilenames), it's probably unnecessary.

You can also insert the Vite build options directly in `astro.config.mjs`. To maintain the same folder structure as Astro's default build process, use `_astro/` as the folder. (You can customize and use any folder name you like.)

```js
// @ts-check
import { defineConfig } from 'astro/config'

// https://astro.build/config
export default defineConfig({
  vite: {
    build: {
      rollupOptions: {
        output: {
          // Disable hashes for assets
          assetFileNames: `_astro/[name].[ext]`,
        },
        // ... other Rollup options
      },
    },
    // ... other Vite options
  },
  // ... other Astro options
})
```

**Note:** The image optimizer inserts its own hashes on the generated `.webp` files, which you will start to see in their filenames. This is a separate configuration issue in the optimizer and isn't related to Vite/Rollup configuration.

**Comment by ADTC** [comment]
> It seems like a edge case and something I wouldn't incentivice, because having different hashes for each build prevents a new deployment to accidentally have old code/styles

You never know when you will actually need this! We are apparently hit by a client with a very legacy system that has many restrictions and difficulties. I started the project in Astro but had to make many customizations in it to gel with the limitations of the legacy system, one of which being that all deployments are manual and previously deployed files cannot be deleted (do NOT ask me why! I don't know). This makes the hashes added at the end of asset files become a troublesome anomaly that must be removed, as the legacy system will get a pile up of old files with previous hashes instead of simply replacing the file (without hash) with a new version of it.

Remember, in my last comment I said that "The image optimizer inserts its own hashes"? I need to stop this behavior too! And I don't know how. @sarah11918
