### ISSUE TITLE
Motion.dev new JS API 

### ISSUE THREAD

**Issue by Dillonpw** [withastro/docs#10207]
### 📚 Subject area/topic

Guides and recipes

### 📋 Suggested page

https://docs.astro.build/en/recipes/

### 📋 General description or bullet points (if proposing new content)

I'm interested in putting together an example for how to use the new motion.dev javascript API with Astro. So far, the new API works seamlessly with Astro 5.0 and a quick guide with a few examples could be great for devs looking to add some animation to their projects beyond View Transitions.

**Comment by delucis** [comment]
On the whole we don’t add documentation for specific third-party libraries as it can be difficult for us to maintain — if things change in the third-party library, we may not notice, and the information can become out of date.

Would still love to read your guide though — maybe you could publish it as a blog post somewhere? Or propose it to https://astro-tips.dev/?

**Comment by sarah11918** [comment]
Hi @Dillonpw , that sounds great!

We do follow a specific format and writing style for our official recipes, so you should model it on the existing ones. And, we have some guidance on our contributing site about specific writing advice for docs, like [writing and annotating code samples](https://contribute.docs.astro.build/reference/code-samples/) and the [process for writing a recipe](https://contribute.docs.astro.build/guides/recipe-writing/).

I'm sure Astro Tips would also be interested, if you prefer to contribute there!
