### ISSUE TITLE
auth-astro instructions show using a .mjs

### ISSUE THREAD

**Issue by JusticeMatthew** [withastro/docs#10218]
### 📚 Subject area/topic

Guides

### 📋 Page(s) affected (or suggested, for new content)

https://docs.astro.build/en/guides/authentication/#configuration

### 📋 Description of content that is out-of-date or incorrect

The Astro docs show using a `.mjs` file for the auth config while the [official readme](https://github.com/nowaythatworked/auth-astro?tab=readme-ov-file#configuration) for the lib shows using a `.ts` file

This resulted in errors for a user of the library which can be found in [this support thread](https://discord.com/channels/830184174198718474/1314385854315368468/1314405117772173392) on the discord

**Comment by sarah11918** [comment]
This sounds like a simple PR fix to update the docs to me! Would happily accept a PR to match their own example!

**Comment by Kevin2606** [comment]
Hi! 👋 I’ve created a PR to address this issue: #10275 . Let me know if any changes are needed.
