### ISSUE TITLE
Reformat code samples on UI Frameworks page

### ISSUE THREAD

**Issue by sarah11918** [withastro/docs#1025]
On this page - https://docs.astro.build/en/core-concepts/framework-components/#passing-children-to-framework-components

The code samples don't conform to our standard syntax, so the Astro code highlighting isn't taking effect.

Please reformat these samples so that the file name is located **inside, and directly following the first `---`*** (to match the examples e.g. on https://docs.astro.build/en/core-concepts/astro-components/#slots) instead of written before the code fence.

Happy to receive a PR for this from any of our community members! 🚀

**Comment by kevinzunigacuellar** [comment]
I am happy to take this off your hands Sarah, I see that we also have another way to include titles in codeblocks as in https://docs.astro.build/en/core-concepts/layouts/#sample-layout . Should this be changed as well?
