### ISSUE TITLE
📘 DOC: Lint for broken links in all languages

### ISSUE THREAD

**Issue by jasikpark** [withastro/docs#103]
Currently we have a `yarn lint:linkcheck:local` command that can check for broken links, but we don't have any way to switch what language you're using without JS, so it only checks the English pages.

I want to write a script using the programmatic version of [blc](https://github.com/stevenvachon/broken-link-checker) to check all translations of the docs for broken links!

**Comment by hippotastic** [comment]
Sure @sarah11918, why not! I'll have a look 🙂

**Comment by hippotastic** [comment]
I've implemented it myself. See my PR above. The output looks like this:

```
/da/getting-started/
  ❌ https://docs.astro.build/quick-start
  ❌ https://docs.astro.build/installation
  ❌ https://docs.astro.build/reference/builtin-components

/de/core-concepts/component-hydration/
  🔗 https://docs.astro.build/de/core-concepts/component-hydration/#mycomponent-clientonly-

/de/core-concepts/routing/
  🔗 https://docs.astro.build/reference/api-reference#getstaticpaths

/de/getting-started/
  ❌ https://docs.astro.build/reference/builtin-components

[...]

*** Found 76 broken links.
```

When a link leads to a 404 page, the target href is prefixed by a ❌.
When the target page exists, but the link contains an URL hash that does not exist on that page, the prefix is 🔗.

**Comment by hippotastic** [comment]
@sarah11918 This issue can be closed now, my PR got merged. 🎉

**Comment by sarah11918** [comment]
YAY! 🥳
