### ISSUE TITLE
Improvement to MDX section

### ISSUE THREAD

**Issue by jamesli2021** [withastro/docs#10408]
### 📋 Explain your issue

1) I feel MDX in the docs can be improve, found it confusing with the flow as you may think whether you should name mdx or .md

2) Adding Astro components to the MDX contents could be mentioned but I didn't really notice this.
https://docs.astro.build/en/guides/integrations-guide/mdx/#using-components-in-mdx

There is no mentioned of how to add components on this page to .md/.mdx:
https://docs.astro.build/en/basics/astro-pages/#markdownmdx-pages
When I first read, I was not aware that imported components has to be outside the codefence, different from Astro source file.

3) I found the code example are confusing, with `Content`, should we rename it for better explaination?
https://docs.astro.build/en/guides/markdown-content/#the-content--component

4) Need an informative box for choosing .md or .mdx. What is the difference? The `Tips` for these is a bit vague
```
For additional functionality, such as including components and JSX expressions in Markdown, add the [@astrojs/mdx integration](https://docs.astro.build/en/guides/integrations-guide/mdx/) to write your Markdown content using [MDX](https://mdxjs.com/).
```
Should we rename title to `Tips: Choosing MD vs MDX`.

**Comment by sarah11918** [comment]
Hi! I'm sorry you didn't find the flow of docs easy to understand. You seem to be expecting Astro to give you more guidance on whether to use Markdown or MDX, and that's not really what Astro docs documents, as it is a personal preference and depends on what you need to do. We document *how each of these work in Astro*, but not what Markdown is nor what MDX is, just like for example we don't document what Tailwind is or how to use it, only what specific information you need to know to be able to use Tailwind in Astro.

You also are mentioning different pages where you expect more MDX information, but the MDX information is only intended to be on the page about installing, configuring and using the MDX integration. We intentionally keep the rest of the documentation very minimal about MDX as it is not built-in to Astro and is only appropriate for people who have the integration installed.

So, we will keep the docs as they are at this time!
