### ISSUE TITLE
404 page content is hidden

### ISSUE THREAD

**Issue by Yan-Thomas** [withastro/docs#1050]
The docs' 404 page has a CSS conflict that is hiding its content, as you can see in the screenshot below:
![image](https://user-images.githubusercontent.com/61414485/180035859-3613cd84-5e20-4b01-8d14-4ac7baa619c0.png)

**Comment by delucis** [comment]
Ohhh, is that what is happening! I noticed this in dev and assumed it was a dev server bug without investigating. Thanks for the issue!
