### ISSUE TITLE
Publish llms.txt

### ISSUE THREAD

**Issue by dandv** [withastro/docs#10508]
### 📚 Subject area/topic

The entire Astro documentation

### 📋 Suggested page

https://docs.astro.build/llms.txt

### 📋 General description or bullet points (if proposing new content)

The `llms.txt` standard ([llmstxt.org](https://llmstxt.org/)) makes documentation available to large language models and the applications that make use of them, such as ChatGPT, GitHub Copilot, or IDEs like Cursor.

See https://svelte.dev/docs/llms for example, and [this post](https://scalabledeveloper.com/posts/llms-txt-with-astro/) for how to generate LLMs.txt with Astro.

**Comment by sarah11918** [comment]
This is not something we're interested in adding at this time.
