### ISSUE TITLE
Add Reading Time Recipe needs to be update to reflect new render method.

### ISSUE THREAD

**Issue by enigmalea** [withastro/docs#10519]
### 📚 Subject area/topic

Recipes

### 📋 Page(s) affected (or suggested, for new content)

https://docs.astro.build/en/recipes/reading-time/

### 📋 Description of content that is out-of-date or incorrect

The line `const { Content, remarkPluginFrontmatter } = await entry.render();` in the code sample for dynamically generated pages needs to be updated to `const { Content, remarkPluginFrontmatter } = await render(entry);` to reflect the new use of render.

`params: { slug: entry.slug },` should be updated to `params: { slug: entry.id },`.

I'm willing to do a PR to correct.

### 🖥️ Reproduction in StackBlitz (if reporting incorrect content or code samples)

https://codesandbox.io/p/devbox/billowing-fast-flypqx?workspaceId=ws_G4yXD7UznkG3Cy1arhHtf1

**Comment by sarah11918** [comment]
Thank you for spotting this! We would be happy to have a contribution to update the recipe for the current version of content collections, (and note that I think you'll need to now include `render` in the import statement, too).

I'll add the tag `help wanted` which means we're happy to have a PR!
