### ISSUE TITLE
Automatically label i18n PRs?

### ISSUE THREAD

**Issue by sarah11918** [withastro/docs#1052]
Investigate ways to automatically apply the label `i18n` to translation PRs when they are created. This could involve GitHub actions (`.github/labeler.yml`)

Then, submit a corresponding update to the [i18n README Guide for Translators](https://github.com/withastro/docs/blob/main/src/i18n/README.md) documenting whatever measure PR authors should take to trigger this automation.  (e.g. Prefix all translation PRs with `[i18n]`?)

**Comment by delucis** [comment]
Linking here to the GitHub Action that we can use: https://github.com/actions/labeler

We need to update our config in `.github/labeler.yml` to target the right paths. We can probably safely label any Markdown page that is not in `/en/` as an i18n PR.

**Comment by kevinzunigacuellar** [comment]
I would like to take this one off your hands. Q: should we also include the `/i18n/` folder?

**Comment by delucis** [comment]
Yes! I think including `src/i18n` makes sense here.
