### ISSUE TITLE
Improve and highlight the i18n Guide

### ISSUE THREAD

**Issue by Yan-Thomas** [withastro/docs#1060]
This issue lists a few improvements we can make in the i18n Guide:

- [x] Warn contributors to avoid translating pages that aren't listed as part of the Translation Status Overview. These pages can be heavily changed, or even removed on short notice, so they are marked as `i18nReady: false` to avoid wasting the translators' time and effort.

- [x] Document the use of `minor` commits and explain how the pages are added to the "needs updating" section ([see the original issue](https://github.com/withastro/docs/issues/359)).

- [ ] Highlight the i18n guide more: this guide is hard to find because it is inside the `i18n/` folder and is briefly mentioned in the top-most README as a level 3 heading. Maybe we could move the guide to the root folder and use a bigger heading to mention it in the docs' README.

**Comment by sarah11918** [comment]
I think the first two issues can be considered "marginally covered" by #1079 (Documenting "minor" in CONTRIBUTING) and #1078 (i18n READMEre: do not translate advice).

**Comment by sarah11918** [comment]
Do we have consensus re: moving `i18n README` to root?

- rename to I18N ?
- move to root?
- update any relative links?

**Comment by delucis** [comment]
I might rename to `TRANSLATING.md` to match our other `PRESENT-CONTINUOUS-VERB.md` files? But I’m OK with moving it, yup 👍

**Comment by Yan-Thomas** [comment]
> update any relative links?

I think the only places we link to the i18n guide are on the `README.md` file and in the "Translate this page" on the Docs, I can take care of this one once we decide what to do with the file. 

I agree with renaming to `TRANSLATING.md`.

**Comment by sarah11918** [comment]
Great, @Yan-Thomas ! Move it, and make it so!

**Comment by sarah11918** [comment]
@Yan-Thomas , when you've moved the file, maybe we close this issue and move video caption documenting into one of the issues like the one for tracking captions for translations? 

I think videos themselves are still work in progress, so maybe move this to align with those tasks? What do you think?

**Comment by Yan-Thomas** [comment]
> I think videos themselves are still work in progress, so maybe move this to align with those tasks? What do you think?

Sure, I'm OK with moving the last "TODO" to the other task. I'll update this (and the other issue) to reflect this.
