### ISSUE TITLE
Add more accessibility guidance to the Maintainers Manual

### ISSUE THREAD

**Issue by Yan-Thomas** [withastro/docs#1061]
We briefly mention accessibility in [our Maintainers Guide](https://github.com/withastro/docs/blob/main/MAINTAINERS.md#triaging-issues-and-prs), but we don't give more information about what accessibility really is and what and how you can test it. Rather than creating an "Accessibility Guide", I believe we could add a new heading linking to relevant, trusted sources, explaining what is accessibility, how and what to test (color contrast, high contrast, reduced motion, keyboard and screen reader behavior, etc)

**Comment by sarah11918** [comment]
@Yan-Thomas , do you know of particular sources that you recommend? Would you like to go ahead and draft this? I think PR'ing a section to this would be great!

**Comment by Yan-Thomas** [comment]
> @Yan-Thomas , do you know of particular sources that you recommend? Would you like to go ahead and draft this? I think PR'ing a section to this would be great!

Yes @sarah11918, I have a lot of sources that I recommend, I'd say the best resources to get started are the WAI's [Resources for Developers](https://www.w3.org/WAI/roles/developers/) and [ARIA Authoring Practices Guide](https://www.w3.org/WAI/ARIA/apg/patterns/) and [The A11y Project's](https://www.a11yproject.com/) checklist and resources list. I thought I had assigned myself to this issue but I haven't :sweat_smile:. I'll start working on this PR today! :raised_hands:
