### ISSUE TITLE
📘 DOC: Improve docs around deployment script to gh-pages

### ISSUE THREAD

**Issue by arecvlohe** [withastro/docs#108]
Hello all! I think Astro is pretty great at what it does and I even contribute a small amount each month to help support your work. 

I came across the docs for deploying to github pages and found the deploy script would overwrite my `main` branch with the output of the `dist` folder. I'd like to be able to maintain my `main` branch as it is but to instead deploy to a separate branch named `gh-pages`. I ran into issues with the deploy script for this scenario and instead went with using an npm package to help: `gh-pages`. All I had to do was run `yarn build && touch ./dist/.nojekyll && gh-pages -d dist -t true` and it worked like a charm. In my settings for the repo, I just point to `gh-pages` as the branch I want deployed.

I thought this would be a good idea to add to the docs but maybe it's too specialized to npm land, hence the bash script you have as the first/primary way to deploy. Anyhow, I'd thought I'd at least bring up the idea and see what you all thought in case there was agreement there. Thanks for all the work on this project, I am excited to see where things go.

**Comment by eallenOP** [comment]
I followed the instructions both under the GitHub Pages heading and the GitHub Actions heading, and it's working fine but it removes my custom domain every time. Do I need to add `echo 'my.domain' > CNAME` to the build step or something?

Yes, I have the correct `buildOptions.site` in `astro.config.mjs`. These instructions seem to assume that anyone who learns Astro will also know how to set up CI or edit bash scripts etc.
