### ISSUE TITLE
reference to `slug` in RSS docs

### ISSUE THREAD

**Issue by garfieldnate** [withastro/docs#1082]
The docs for generating RSS make reference to a frontmatter field called "slug" which is not auto-generated. Trying to use the code given [here](https://docs.astro.build/en/guides/rss/#2-list-of-rss-feed-objects) as-is results in errors. All references to `slug` should be changed to `url`, which works correctly and is what's actually used if you call the glob version of `rss()` instead of the feed objects version.

**Comment by delucis** [comment]
Makes sense! Would you like to make a PR with those changes @garfieldnate?

**Comment by garfieldnate** [comment]
I would have sent a PR but the edit button on GitHub was disabled. 🤷  More importantly, though, I wasn't sure if you had unit tests or something else that needed to be updated.

I do appreciate you inviting me to participate, but I won't be able to make time to send a PR for now. Sorry 🙇
