### ISSUE TITLE
📘 DOC: Add docs and tests for passing options to custom renderers

### ISSUE THREAD

**Issue by tony-sull** [withastro/docs#109]
This came up for me while working on withastro/astro#935, apparently Astro actually does have support for passing options to a renderer.  We should add docs to cover this and also make sure there is test coverage for it as well

https://github.com/snowpackjs/astro/pull/935#issuecomment-899567509

**Comment by sarah11918** [comment]
@tony-sull is this a relevant issue anymore? :)

**Comment by sarah11918** [comment]
So, @tony-sull ... Aug 2021, eh?  I'm going to slowly close this and back away... and if it comes up again, it comes up! 😅
