### ISSUE TITLE
I would like to add another deployment option: Codeberg Pages

### ISSUE THREAD

**Issue by redwerkz** [withastro/docs#1103]
It's a free, independent and non-profit git hosting provider from germany.
They are running on a gitea fork.

https://codeberg.com
https://codeberg.page

**Comment by sarah11918** [comment]
Hi @redwerkz! Would you be willing to write the detailed instructions for this page, to match the style of the other deployment options?

If so, we can guide you through this process!

**Comment by sarah11918** [comment]
Just checking in, @redwerkz! If you'd still like to create another page for us, you're welcome to make a PR by creating a new page in this folder:  `https://github.com/withastro/docs/tree/main/src/pages/en/guides/deploy` called `codeberg.md`.

We will also need a few new files to fit it into our existing format, and this PR is a great example of what's needed:  https://github.com/withastro/docs/pull/1114/files  You can use that as a model, and we'll help if it needs any adjustment from there.

Let us know if you are still interested (maybe this issue could be closed either way? either you're no longer interested in this content, or you're actively working to provide it?) or if we can help you further!

**Comment by redwerkz** [comment]
OK, sorry I'm quite busy atm.
