### ISSUE TITLE
📘 DOC: Add usage of `--site` to /guides/deploy for preview sites

### ISSUE THREAD

**Issue by jasikpark** [withastro/docs#113]
For example on Netlify we should add 
```shell
yarn build --site $DEPLOY_PRIME_URL
```
for Deploy Previews and Branch Deploys in the explanation

**Comment by sarah11918** [comment]
Ya got reeeeeaaallly distracted, @aFuzzyBear ! :sweat_smile: 

Should this still be an open issue?

**Comment by aFuzzyBear** [comment]
😂😂 no anymore, we got the one click deploys on the repository now along with all the ide integrations, I think this is safe to close,
