### ISSUE TITLE
legacy.astroFlavoredMarkdown explained

### ISSUE THREAD

**Issue by Hopelezz** [withastro/docs#1191]
## Problem:

I'm new to programming in general. 

Enabling a flag isn't something I've done before. So when the migration guide and @bholmesdev suggested I add this flag I went searching for how to do it.

The site only references the fact there's a new flag and the details about it, but not HOW TO implement it.
![image](https://user-images.githubusercontent.com/72772558/182751037-68dcba58-5d8f-4614-97cd-78ede549ea16.png)

I even read further up on the page for how these things might be handled.

## Solution:

After much effort I figured out how to implement it. That said I think this can be easily stated as such:

Add the following to your `astro.config.mjs` file.
```
export default defineConfig({
legacy: {
		astroFlavoredMarkdown: true,
	},
});
```

or something to that effect.

**Comment by sarah11918** [comment]
Thanks, @Hopelezz! You're right, this entire legacy section is brand new on the page (it might be the first legacy flag ever publicized for users to enable?) so there is no example of `legacy:` in `defineConfig()`... and I think there should be!

What makes this page a little different is that it's automatically generated from a file in the main Astro repository which is a little more fussy to edit than a regular page in docs. https://github.com/withastro/astro/blob/main/packages/astro/src/%40types/astro.ts

Would you like to start a **draft** PR to that file on withastro/astro using "edit this page" on GitHub, and see how far you can get adding that code sample to the "description" area of that content, using the other code samples as a model for how to write it? Make sure it's a draft and there are no worries of it going wrong! Then, mention me to hop in and I'll make whatever polishing changes are needed to it.

If you'd rather I just take care of it, that's fine too! Just let me know!

**Comment by Hopelezz** [comment]
@sarah11918 Happy to give it a go!

**Comment by Hopelezz** [comment]
@sarah11918 PR requested [Modify legacy flag description #4187](https://github.com/withastro/astro/pull/4187)

Trust this should resolve this issue upon merge.

**Comment by sarah11918** [comment]
Yes, the other PR on withastro/astro should take care of this... so I'll do a little early housekeeping and close this here now! (It's a little fussier when the PR that closes an issue is on a different repository... we'd have to close this manually anyway, so I'll just do it because we have our fix there!)
