### ISSUE TITLE
List not consistent in titling on astro-components.md

### ISSUE THREAD

**Issue by darusk** [withastro/docs#1229]
The list under the heading `The Component Script` on page https://github.com/withastro/docs/blob/main/src/pages/en/core-concepts/astro-components.md mixes a leading capital for the first three entries, and all lower case for the final two.

The final two entries should probably be capitalised for consistency.

**Comment by sarah11918** [comment]
Great call out @darusk! Normally in this case, when the bullet points are finishing a sentence (i.e. aren't full sentences themselves), I'd use lower case to start everything. Would you like to make a PR for this page in particular?

**Comment by darusk** [comment]
Ok, that's done (after second attempt! still getting used to Github ;) )  https://github.com/withastro/docs/pull/1238
