### ISSUE TITLE
Add instructions for "how to update css classes on save", onto Tailwindcss integration page

### ISSUE THREAD

**Issue by viszya** [withastro/docs#1241]
## The Issue:
 There is currently no **clear** instruction on Astro docs on how to make Tailwindcss classes **update on every file save** instead of reloading or restarting the build.
Thanks to @aFuzzyBear & @weoperate for helping with this

## Solution:
   You can add the following (below) to the Tailwindcss integration [page](https://docs.astro.build/en/guides/integrations-guide/tailwind/)
   Either under the Install, Usage, or Troubleshooting Section

### Updating Tailwind Classes on Every File Save
Currently, Astro does not support updating Tailwind's classes on every file save. 
To make Tailwind's classes update on every file save, type this command into your Terminal window.
This will install the necessary utilities to integrate with Astro.
``` npm i -D tailwindcss ```

For more help, view the official [website](https://tailwindcss.com/docs/installation) for Tailwindcss

**Comment by sarah11918** [comment]
Thanks for noting this here! I'm glad you found a solution! 

I'm going to investigate this with the technical steering committee, to make sure they know that this step is necessary, and to see whether they might want to try to find a workaround to needing to do this in the first place (vs us recommending this step in docs).

Either way, now that you've made the issue, there's a record of it, and a solution here for anyone else who might be searching! Thank you!

**Comment by delucis** [comment]
`tailwindcss` is already a dependency of the `@astrojs/tailwind` package, so should be installed for you when you run `npx astro add tailwind` or manually `npm i -D @astrojs/tailwind` and add the integration to your `astro.config` file.

I’m going to close this as I don’t think we have anything more to document, but if you still see extra steps needed to get this working, I’d recommend opening a bug report on https://github.com/withastro/astro as it shouldn’t be needed.
