### ISSUE TITLE
Additional configuration needed to configure astro in (neo)vim

### ISSUE THREAD

**Issue by threkk** [withastro/docs#1257]
Hello! I am trying astro for the first time, so following the guide, I set up my editor to work with astro. Using Neovim 0.7.0, I followed the instructions provided, but I realised that there were a couple of missing steps that are not documented. These steps are not critical, and many (Neo)vim users would likely be familiar with them already, but I think it is important to highlight them for less experienced users.

1. In order to install the [tree-sitter astro grammar](https://github.com/virchau13/tree-sitter-astro), the user does not need to donwload or install the project. They just need to run `:TSInstall astro` (assuming that they have installed [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter) which is sort of a requirement).
2. The LSP and tree sitter will not trigger by default because (Neo)vim is not able to detect `*.astro` files as astro files. This might change in the future, but currently the users will need to add something like `autocmd BufEnter *.astro set filetype=astro` to their vimrc or init.vim to make it work.

I am opening this ticket to discuss
- If this is really an issue, or it is just my setup.
- How it is the most appropriate way to communicate this information to the users. I didn't find an obvious place in the docs to add this information.

**Comment by sarah11918** [comment]
Thank you for this comment! Certainly, we do want everyone to be able to get set up with any of the editor tools for Astro. Right now, we don't provide additional instructions for any community projects; we only list them. If extra Astro-specific steps are necessary for a user, then I agree it would be nice to be able to let them know, especially if we suspect that the project itself doesn't provide guidance on working with Astro

I notice you've said "users will need to add *something like*..."  "to vimrc *or* init.vim." Even when different strategies work, if there is one, consistently reliable method most users can follow, I think it's simpler to be able to just say "do this" (or "the most common way is to...") and maybe provide a link to either our "Troubleshooting" page or external support.

Can you put yourself in the position of a beginner user, someone you're thinking might need this extra help, and list out the steps, in order, that they would have to take to get set up? At each step, indicate if this is a "normal" Neo(vim) step that they either would have already done / would already expect to do for any new project OR if this is "an extra thing they have to do to work with Astro." I'd like to see exactly what we're dealing with here. :) It might be too much to contain in a bullet point, which is how we currently mention these now. So, depending on what we're looking at, we may need to rethink that organization.

**Comment by threkk** [comment]
I was referring more to the second, an extra thing to work with Astro. I am going to create a minimal set up for Neovim to work with Astro from scratch. This is, proper syntax highlighting, and a working language server. I will follow the documentation as much as possible and see what is missing after. Based on the missing steps, I guess it will be easy to make a decision if we just need an extra line or if we need a longer write-up :)

**Comment by wuelnerdotexe** [comment]
Hi @sarah11918, @threkk  - I have recently commented on [Discord](https://discord.com/channels/830184174198718474/1007057863199441026) my opinion as a Vim & Neovim user of what I think is the best way to solve this, in case it can help.

About the first thing here, I think the `:TSInstall astro` command to install Astro with Tree-sitter is extremely obvious for Neovim users, as is installing an extension for VS Code users.

About the second, when installing my recent added #1235 [vim-astro](https://github.com/wuelnerdotexe/vim-astro) plugin, the `.astro` files are recognized by Vim or Neovim automatically, therefore, it can serve as a base for later installing the LSP and Tree-sitter.

I hope I can be of help \0/

**Comment by threkk** [comment]
It looks like this will not be a problem any more. Vim and Neovim have added a patch in their master branches which solves the main issue I describe. This should fix the tree-sitter and LSP triggering without any additional plugin.

https://github.com/neovim/neovim/commit/33b49d5f55423a1a3174ad0ce42c4454871aa9f8
