### ISSUE TITLE
Clarify that named slot syntax in Astro files is Astro syntax

### ISSUE THREAD

**Issue by drewtownchi** [withastro/docs#1270]
It was confusing to me how Astro is different than Vue when using named slots.

Normally I would do something like this in Vue

```js
    <contact-form default-option="Volunteer">
      <template #title> // or v-slot:title
        Contact us for more information!
      </template>
      <template #subtitle>
        Help out today!
      </template>
    </contact-form>
```

But with my Vue component in Astro I do this?:

```js
    <ContactForm default-option="Volunteer" client:visible>
      <Fragment slot="title">
        Contact us for more information!
      </Fragment>
      <Fragment slot="subtitle">
        Help out today!
      </Fragment>
    </ContactForm>
```

It's weird to me because it looks very similar to the Vue syntax but is clearly not. I think the documentation should somehow clarify that even though Vue (and possibly other frameworks) has its own named slot syntax when in an Astro component you must use the Astro syntax.

**Comment by sarah11918** [comment]
That's for the feedback, @drewtownchi! Yes, it's certainly a challenge for documentation in a project where people may have different files using different syntaxes within the same project. And, many of these file types share similar elements.

We will take a look at our description of slots to make sure it's clear that when you're writing `.astro` files, you should be using `.astro` syntax!
