### ISSUE TITLE
Docs about integrations conflict with Typescript Types

### ISSUE THREAD

**Issue by cameronmcefee** [withastro/docs#1334]
In the docs about using integrations, the docs state that falsy values are ignored and can thus be used to conditionally add integrations: https://docs.astro.build/en/guides/integrations-guide/#toggle-an-integration

> Falsy integrations are ignored, so you can toggle integrations on & off without worrying about left-behind undefined and boolean values.
> ```
> integrations: [
>   // Example: Skip building a sitemap on Windows
>   process.platform !== 'win32' && sitemap()
> ]
> ```

However, doing so will create a typescript error:

```
Type 'false | AstroIntegration' is not assignable to type 'AstroIntegration | AstroIntegration[]'.
```
I'm making an issue here because the docs do not correctly describe reality, but I think the actual fix should be to the type, because this functionality is useful.

**Comment by delucis** [comment]
Thanks @cameronmcefee! I _think_ this is actually an error in the types as I’m fairly sure that toggling approach is supported.

**Comment by cameronmcefee** [comment]
Thanks @delucis, should I create an issue over there, or is this considered known at this point?

**Comment by delucis** [comment]
An issue or even a PR on https://github.com/withastro/astro would be super helpful! Thank you 🙌

**Comment by cameronmcefee** [comment]
Done: https://github.com/withastro/astro/pull/4427
