### ISSUE TITLE
Flesh out the GitHub Pages deployment guide

### ISSUE THREAD

**Issue by swift502** [withastro/docs#1355]
Hi! I followed the [github deployment guide](https://docs.astro.build/en/guides/deploy/github/) and for me it just flat out doesn't work.

## 1. Base

The guide states:

> Set the **site** and, if needed, **base** options in astro.config.mjs.
> **base** should be your repository’s name starting with a forward slash, for example /my-repo
> If your repository is named <YOUR_USERNAME>.github.io, you don’t need to include base.

My repository is called "Web" so I set base to "/Web" and the deployment completely broke my website. While assets were in the /assets folder, pages were looking for them in /Web/assets.

The solution was to not include any base parameter in astro.config.mjs.
Why? My website and repository are not called <YOUR_USERNAME>.github.io, so why do I have to omit the base parameter, and not set it like the guide says?

## 2. Deployment source

The guide states:

> On GitHub, go to your repository’s Settings tab and find the Pages section of the settings.
> Choose the gh-pages branch and the "/" (root) folder as the Source of your site and press Save.

I did and the deployment action failed with the error `Invalid deployment branch and no branch protection rules set in the environment`.

Why? How does one set "branch protection rules"? Maybe that it could be included in the guide?

The solution was to set the source to "GitHub Actions" instead of "Deploy from a branch" altogether. It might be in Beta, but it works without any issues.

![image](https://user-images.githubusercontent.com/24359130/185671560-ab0138fe-6708-423d-bfdd-71f4cfb368eb.png)

---

I managed to figure it out but it wasn't exactly a smooth experience.
I think it would be great to improve it so other people don't run into the same issues.

**Comment by sarah11918** [comment]
Thanks for this, @swift502! I'm going to ping @natemoo-re to make sure he sees these comments, too! 

The solution may be adding more documentation around the entire process, but I just want to check with Nate first to make sure there's nothing that he'd change re: the GitHub action itself that would affect the steps that get documented!
