### ISSUE TITLE
CORS Error When Adding A Paperform Script

### ISSUE THREAD

**Issue by WallaceSociety** [withastro/docs#1427]
Probably not the best title, but as I'm not really sure what's happening under the hood I figured I'll start with the output and then can rename it to the specific problem later. 

**Desired Outcome:**
Display an embedded paperform on an HTML page

**Current Results:**
CORS error from embed script

**Steps to Reproduce:**
npm create astro@latest paperformIssue
( install empty project )
Add following code to body of index.astro and run dev or build
```
<div data-paperform-id="ztxmmoot"></div>
<script src="https://paperform.co/__embed.min.js"></script>
```

**My Notes**
As I mentioned I'm not quite sure what is happening, but it looks like the script is somehow getting repackaged as a hoisted.js and something is being changed in the request headers. 

**Workaround**
Omit the `<script src="https://paperform.co/__embed.min.js"></script>` tag and add it just before the body of the compiled HTML.

**Comment by delucis** [comment]
Thanks for this @WallaceSociety! This is actually the issue tracker for our documentation site. If you're still running into this, could you please repost this in https://github.com/withastro/astro/issues with a reproduction?

**Comment by WallaceSociety** [comment]
Posted: https://github.com/withastro/astro/issues/4532
