### ISSUE TITLE
[Question] Will a jetbrains plugin be developed?

### ISSUE THREAD

**Issue by yesworld** [withastro/docs#1453]
Hi there! 

I am using PHPstorm and astro type of file is not supported by the ide. Are there plans to develop a plugin for it?
Thanks.

**Comment by Yan-Thomas** [comment]
> I am using PHPstorm and astro type of file is not supported by the ide. Are there plans to develop a plugin for it?
Thanks.

Hello @yesworld, we talk about this on our docs' Editor Setup page: https://docs.astro.build/en/editor-setup/#jetbrains-ides

TL;DR: We would love to support JetBrains IDEs but they don't support language servers, meaning we would have to write an entirely new extension in another language. The future Fleet IDE will support language servers though, and then we will be able to run our current tooling in it.
