### ISSUE TITLE
Adding integrations via npm?

### ISSUE THREAD

**Issue by altano** [withastro/docs#1468]
I don't think this used to be broken but all the integrations (e.g. [vue](https://docs.astro.build/en/guides/integrations-guide/vue/) / [image](https://docs.astro.build/en/guides/integrations-guide/image/)) say to add them via:

`npm run astro add image`

![image](https://user-images.githubusercontent.com/1009/188332911-05e3472d-262e-4572-be67-8320b1e4fcb2.png)

But that doesn't make sense as there isn't an `astro` script by default in packages.json and, even if there was, it wouldn't take arguments.

I believe this used to say `npx astro add image` which would work.

**Comment by altano** [comment]
And if you want a dependency (`npx`) free version:

`npm exec astro add image`

**Comment by sarah11918** [comment]
Thanks for this, @altano! 🙌  I'm tracking down where (and why) these changed because you're right... they were correct before. Not sure what happened there, but I'm going to get that reverted pronto.

**Comment by sarah11918** [comment]
@delucis Can I assign this one to you? It seems to be your PR here https://github.com/withastro/astro/pull/4340 where this change was made. I can see this was an intentional change.

**Comment by altano** [comment]
Turns out I am mostly wrong.

1. It looks like a newly created `astro` project does include an `astro` npm script in package.json.
2. And, if that script exists, `npm run astro add image` seems to do the right thing. I'm very confused on this last point: npm scripts didn't always take arguments ([unless you use `--`](https://docs.npmjs.com/cli/v8/commands/npm-run-script#synopsis))? It's still documented to require `--`. Did npm change how script arguments work? I can't find any announcements or documentation. Consider me confused.

Anyway, `npm exec` might be the safest bet since it doesn't rely on the package script existing. Or just leave it as-is and assume I'm probably the only person who screwed up their package.json and removed the `astro` script and this isn't super important.

**Comment by sarah11918** [comment]
Thanks again for bringing this to our attention, @altano! It sparked some discussion, and we ultimately opted to go for what had a lower chance of not working for people. (I think a good choice.)
