### ISSUE TITLE
link lang?

### ISSUE THREAD

**Issue by cfv1984** [withastro/docs#147]
Hi! Tried several increasingly cheekier ways of linking to my SCSS files, to no avail. Several times, in fact, because I keep forgetting this not being possible from my experiments. 

Is this something that is possible? The docs consistently `<link />` to CSS. Could a notice be added noting that this is not an option?

Examples: 

```html
<!-- none of these work for me -->

<link rel="stylesheet" src={Astro.resolve("@styles/heet.scss")} lang="scss" /> <!-- using my tsconfig alias -->
<link rel="stylesheet" src={Astro.resolve("../../../styles/heet.scss")} lang="scss"  /> <!-- using astro.resolve -->
<link rel="stylesheet" src={path.join(PUBLIC_SRC_DIR, 'styles/heet.scss')} lang="scss" /> <!-- using an actual absolute path -->
``` 
In all 3 cases, the actual file is resolved, and in the 2nd case I can get Astro to point to the correct, if uncompiled, SCSS file. But I was expecting it would render it for me? If this isn't supposed to happen, it'd be pretty cool if the docs would mention it.

**Comment by sarah11918** [comment]
I believe we have now documented the deprecation of the Astro.resolve() behaviour, and are currently in the process of updating other docs regarding our styling and css imports, including how they're now going to work with some recent changes, so I'm going to close this issue. If you have issues with how things are documented going forward, with our newer methods, please do feel free to open a new issue!  :)
