### ISSUE TITLE
Inconsistency between dev and build with trailing slash

### ISSUE THREAD

**Issue by AidanNichol** [withastro/docs#1470]
working with astro 1.1.5
```
let pathname = new URL(Astro.request.url).pathname;
```
with astro dev dev this doesn't return a trailing '/' whereas build does.

**Comment by Yan-Thomas** [comment]
Thanks for reporting this @AidanNichol! This repo is meant for our docs, not for the framework itself. May I ask you to make the issue in the main Astro repo instead? https://github.com/withastro/astro/issues/new/choose
