### ISSUE TITLE
Notify translators when English pages are changed?

### ISSUE THREAD

**Issue by sarah11918** [withastro/docs#1480]
How can we notify tranlsators when English pages are changed, in case they have open PRs or are currently working on that page's translation? What will a translator need (or find convenient) in this case that we can provide?

Can this be related to Docs congratsbot somehow? Is DocsCongrats bot ENOUGH, if we document, remind translators to pay attention to it?

Original Message:
"Can we post a message to open translation PRs when an English page they impact is updated? This avoids the scenario where a translation is proposed, the English page is changed, and the translation is then merged, missing the English changes. (h/t @Chrissdroid on Discord)"

**Comment by delucis** [comment]
I think this might be a duplicate of #1057?

**Comment by sarah11918** [comment]
Ah! Yup, about pinging, though this was specifically aimed at letting translators know ASAP so as not to mess up their current work, vs a more regularly-scheduled shoutout. 

I made this from an un-issued task in #359 but can link there to the other one instead.

**Comment by delucis** [comment]
Ah right. I’m not sure of the benefits of over-eager pinging — I suspect it could get kind of annoying, especially as folks aren’t necessarily sitting around just desperate for the next English changes to come in. I personally think the weekly digest would be a more friendly way to regularly prompt and batch up work.

**Comment by sarah11918** [comment]
Yup, closing this one now, added the content to the existing issue as a consideration, but unsure about helpfulness of a more frequent ping!
