### ISSUE TITLE
Display the "freshness"/status of a translated page

### ISSUE THREAD

**Issue by sarah11918** [withastro/docs#1481]
Is it possible (desirable?) to display the "Freshness" of a translated page directly on it? (If so, where? Near "edit this page?.")

This could be a good way for translators to be on a page and know that it does/doesn't need an update, as well as being an indication to the reader that the English page might be more updated. (We already "know" if a page is not updated, because of the disclaimer at the top. So presumably we can "know" the other statuses as well?)

Original Message:

"If a reliable enough estimate of “out-of-datedness” can be calculated, add a disclaimer to translated pages that meet some criteria (based on Hippo’s suggestion on Discord)."

**Comment by rishi-raj-jain** [comment]
@sarah11918 How about something like Last Updated?

**Comment by delucis** [comment]
“Last updated” is definitely part of it, but this is more like: how different is the translation’s last updated & the English version last updated — excluding minor English typo fixes. For example, a translation is still up-to-date/“fresh” if it was updated 2 months ago if the only commits to the English version in the last 2 months were typo fixes that don’t need reflecting in the translated page.

So it’s a bit of a tricky one, but would certainly love to talk about this, if you’re interested. We might be able to reuse some of the logic from https://github.com/withastro/docs/blob/main/scripts/github-translation-status.mjs.

**Comment by rishi-raj-jain** [comment]
@delucis Yup, let's get started!

How do we spot " were typo fixes that don’t need reflecting in the translated page."?

**Comment by rishi-raj-jain** [comment]
Instead of adding onto the sidebar, if we're able to assert that it's outdated, I think it'd make more sense to add it to the top of the heading in some form of a badge perhaps.

**Comment by sarah11918** [comment]
I wonder if a short-term first solution could be as simple as starting with mirroring the icon that's on our pinned Translation Status issue. So it's either a check for completely up-to-date with the English page or a symbol for "something on this page needs updating to the English version." (Probably don't need the X for not translated yet, since we have something in place for that?)

The cool thing about mirroring the status on the page, is it might encourage more translators!

As @delucis said, I don't think "date" or "last updated" is as useful in this specfic case, since it's really about keeping sync with the English page that is the important thing. Sometimes, no news is good news!  ;)

**Comment by delucis** [comment]
Definitely agree with the idea of something at the top of the page rather than in the navigation — gives us some room to provide context. For example, we currently show a note in our `[...fallback].astro` route for pages that aren’t translated at all, which also supports translation of the explanation itself:

<img width="840" alt="image" src="https://user-images.githubusercontent.com/357379/198995035-25986e61-6deb-4578-b3d6-35c7955cf9dc.png">

(Live example: https://docs.astro.build/de/migrate/)

> How do we spot "were typo fixes that don’t need reflecting in the translated page."?

So our translation status script filters by keywords in the commit message. It has a concept of a “major” commit, which is any commit that doesn’t include specific keywords:

https://github.com/withastro/docs/blob/0dddd9ce8a6d9654be8be3f89102c6e4f313cda2/scripts/github-translation-status.mjs?rgh-link-date=2022-10-31T10%3A41%3A24Z#L323-L328

**Comment by sarah11918** [comment]
@rishi-raj-jain Are you still interested in exploring some kind of badge/notification at the top of a translated page to indicate whether the translation needs updating because the English page has changed?

**Comment by delucis** [comment]
Sharing a link to some other related code @Princesseuh uses to calculate last modified dates on her site:

https://github.com/Princesseuh/erika.florist/blob/8bfb04562530d99deee0974bb0f4fc5d94840c76/src/data/wiki.ts#L6-L19
https://github.com/Princesseuh/erika.florist/blob/8bfb04562530d99deee0974bb0f4fc5d94840c76/scripts/getLastModified.sh

**Comment by sarah11918** [comment]
Bumping for the "sort by newly updated" crowd... this is still a great idea that we'd love to explore in Docs, and are open to community contributions to make it happen!  :raised_hands:
