### ISSUE TITLE
Broken link on Environment Variables section of Docs

### ISSUE THREAD

**Issue by pinnheads** [withastro/docs#1535]
The link to [Environment Variables example](https://github.com/withastro/astro/tree/main/examples/env-vars) on the page "[Using environment variables](https://docs.astro.build/en/guides/environment-variables/)" seems to be broken.

**Steps to Reproduce**
1. Navigate to [https://docs.astro.build/en/guides/environment-variables/](https://docs.astro.build/en/guides/environment-variables/)
2. Click on [Environment Variables example](https://github.com/withastro/astro/tree/main/examples/env-vars) 

**Expected Result**
Navigated to a GitHub page
[Screencast from 11-09-22 07:52:44 PM IST.webm](https://user-images.githubusercontent.com/49411434/189532688-d0747e07-4ee4-4b0b-ac0a-866340b6ba70.webm)

**Actual Result**
Navigated to a GitHub 404 screen and the following error is shown `The 'withastro/astro' repository doesn't contain the 'examples/env-vars' path in 'main'.`

**Comment by delucis** [comment]
Wow, amazing timing @pinnheads! We literally just merged #1531 fixing this!

Thanks nevertheless for the report — we removed that example recently but forgot to delete the link 🙌
