### ISSUE TITLE
Gotcha: style object custom properties are transformed from camel case to kebab case

### ISSUE THREAD

**Issue by Jutanium** [withastro/docs#1539]
See [here](https://discord.com/channels/830184174198718474/872579324446928896/1018807581600382978).

**Comment by sarah11918** [comment]
(Copied text so it's easier to keep an eye on from a distance)

toonddd — 09/12/2022
Astro automatically transforms component style object custom properties from camel case to kebab case.

What is the original reason/benefit for doing so?

From my current perspective it looks unnecessary and even confusing, added complexity.

nate (he/him) — 09/12/2022
Ah this is a good point! Nobody has ever brought this up as a pain point before, so I think we're stuck with it for v1.0, but it could certainly be a breaking change in the future! CSS custom properties are usually --kebab-case but there's no technical reason they can't be --camelCase

**Comment by WintrCodes** [comment]
Would love to make this my first Astro contribution! 
Are we wanting to add this as a 'Gotcha'/good-to-know part of the docs?

If so, I can put something together for it. Please assign to me! Thanks!

**Comment by sarah11918** [comment]
On a roll today with the contributions, @WintrCodes!  🚀 

Sure, let's start by thinking of this as one of those "gotchas" for the Troubleshooting page! Depending on what you come up with, there may end up being a different fit, but I think thinking of it as troubleshooting advice makes a lot of sense to start.

**Comment by Jutanium** [comment]
This behavior no longer seems to occur. [See Stackblitz](https://stackblitz.com/edit/github-2cyv6w?file=src/pages/index.astro): Kabab case stays as kabab case.

**Comment by WintrCodes** [comment]
Here's a first draft!

#### Gotcha: --camelCase transformed to --kebab-case
If you attempt to override CSS variables by including them in your HTML using style object custom properties, do note that anything written in `--camelCase` will be transformed to `--kebab-case`. See the example below.

```astro
<body  style={{ '--cssVariable': 'brown' }} >
	<div  style="--anotherVar: blue">
		<h1>Astro</h1>
	</div>
</body>
```

```
<style>
h1 {
	color: var(--css-variable);
	background-color: var(--another-var);
}
</style>
```

In this example, `style={{ '--cssVariable': 'brown' }}` will be transformed to `style="--css-variable:brown"`, however `style="--anotherVar: blue"` does not get transformed.
