### ISSUE TITLE
Image tag

### ISSUE THREAD

**Issue by pqxglobal** [withastro/docs#1555]
After replacing html img tag with Astro Image tag image was not visible. tried multiple times to reload dev server, refresh page and adjust the path without results. Then I just cut the <div> tag en paste it again, and the image shows.
<div>
      <Image src="/images/Ellipse_4.png" width="114px" height="114px" alt="Donnajean	Critzen" format="webp" fit="cover" 
      background="#0F172A" />
</div>

seems to be a bug!!

regards Leo

**Comment by delucis** [comment]
Hi @pqxglobal! Thanks for the report but this is the Astro documentation repo. Please fill in the form here to submit an Astro bug report: <https://github.com/withastro/astro/issues/new?assignees=&labels=&template=---01-bug-report.yml>

**Comment by pqxglobal** [comment]
Thanks delucis,

I will fill out the right form.

Regards Leo
