### ISSUE TITLE
examples: drop "with Shiki", add "with Prism"

### ISSUE THREAD

**Issue by mrienstra** [withastro/docs#1557]
_**Note:** this issue proposes code changes to `withastro/astro/examples`, but the only way to make a new issue on `withastro/astro` is to [open a "Bug Report"](https://github.com/withastro/astro/issues/new/choose), so here seems like the next best option, as it arguably falls under the umbrella of "documentation"._

_**Note:** "examples" are also referred to as "templates" or "official example projects", and are shown at https://astro.new/_

Given that Shiki is now the default for syntax highlighting (see [Markdown & MDX > Syntax Highlighting](
https://docs.astro.build/en/guides/markdown-content/#syntax-highlighting)):

The ["Markdown Shiki" integration example](https://github.com/withastro/astro/tree/e73d2d1/examples/with-markdown-shiki) no longer makes sense. Seems like it should be replaced with a new (but very very similar) "Markdown Prism" integration example.

For reference, the `with-markdown-shiki` example was added in https://github.com/withastro/astro/pull/2497, which was part of [RFC 4 "Replace Prism with Shiki"](https://github.com/withastro/rfcs/blob/main/proposals/0004-replace-prism-with-shiki.md).

**Comment by sarah11918** [comment]
Hi @mrienstra! This isn't really a docs issue at all, but it is good feedback! (For reference, I think it would have been fine to open this as a bug report and let the team triage it. Or, we do have a #feedback channel in our Discord where people will often bring up issues like this that are more "feedback" in nature!)

I will mention this to @bholmesdev and other core members who may decide to remove this template entirely (as we've recently done with a couple of templates that seemed similarly less useful now). I'm not sure whether they will consider a Prism template useful to add in its place, but I do think it at least makes sense to decide whether this Shiki template is still useful.

**Comment by bholmesdev** [comment]
Thanks @sarah11918! Just discussed with core, and it sounds like a `with-prism` would be pretty helpful as a link from our docs. I'm in favor of creating a `with-prism`!
