### ISSUE TITLE
Minor: Type checking: --noEmit likely redundant

### ISSUE THREAD

**Issue by mrienstra** [withastro/docs#1566]
https://docs.astro.build/en/guides/typescript/#type-checking suggests `tsc --noEmit`, but `noEmit` is included in [packages/astro/tsconfigs/base.json](https://github.com/withastro/astro/blob/77ce6be/packages/astro/tsconfigs/base.json#L13-L14), which most Astro project will use (included automatically in all projects generated  with `create-astro`). A few thoughts:

1. Part of me feels like it should be removed ("tsc ~--noEmit~" --> `tsc`), as it isn't needed, and someone doing a quick drive-by of the docs might end up assuming it's necessary, and also then expect `tsc` without `--noEmit` to generate compiler output. Obviously they could pretty easily learn otherwise through trial-and-error or searching the Astro source code for "noEmit".

2. On the other hand, it doesn't hurt to have it there, and it makes it immediately obvious what the command will do. Also, some projects may not be using one of the Astro-provided tsconfig templates (e.g. manual install).

So... Leaning toward calling it good as-is, but my inner perfectionist wants to (A) remove it or (B) add a note about it being redundant when `tsconfigs/base.json` is in effect. 🤔

**Comment by sarah11918** [comment]
Now that we've done so much TS doc'ing lately... I'm going to ask @Princesseuh if she'd like to weigh in on this!

It sounds like the docs are not *wrong* currently, just maybe suggesting something redundant for some (most?) people. I am happy to follow Erika's lead on this one as to what is most helpful to have.
