### ISSUE TITLE
Document dynamic tag limitation

### ISSUE THREAD

**Issue by delucis** [withastro/docs#1587]
We document a useful dynamic tags pattern here: https://docs.astro.build/en/core-concepts/astro-components/#dynamic-tags

TIL that this does not work for `client:*` components and we should document this caveat.

Details here: https://discord.com/channels/830184174198718474/1021446382982266910/1021468769102598206

**Comment by sarah11918** [comment]
I think this was closed by #1596? Closing here, but reopen if I got this wrong!

**Comment by delucis** [comment]
Yes! Thank you 💜
