### ISSUE TITLE
Cannot access MDX exports in layout file

### ISSUE THREAD

**Issue by connor-baer** [withastro/docs#1589]
### What version of `astro` are you using?

1.2.6

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Variables that are exported from an MDX file aren't accessible in the layout component.

```mdx
// pages/posts/example.mdx
---
layout: '../../layouts/post.astro'
---

export const published = new Date('2022-09-17');

Here's some markdown...
```

```astro
// layouts/post.astro
---
// published is undefined
const { published } = Astro.props;
---

<p>Published on: {published}.</p>
<slot />
```

The docs on [MDX variables](https://docs.astro.build/en/guides/integrations-guide/mdx/#variables) state:

> MDX supports export statements to add variables to your templates. These variables are accessible both from the template itself _and_ as named properties when importing the template somewhere else.

I've verified that the exported variables are accessible when importing the MDX file individually or using a glob.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-7oqnyx?file=src/layouts/post.astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by sarah11918** [comment]
Closing this issue, as I believe Docs shows an example of this now. (importing the layout component, and then passing both something defined in frontmatter, and something defined not in frontmatter as props)
