### ISSUE TITLE
Update/New Option for Fetching Remote Markdown

### ISSUE THREAD

**Issue by BryceRussell** [withastro/docs#1590]
Currently the section on [Fetching Remote Markdown](https://docs.astro.build/en/guides/markdown-content/#fetching-remote-markdown) states:

> This will not inherit from any of Astro’s built-in Markdown and MDX settings that you have configured

But there is a community made package that allows you to do this [@astropub/md](https://github.com/astro-community/md) which makes it easier to have parity between rendering markdown from files and strings from remote sources

I want to suggest that the docs mention this package as an option and that it can integrate with your current markdown settings in Astro unlike other options

**Comment by delucis** [comment]
Does this work in SSR deployments? Looks similar to Astro's `<Markdown>` component (down to using the same Astro internals). That is now in a separate package and not recommended because of its lack of SSR support.

**Comment by BryceRussell** [comment]
I thought it did work with SSR but I have only used the dev server and have never tested a deploy so I deployed a small test to Netlify and I got this error

`Error - Cannot find package 'remark-gfm' imported from /var/task/.netlify/functions-internal/entry.js`

So like you said it looks like it doesn't work with SSR which is sad because it is an otherwise awesome package, I will have to keep this in mind when I recommend this package to others.

I guess it would be too much of an edge case to explain that configuration inheritance only works using two packages with SSG

**Comment by delucis** [comment]
Right — both those external packages are cool but maybe we should leave them to document their caveats as we can’t cover all of that in the main Astro docs. In the meantime the documented solution should work although it is a shame it can’t support the full power of the remark ecosystem.

I’ll close this for now, but thanks for bringing it up!

**Comment by almereyda** [comment]
There is `@astropub/md` now, which uses `@astrojs/markdown-remark` and depends on `astro@^3.0.0`.
