### ISSUE TITLE
Param can be a numer or not?

### ISSUE THREAD

**Issue by angelcervera** [withastro/docs#1591]
From the [documentation](https://docs.astro.build/en/reference/api-reference/#params):
```
For example, suppose that you have a page at src/pages/posts/[id].astro. If you export getStaticPaths from this page and return the following for paths:

---
export async function getStaticPaths() {
  return [
    { params: { id: '1' } },
    { params: { id: '2' } },
    { params: { id:  3  } }  // Can be a number too!
  ];
}

const { id } = Astro.params;
---
<h1>{id}</h1>
Then Astro will statically generate posts/1, posts/2, and posts/3 at build time.
```
So the comment is clear: **``{ params: { id:  3  } }  // Can be a number too!``**

but if executing this code, I get the following error, so looks like it cannot be a number!:
```
07:09:57 [getStaticPaths] invalid path param: id. A string value was expected, but got `3`.
```

What is wrong? The documentation or Astro engine? I'm using **astro 1.2.3**

**Comment by delucis** [comment]
Thanks for the issue @angelcervera! Just checked with the core team and it sounds like the docs are outdated and we shouldn’t show that line where a param can be a number.

Would you like to open a PR fixing this or should I?

**Comment by angelcervera** [comment]
@delucis I would fix it, but not sure if is a bug in the documentation or in the implementation. Could you confirm that the documentation is outdated?

**Comment by angelcervera** [comment]
@delucis Create PR #1594
