### ISSUE TITLE
Escape `--flags` in Discord CongratsBot

### ISSUE THREAD

**Issue by delucis** [withastro/docs#1615]
We generate a Discord post congratulating commit authors using [a workflow](https://github.com/withastro/docs/blob/main/.github/workflows/discord-congrats.yml) and [custom script](https://github.com/withastro/docs/blob/main/scripts/congrats-bot.mjs).

A couple of times now, commits containing something like a shell flag, e.g. `--template` or `--experimental-integrations`, has broken the formatting, with the flag and everything following it omitted from the Discord output. Here’s the result of [a recent example run](https://github.com/withastro/docs/actions/runs/3111970690/jobs/5044872096):

<img width="424" alt="Screenshot of Congrats Bot Discord message reading “🚀 Merged! Mayank: [`Document create-astro”" src="https://user-images.githubusercontent.com/357379/191960018-797d7344-bf8e-4eac-9a2a-0aedf1a3dfda.png">

We probably need to escape flags starting with two hyphens somehow.

**Comment by Lofty-Brambles** [comment]
This seems like a really easy fix, I'd like to work on it!
[Just a question, would this be considered as a hacktoberfest PR? Then I'd wait a day, otherwise it should be done in a bit.]

**Comment by sarah11918** [comment]
@Lofty-Brambles Wait a day!  😉  And thank you!  🥳

**Comment by Lofty-Brambles** [comment]
The script should be working properly - did a sneaky substitution there 🤣
