### ISSUE TITLE
Docker Deployment docs

### ISSUE THREAD

**Issue by jackmerrill** [withastro/docs#1667]
I've noticed the docs prioritize Astro deployment with serverless (or static) hosts. I personally use Docker for deploying things on non-serverless hosts, so I feel others should be able to do the same without having to do any research.

I can easily make a tutorial and make a PR.

LMK if anyone has any questions!

**Comment by zenflow** [comment]
I'm definitely interested in this, and a bit surprised that we don't already have it, since it's a generic non-vendor-specific way to deploy apps.

**Comment by zenflow** [comment]
I guess the way to deploy with Docker is basically just
1. use the [@astro/node adapter](https://docs.astro.build/en/guides/integrations-guide/node/) in "standalone" mode
2. Dockerize as you would a normal Node.js app

**Comment by Tobeworks** [comment]
So long this can be used for deploying to AWS or GCP, too:

Dockerfile
```
FROM node:16.14 AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build -- --mode custom

FROM nginx:alpine
COPY ./nginx/nginx.conf /etc/nginx/nginx.conf
COPY --from=build /app/dist /usr/share/nginx/html
```
nginx.conf
```
worker_processes  1;

events {
  worker_connections  1024;
}

http {
  server {
    listen 8080;
    server_name  localhost;

    root   /usr/share/nginx/html;
    index  index.html index.htm;
    include /etc/nginx/mime.types;

    gzip on;
    gzip_min_length 1000;
    gzip_proxied expired no-cache no-store private auth;
    gzip_types text/plain text/css application/json application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript;

    location / {
      try_files $uri $uri/ /index.html;
    }
  }
}
```


Build:
```
docker build --pull --rm -f 'Dockerfile' -t yourastro '.'
```
Docker run (Port 8080):
```
docker run  -p 8088:8080 yourastro
```

**Comment by delucis** [comment]
Thanks for the issue! Does seem like this could be helpful content maybe. If anyone’s interested in picking this up as a contribution, that would be great!

**Comment by etmartinkazoo** [comment]
Creating a deployment guide for Docker might be difficult for a number of reasons. Primarily, there are a lot of considerations regarding Nginx and whether to Dockerize it, Encryption certificates, etc...

I think having a variety of production deployment options like Netlify and others works well. Keeping up with custom Docker deployments might be a lot to continue to keep up on. I'd be happy to be wrong though.

Regarding a Docker development environment, I use the following as a *very* simple foundation:
`Dockerfile`
```
FROM node:18-alpine
RUN apk add --no-cache bash git
USER node
WORKDIR /code
```
`docker-compose.yml`
```
version: "3"
services:
  web:
    build: .
    restart: always
    user: node
    ports:
      - "3000:3000"
    volumes:
      - .:/code
    tty: true
    stdin_open: true
```
I append ` --host 0.0.0.0 --port 3000` to `astro dev` in the scripts object inside of the `package.json` file.

From here it is straight forward to run `docker-compose up` and then in a new terminal window/tab `docker-compose exec web bash` to have a shell out of which to work.

**Comment by sarah11918** [comment]
Just following up here to see if anyone would like to contribute.

One idea: our CMS guides (and in-review Migration guides) have the concept of a "stub" page: something that's not a full guide, but at least a placeholder for content, and links to external/community resources. (e.g. https://docs.astro.build/en/guides/cms/payload/ )

If it's difficult to provide generic advice, we could consider making a "stub" deploy page for Docker, and if anyone here would like to write their own blog post documenting their deployment setup, we can link to it from this page.

Is anyone still interested in this? @jackmerrill @zenflow @Tobeworks @etmartinkazoo

**Comment by ElianCodes** [comment]
Hey, just came across this issue, is it still wanted docs? I can be of help for sure!

**Comment by sarah11918** [comment]
Sure thing, @ElianCodes ! Seems to be popular!

**Comment by ElianCodes** [comment]
Yeah, Docker setups are a really big thing! I'll get working on it! Keep you posted.
