### ISSUE TITLE
Dev server slower boot time as of today

### ISSUE THREAD

**Issue by EricSimons** [withastro/docs#1695]
Hi all- I've been playing with this docs repo recently and noticed that today it was far slower to boot up. I _think_ the issue began after the [og-image PR](https://github.com/withastro/docs/commit/6b78cffd72d2989af88ac160c2ac62e9a287656d) was merged but not 100% sure. The terminal is also showing this error about `The language "txt" doesn't exist, falling back to plaintext.`: 

![Screen Shot 2022-10-02 at 8 25 13 PM](https://user-images.githubusercontent.com/556934/193496242-939f60e5-c6ef-479d-8485-9a920d683a78.png)

**Comment by Jutanium** [comment]
Thanks for reporting - we're all experiencing the same thing, and looking into it!
