### ISSUE TITLE
The Install Script is missed

### ISSUE THREAD

**Issue by zihan-ch** [withastro/docs#1696]
The install script in the docs is missed. It disappeared in all languages.
![Screenshot 2022-10-03 at 3 18 43 PM](https://user-images.githubusercontent.com/110709026/193521461-67e9e701-e1dc-42d6-bc68-6849e271d3a5.png)

Look at the Automatic CLI. The script disappeared. [See it here](https://docs.astro.build/de/install/auto/).

I am going to fix it.

**Comment by darkRaspberry** [comment]
The install script is there, Can you explain your issue.

**Comment by zihan-ch** [comment]
Sorry, my fault.

It is a little bit confusing😆. I thought that there must be a script (like shell or bash) under it, but now I found that it is actually for different ways to install it.
