### ISSUE TITLE
Document that `markdown.shikiConfig.theme` can be a relative path

### ISSUE THREAD

**Issue by delucis** [withastro/docs#1715]
It came up in a support thread recently that Shiki themes can be loaded by providing a relative path: https://discord.com/channels/830184174198718474/1026227648055222363/1026235701777412157

Would be great to add a small example [to the Markdown guide](https://docs.astro.build/en/guides/markdown-content/#shiki-configuration) as it’s not obvious what such a path should look like, but this is often nicer than passing lots of config options.

**Comment by nujovich** [comment]
Can I be assigned to this? I'd love to help

**Comment by kevinzunigacuellar** [comment]
> Can I be assigned to this? I'd love to help

You got it!
