### ISSUE TITLE
Update Markdown example showing rehype-minify plugin

### ISSUE THREAD

**Issue by sarah11918** [withastro/docs#1722]
Our example for Markdown plugins (https://docs.astro.build/en/guides/markdown-content/#markdown-plugins) shows a rehype-minify plugin being used. But, this is a collection of plugins, not a plugin itself. 

The plugin used in the example code should be replaced. Maybe the preset [`rehype-preset-minify`](https://github.com/rehypejs/rehype-minify/tree/main/packages/rehype-preset-minify) should be used instead? Maybe @bholmesdev has an opinion?

**Comment by Artur-Galstyan** [comment]
This is my astro config file using the rehype-preset-minify plugin, which leaves me with a "invalid input" error:

```
import { defineConfig } from 'astro/config';
import tailwind from "@astrojs/tailwind";
import deno from "@astrojs/deno";
import remarkMath from "remark-math";
import rehypeKatex from 'rehype-katex';
import rehypePresetMinify from 'rehype-preset-minify';

export default defineConfig({
  integrations: [tailwind({
    config: {
      applyBaseStyles: false
    }
  }),],
  markdown: {
    remarkPlugins: [remarkMath],
    rehypePlugins: [rehypeKatex, rehypePresetMinify],
    extendDefaultPlugins: true,
    shikiConfig: {
      theme: 'github-light',
      langs: [],
      wrap: false
    }
  },
  output: "server",
  adapter: deno()
});


```
