### ISSUE TITLE
Cookies: Needs guide + examples

### ISSUE THREAD

**Issue by Jutanium** [withastro/docs#1732]
Now that the [Cookies API](https://docs.astro.build/en/reference/api-reference/#astrocookies) is documented on our references page, we need to provide some instructional content and examples. 

This probably makes the most sense on the SSR page, as cookies are specific to SSR mode.

**Comment by wassfila** [comment]
I have an example I'd be happy to contribute it to the Astro examples if needed
https://github.com/MicroWebStacks/astro-examples#13_client-persistent-counter

**Comment by sarah11918** [comment]
Sounds great, @wassfila! 🙌 

Looking at the SSR page now, it seems like something alongside and approx the same length/depth as `Astro.request.headers` and `Astro.redirect` would fit. That is, a very basic, minimal usage example to show `Astro.cookies` in use, and then link to the reference page for the details. This page isn't the place for a full-featured example, but it would be nice to have a visual of it in use.

**Comment by pilcrowOnPaper** [comment]
I think this should be closed?

**Comment by delucis** [comment]
Oh yes, well spotted @pilcrowOnPaper! Thanks again @wassfila 🙌
