### ISSUE TITLE
Move `getStaticPaths` instructional content out of the reference page

### ISSUE THREAD

**Issue by Jutanium** [withastro/docs#1733]
The `getStaticPaths` content on our reference page is not reference content - it's better suited for a guides page. We link to it on our Routing guide, but that Routing guide should be the home for this content.

We've also gotten feedback that `getStaticPaths` is particularly difficult to understand, so it's worth revisiting how we explain it when we integrate it into that guides page.

**Comment by Jutanium** [comment]
The tutorial presents `getStaticPaths` in a more friendly beginner way; our docs could build off of that for our explanatory content.

The examples in the dynamic route section need another pass; we've seen support threads of people being confused by them.

**Comment by sarah11918** [comment]
Agreed that this could use another look at how the content is divided between pages.

In particular, and perhaps more urgently, now that each error message has their own page in the reference section, we should decide whether error messages should be their own category. Even the API reference docs for `getStaticPaths` are getting drowned out by error message returns.

And currently, `getStaticPaths()` is not even in a heading on the routing page, making it not visible in the right sidebar, but also, it doesn't show up in Algolia results AT ALL.  So urgently, Routing page should get a quick-fix heading for this. But, I also think these Algolia results are not as helpful as they could be.

![getStaticPathsAlgolia](https://user-images.githubusercontent.com/5098874/209950121-7a6fdfc9-0d5c-4e0d-ab25-19f2cba2bf8a.png)

**Comment by Jutanium** [comment]
Note that our search doesn't bring you to the routing page at all - headers need rewriting.
