### ISSUE TITLE
Elaborate on ecommerce in Why Astro

### ISSUE THREAD

**Issue by Jutanium** [withastro/docs#1736]
We've had several comments as to what we mean by
> Astro was designed for building content-rich websites. This includes most marketing sites, publishing sites, documentation sites, blogs, portfolios, and **some** ecommerce sites.

([Discord message](https://discord.com/channels/830184174198718474/853350631389265940/1027626981677875350), [support thread](https://discord.com/channels/830184174198718474/853350631389265940/1027652015662313563))

We could take the ecommerce mention out of that sentence and add a new sentence that describes in more detail Astro's suitability for ecommerce and some of the problems you might run into along the way.

**Comment by sarah11918** [comment]
Closing this for now, as adding an eCommerce guide is on the radar. Adding a new sentence there, at the top of the page, doesn't feel like the place for getting more into explanations. When we build more ecommerce content, we will likely have thought about this, have have a better way of expressing in this sentence. For now, it can stay!
