### ISSUE TITLE
Supporting "Open in gitpod" for quick document changes

### ISSUE THREAD

**Issue by naveennamani** [withastro/docs#1750]
As I've observed most of the recent pull requests consists of small document changes (like typos and translations) which requires the user to fork the repo, install all dependencies, test the changes and then push them.

This may not be a problem if the user is willing to contribute more than just typos, but in case of typos, this whole process is somewhat an overkill. So, I'm suggesting adding a .gitpod.yml file and an "Open in gitpod" button in the readme file. This way, the process of installing packages, starting a dev server can be automated and the user can quickly test the changes.

**Comment by sarah11918** [comment]
Thanks for bringing this up, @naveennamani . I saw your PR first so I've just commented there.

The reason the file was originally ignored was to prevent people commiting back their own custom Gitpod settings, which used to happen. For very small typo changes, we normally suggest people use the "edit this page" and edit directly on GitHub.com to avoid the kind of overkill you suggest. 

So, I'm not sure whether we actually want to revert the ignoring of the file, and I'm also not sure that setting the `gitpod.yml` is going to be wanted by everyone. I can tell you that right now I do also have mine configured to open on port 3000 as part of the file in the one branch I'm currently working on, and that opens a new browser tab every time the dev server is restarted, and everytime my Gitpod workspace times out and I restart it.. while I already *do* have a browser tab open to preview. So, I'm not convinced about that setting even for myself, after working with it for a while.

And as a side note, I'm glad you made the issue, but we normally don't suggest making a PR until the issue has been discussed and we've come to a consensus on the solution. PRs are our "inbox" of tasks to complete, and it's a little premature to put a PR there when there's an issue that we haven't even discussed yet. So in future, it's most helpful if you include right here in the issue a description of the PR you *would* make, so we can discuss it here!

**Comment by naveennamani** [comment]
> For very small typo changes, we normally suggest people use the "edit this page" and edit directly on GitHub.com to avoid the kind of overkill you suggest.

Yes, even I thought of the same after creating the PR 😅. But just wanted to know your team opinion and glad to know that you also use gitpod.yml as part of your work. This only gives me confidence that we can atleast have a discussion on this issue.

> but we normally don't suggest making a PR until the issue has been discussed and we've come to a consensus on the solution.

As it was rather a small change, I made PR also. Now the biggest decision is to whether accept it or reject it :)

**Comment by sarah11918** [comment]
Haha, always the decision!  😉 

Yes, many of Astro's team do use Gitpod, although perhaps me the most, and also @aFuzzyBear. I would be interested to hear what he thinks! Fuzzy, do you think removing the gitpod file from gitignore makes sense? Or are there any Gitpod settings we want to impose on everyone, all the time (and, I suppose keeping the file in gitignore so that no one ever commits it back and changes it.) 

Or then are we just imposing a setup on people who might end up stuck with things they don't want happening, like the browser automatically launching on them, etc.?
