### ISSUE TITLE
Add a link to the repo in the "More" section

### ISSUE THREAD

**Issue by Princesseuh** [withastro/docs#176]
In the more menu in the sidebar:

![image](https://user-images.githubusercontent.com/3019731/156175054-d1178b13-4522-4f08-9aed-e4807659110d.png)

I'd love to see a link the repo here added, in order to be able to quickly access it from the website itself, much like you can access the repo of Astro itself quickly on the main website by clicking the GitHub icon

**Comment by PatrickDrummond** [comment]
I'd like to take this on if possible

**Comment by sarah11918** [comment]
Thanks, @chriswburke ! I see the PR, so I'll close this issue because you stepped up, and I've requested that @Princesseuh review it. 

I can see this is your first contribution to the docs repository! Welcome!

**Comment by chriswburke** [comment]
Thanks @sarah11918! 🎉
