### ISSUE TITLE
Docs: Improvements for core-concepts/layouts

### ISSUE THREAD

**Issue by himanshu007-creator** [withastro/docs#1781]
In [core-concepts/layout page](https://docs.astro.build/en/core-concepts/layouts/#markdown-layouts), the markdown example can be improved to maontain continuity with above stated specifications, here (https://github.com/withastro/docs/blob/main/src/pages/en/core-concepts/layouts.md)

<img width="801" alt="Screenshot 2022-10-12 at 12 30 21 PM" src="https://user-images.githubusercontent.com/65963997/195272377-4c901ed7-1a2a-45c7-931d-6809531b1b91.png">

Improvements:
1) Comment the indication that the long text below the **---** will be shown in slot
2) **{frontmatter.author}** is useless as-of-now as there is no author defiend in above markdown file. Therefore we can add an author + utilise the description property from above markdown to maintain consistence. 

P.S: I would like to work on this issue and would like to be counted as a valid **hacktoberfest** contribution.

**Comment by sarah11918** [comment]
Hi @himanshu007-creator! 

I'd be happy to have you make a PR to address those two specific issues! Thank you for offering to work on this. I believe your improvements will be helpful. When you make the PR please do mention that it "closes" this issue 1781, and I'll apply the hacktoberfest label to it.  🎃
