### ISSUE TITLE
Integration Page missing Link to Prism Docs

### ISSUE THREAD

**Issue by Artur-Galstyan** [withastro/docs#1785]
On this website:
https://astro.build/integrations/official/

the integration box for Prism just links back to the main page instead of linking to this (for example):

https://docs.astro.build/en/reference/api-reference/#prism-

**Comment by ShaswatPrabhat** [comment]
Can I pick this up please @Artur-Galstyan ?

**Comment by Artur-Galstyan** [comment]
Of course 😊

**Comment by ShaswatPrabhat** [comment]
This would mostly mean a change in the `url` in `package.json` for the astro/prism package:

https://github.com/withastro/astro/blob/main/packages/astro-prism/package.json

Shall I rather open a PR against this package in the [astro](https://github.com/withastro/astro) repo ?

**Comment by ShaswatPrabhat** [comment]
Thank you for the detailed explanation @sarah11918 !

**Comment by sarah11918** [comment]
This was fixed! Thanks again for bringing it to our attention!
