### ISSUE TITLE
Missing documentation on slots and named slots

### ISSUE THREAD

**Issue by andersbc** [withastro/docs#179]
**UPDATE**: seems it for some reason was recently removed from the docs 1 day ago, at this commit: https://github.com/withastro/docs/commit/aece7ded51d191b37ada32f00c702a7f101dee23

----

https://docs.astro.build/en/core-concepts/layouts/#article says

> Learn more about how `<slot/>` works in our [Astro component guide.](https://docs.astro.build/en/core-concepts/astro-components/#slots)

.. but slots are not mentioned in the linked component page.

Also when I search the docs for `slot` (via the built in search ui) it doesn't come op (the only hits are the layout page and api references)

**Comment by sarah11918** [comment]
Thanks! I'll track this down!

**Comment by sarah11918** [comment]
Up on the site now, thanks again!

https://docs.astro.build/en/guides/slots/
