### ISSUE TITLE
Safari on macOS: Poor rendering performance 

### ISSUE THREAD

**Issue by getflourish** [withastro/docs#1790]
**Problem**
Browsing and scrolling through the docs is very slow and laggy. High CPU usage. Especially when code blocks come into view.

- Intel MacBook Pro, 8 GB RAM
- macOS 12.4 
- Safari 
 
**Screen recording**
You can see poor scrolling performance, invisible content, flickering content.

- excessive CPU usage
- excessive memory usage, up to 300 MB graphics memory when scrolling

https://user-images.githubusercontent.com/183989/195606103-14cebfb3-9c73-41f6-b34e-347eb41aa435.mov

**Troubleshooting**
- Removing the filter seems to resolve the issue

<img width="495" alt="image" src="https://user-images.githubusercontent.com/183989/195604770-ef066b19-c8fe-4243-96c9-4315b122699e.png">

You probably won’t see this on a M1 or M2. The issue is running the site on an older Macbook on a 5K display. But it’s a sign that there’s a potential issue for anyone with older hardware. With my setup I can spot performance issues in any three.js site, Figma, etc. 😄 But it doesn’t mean that everything is slow. It’s just a sign that there might be excessive graphics memory used (e.g. massive sized layers)

**Comment by getflourish** [comment]
I think the issue in general are the amount of layers created. One reasons is the use of `filter`. The other issue is the opacity on `.heading-wrapper > .anchor-link`.

- 70 layers
- 344 MB memory
-  1529x16513 px compositing

<img width="1082" alt="image" src="https://user-images.githubusercontent.com/183989/195608606-e481ef37-f72a-41ac-9940-04409a8713f8.png">

**Comment by sarah11918** [comment]
Thanks for this! Pinging @hippotastic so that he sees it, too!

**Comment by getflourish** [comment]
Layers with and without the CSS filter. 84 layers vs. 14 layers. Together with the fixed elements on the page (body::before gradient and fixed sidebars) Safari starts sweating. Removing the filter alone doesn’t make performance perfect but acceptable :)


<img width="1082" alt="Bildschirmfoto 2022-10-14 um 07 16 42" src="https://user-images.githubusercontent.com/183989/195767853-a78e048a-5aac-479c-b007-1ca20275fd59.png">


<img width="1082" alt="Bildschirmfoto 2022-10-14 um 07 16 54" src="https://user-images.githubusercontent.com/183989/195767869-e28f0ec8-e943-4630-8c3e-506a6af163fd.png">

**Comment by sarah11918** [comment]
As the docs site has just had an entire makeover, converted to MDX, does anyone care to take a look at this again and see whether the problem still exists? or exists to the same extent?

**Comment by delucis** [comment]
Pretty sure this is as “simple” as dropping `drop-shadow` here:

https://github.com/withastro/docs/blob/0bb3e8f9380bbdff7910ad226570c09a717dedde/src/components/CodeSnippet/CodeSnippet.astro#L143

We can probably get a similar effect with a `box-shadow` or two although it’s not quite the same thing. If no-one tackles this, we might very probably change this style when redesigning docs in the new year, so will certainly bear this in mind then.

**Comment by getflourish** [comment]
FYI:

The issue still exists on my old MacBook Pro.
I have a new MacBook Air M2 with no issues (as expected).

I hate to report these niche issues related to hardware :'(
