### ISSUE TITLE
A video on @astrojs/tailwind page plays the voice only on left audio channel

### ISSUE THREAD

**Issue by qyurila** [withastro/docs#1802]
The installation guide video on [@astrojs/tailwind](https://docs.astro.build/en/guides/integrations-guide/tailwind/#installation) page has undesirable audio tracks. The voice is played only on left channel of stereo audio tracks. It makes one very uncomfortable when playing the video with their earphones or headphones.

It's possibly because of faulty record program or mic. Anyways, it can be fixed easily by re-encoding. The video should have a mono track or stereo tracks which are almost no difference.

**Comment by stefkudla** [comment]
Went ahead and re-processed the audio for this one: https://imgix.cosmicjs.com/84c3f5b0-5211-11ed-89d4-853fd6bb9a28-AstroTailwindCSSmonoaudio.mp4

**Comment by qyurila** [comment]
@stefkudla Thank you for the fix, it sounds good now!

**Comment by sarah11918** [comment]
Thanks @qyurila for bringing this up! And thanks @stefkudla for the audio re-processing! 

I've assigned this to @Jutanium to review, and we'll see about getting this added to the Docs site.  🥳

**Comment by Jutanium** [comment]
Thank you @stefkudla! I reuploaded the video to GitHub and opened a PR to replace it.
