### ISSUE TITLE
Images: `format` prop is required for remote images

### ISSUE THREAD

**Issue by Jutanium** [withastro/docs#1892]
Following up on [this support thread](https://discord.com/channels/830184174198718474/1032660889318461482), the `format` attribute is _required_ for remote images. Let's note this when we [introduce remote images](https://discord.com/channels/830184174198718474/1032660889318461482).

**Comment by sarah11918** [comment]
Closing this, as we just updated the images guide and the integration README. It's now listed as required for `<Image />` and explains which default is used for `<Picture />` (so, it's not required there).
