### ISSUE TITLE
[nice-to-have] Add Fresh to framework comparison

### ISSUE THREAD

**Issue by olee** [withastro/docs#1898]
The [Fresh](https://fresh.deno.dev/) framework which is running on deno seems to serve a similar purpose as Astro and it would probably be nice to also include this https://docs.astro.build/en/comparing-astro-vs-other-tools/

**Comment by delucis** [comment]
Thanks for the suggestion @olee!

We’re not actively maintaining that page anymore as we found it hard to keep up with updates to all the different frameworks, so I don’t think we’re likely to find time to add new content.

I think this could be great material for a blog post comparing island architecture/performance between Fresh and Astro though.
