### ISSUE TITLE
Typos in tutorial page "Generate tag pages"

### ISSUE THREAD

**Issue by ScriptRaccoon** [withastro/docs#1949]
On the tutorial page [Generate tag pages](https://docs.astro.build/en/tutorial/5-astro-api/2/) there are several typos in the file names and file paths.

1. "src/pages/tags/[tag]" has to be replaced by "src/pages/tags/[tag].astro". 
2. "src/pages/posts/tags/[tag].astro" has to be replaced by "src/pages/tags/[tag].astro" (many times)
3. "/src/pages/posts/tags/[tag]" has to be replaced by "src/pages/tags/[tag].astro"
4. "src/pages/tags/index.astro" refers to a page which has not been created before, so I am not sure if the file name is correct. That file will be created only in the [next lesson](https://docs.astro.build/en/tutorial/5-astro-api/3/). I assume it has to be "src/pages/tags/[tag].astro" again.

**Comment by delucis** [comment]
Thanks so much for reporting these! Would you be up for creating a PR fixing these?

**Comment by ScriptRaccoon** [comment]
> Thanks so much for reporting these! Would you be up for creating a PR fixing these?

Unfortunately I am not able to do so in the next days. But (if nobody comes first) I can do it in about one week.
