### ISSUE TITLE
There is no example simple code on how to write an Astro integration in the docs

### ISSUE THREAD

**Issue by kyr0** [withastro/docs#1969]
Hi all,

as discussed on Discord with @sarah11918, I'd like to open this issue to bring the following topic to our awareness:

In this section: https://docs.astro.build/en/guides/integrations-guide/#building-your-own-integration it is explained that a developer can implement an integration on their own, but the section only refers to the API reference which just explains the datatypes on what Astro would expect in an integration. The API reference also names example integrations but if you click on them, you're routed to pages that explain how to use them, not how to write your own. 

Thus, the exact way on how to implement your own integration remains unclear until you find and read the code of rather complex existing integrations. This is not easy for beginners and makes it harder for people to come up with new integrations for Astro.

I'd propose to add the following paragraph and example code to the section, below:

----

> Astro’s Integration API is inspired by Rollup and Vite, and designed to feel familiar to anyone who has ever written a Rollup or Vite plugin before.

Here is, how a simple integration could be implemented:

````ts
// in myCustomIntegration.ts
import type { AstroConfig, AstroIntegration } from 'astro'

interface MyCustomIntegrationOptions {
    message: string
}

// this integration prints the Astro config and a message after each build
export const myCustomIntegration = (options: MyCustomIntegrationOptions): AstroIntegration => {
  let config: AstroConfig
  return {
    name: 'myCustomIntegration',
    
    // you can register for different hooks (see API reference)
    hooks: {
    
      // this hook function is called by Astro when the config has been processed
      'astro:config:done': async (result) => {
      
        // we store the config in case we need to access the config object in other hooks
        config = result.config
        
        console.log('Astro config is ready:', config)
      },

      // this hook function is called by Astro when a build is done
      'astro:build:done': async ({ dir, pages }) => {
        console.log(options.message, pages)
      },
    },
  }
}
````

Every integration can be implemented in your project by simply calling it's function with the options provided:
````ts
// in astro.config.ts
import { defineConfig } from 'astro/config'
import { myCustomIntegration } from './myCustomIntegration'

export default defineConfig({
  ...
  integrations: [myCustomIntegration({ message: 'Another build is done' })],
})
````

Check out the [Integration API](https://docs.astro.build/en/reference/integrations-reference/) reference to learn about the different hooks that are available to customize your Astro projects lifecycle.

----
With such an addition it would be clear how to implement your own integration at first sight - even for beginners.

edit: The example can also be further simplified and the integration function could even be moved into astro.config.ts (or mjs) but usually a developer wouldn't do this because it's not so clean. 

edit 2: Here is a working demo: 
https://codesandbox.io/s/peaceful-benji-oo3j7m?file=/astro.config.ts:0-1149

If you wanna try it in the demo, please find the "+" button in the "console" tab and click it (top right corner).

<img width="771" alt="Bildschirmfoto 2022-11-01 um 23 30 57" src="https://user-images.githubusercontent.com/454817/199354187-891d58f6-1249-4bbd-aa34-745be84d88bf.png">

 A new console will open.
Write the command "yarn build" to execute a build with [ENTER]:

<img width="748" alt="Bildschirmfoto 2022-11-01 um 23 31 23" src="https://user-images.githubusercontent.com/454817/199354520-6360351f-429c-45fa-b0da-e60ad59bea06.png">

The result should look like this and show the integration working:

<img width="747" alt="Bildschirmfoto 2022-11-01 um 23 31 44" src="https://user-images.githubusercontent.com/454817/199354287-e768fc59-c260-4f96-9be0-85f16ba0967a.png">

You can also scroll up and see the config printed..

Please let me know what you think :)

Thanks and best,
Aron

**Comment by Jutanium** [comment]
We do have an [integration example](https://github.com/withastro/astro/tree/main/examples/integration) in the monorepo, but this is hard to discover. We could link to it as a quick, though I agree that more instructional content around integrations would be helpful!

**Comment by delucis** [comment]
Adding here that we have an older issue that asked about how to set up and test an integration package: https://github.com/withastro/docs/issues/414

Here’s the original issue text from @roblevintennis:

> Capturing the idea that we should show instructions for setting up a local dev env and testing a non-internal integration (see [this comment](https://github.com/withastro/docs/pull/388#issuecomment-1112041968)) per @bholmesdev request. One will need to configure their own `tsconfig` as `astro-scripts` which is typically used within astro's main monorepo is not available. Also, many folks new to npm publishing won't be aware of tooling like `npm pack` etc., so a hello world example of all this will help them get to a place where they can contribute.
>
> Here's a small readme [showing how I did it](https://github.com/AgnosticUI/agnosticui/tree/master/integrations/agnosticui-astro#getting-started) (and the integration seems to be working in this repo link too if you follow those instructions); but I believe Ben wants to investigate if there's a cleaner `pnpm` way to approach to this :)

This could be a stretch goal of any future integration guide!

**Comment by kyr0** [comment]
Yeah cool, just tell me what would be the next steps here. I'd like to contribute but I don't know the process.

**Comment by sarah11918** [comment]
Just following up on this issue that I think just missed our big "Issue Triage!"

@kyr0 if you are still interested in adding to this section of the page then let us know what you need from us to do that! If you're not sure how to get started with the Docs repo itself, one of the quickest ways is to click on "Edit this page" from that page in docs (since you're proposing changes to one single page). There, you can use the GitHub web interface to "edit" the page and submit a PR that way. Once it's a PR, we can all see a preview and make edits/suggestions as we refine it there.

If anything else can help you with this, then let us know! If you're no longer interested in a contribution like this, then I can add a "help wanted" label for someone else to pick it up from here.  🙌

**Comment by sarah11918** [comment]
I am closing this because no one has seemed to want to contribute and we haven't had any requests for this lately . It can still be reopened in the future!

**Comment by wassfila** [comment]
@sarah11918 as pointed out on discord, I have a simple yet efficient approach how to bring something to this topic

It's easy, the idea is to show how to create an integration that does literally nothing. The confusing things about integrations is not to understand the API one by one, but rather :

* the workflow, when does what run ?
* How to get started and create a simple example

In all existing examples, people ~~abuse~~ take advantage of JavaScript ability to embed callback functions everywhere, which looses new comers on understanding what is called where

Myself, I never created an integration yet, so would prefer to have some assistance, if not, what I commit to is simply adding an example guide here 

https://docs.astro.build/en/guides/integrations-guide/

with this 

```javascript

...

async function build_done({ pages, dir, routes }){
	console.log(`astro:build:done> @ (${dir})`)
}

function int_test(options){
	return {
		name: 'int_test',
		hooks: {
			'astro:config:setup': config_setup,
			'astro:config:done' : config_done,
			'astro:server:setup': server_setup,
			'astro:server:start': server_start,
			'astro:server:done' : server_done,
			'astro:build:start'	: build_start,
			'astro:build:setup'	: build_setup,
			'astro:build:generated'	: build_generated,
			'astro:build:ssr'	: build_ssr,
			'astro:build:done'	: build_done,
		},
	};
}

```

not sure if the output should be part of the guide, but that's the revelation when people see the log, also another trick of having it in a different color, which complicates the example that I left with a simple console.log
![image](https://user-images.githubusercontent.com/1510763/210182218-2c7b1446-2761-4a8b-9449-7b647442a83a.png)

**Comment by wassfila** [comment]
In case we think output is relevant and helpful, the green color could be replaced with highlighted lines

```cmd
astro:config:setup> running (build) 
 astro:config:done> 
 astro:build:start> 
08:10:44 PM [build] output target: server
08:10:44 PM [build] deploy adapter: @astrojs/node
08:10:44 PM [build] Collecting build info...
08:10:44 PM [build] Completed in 95ms.
08:10:44 PM [build] Building server entrypoints...
 astro:build:setup> target = (server) 
08:11:02 PM [build] Completed in 17.78s.
 astro:build:ssr> 
 
 finalizing server assets 

08:11:04 PM [build] Rearranging server assets...
 astro:build:done> @ (file:///home/projects/mklipvbwp.github/dist/client/) 
08:11:04 PM [build] Server built in 19.96s
08:11:04 PM [build] Complete!
```

**Comment by leen-neel** [comment]
In address to this issue, I've written a quick guide and opened #2273 
Any tips and suggestions would be greatly appreciated.

Best regards,
Neel

**Comment by sarah11918** [comment]
Just following up on this! I know @leen-neel has started the ball rolling with a draft PR. @wassfila, is that something you're interested in taking a look over and commenting on?

The PR is in draft mode because we have had to prioritize some other content while getting V2 ready, moving the repo to content collections, doing some docs reorganization. So, I marked it as draft so it could at least be there for working on in the mean time.

Now that we are getting closer to being able to spend time on it, I'll assign this to @Jutanium to keep track of, but anyone here who wants to help contribute the content is welcome!  🥳

**Comment by wassfila** [comment]
sure, I will make a review

**Comment by Jutanium** [comment]
Ideally, this becomes a recipe - or multiple recipes - that show real-world examples of integrations. It's not enough to use all the hooks - a reader needs to learn what you can do _inside_ a hook.

**Comment by delucis** [comment]
Mentioning that there is a third-party Astro guide that was published recently and includes a “How to build an integration” section: https://www.freecodecamp.org/news/how-to-use-the-astro-ui-framework/#chapter-8-build-your-own-astro-integrations-1

Might make a helpful community recipe link?

**Comment by bholmesdev** [comment]
This sounds like a perfect recipe opportunity. Go for it @leen-neel!

**Comment by sarah11918** [comment]
Closing this issue in part for inactivity, and in part because we are not accepting big community contributions to docs until docs has migrated to Starlight so we can handle the migration.

If anyone wants to write and publish a blog post, or PR the freecodecamp article listed here to the community recipes page, please do! But Docs will not be writing this at this time! We'd like to in future, though!
