### ISSUE TITLE
Search bar is harder to click because of the language dropdown

### ISSUE THREAD

**Issue by surjithctly** [withastro/docs#1972]
If you take 100 times, you want to click on the search bar 99 times, people would only change language once or twice. 

The current design makes it hard to click the search button, most of the time I end up clicking the dropdown instead. See the current design and proposed solution. Also the search button height & width needs to be big to match with the layout. 

**Current Design**

 
<img width="610" alt="Current" src="https://user-images.githubusercontent.com/1884712/199461698-c3a5642b-e917-4cc8-8ac1-65aaea28962f.png">

**Proposed Solution**

<img width="610" alt="Proposed" src="https://user-images.githubusercontent.com/1884712/199462172-cc447151-3c72-41c8-a1c8-abf7767a1a22.png">

**Comment by sarah11918** [comment]
Hi there!  

We've actually discussed this a lot 😅  and we have decided against a smaller language picker. You can see the open issue #618 (towards the bottom, this comes up and we discuss some strategies and what will/won't work for us) and the PR that we recently merged to distinguish the two is here: https://github.com/withastro/docs/pull/1583 

So, I'm going to close this issue and ask you to continue with any thoughts in #618 where this conversation is already happening! There are still aspects of our search that we'd like to improve, and we may not have this visually perfect yet. But the answer isn't as simple as it seems... 😄

**Comment by kyr0** [comment]
I'd like to add here that storing the language setting in localStorage would be desirable too. I don't know how often I had to switch from german to english - it's a few lines of code only; I can provide a pure TS solution that also covers "private mode" edge cases (when using localStorage might throw errors in some browsers).
