### ISSUE TITLE
Add Tencent Cloud deploy guide

### ISSUE THREAD

**Issue by kyoukhana** [withastro/docs#1979]
Astro is Amazing.

Most of Astro supports deployment to GCP, AWS, Netlify and Vercel.  But all of these servers have limited support to Asian countries especially China.  one of the cloud providers I have researched is the following below

https://www.tencentcloud.com/

It would be good to start a discussion on this on how can we get some kind of deployment process for this.

**Comment by delucis** [comment]
Thanks @kyoukhana! We'd definitely be happy to see a new page added to our deploy guides documenting this platform. Would you be interested in making a PR?

**Comment by kyoukhana** [comment]
I am actually trying to work with Tencent Cloud CD/CI pipeline to deploy a Astro project.  First starting with Basic NodeJS then will move ahead with a Astro project

**Comment by sarah11918** [comment]
I am going to close this issue due to inactivity. But, we would welcome a PR to our deploy docs @kyoukhana! It's just not an outstanding issue that we intend to track. So when you're ready, come back with a PR!  :partying_face:
