### ISSUE TITLE
exported variables in Astro files can be accessed through Astro.glob() (this is not mentioned in the documentation) 

### ISSUE THREAD

**Issue by amirvahidian** [withastro/docs#2001]
Hello,

I am not sure whether this is a feature or just something that works for the time being but I found out that variables in Astro files that are imported through the Astro.glob() function can be accessed if the variables are exported.

If I want to use Astro.glob() to import an Astro file along with some of its variables, all I need to do is to export the variables in the Astro file:

```
someAstroFile.astro

---
export let someVariable ="someValue"; 
---

<div></div>
```

In the Astro file which uses astro.glob() to import the file/files I can have access to that variable:

```
someAstroFileToImportOtherFiles.astro

---
const astroFiles = await Astro.glob("./folder-with-astro-files/*.astro")
---

<Layout>
  {astroFiles.map((astroFile) => <div>{astroFile.someVariable}</div>)}
</Layout>
```

The IDE I am using gives a warning that the property 'someVariable' does not exist on type 'AstroInstance' but regardless it works in development and build.

If this is a feature, I think it would be useful to mention it in the documentation.

P.S I am not sure maybe this is something very obvious and does not even need to be mentioned :)

**Comment by Jutanium** [comment]
Closing as this is an inconsistent feature that shouldn't be documented!
