### ISSUE TITLE
Emphasis on introducing component props in tutorial

### ISSUE THREAD

**Issue by naveennamani** [withastro/docs#2011]
In the tutorial when introducing social media component at https://docs.astro.build/en/tutorial/3-components/2/#create-a-social-media-component `Astro.props` was used for the first time. And there was no mention about what are props, how you can pass them to components and how you can access them in the components. The example straight away introduce this concept and encourages user to copy paste the code.

There was a reference to component props basics at the end of the page, but a brief introduction can be given about the component props or link to the basics can be mentioned before beginning of this header https://docs.astro.build/en/tutorial/3-components/2/#create-a-social-media-component so that interested readers can cover the basics to understand what they'll be doing.

The following file is the source code
https://github.com/withastro/docs/blob/main/src/pages/en/tutorial/3-components/2.md

**Comment by delucis** [comment]
I think this should have been closed by https://github.com/withastro/docs/pull/2023 which added a brief intro about props to 3.2 exactly like you suggest here. I’ll close as done, but if you think there’s anything still missing, let us know!
