### ISSUE TITLE
*dynamic* fetch() in framework components?

### ISSUE THREAD

**Issue by zenflow** [withastro/docs#2016]
This section of the documentation has me wondering: https://docs.astro.build/en/guides/data-fetching/#fetch-in-framework-components

The fetch() is done outside the component definition, so it doesn't receive the component's props.

Is there any way to fetch() based on the component's props?

Something like this?

```jsx
function Movie ({ movieId }) {
   const data = await fetch(`https://example.com/movie/${movieId}.json`).then(res => res.json());
   return <div>{JSON.stringify(data)}</div>;
}
```

**Comment by MoustaphaDev** [comment]
You can't do that unfortunately as react/preact components can't be asynchronous.
A workaround I'm thinking about would be to wrap the react component inside an Astro component, do the data fetching at that level and pass the result down to your react component as props.

**Comment by dsomel21** [comment]
I had a similar question regarding Dyanmic vs Reactive. 

I haven't received an answer, but this is what I proposed:

<img width="1006" alt="SomeQuestions" src="https://user-images.githubusercontent.com/17516559/202922422-998716b2-bf81-491e-ae5b-c65219176e9a.png">

**Comment by sarah11918** [comment]
I'm going to close this issue since the original question has been answered. If there are further questions re: what Astro can/can't do, it would be great to take them to the Discord. If this leads to some changes or clarifications that need to be documented, then anyone is welcome to open another issue!
