### ISSUE TITLE
Invalid URL from MD docs

### ISSUE THREAD

**Issue by Astisme** [withastro/docs#2035]
At the [Markdown page](https://docs.astro.build/en/guides/markdown-content/#frontmatter-layout) of the documentation there's a snippet of code to try out the .md files with Astro.

I've set up the files like they are in the documentation
- src/pages/mark.md
- src/layouts/MarkLayout.astro

and I've copy-pasted the snippets given in both. I'm leaving the code for each below.

mark.md:
```
---
layout: ../layouts/MarkLayout.astro
title: Hellp, World!
author: John Doe
date: "09 Aug 2022"
---

# Hi there!

This is a test page.

This is your first markdown page. It probably isn't styled much, although
Markdown does support **bold** and _italics._

To learn more about adding a layout to your page, read the next section on **Markdown Layouts.**
```

MarkLayout.astro (without comments):
```
---
import type { MarkdownLayoutProps } from 'astro';

type Props = MarkdownLayoutProps<{
	title: string;
	author: string;
	date: string;
}>;
const { frontmatter, url } = Astro.props;
---


<html>
  <head>
    <meta rel="canonical" href={new URL(url, Astro.site).pathname} />
    <title>{frontmatter.title}</title>
  </head>
  <body>
    <h1>{frontmatter.title} by {frontmatter.author}</h1>
    <slot />
    <p>Written on: {frontmatter.date}</p>
  </body>
</html>
```

but there seems to be a problem with the `href` attribute because after using `npm run dev` and looking up `localhost:3000:mark` gives out this error:
![image](https://user-images.githubusercontent.com/96465880/201318354-8a7daefe-5e42-4c64-8b16-633bb2fc55af.png)

If I were to omit the `href` attribute of the `meta` tag, the page loads fine.
![image](https://user-images.githubusercontent.com/96465880/201318584-88f20773-0863-4005-85b2-3077832f096c.png)

Here I've also added
```
<br />md url: {url} |<br />astro site: {Astro.site} |
```
after the date so I could see what the website was getting for each of the components of `new URL` used in the docs.

PS: My editor (and a quick search) points out that there shouldn't be a `rel` and an `href` attributes inside a `meta` tag so I would consider swapping the `meta` for a `link` tag, which is fine inside of `head` and obviously accepts `rel` and `href`.

**Comment by delucis** [comment]
Hi @Astisme! I think the `Invalid URL` error might be because `Astro.site` is undefined. Does setting `site` in your `astro.config.mjs` file fix it?

Because in this case we can’t guarantee `Astro.site` is defined, it might make sense to remove the canonical tag from this layout example. (And you’re right, I we decided to keep it, it should be a `link` not `meta`!)

Would you be interested in submitting a PR removing that?

**Comment by Astisme** [comment]
Where and how should I set `site`?
I'm sure it's not here xD
```
export default defineConfig({
  output: "server",
  adapter: deno(),
  site: "localhost:3000",
});
```

I'm available to submit a PR.

**Comment by delucis** [comment]
Yes, that’s the right place! Just needs to be a full URL:

```js
export default defineConfig({
  output: "server",
  adapter: deno(),
  site: "http://localhost:3000",
});
```

> I'm available to submit a PR.

Awesome — thank you!

**Comment by Astisme** [comment]
Ok. Now it's working as expected!

**Comment by Astisme** [comment]
Where is the file to be changed? I'm getting lost ahah

**Comment by delucis** [comment]
I see you found it! 🙌 

The simplest is to go to the page you want to edit and follow the “Edit this page” link in the right sidebar, which will open up GitHub’s editor right in your browser.
