### ISSUE TITLE
Docs "search stats" investigation

### ISSUE THREAD

**Issue by sarah11918** [withastro/docs#2042]
Hey Team Docs!

We have our first "data dump" of the search terms people have been using on the Docs site. Since we know these are all popular searches, we want to make sure that people are being pointed to the best places in docs to answer their questions.

So, **we're looking for interested people to a) try searching some of these terms and b) report back here in a reply re: whether you think our search widget is currently helpful to our readers**, returning good results etc. 

Of particular interest, things like:

1. How many *different pages* were represented by these 5 results?
2. Was the **top result** the "best" suggestion (in your mind - the most helpful/general page on the topic)? If not, was the first search term result at least a "good" suggestion?
3. Was a page entirely missing from the results that probably *should* have been included? (e.g. You searched for Markdown and did *not* see "Markdown & MDX" as one of the 5 results.)
4. Do you think more results would be helpful for this search term?
5. Do you feel that someone looking at the 5 results gets enough info about each search result to know the best one to choose?

And any other observations are welcome!
 
This is the list of our most-searched for terms in Docs. It's fine if multiple people report back their observations for the same term, but in the interest of getting as many covered as possible, I'll come back periodically and check ones off this list if at least one person has replied with their observations.  (And, I might update and add to the questions above too, as I think of new things, so keep checking back!)

_🔍 = carried out before search overhaul; 🔎 = carried out after search overhaul_

- [x] [image — 🔍](https://github.com/withastro/docs/issues/2042#issuecomment-1312513289)
- [x] [react — 🔍](https://github.com/withastro/docs/issues/2042#issuecomment-1312723775)
- [x] [tailwind — 🔍](https://github.com/withastro/docs/issues/2042#issuecomment-1320485371)
- [x] [props — 🔎](https://github.com/withastro/docs/issues/2042#issuecomment-1338835317)
- [x] [script — 🔍](https://github.com/withastro/docs/issues/2042#issuecomment-1312213968)
- [x] [slot — 🔎](https://github.com/withastro/docs/issues/2042#issuecomment-1369334301)
- [ ] client
- [x] [glob — 🔎](https://github.com/withastro/docs/issues/2042#issuecomment-1426952111)
- [ ] ssr
- [ ] mdx
- [x] [css — 🔎](https://github.com/withastro/docs/issues/2042#issuecomment-1548229593)
- [ ] 404
- [ ] env
- [ ] vite
- [ ] build
- [x] [svg — 🔎](https://github.com/withastro/docs/issues/2042#issuecomment-1421579068)
- [x] [vue — 🔍](https://github.com/withastro/docs/issues/2042#issuecomment-1318754396)
- [ ] sass
- [ ] class
- [x] [redirect — 🔎](https://github.com/withastro/docs/issues/2042#issuecomment-1657429381)
- [ ] link
- [x] [onclick — 🔍](https://github.com/withastro/docs/issues/2042#issuecomment-1312089721) 

Others:

- [x] [getStaticPaths — 🔎](https://github.com/withastro/docs/issues/2042#issuecomment-1367305103)

**Comment by dreyfus92** [comment]
A few comments on `script` keyword:

1.- How many different pages were represented by these 5 results? **5**.
![image](https://user-images.githubusercontent.com/85648028/201434197-aad9cd0d-23a5-49ec-99d0-363f6037cfaf.png)

2.- Was the top result the "best" suggestion (in your mind - the most helpful/general page on the topic)? If not, was the first search term result at least a "good" suggestion? No,  I think that there should be results regarding the script tag or showing as the last result TypeScript section.

3.- Was a page entirely missing from the results that probably should have been included? (e.g. You searched for Markdown and did not see "Markdown & MDX" as one of the 5 results.)  No.

4.- Do you think more results would be helpful for this search term? Not really.

5.- Do you feel that someone looking at the 5 results gets enough info about each search result to know the best one to choose? Yeah I feel like the info is accurate and easy to understand.

**Comment by sarah11918** [comment]
Ooh, especially glad someone chose to do `script` since I just got this week's stats report, and that term jumped up to make it to #1 this week! (And, we *know* we want to analyze onClick, so great first choice!)  🚀

**Comment by sarah11918** [comment]
OK, so these are GREAT, and I'm loving the screenshots of the results! @dreyfus92 @the-dijkstra 

I mean, I'm not loving the *results*.. onClick and script are terrible!  But this is so incredibly helpful! It's great for docs planning, for sure. I'm hoping more people step up, but as you have time to try more of these, please do!  ❤️ 🚀

**Comment by dreyfus92** [comment]
### Keyword: `vue`

**1.-How many different pages were represented by these 5 results?** 5.

![image](https://user-images.githubusercontent.com/85648028/202477343-1c66a956-bcaf-4abe-ab62-61713d264e75.png)

**2.-Was the top result the "best" suggestion (in your mind - the most helpful/general page on the topic)? If not, was the first search term result at least a "good" suggestion?** Yes it was.

**3.-Was a page entirely missing from the results that probably should have been included? (e.g. You searched for Markdown and did not see "Markdown & MDX" as one of the 5 results.)** I don't think so.

**4.-Do you think more results would be helpful for this search term?** I think that the last 2 results should be changed cause the reference sends you to an icon that appears on the bottom of `@astrojs/solid-js` and `@astro/react` guides which doesn't  provide you anything anything relevant of Vue.

**5.-Do you feel that someone looking at the 5 results gets enough info about each search result to know the best one to choose?** Yeah I think so it is enough, but according to 4th question last 2 results should be changed.

**Comment by delucis** [comment]
These are so helpful! Thank you all. I hadn’t noticed that weird thing showing in both the `react` and `vue` searches that seem to also show pages where `react`/`vue` are in the navigation in the page footer. Definitely going to look at fixing that.

**Comment by kevinzunigacuellar** [comment]
<img width="574" alt="image" src="https://user-images.githubusercontent.com/46791833/202793961-23be2d43-7130-46d4-845e-843e31888d5a.png">

**Keyword** : `tailwind`

1. **How many different pages were represented by these 5 results?**

   There are 3 different pages.

2. **Was the top result the "best" suggestion (in your mind - the most helpful/general page on the topic)? If not, was the first search term result at least a "good" suggestion?**

   The top result was the best result in my opinion.

3. **Was a page entirely missing from the results that probably should have been included? (e.g. You searched for Markdown and did not see "Markdown & MDX" as one of the 5 results.)**

   No, I don't think there are missing pages.

4. **Do you think more results would be helpful for this search term?**

   I don't think so. The search results cover this term very well.

5. **Do you feel that someone looking at the 5 results gets enough info about each search result to know the best one to choose?**

   Yes, I think they get more than enough information.

**Comment by sarah11918** [comment]
I find it super-interesting that our CSS & Styling page was not a hit for Tailwind!  Not bad... just interesting!

**Comment by dreyfus92** [comment]
![image](https://user-images.githubusercontent.com/85648028/205836506-1ee6149b-b0fd-4dee-842c-b9db300459ca.png)

**Keyword** : props

**1.-How many different pages were represented by these 5 results?**

There are 4 different pages.

**2.-Was the top result the "best" suggestion (in your mind - the most helpful/general page on the topic)? If not, was the first search term result at least a "good" suggestion?**

The fourth result is the best result in my opinion.

**3.-Was a page entirely missing from the results that probably should have been included? (e.g. You searched for Markdown and did not see "Markdown & MDX" as one of the 5 results.)**

No, I don't think there are missing pages.

**4.-Do you think more results would be helpful for this search term?**

No, I don't think so.

**5.-Do you feel that someone looking at the 5 results gets enough info about each search result to know the best one to choose?**

Yes, the results help you get a good grasp of how props work within `Astro`.

**Comment by sarah11918** [comment]
I just did `getStaticPaths()` and I am NOT HAPPY.

![getStaticPathsAlgolia](https://user-images.githubusercontent.com/5098874/209954575-3d227a1b-d801-41cf-899e-82f01b5bd3b8.png)

Keyword : `getStaticPaths()`

How many different pages were represented by these 5 results?

There are 5 different pages.

Was the top result the "best" suggestion (in your mind - the most helpful/general page on the topic)? If not, was the first search term result at least a "good" suggestion?

No. The top 4 results were all error messages. These are helpful to show up, but should they really show up *instead* of any reference or learn material? Maybe Error messages needs its own category?

The only other result was from the tutorial. The good news is, it's clearly visible that it's from the tutorial!

Was a page entirely missing from the results that probably should have been included? (e.g. You searched for Markdown and did not see "Markdown & MDX" as one of the 5 results.)

Yes, neither the API reference page, nor Routing showed up. (There is a separate open issue re: how we describe `getStaticPaths` in both of these places, and whether the content is appropriately divided between the two of them. #1733 

Do you think more results would be helpful for this search term?

If we're going to be including individual error message pages, then yes!  :sweat_smile: 

Do you feel that someone looking at the 5 results gets enough info about each search result to know the best one to choose?

Nope.

**Comment by delucis** [comment]
Oh, interesting. Looks like those error pages are categorised as “Reference” whereas I thought we had decided to give them their own dedicated “Error Reference” category we could de-prioritise.

I _think_ if we make sure that’s the case, the relevant `getStaticPaths` reference should float up the results. But still a question whether we can get the routing docs to rank better for this.

**Comment by BryceRussell** [comment]
## Keyword: `slot`

![image](https://user-images.githubusercontent.com/19967622/210292123-9ad0d4e3-e22c-49a1-ac7e-9381d4ea0e5d.png)

**How many different pages were represented by these 5 results?**

2 different pages

**Was the top result the "best" suggestion? If not, was the first search term result at least a "good" suggestion?**

Currently the top result is the 'invalid slot name' error page which is not the best result, I feel like the slot results in order of importance are something like:

1 (Learn Tab) `<slot />`, named slots, fallback
2 (Refrence Tab) `Astro.slots` API
3 Slot tutorials
4 'invalid slot name' error page

**Was a page entirely missing from the results that probably should have been included?**

No

**Do you think more results would be helpful for this search term?**

No, all results are there they just need to be shifted upwards by deprioritzing the error page

**Do you feel that someone looking at the 5 results gets enough info about each search result to know the best one to choose?**

No, I think most people searching the term 'slot' are looking for information about `<slot />` and named slots, but the first 2 results are taken up by the 'invalid slot name' error page

**Comment by delucis** [comment]
Update re: `getstaticpaths` and `slot` keywords. The error references are now correctly categorised to separate things out a bit more clearly. Unfortunately we’re still running into the issue we’ve encountered previously that while we can demote pages with Algolia’s `pageRank`, because errors often include the term **in the page title** vs in a subheading in docs, those are still considered more relevant results:

|  |  |
|---|---|
| ![screenshot of search results for “getStaticPaths”](https://user-images.githubusercontent.com/357379/210370576-8ca344e0-635e-494e-a2ea-30b1b85e712f.png) | ![screenshot of search results for “slot”](https://user-images.githubusercontent.com/357379/210370508-3b082365-9c63-4a70-960f-c3eddab01ce2.png) |


Ideas welcome here and will continue to think on this myself.

**Comment by Tyson910** [comment]
<img width="1512" alt="Screenshot 2023-02-07 at 5 18 39 PM" src="https://user-images.githubusercontent.com/45476882/217384870-774030c7-86ec-49c4-843a-4898b38793a1.png">

**How many different pages were represented by these 5 results?** 

4 Project structure, Imports (static assets section), Routing, & Migrating from SvelteKit

**Was the top result the "best" suggestion (in your mind - the most helpful/general page on the topic)? If not, was the first search term result at least a "good" suggestion?**

No, favicon.ico is relevant and belongs in the search, but I feel like the images & static assets page should be number one.

**Was a page entirely missing from the results that probably should have been included? (e.g. You searched for Markdown and did not see "Markdown & MDX" as one of the 5 results.)**

 I think adding the image guide https://docs.astro.build/en/guides/images/ could be helpful. Depending on use case, svgs can be used with the Astro/Image component. Plus, the page has multiple examples of how to work with svg’s in Astro

**Do you think more results would be helpful for this search term?**

 In this case I could only find 3 search results are relevant to the _svg_ keyword.

**Do you feel that someone looking at the 5 results gets enough info about each search result to know the best one to choose?**

IMO the first two results are good. The third result links to the routing page b/c it just so happens to contain “_svg_”.  I’m assuming the last two are there in case of a svelte typo? (“Migrating from SvelteKit” & “Similarities between SvelteKit and Astro”)

**Comment by Tyson910** [comment]
<img width="1512" alt="Screenshot 2023-02-12 at 12 06 26 AM" src="https://user-images.githubusercontent.com/45476882/218295788-af7738cb-c322-4e1d-a819-dcb54acca7a5.png">

**How many different pages were represented by these 5 results?**

2 - Error Reference & API reference

**Was the top result the "best" suggestion (in your mind - the most helpful/general page on the topic)? If not, was the first search term result at least a "good" suggestion?**

No, I don't think giving a such a specific error message should be in the top 5 results. I feel like the [Astro.glob section of the imports page](https://docs.astro.build/en/guides/imports/#astroglob) OR the [Astro.glob API reference](https://docs.astro.build/en/reference/api-reference/#astro-global) should be number one.

**Was a page entirely missing from the results that probably should have been included? (e.g. You searched for Markdown and did not see "Markdown & MDX" as one of the 5 results.)**

I think adding both the [Astro.glob section of the imports page](https://docs.astro.build/en/guides/imports/#astroglob) page AND the [RSS guide to using glob imports](https://docs.astro.build/en/guides/rss/#using-glob-imports) should be in higher in the search results. Another result that could be added could be the [Astro.glob() - no matches found section of the troubleshooting page](https://docs.astro.build/en/guides/troubleshooting/#astroglob---no-matches-found)

**Do you think more results would be helpful for this search term?**

No, I don't think so

**Do you feel that someone looking at the 5 results gets enough info about each search result to know the best one to choose?**

Yes, for the most part. I think the API reference section gives a good idea of how to use Astro.glob()

**Comment by Jothsa** [comment]
# CSS

1. **How many different pages were represented by these 5 results?** 2 separate pages, "Styles and CSS" and the "Imports" page.

2. **Was the top result the "best" suggestion (in your mind - the most helpful/general page on the topic)? If not, was the first search term result at least a "good" suggestion?** Yes, the "Styles and CSS" page is very comprehensive and the best suggestion.

4. **Was a page entirely missing from the results that probably should have been included? (e.g. You searched for Markdown and did not see "Markdown & MDX" as one of the 5 results.)** Nothing was missing afaik.

5. **Do you think more results would be helpful for this search term?** No

7. **Do you feel that someone looking at the 5 results gets enough info about each search result to know the best one to choose?** Yes


<img width="1427" alt="Screenshot 2023-05-15 at 11 41 37 AM" src="https://github.com/withastro/docs/assets/58094796/90b92d63-f339-4915-968f-38c57bfbad0f">
<img width="1427" alt="Screenshot 2023-05-15 at 11 42 26 AM" src="https://github.com/withastro/docs/assets/58094796/5a532891-1caf-4bf2-aa6d-a856ce422b96">

**Comment by AishaBlake** [comment]
I know I'm late to the party but I actually did search some of these in the last couple of days, so adding some notes!

Keyword: redirect
<img width="555" alt="Astro docs search for redirect shows Error reference pages Astro.redirect is not available in static mode and a redirect must be given a location. Learn results include redirects, configured redirects, and dynamic redirects from the Routing page" src="https://github.com/withastro/docs/assets/7365296/687d6441-5041-4290-9f88-bee24f18a187">

1. How many different pages were represented by these 5 results? **3**
2. Was the top result the "best" suggestion (in your mind - the most helpful/general page on the topic)? If not, was the first search term result at least a "good" suggestion? **No, I think the sections from the Routing page are what most people would be looking for. It's what _I_ was looking for last night!**
3. Was a page entirely missing from the results that probably should have been included? (e.g. You searched for Markdown and did not see "Markdown & MDX" as one of the 5 results.) **Maybe the section on [Astro.redirect](https://docs.astro.build/en/reference/api-reference/#astroredirect)? I think, if someone is _just_ searching for "redirect", they're more likely to want the API reference than the error reference.**
4. Do you think more results would be helpful for this search term? **Potentially. It would be nice to show something descriptive about Astro.redirect in the results.**
5. Do you feel that someone looking at the 5 results gets enough info about each search result to know the best one to choose? **Personally, I was looking for info on redirects in the context of switching my site over from Gatsby (and reworking my folder structure as a result). The Routing page had exactly what I needed.**

Side note... I'm not sure if this just the style since there's a similar code snippet just before this, but it seems like this code sample should also include `astro.config.mjs` in the corner. Is that the case?
<img width="773" alt="configured redirect sample coding showing how to provide an object as the destination value is not labeled with a file name" src="https://github.com/withastro/docs/assets/7365296/3559df75-fc5a-469c-ad41-d0c1711ac2a5">

**Comment by sarah11918** [comment]
Thanks @AishaBlake ! Great feedback, and yes, we tyically *would* show the file name there. Would you like to make a PR to docs to add that? You can find the syntax we use for our code samples here: https://github.com/withastro/docs/blob/main/contributor-guides/writing-and-style-guide.md#code-samples

If not, no worries! I'll add that to to the stack of tasks!

**Comment by AishaBlake** [comment]
> Thanks @AishaBlake ! Great feedback, and yes, we tyically _would_ show the file name there. Would you like to make a PR to docs to add that? You can find the syntax we use for our code samples here: https://github.com/withastro/docs/blob/main/contributor-guides/writing-and-style-guide.md#code-samples
> 
> If not, no worries! I'll add that to to the stack of tasks!

No problem. PR is up! #3992

**Comment by sarah11918** [comment]
Retiring this issue for now! 🫡

It has served us well, and we will think of things to do in the new year!
