### ISSUE TITLE
No documentation about fetching Astro endpoints on the server

### ISSUE THREAD

**Issue by UltimateDoge5** [withastro/docs#2043]
On the page [data fetching](https://docs.astro.build/en/guides/data-fetching/) there is no mention how to fetch data from endpoints made using Astro. This caused me some problems with fetching while in production, as fetching a `/api/example` doesn't work.

I finaly stumbled upon the [Astro.url ](https://docs.astro.build/en/reference/api-reference/#astrourl) Api reference. We can use the origin to assemble the url. The docs could provide a simillar snippet like this.

```astro
---
const books = await fetch(new URL("/api/books", Astro.url.origin)).then((res) => res.json());
---

<!--Display content--!>
```

**Comment by wassfila** [comment]
👍  I think I met it few times and the support post was left unanswered with a workaround :(

When documenting this I would suggest if possible to document the alternative and explain the consequences.

=> **it is a bad practice to fetch its own data through API**

anything the Endpoints provides can be accessed directly though pure js function call given that Astro SSR is a single running process, so passing its own data through serialization and API fetch is a bad practice that many beginners think of as first alternative when not thinking about performance and not being familiar with process and memory. Spreading such practice in docu without alternative can result in people not satisficed with Astro's performance while misusing it.

The alternatives are accessing shared exported variables, I have some examples but I think it is so trivial that just few lines of code example is enough, or just mentioning the concept 'module variables, getters, setters export'
