### ISSUE TITLE
The markdown layout example throws an error

### ISSUE THREAD

**Issue by jeksn** [withastro/docs#2046]
The paragraph tag is missing its closing tag in the markdown layout example code block.
[Link to the issue](https://docs.astro.build/en/core-concepts/layouts/)

It's this one:
`<p>{frontmatter.description}<p>`
That should be changed to this:
`<p>{frontmatter.description}</p>`

**Comment by delucis** [comment]
Thanks for spotting that @jeksn! Would you be interested in opening a PR with your proposed fix? Let me know if you have any questions if so 🙌

**Comment by sarah11918** [comment]
Closed by #2052
