### ISSUE TITLE
`/routing/#rest-parameters` - Description says `[...param]` but code example uses `[...path]`

### ISSUE THREAD

**Issue by dsomel21** [withastro/docs#2077]
## Description

<img width="833" alt="Screenshot of the 'Rest paramters' page" src="https://user-images.githubusercontent.com/17516559/202922296-25d37622-fad8-410e-9055-be0be304f62d.png">

https://docs.astro.build/en/core-concepts/routing/#rest-parameters

**Comment by delucis** [comment]
The naming is not actually important as long as it matches the name returned in `getStaticPaths`. For example, `[...cats].astro` should return `[{ params: { cats: 'path/to/cat' } }]` but `[...dogs].astro` should return `[{ params: { dogs 'path/to/dog' } }]`.

That said, I agree that these should match for clarity. Want to open a PR updating `[...param]` to `[...path]`?

**Comment by dsomel21** [comment]
Sounds good! 

Actually, another reason why I got confused was because... when it said "rest parameter" I immediately began thinking about RESTful APIs endpoints. 

Do you think it make sense to add a link to the MDN doc on [rest parameters](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/rest_parameters)?

**Comment by delucis** [comment]
Sure! Seems like a good idea to me 👍

**Comment by sarah11918** [comment]
Hi @dsomel21! I'm not sure whether this is still on your radar, but since you've discovered something helpful to add to docs (no matter who does it), I'm going to go ahead and add some labels to encourage someone (maybe you!) to pick this up.  😄
