### ISSUE TITLE
No hierarchy in table of contents

### ISSUE THREAD

**Issue by chenxsan** [withastro/docs#2099]
I noticed that there's no hierarchy in the list of table of contents.

<img width="502" alt="" src="https://user-images.githubusercontent.com/1091472/203541940-479ff6e8-5e88-43ab-b434-0e84c64fae25.png">

While I expect it to be something like:

```
<ul>
  <li>h2 title</li>
  <li>another h2 title
    <ul>
      <li>h3 title</li>
      <li>another h3 title</li>
    </ul>
  </li>
</ul>
```
Let me know if you're interested in a pull request to update it now that I've finish the code for my own Astro site's table of contents.

**Comment by delucis** [comment]
That sounds helpful, thanks @chenxsan! We’ll need to make sure the code highlighting the current item still works.
