### ISSUE TITLE
No documentation about Web Components

### ISSUE THREAD

**Issue by fernandofranca** [withastro/docs#2100]
Though it's straightforward to set up and use web components with Astro, it can be confusing for newcomers to figure out the preferred way to enable and use them.

Thanks to @delucis help on Discord I managed to create a [sample repo](https://github.com/fernandofranca/astro-web-components) with web components, however I think it's an important subject to be added to the docs.

**Comment by delucis** [comment]
Thanks! I’m actually working on this this afternoon!
