### ISSUE TITLE
Document how to write links that respect the base path

### ISSUE THREAD

**Issue by jyasskin** [withastro/docs#2135]
https://docs.astro.build/en/reference/configuration-reference/#base describes how to deploy a site to a sub-path of the [site's domain](https://docs.astro.build/en/reference/configuration-reference/#site), but I don't see any documentation about how to fill in the `<a href>` attribute so that it gets to the right page when `base` isn't `/`.

I'd expected to find something like [`Flask.url_for`](https://flask.palletsprojects.com/en/2.2.x/api/#flask.Flask.url_for) so I could ask the framework what URL to use, or maybe an explanation of what URL patterns are safe to use in the `<a href>` so Astro can automatically transform them.

**Comment by sarah11918** [comment]
Thanks for commenting! This entire issue has been a bit of an ongoing adventure, but https://github.com/withastro/astro/pull/5693 has been made to address this. Comments can be made there!
