### ISSUE TITLE
Cloudflare streams docs outdated.

### ISSUE THREAD

**Issue by davycoe** [withastro/docs#2142]
Cloudflare Pages now builds with `streams_enable_constructors` as default.

If added as docs suggest Cloudflare Pages will fail to build with the following output: 
```Error: Failed to publish your Function. Got error: The compatibility flag streams_enable_constructors became the default as of 2022-11-30 so does not need to be specified anymore.```

Link: [https://docs.astro.build/en/guides/integrations-guide/cloudflare/#streams](url)

Outdated:
```Streams
[Section titled Streams](https://docs.astro.build/en/guides/integrations-guide/cloudflare/#streams)

Some integrations such as [React](https://github.com/withastro/astro/tree/main/packages/integrations/react) rely on web streams. Currently Cloudflare Pages Functions require enabling a flag to support Streams.

To do this:
    go to the Cloudflare Pages project
    click on Settings in the top bar, then Functions in the sidebar
    scroll down to Compatibility Flags, click Configure Production Compatibility Flags, and add streams_enable_constructors
    do this for both the Production Compatibility Flags and Preview Compatibility Flags
```

**Comment by sarah11918** [comment]
Thanks for this comment! I know we've had some updates to our cloudflare pages recently, and the section on streams no longer seems to be there, so I'm closing this issue. :partying_face:

**Comment by sarah11918** [comment]
Oops, reopening as I found the offending, outdated content elsewhere!

**Comment by sarah11918** [comment]
Have opened https://github.com/withastro/astro/pull/5694 to remove the outdated advice. Thank you again, @davycoe!
