### ISSUE TITLE
Suboptimal blog theme toggler

### ISSUE THREAD

**Issue by ohansemmanuel** [withastro/docs#2146]
Hey 👋🏽

## Context 

Consider the [Back on dry land. Take your blog from day to night, no island required!](https://docs.astro.build/en/tutorial/6-islands/2/) section of the docs / tutorial. 

A toggler switch is built, and rightly works: 

![The toggler](https://user-images.githubusercontent.com/10930234/206131727-4e69553c-c130-44f9-b479-bad2a62a25d4.png)

But this is faulty in certain regards 

### - The first obvious one here is the use of a standard `div` element. 

![CleanShot 2022-12-07 at 09 50 15@2x](https://user-images.githubusercontent.com/10930234/206132182-a75fe735-1c08-45e5-a25b-88d46496afbe.png)

At the very least, this should be a `button` element 

### - Conversely, the entire block is clickable 

![CleanShot 2022-12-07 at 09 51 08@2x](https://user-images.githubusercontent.com/10930234/206132516-42f819d4-e430-44a2-9300-563cf78091d3.png)

An unintended consequence of using a block element here is the entire described block above is clickable and toggles the theme

## How should this be fixed? 

- Ideally, change this to a `button` element: 
- Secondly, the least amount of `css` required to keep the same style would be: 

```css
 #themeToggle {
    border: 0;
  }
```

## Why do this? 
- This is a relatively simple fix **(I'm happy to issue a PR)**, and it promotes better web practices in the official doc. 
- This is also not very opinionated and eradicates the unintended click behaviour earlier discussed

**Comment by sarah11918** [comment]
Hi @ohansemmanuel! Thank you for this! I love the committment and the detail here. :purple_heart:

I'm going to ask @delucis and @Yan-Thomas to comment here, and for them to come to an agreement on the code changes that they think will fit best for the tutorial project itself. (Which itself is not a PR to docs, and so you'll need Chris involved.)

Then, we will need to update the documentation itself explaining how to do this, which sounds like a PR you'd be interested in making, and I'd be happy to receive!  :muscle: 

So first order of business is to agree on the code we want to use, then we can get to a docs PR for the tutorial instructions.

**Comment by ohansemmanuel** [comment]
@sarah11918 just following up here 😊

**Comment by Yan-Thomas** [comment]
Sorry for not joining the discussion earlier. I think this is a small and valid change, this way we aren't promoting "divs everywhere" and also get the more precise clickable area for free.

I'm considering we don't want to go deep with styling and accessibility in the tutorial, so maybe we could add a small aside explaining this is more of a basic implementation and that the user can check the more complex and accessible ThemeToggle developed for the redesigned portfolio template.

By the way, we also need `background: none` here. The default button color would be visible in dark mode otherwise.
```css
 #themeToggle {
    border: 0;
    background: none;
  }
```

**Comment by Jutanium** [comment]
Went ahead and updated the `blog-tutorial-demo` to use this. Docs PR coming soon - I think this addition is simple enough to make it into the tutorial.
