### ISSUE TITLE
More advanced slots behavior

### ISSUE THREAD

**Issue by sarah11918** [withastro/docs#2147]
Adding an issue so this idea doesn't get lost:  https://discord.com/channels/830184174198718474/853350631389265940/1047820144669376532

--------
Hey, I am having a hard time to wrap my head around some use case with named slots https://docs.astro.build/en/core-concepts/astro-components/#named-slots

Since docs covers the most basic usages, I found some use cases that might be covered to make slots functionality even clearer.
Or maybe I found a bug of Astro slots? 🤔 

Before we dive in, the discussion is about the slot usage when consuming component which handles slots, but not slots defining in component itself (this part works well).

When it comes to slots, it has weird bug (or maybe limitation) that we cannot do two things:
1. Nest slots usages with additional html (only root level slot works fine) - ❌ 

```
<MyComponent>
  <div>
     <Fragment slot="mySlot">...</Fragment>
  </div>
</MyComponent>
```
2. Nest slots usages with conditional statements (the slot is still registered under-the-hood!!!) - ❌ 

```
<MyComponent>
  {shouldRender && <Fragment slot="mySlot">...</Fragment>}
</MyComponent>
```

Result of the above: slot is not rendered in html (which is cool), but it was still registered and visible in the component logic (which is not cool, because the Astro.slots.has('mySlot') is true, while the contents of it (when you render it) is empty ⚠️ ) which supposedly would have some extra logic to wrap with div+margin+padding, but only when slot exists.

I did some examples what works and what not: https://stackblitz.com/edit/github-zwgejy?file=src%2Fpages%2Findex.astro,src%2Fcomponents%2FMyComponent.astro&on=stackblitz
Please see comments in specific places, and maybe we could come up with bits to cover in docs or bug task for Astro devs to fix 🙏 

---
Btw, how I did solve conditional slots is this workaround:

```
<MyComponent>
  <Fragment slot={shouldRender ? "mySlot" : null}>...</Fragment>
</MyComponent>
```
NOTE: since slot name is stringified, I do get slot registered both ways, but just with different name, which is first nasty and second presumably non-performant.

**Comment by Jutanium** [comment]
The example #2 above now does get rendered:
```
<MyComponent>
  {shouldRender && <Fragment slot="mySlot">...</Fragment>}
</MyComponent>
```
If `shouldRender` is true, the slot will be rendered.
But _whether or not_` shouldRender` is true, `Astro.slots.has('mySlot')` will be true.
