### ISSUE TITLE
Astro inlines script and style for astro islands even with assetsInlineLimit set to 0

### ISSUE THREAD

**Issue by gerjon-eatch** [withastro/docs#2150]
Astro's docs here: https://docs.astro.build/en/guides/troubleshooting/#refused-to-execute-inline-script suggest the following config to force script and styles to be not inlined, so that an astro generated site is comptible with Content-Security-Policy that doesn't allow unsafe-inline:

```
export default defineConfig({
  vite: {
    build: {
      assetsInlineLimit: 0,
    },
  },
});
```

This works for a site that uses simple Astro components. It stops working once you start using the Astro Islands architecture to hydrate e.g. svelte components. Astro always inlines the island hydration script and related style, even wiht the above configuration.

It would be nice if the documentation could be updated to reflect this. Hopefully with an alternative way to achieve the island hydration script and style not to be inlined in the html..

**Comment by delucis** [comment]
Thanks for reporting this @gerjon-eatch! Just spoke to the team and we unfortunately don’t have a good way to support CSPs without `unsafe-inline` for this scenario currently. Would be good to add one though. Would you [mind opening an issue in the main astro repo](https://github.com/withastro/astro/issues/new/choose) so we can track adding this support? 

In the meantime we should add a note to this workaround regarding its limitations — sorry you ran into that!

**Comment by delucis** [comment]
@matthewp I think when we discussed this, you were suggesting we should remove our troubleshooting guidance here entirely. Is that correct? We have this currently: https://docs.astro.build/en/guides/troubleshooting/#refused-to-execute-inline-script

<img width="869" alt="image" src="https://user-images.githubusercontent.com/357379/206531647-b57f72e5-dc6a-4daa-95d0-05696dc27400.png">

**Comment by matthewp** [comment]
Yeah, those docs are what to do when you encounter an error, so they should point users towards changing their CSP to allow the inline scripts, rather than workarounds that don't work once you use hydrated components.

**Comment by gerjon-eatch** [comment]
> Thanks for reporting this @gerjon-eatch! Just spoke to the team and we unfortunately don’t have a good way to support CSPs without `unsafe-inline` for this scenario currently. Would be good to add one though. Would you [mind opening an issue in the main astro repo](https://github.com/withastro/astro/issues/new/choose) so we can track adding this support?

I would love to create an issue. But from the template it looks like feature requests are not supposed to be entered on https://github.com/withastro/astro/issues, but instead on https://github.com/withastro/rfcs/discussions. And there are already RFCs there covering this subject, such as 
https://github.com/withastro/rfcs/discussions/377.

**Comment by gerjon-eatch** [comment]
> Yeah, those docs are what to do when you encounter an error, so they should point users towards changing their CSP to allow the inline scripts, rather than workarounds that don't work once you use hydrated components (a huge part of Astro).

It looks like the scripts/style that astro inserts for the islands is not dynamic. You could add their hashed to the doccumentation there, with instructions to use CSP hashes to whitelist those. Something like:
```
base-uri 'self'; default-src 'self'; script-src 'self' 'sha256-cJWPGGESIyhUXJ9vB0wpOBXlT5c9ip93D2hIm510Oqc=' 'sha256-L2fNHQpcymuKkRQP9Gg4o2NyB4UmS3otPGksNgkoDYY=' 'sha256-ktpqgMRCiAIxLPSP34mglc7oKASP3QGbNy59FMmUORM='; style-src 'self' 'sha256-294PHO/1REFbepcFVrNwZMFvgez5hYst8E48Q7WfO7w=' 'sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=';
```

Of course this will change if those scripts may change between astro versions.

**Comment by delucis** [comment]
Yeah I think that’s probably too fragile a solution: we should look at some of these RFCs and try to do something to properly support this. You _could_ create an issue that says “Astro breaks with my CSP” and claim it’s a bug, which… it kind of is, but appreciate you sharing those RFC links!

**Comment by delucis** [comment]
Posted some thoughts at https://github.com/withastro/rfcs/discussions/377#discussioncomment-4368955

@matthewp You likely have much a better grip on all the technical considerations here — or maybe someone else in core has some CSP experience they can share.
