### ISSUE TITLE
Replace binary body-encoding in examples

### ISSUE THREAD

**Issue by fflaten** [withastro/docs#2202]
The png-example in https://docs.astro.build/en/core-concepts/endpoints/#static-file-endpoints uses `Buffer` and deprecated `binary` encoder. There's a few other examples as well: https://github.com/search?q=repo%3Awithastro%2Fdocs%20encoding%3A%20%27binary%27&type=code

- `APIRoute` type expects `body` to be string, not `Buffer`.
- `binary` BufferEncoding is deprecated in node AFAIK.

Suggestion: 
```js
// I'm not sure if `hex` or `base64` is the new preferred encoding
export async function get({ params, request }) {
  const response = await fetch("https://astro.build/assets/press/full-logo-light.png");
  const buffer = Buffer.from(await response.arrayBuffer());
  return {
    body: buffer.toString('hex'),
    encoding: 'hex',
  };
}
```

**Comment by aFuzzyBear** [comment]
Good question,  Using `hex` here may lead to problems as it performs data truncation with some inconsistencies. For this example I would recommend if you are sending a image to use `base64` encoding over `hex` when encoding binary data to be sent over the wire. 

With your amended code sample:
```
export async function get({ params, request }) {
  const response = await fetch("https://astro.build/assets/press/full-logo-light.png");
  const buffer = Buffer.from(await response.arrayBuffer());
  return {
    body: buffer.toString('base64'),
    encoding: 'base64',
  };
}
```
https://nodejs.org/api/buffer.html#buffers-and-character-encodings

**Comment by fflaten** [comment]
Found a downside. Both will break png in dev. 😞

**Comment by aFuzzyBear** [comment]
@fflaten could you raise an issue for this on the main astro repo if possible, and we will get it on the board to get looked at, Thank you, 👊

**Comment by Jutanium** [comment]
After exploring the [Node documentation](https://nodejs.org/dist/latest-v18.x/docs/api/buffer.html#buffers-and-character-encodings), it seems that binary encoding is legacy, but not deprecated. Since this instructional example works and is a simpler way to explain the concept (returning a custom `encoding`), we'll leave it as-is.
