### ISSUE TITLE
a11y contrast issues after theme update

### ISSUE THREAD

**Issue by delucis** [withastro/docs#224]
@FredKSchott Looks like deb66f5 re-introduced a few a11y contrast issues that had been fixed in #198. We can’t use the orange accent for links against a light background.

Even in dark mode links containing inline code now fail an audit because the code bg is just _slightly_ lighter:

<img width="340" alt="image" src="https://user-images.githubusercontent.com/357379/158362143-cf9a620d-c98c-43c5-866d-15af1bbb3192.png">

The dark theme fix could be fairly simple: set `--theme-code-inline-bg` to a darker shade than the background gradient (although even at full black that doesn’t quite pop like the lighter shade — would work better with a slightly lighter bottom gradient shade).

In the light theme we need to choose a different colour for links (i.e. use `--theme-text-accent` not `--theme-accent`). I know the orange really pops and I love it too, but it’s a long way from being accessible (a ratio of 4.5 is the minimum to pass an AA audit):

<img width="229" alt="image" src="https://user-images.githubusercontent.com/357379/158364547-77e7b40e-5ae2-43b9-a69a-a54a755d70c6.png">

Maybe a darker orange or a purple? 

---

If anyone’s interested in how to do an audit, I find Firefox’s built-in Accessibility panel in dev tools the easiest to use quickly. You can select “Contrast” from the “Check for issues” drop-down menu and it will scan the page for any colour contrast issues, listing any text with insufficient contrast.

<img width="268" alt="image" src="https://user-images.githubusercontent.com/357379/158365264-ef3df0e0-7a15-4908-adef-d4aa7110087a.png">

On the docs site, the Framework Components page is a good litmus test as it contains most possible combos of background and text colours.

**Comment by sarah11918** [comment]
Just musing out loud, but I had it in my head that sometimes the numbers didn't always coincide with what was otherwise agreed-upon as "easiest to read" by readers, and I thought orange (and in particular, orange-white) was a particular culprit here.

I think some standards are scheduled to change (but I don't recall a timeline) to reflect some of the issues with current ratios, and of course, if we are required in some way to pass particular standards now, then I suppose we have to adhere to the letter of them!

**Comment by delucis** [comment]
Interesting! I hadn’t heard that. I managed to dig up some anecdotal stuff about white text on orange backgrounds being more accessible in user tests than the colour contrast suggests ([link](https://www.bounteous.com/insights/2019/03/22/orange-you-accessible-mini-case-study-color-ratio/)). Would love to read more if you know where you saw that.

I guess the dark theme contrast is marginal, so I’d buy that — without a budget for user testing 😅 — but the orange on light contrast is still _very_ low (lower still in inline code snippets and blockquotes), so I’m less sure there.

**Comment by sarah11918** [comment]
I'm going to close this now, @delucis since you are clearly ON THE CASE, ON THE REG, and I'm sure this will be taking into consideration going forward.  :)
