### ISSUE TITLE
Use typescript in hoisted script

### ISSUE THREAD

**Issue by Akxe** [withastro/docs#225]
I am not sure, what am I doing wrong, but my typescript does not get executed. If typescript is present during the build I get an error `Expected ";" but found ":"`, but if the file is valid JS, and after the first build I change the code, I gen no error, but neither the code does change on client

**Comment by sarah11918** [comment]
Hi @Akxe ! The best place to ask about this is in our Discord community https://astro.build.chat

This location is only for issues with our documentation repository, so you won't find the right people here to help you. But, if you join us in Discord, you'll find people more than happy to help you out with this! We have a dedicated team of people who will receive a notification if you post your question/problem in our #support-threads channel there!
