### ISSUE TITLE
Add optional info to vercel deployment: Project config with vercel.json

### ISSUE THREAD

**Issue by redwerkz** [withastro/docs#2263]
This is very useful and definitely worth mentioning at this page: [Deploy your Astro Site to Vercel](https://github.com/withastro/docs/edit/main/src/pages/en/guides/deploy/vercel.mdx)

It even offers advanced configuration options like setting http-header. 😏

> [Project config with vercel.json](https://vercel.com/docs/project-configuration#)
> The vercel.json configuration file lets you configure, and override the default behavior of Vercel from within your project.

**Comment by sarah11918** [comment]
Closing this issue, as it seems the docs merge didn't close this automatically! 🎉
