### ISSUE TITLE
Support safe area on mobile devices

### ISSUE THREAD

**Issue by fflaten** [withastro/docs#2270]
On touch devices like iPhones, iPads etc. the website is padded by the browser to avoid content under UI-elements like the "slide for home screen"-bar etc. In this area the gradient background is not visible and the website might also get double padding in some elements close to the edges.

![image](https://user-images.githubusercontent.com/3436158/210259906-41f43b06-7d3f-490f-b836-1ceed1572062.png)

This can be fixed by using css environment variables and max/calc to adjust the padding per device when the viewport meta includes `viewport-fit=cover`. See https://developer.mozilla.org/en-US/docs/Web/CSS/env#usage

**Comment by Jutanium** [comment]
Hey, if anyone has one of these devices and is excited about trying these new media queries, we'd love contributions!

**Comment by delucis** [comment]
No-one’s picked this up and we’ll be moving the docs site to [Starlight](https://starlight.astro.build/) soon, so then this will be redundant, so I think we can close for now. But thank you for reporting!

**Comment by fflaten** [comment]
No problem. It was just a suggestion, so I'm fine with closing but..

> we’ll be moving the docs site to [Starlight](https://starlight.astro.build/) soon, so then this will be redundant

Will it be redundant? Same issue applies to https://starlight.astro.build/ atm.

**Comment by delucis** [comment]
Ah, good to know! Then a PR to Starlight fixing that would be appreciated!
