### ISSUE TITLE
Guidance on when/why to use SSR

### ISSUE THREAD

**Issue by sarah11918** [withastro/docs#2292]
Our SSR page currently says *how* to enable SSR, but not *why* you might want to enable SSR!

https://docs.astro.build/en/guides/server-side-rendering/

Looking for anyone who wants to write a user-friendly summary for people who might not know what SSR is or why it might be useful. Our standard advice is that unless you *need* SSR, you're probably good with SSG. But, a lot of people still don't know why/when they might need it.

The following are some questions you might ask someone to decide whether SSR is a good (or needed!) decision for them:

what type of website are you using it for?
where does the content come from?
how often will it be updated?
is there authentication?
any specific requirements in terms of deployment & hosting?

Maybe a friendly paragraph or two that helps people learn about SSR, or mentions these questions in particular and then, which answer would indicate SSR is for them, or whether to just stick with SSG.

**Comment by ohansemmanuel** [comment]
I'm happy to work on this re: help wanted.

**Comment by Jutanium** [comment]
Pinging for freshness! 💐 @ohansemmanuel, feel free to take it - let us know if you need any help.

**Comment by bandantonio** [comment]
I can try to create this guide as well

**Comment by ohansemmanuel** [comment]
I forgot about this, my bad. Opened https://github.com/withastro/docs/pull/3332 to begin a conversation cc @sarah11918 @Jutanium
