### ISSUE TITLE
Prop to check Client Directive

### ISSUE THREAD

**Issue by silveltman** [withastro/docs#2322]
Do framework components receive a prop with which we can check the component's client directive? If so, it's hard to find...

I have this horizontal scrollable container, but scrolling buttons. When I do not specify a client directive, I want the buttons to be hidden, so it's just a regular horizontally scrollable container. 

My solution at the moment is a variable that changes to true when the component is loaded. However, this is not ideal since it causes the buttons the flicker at the start of the component load. 

Thanks! :)

**Comment by delucis** [comment]
Hi @silveltman! I don’t believe we currently expose this, so you would probably need to duplicate things a bit unfortunately. For example with a boolean `hydrated` prop:

```js
<ReactComponent client:load hydrated />
<ReactComponent />
```

This is actually the repo for the Astro documentation website, so I’m going to close this. You could start a discussion in https://github.com/withastro/rfcs to propose this idea.
