### ISSUE TITLE
404 for cover image in post 4 of the tutorial

### ISSUE THREAD

**Issue by bytrangle** [withastro/docs#2357]
[Post 4](https://docs.astro.build/en/tutorial/5-astro-api/1/#dynamically-display-a-list-of-posts) of the tutorial series contains an image of the earth seen from the space.

The image url is `https://astro.build/assets/hero_NkT0b.avif`, but that will lead to 404.

I suppose the intended image is available [here](https://astro.build/assets/hero_Z2v0k6i.png)?

**Comment by Yan-Thomas** [comment]
Fixed in #2382
