### ISSUE TITLE
Wrong starter template description (and typo)

### ISSUE THREAD

**Issue by ohansemmanuel** [withastro/docs#2372]
## What? 
The following is a rather ambiguous (slightly misleading) sentence as it gives the impression you can take any public Github astro project and start a new project based on it (i.e., copy the files as a "template") 

![CleanShot 2023-01-14 at 08 51 57@2x](https://user-images.githubusercontent.com/10930234/212462184-47ccb2c3-7424-4beb-97a0-d0688ff727f2.png)

> You can also start a new astro project based on an existing GitHub repostory by passing a --template argument to the create astro command.

In reality, this does not seem to be the case. 

## How? 

![CleanShot 2023-01-14 at 08 39 04@2x](https://user-images.githubusercontent.com/10930234/212462201-1fb76785-1fff-4270-8b4c-85cd7f8cb19c.png)

it appears (as I suspected), the creation from an "existing Github repository" command/description only works with existing starter templates 

e.g., 

✅ this works: 

```bash
npm create astro@latest -- --template satnaing/astro-paper
```

❌ this does not work: 

```bash
npm create astro@latest -- --template ohansemmanuel/astrojs-ditch-the-runtime-react 
```

## Suggestion 
If the assumption above is correct i.e., this works for existing templates, then it's **perhaps** worth reconsidering rewording the sentence to: 

> You can also start a new astro project based on an existing **starter template** GitHub ~repostory~ **repository** by passing a --template argument to the create astro command.

![CleanShot 2023-01-14 at 08 58 12@2x](https://user-images.githubusercontent.com/10930234/212462384-fd509d79-9f1f-496b-8665-98565d3ac216.png)

**Comment by delucis** [comment]
Hmm. Interesting I’m not actually clear what the difference between those two repos is that makes one fail, I think theoretically they should both work. It might be the branch name? Noticing that the one that fails uses `master` instead of `main` for the primary branch. Wonder if `create astro` specifically expects to copy from `main`.

**Comment by ohansemmanuel** [comment]
@delucis you're right. `create astro` seems to specifically copy from `main`. 

I added a `main` branch and this worked: 

![CleanShot 2023-01-16 at 16 46 20](https://user-images.githubusercontent.com/10930234/212718026-846d814f-67d2-4058-8d16-d03050e0412a.png)

Is this worth documenting? Or perhaps `create astro` tweaked to copy from the default branch?

**Comment by delucis** [comment]
Let me check with the core team. Maybe we can use the default branch in `create astro`. Feels like a bug to me, but if we can’t fix it, at that point it might make sense to document.

**Comment by delucis** [comment]
As a side note, it looks like you can also specify the branch name after a `#` in the command, e.g.

```sh
npm create astro@latest -- --template ohansemmanuel/astrojs-ditch-the-runtime-react#master
```

It looks like this could be a limitation of the underlying tool Astro uses: https://github.com/unjs/giget/

**Comment by ohansemmanuel** [comment]
> It looks like this could be a limitation of the underlying tool Astro uses

That makes sense. It does work with the branch name after a `#`. 

Thanks for the input @delucis - Please feel free to either close this issue or consider a possible next step: documenting this limitation (with a small note after the instructions)

**Comment by delucis** [comment]
Opened to #2413 address this. Thanks for raising this issue @ohansemmanuel!
