### ISSUE TITLE
ESLint not enabled for tsx

### ISSUE THREAD

**Issue by chenxsan** [withastro/docs#2398]
Just noticed that ESLint is not enabled for `.tsx` file https://github.com/withastro/docs/blob/main/.eslintrc.js#L24

<img width="870" alt="" src="https://user-images.githubusercontent.com/1091472/212904835-9e6916ea-218d-4dd3-a590-35a5c780bab3.png">

Was it left out on purpose?

Once enabled with `eslint-plugin-react`, I can see quite a lot of error report:

<img width="990" alt="" src="https://user-images.githubusercontent.com/1091472/212906469-2209e0ac-7194-4aaa-ae9d-6bd9ee1418a0.png">

Let me know if you're interested in a pull request to have it enabled.

**Comment by delucis** [comment]
I think enabling eslint for tsx could be helpful, thank you! One thing though: we're using Preact not React so maybe need different rules?

**Comment by chenxsan** [comment]
> I think enabling eslint for tsx could be helpful, thank you! One thing though: we're using Preact not React so maybe need different rules?

I think most works the same, `eslint-plugin-react` provides this `pragma` which can be set to `preact`:

![](https://user-images.githubusercontent.com/1091472/212907935-7fe60f91-a478-440d-b6d8-3505b8705ed5.png)

**Comment by delucis** [comment]
Thanks! I also found this which could be a useful reference: 
https://github.com/preactjs/eslint-config-preact/blob/master/index.js
