### ISSUE TITLE
Reference https://github.com/lukeshay/astro-aws in the AWS deploy docs

### ISSUE THREAD

**Issue by lukeshay** [withastro/docs#2402]
I created a couple of packages to help with deploying Astro to AWS. It would be cool if they were referenced in the docs. Let me know if that is possible.

Thanks!

**Comment by sarah11918** [comment]
Hi @lukeshay! We don't typically document third-party integrations in our own docs, but I looked and noticed that your integrations aren't listed at https://astro.build/integrations ... which is where they should be!

Here's a link to docs with some instructions for making sure that your packages are picked up by our script and included there. (Maybe adding one of the keywords we search for will help.) There's also a link where you can file an issue directly to get your packages added if the automatic method doesn't seem to be working.  

https://docs.astro.build/en/reference/publish-to-npm/#integrations-library

So, I'm going to close this as a docs issue, and will let you and the https://github.com/withastro/astro.build repo finish this one off!  🙌
