### ISSUE TITLE
"astro dev" in production

### ISSUE THREAD

**Issue by 7flash** [withastro/docs#242]
Is that (just) a bad practice or strongly prohibited way to deploy app?

I have strong use case for doing that, specifically rendering fresh files to client without rebuild; but it feels like that would defeat the whole idea of Astro about static rendering?

**Comment by sarah11918** [comment]
Hi @7flash !

Someone will be able to answer your question in our Discord channel! That's where we provide support for using Astro. This repository is exclusively for issues with fixing/improving our documentation site, so you won't have the right people looking at your question here.

Please visit https://astro.build/chat to join our Discord and ask a question there! Thank you!
