### ISSUE TITLE
Reference to headings being in Astro.props not evident in docs

### ISSUE THREAD

**Issue by sarajw** [withastro/docs#2429]
Happy to be proved wrong! But I was unable to find this information, until I happened upon the comment below:

___
So to confirm everything here:
- Today, you can access headings from MD and MDX using `Astro.props.headings`. Update to `astro@latest` and `@astrojs/mdx@latest` if that isn't the case!
- We should update `@examples/docs` to use `headings` properly

@danilopolani Let me know if that's correct!

_Originally posted by @bholmesdev in https://github.com/withastro/astro/issues/4218#issuecomment-1213552093_

**Comment by Jutanium** [comment]
This refers to accessing `Astro.props` from a layout assigned to a MD/MDX page, right? We do have this information on [the Layouts page](https://docs.astro.build/en/core-concepts/layouts/#markdown-layout-props). 

I do think we should add something to the [layout section of the Markdown & MDX guide](https://docs.astro.build/en/guides/markdown-content/#frontmatter-layout). That section does have a "learn more" link to the layouts page, but doesn't give any indication that props other than `frontmatter` exist.

**Comment by sarajw** [comment]
Nevermind, I wasn't looking in the right place, of course - found it right under my nose: https://docs.astro.build/en/core-concepts/layouts/#markdown-layout-props

**Comment by sarajw** [comment]
> This refers to accessing `Astro.props` from a layout assigned to a MD/MDX page, right? We do have this information on [the Layouts page](https://docs.astro.build/en/core-concepts/layouts/#markdown-layout-props).
> 
> I do think we should add something to the [layout section of the Markdown & MDX guide](https://docs.astro.build/en/guides/markdown-content/#frontmatter-layout). That section does have a "learn more" link to the layouts page, but doesn't give any indication that props other than `frontmatter` exist.

Goodness, you just replied the same time as I did! Thank you - maybe I just came at it from a strange angle and missed it.

**Comment by Jutanium** [comment]
It isn't your fault that you missed it - the MD guide is a bit misleading in that it _only_ mentions `Astro.props.frontmatter`! The fact that you searched for an answer and found it not in the docs but in a GitHub comment indicates that we can do a better job at placement within the docs. This is great feedback for us.

**Comment by sarajw** [comment]
OK!

I'm actually starting to write a little blog post, as a guide to building a ToC into astro blog post layouts in case it'll help anyone else. I'm already in touch with @sarah11918 to see if we can jiggle it afterwards to be good stylewise for the docs, and find a good place to put elements of it once it's written.

If it helps, I think I was thrown by references to getHeadings() here: https://docs.astro.build/en/guides/markdown-content/#heading-ids-and-plugins - and then didn't think to look in the Layouts section.

**Comment by sarajw** [comment]
You all rock, saw the other ticket that closes this one - thank you :)
