### ISSUE TITLE
[i18n] ES: inconsistency of formal & informal language in Note 

### ISSUE THREAD

**Issue by ximenavf92** [withastro/docs#2457]
I noticed a minor inconsistency in the "Note" component that informs the user that the current page is not yet available in their language. The majority of the site uses the informal version of Spanish, which is definitely the preferred for this application. However this particular components uses both in the same paragraph. 

<img width="778" alt="image" src="https://user-images.githubusercontent.com/17228655/214395583-30913fd8-3f07-4273-bccf-3afc9de5e5cd.png">

It currently reads:
> _Esta página aún no está disponible en su idioma, mientras tanto verá la versión en inglés. ¡Ayúdanos a traducirla!_ 

It should read:
> _Esta página aún no está disponible en tu idioma, mientras tanto verás la versión en inglés. ¡Ayúdanos a traducirla!_

I believe that would be updated [here](https://github.com/withastro/docs/blob/main/src/i18n/es/ui.ts), correct?

**Comment by delucis** [comment]
Hey @ximenavf92! Yes, that `src/i18n/es/ui.ts` file is the right place for this. Would you like to submit a PR?

**Comment by ximenavf92** [comment]
Sure @delucis! I may bug you, it has been a while since I've done this but happy to help. 😬

**Comment by delucis** [comment]
Of course! Bug away 💜
