### ISSUE TITLE
Adding a "caution" box to the integration API reference

### ISSUE THREAD

**Issue by vogtm** [withastro/docs#2506]
I run into an issue with the integration API today. 

When you import lib functions within an custom integration which itself use the env variables as described [here](https://docs.astro.build/en/guides/environment-variables/) the env vars will be undefined. 

aFuzzyBear on the official Discord looked into this and there is a proper way also make them available in the config script. 
But at first glance it may not be obvious. 

**Possible solution:**
I am happily create an PR with a little "caution" box to hint to this behaviour and show the possible workaround aFuzzyBear provided to make env vars available also in the astro.config.mjs file.

The example code by FuzzyBear, i would try to make it a little more generic and less about the code we tested it with : 
```js
import { defineConfig } from 'astro/config';
import { test } from './src/lib/test';
import { loadEnv } from 'vite';

const key = loadEnv('', process.cwd(), 'HELLO_WORLD');
// https://astro.build/config
export default defineConfig({
  integrations: [
    {
      name: 'test:id',
      hooks: {
        'astro:build:done': async ({ dir, routes }) => {
          const testVAR = await test();
          console.log('TESTVAR', testVAR);
          console.log(key);
        },
      },
    },
  ],
});
```

Affected page: 
https://docs.astro.build/en/reference/integrations-reference/

**Comment by Jutanium** [comment]
This has more directly to do with configuration files than with integrations - we'd want to add this example to [this section](http://docs.astro.build/en/guides/configuring-astro/#environment-variables) and link it from the integrations page.
