### ISSUE TITLE
[Suggestion] Alleviate confusion around `pagination` used with `[...spread_parameter]`

### ISSUE THREAD

**Issue by Return180bpm** [withastro/docs#2517]
# The issue
`url.prev` on `generated_page/2` is an empty string and DOES NOT link back to `/` (as I had expected)

I spent a good chunk of time debugging this the other day. Other folks [on the discord](https://discord.com/channels/830184174198718474/1031214923667210330) seem to have had the same confusion. 

So here's a space to discuss⚡

---

## Some ideas

**Suggestion A**
Amend the pagination docs. Point this behavior out explicitly. Maybe give a workaround code example. 

**Suggestion B**
Re-write pagination, so it works as some peopl expect it 🙂 - or make it an option.
Not sure how many of us there are, tho. Maybe this is common behavior with SSGs.

**Comment by Jutanium** [comment]
Turns out it was already reported! Thanks, @delucis!
https://github.com/withastro/astro/issues/6147
