### ISSUE TITLE
Update blog tutorial to use new Content Type (Astro 2.0)

### ISSUE THREAD

**Issue by ramadanomar** [withastro/docs#2524]
[The tutorial](https://docs.astro.build/en/tutorial/0-introduction/) should include a small intro about the new content types (src/content) that came with Astro 2.0. 

I might be able to write it once i get a good enough grasp of the new feature.

**Comment by Jutanium** [comment]
Working on a migration guide [here](https://github.com/withastro/docs/pull/2501) (and corresponding [demo branch](https://github.com/withastro/blog-tutorial-demo/tree/content-collections)) that uses the tutorial as a starting point to move to content collections.  Once that's done, we can link to it from the end of the tutorial!

**Comment by ramadanomar** [comment]
> Working on a migration guide [here](https://github.com/withastro/docs/pull/2501) (and corresponding [demo branch](https://github.com/withastro/blog-tutorial-demo/tree/content-collections)) that uses the tutorial as a starting point to move to content collections. Once that's done, we can link to it from the end of the tutorial!

That's great! I will close this issue as it is already addressed in #2501
