### ISSUE TITLE
[suggestion] Amplify meaning of 'context' object in the case of Server Endpoints 

### ISSUE THREAD

**Issue by netaisllc** [withastro/docs#2540]
First, note that this issue is solely focused on _docs_ - it is not a remark on the technical implementation of the `context` object used by Astro. In fact, `context` is great, but I found it subtly confusing when coming from the perspective of "other" frameworks.

![Screen Shot 2023-02-01 at 7 15 13 PM](https://user-images.githubusercontent.com/1242423/216223419-a12301dd-b104-40c0-b818-4da28d3041c8.png)

The above shot is excellent; clear and terse.

![Screen Shot 2023-02-01 at 7 16 07 PM](https://user-images.githubusercontent.com/1242423/216223498-2931176b-fbda-40ba-92cb-03c18af36452.png)

This one caused confusion for me. To me, it too strongly implies that a server endpoint takes a `Request` - as in the standard Web Api sense. Which is true but...

The point is that server endpoints _do_ take a request but it's been recast into the form of the `context` object which is super convenient, but it's different from the Web Api `Request`.  (And endpoints do return a standard `Response` object.)

**Maybe consider adding a note** in the case of the second screen shot (and perhaps everywhere server endpoints are discussed) that amplifies the point that, in Astro server endpoints,  the Web Api `Request` object has been cast into a form more convenient to use called `context`.

**Comment by Jutanium** [comment]
Thanks for this! The `APIContext` _wraps_ the Request, so you can call `context.request` and get a standard request object. I'll make this clear on this page.
