### ISSUE TITLE
Astro 2.0 on AWS Amplify

### ISSUE THREAD

**Issue by lavorato** [withastro/docs#2555]
### What version of `astro` are you using?

2.0.5

### Are you using an SSR adapter? If so, which one?

Node.js

### What package manager are you using?

NPM

### What operating system are you using?

Mac

### Describe the Bug

Hello guys! I'm trying to use the SSR with AWS Amplify but when I activate the Node.js and change the output type to server, when I deploy to server I got an 404 error page. If I change to the static mode, it works well. Do you guys have any idea how could I use the SSR on AWS Amplify? I followed this walkthrough (https://docs.astro.build/en/guides/integrations-guide/node/) until the usage part. 

### Link to Minimal Reproducible Example

N/A

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by Jutanium** [comment]
Thanks for reporting this! Also check out this [SST guide](https://docs.astro.build/en/guides/deploy/sst/) that's specifically geared towards deploying an SSR Astro site to AWS. If these guides don't solve the issue, please let us know and we can figure out what in docs needs to change!

**Comment by sarah11918** [comment]
I'm closing this issue as it's been several weeks. Feel free to open  this, or another issue again if you're still having trouble with the AWS documentation!

**Comment by stephen-wigginton** [comment]
Following up, but AWS Amplify isn't meant for SSR using Astro, the following are the ones that Astro recommends. The 2 options showing AWS for hosting use a mix of S3 buckets and lambdas to serve content.

![image](https://user-images.githubusercontent.com/1105832/233580235-2e02c893-5db6-4bfd-8e97-324d1394c414.png)
