### ISSUE TITLE
[Suggestion] Adding status on translated pages only

### ISSUE THREAD

**Issue by pioupia** [withastro/docs#2562]
*I didn't see any other issue talking about this topic, but I apologize if it has already been mentioned in the past.*

Some pages of the documentation take a *long time* to be updated by the translators (for obvious size reasons).

Moreover, we, the translators, are not always up to date with the maintenance of previously translated pages.

All these reasons cause a sometimes huge gap between the translated pages, and the original pages, letting through many updates, as well as deprecating content, or not sharing new features.

As a result, users reading the translated documentation may have problems when working on their projects.

I don't know if it's technically possible, but why not add a small insert specifying that: `this page has not been updated since xx/xx/xxx, it's better to read the original documentation, or to help with the translation of this page` (or with another text).

This text will inform the user of the age of the translation, and will prevent the most careless from following probable false information.

**Comment by Jutanium** [comment]
This makes a lot of sense! Rather than using a date, we could maybe use number of commits? "This translation is 4 changes behind the English page."

**Comment by pioupia** [comment]
Yeah, it's a good idea to use the number of commits.

**Comment by delucis** [comment]
Thanks @pioupia — this is a great idea and something we’re already tracking in #1481 

I’ll close this as a duplicate but we’d definitely love to figure something out for this. There was also a recent Discord discussion around this: https://discord.com/channels/830184174198718474/1068518996384698430
