### ISSUE TITLE
Doc: Parent layout notes for Layouts section

### ISSUE THREAD

**Issue by KyleFontenot** [withastro/docs#257]
Should be noted that any astro component (layout or not) automatically populates an `<html>`, `<head>`, and `<body>` if none are explicitly defined. If **any** of the `<html>`, `<head>`, and `<body>` tags are defined in a component, that component takes precedence of inserting the three tags and must contain all of the three elements **that are edited**.  

Example: if you want to add a `class` to `body`, it must be in the same component as where the `html` or `head` elements are. If you aren't adjusting the `html` or `head` elements, then you dont necessarily have to include `html` or `head` in that same component. 

Essentially, the docs should say that all three of these elements should be grouped together in only one astro component/layout file.

---
For the main layout component (containing any of the forementioned tags), the `<style>` tag should **not** be inserted on the top of the page like convention says for other astro components. They can pretty much be put anywhere else BUT above `<html>`

**Comment by KyleFontenot** [comment]
The first point is the most important that gives errors commonly found such as https://github.com/withastro/astro/issues/2827

**Comment by sarah11918** [comment]
This behaviour should have been recently fixed by withastro/astro#3408

@KyleFontenot Would you be willing to try a small reproduction to see whether you can confirm that this is no longer an issue? If so, then no addition to the docs us neccessary!  🥳

**Comment by delucis** [comment]
- You don’t _need_ html/head/body but at some point you need `<head>` in one and _only one_ file
- No special layout vs component logic
- head required for script injection
- Can we recommend a standard pattern?

**Comment by sarah11918** [comment]
@delucis I know you've added your notes here from our issue triage with Nate today, so don't want to close this out on you. But, given that the bug causing the initial issue has been fixed, is there anything that you think NEEDS to change in the docs related to the original request? Did we address the issue with the `<style>` tag?

Do we consider a "recommended standard pattern for layouts" to be a separate issue?

Note:
Our docs are currently more "strict" than necessary:

> Astro Pages must return a full <html>...</html> page response, including <head> and <body>. (<!doctype html> is optional, and will be added automatically.)

Do we want to continue being overly conservative for "safety" or be explicitly accurate, as per your notes from today, and simply recommend a particular layout pattern? (And again, is this its own issue?)

**Comment by KyleFontenot** [comment]
Can confirm the issue was fixed! Someone can now refactor `<body>` into a child layout. Even class assignments work (didn't before).  I only tested the `<body>`, but I'm assuming refactoring `<head>` works the same. 

My second point in my original point was to not put `<style>` on top of the `<html>`, but I think it's unnecessary now as developers should know, and it's a small exception because you can put `<style>` anywhere in any other `.astro` file. 

The excerpt @sarah11918 on the docs is accurate and good. My suggestion is to add that excerpt, without the codeblock, as a blockquote underneath the Nested Layouts section. Top-down, I think that would be more specifically relevant to nesting layouts, instead of being on the Pages page.
