### ISSUE TITLE
[deploy] add stub for AWS Lambda?

### ISSUE THREAD

**Issue by sarah11918** [withastro/docs#2609]
Requested via Feedback Fish:

> Hey! Please ad docs on how to deploy to AWS Lambda. Ideally it should just boil down to API Gateway -> Lambda fun (no Express needed). Thanks!

Anyone interested in this?

**Comment by ElianCodes** [comment]
Willing to pick this up!

**Comment by delucis** [comment]
Awesome! We’ll probably want to think about how this meshes with our other AWS guides. Currently we have a [static AWS deployment guide](https://docs.astro.build/en/guides/deploy/aws/) (Amplify + S3), and guides for deploying to AWS via [Flightcontrol](https://docs.astro.build/en/guides/deploy/flightcontrol/) and [SST](https://docs.astro.build/en/guides/deploy/sst/). I’m guessing this would be a fourth “AWS Lambda” guide but happy to hear your thoughts!

**Comment by ElianCodes** [comment]
Yes, we definitely have to give this some more thought, we're going to run into this with probably GCP, Azure, Docker and any platform that supports more than one "simple" step-by-step guide.

**Comment by Jutanium** [comment]
@ElianCodes Hey, don't let the potential menu changes distract you - feel free to just make a new deployment guide for this!

**Comment by ElianCodes** [comment]
Allright! I'll give this some love this week! @Jutanium, can you assign this issue to me (just so I don't forget)?

**Comment by delucis** [comment]
Hey @ElianCodes, still interested in picking this up maybe next month?

**Comment by ElianCodes** [comment]
@delucis, I'll pick this up when I'm back! (Next week somewhere)

**Comment by sarah11918** [comment]
Gonna wait until someone asks for this! NO NEW CMS GUIDES RIGHT NOW lol
