### ISSUE TITLE
Mention that the docs exist on devdocs.io?

### ISSUE THREAD

**Issue by sarah11918** [withastro/docs#2610]
Someone asked about an offline copy of docs. Maybe we should mention they can see the docs there!

**Comment by ElianCodes** [comment]
Yeah, this should definitely be mentioned somewhere on the docs!

What about a fixed link in the right sidebar?

**Comment by sarah11918** [comment]
@Yan-Thomas - Any thoughts on a good spot for this?

**Comment by Yan-Thomas** [comment]
> @Yan-Thomas - Any thoughts on a good spot for this?

I understand that devdocs.io are using our docs, but not sure if we want to have projects not maintained by us in the sidebar. Perhaps we could just add a note to the Getting Started page about it? There's no other page that I think would be fitting for something like this.
