### ISSUE TITLE
astro/image: `src="/foo/bar.jpg` treated as remote image

### ISSUE THREAD

**Issue by tordans** [withastro/docs#2620]
This is either a bug report on the Image component or something to update and clarify in the docs. I assume the later. The Image docs should follow the wording and structure of the Script docs, I think.

---

The images docs at https://docs.astro.build/de/guides/integrations-guide/image/#src suggest say

> For images located in your public directory: use the URL path relative to the public directory. (e.g. src="/images/public-image.jpg")

However, when I try this, I get "Type '{ alt: string; src: string; }' is missing the following properties from type 'ImageComponentRemoteImageProps': width, height" which suggest, that the root import is treated as a remote image.

> <img width="719" alt="image" src="https://user-images.githubusercontent.com/111561/218109343-e00c38d0-9e07-4708-affd-0f580d927647.png">

---

This is actually in line with how the scripts docs https://docs.astro.build/de/guides/client-side-scripts/#load-external-scripts talk about script imports, which treat absolute paths as "(Load) external scripts".

**Comment by Jutanium** [comment]
We do document this in our [Images guide](https://docs.astro.build/en/guides/images/#local-images-in-public) - we could make it more clear in that [Image integration README](https://github.com/withastro/astro/blob/main/packages/integrations/image/README.md) by clarifying that public directory images are treated as remote images, or by combining them under the same remote images heading.

**Comment by tordans** [comment]
I suggest to structure the image docs more like the https://docs.astro.build/de/guides/client-side-scripts/#load-external-scripts docs which for me does a better job to explain this.
