### ISSUE TITLE
Improvements to Node Integration guide

### ISSUE THREAD

**Issue by jamesarosen** [withastro/docs#2639]
I've been trying to follow the [@astrojs/node integration guide](https://docs.astro.build/en/guides/integrations-guide/node/) to convert a pure-astro app to one that runs Fastify (or Express).

I have some suggestions for improvements. I'll be happy to open one or more PRs if there's interest any any of these:

1. `astro add node` runs a codemod on `astro.config.mjs`, but it adds `adapter: node()`, which is invalid. `mode` is required.
2. Under [middleware usage](https://docs.astro.build/en/guides/integrations-guide/node/#middleware), it's not obvious where the Express / Fastify code would live. I can't be in `astro.config.mjs`. Is `server/index.{js,ts}` a reasonable recommendation?
3. The Fastify / Express app has a static dependency on compiled Astro code: `import { handler as ssrHandler } from './dist/server/entry.mjs'`. That means the file fails `tsc` until the developer runs `astro build`.
4. There's no discussion of how to modify the `scripts` in `package.json`. At minimum, I think there needs to be some discussion of
   - `dev` running something like `concurrently` to simultaneously (a) rebuild Astro and (b) run the server. Bonus points for TypeScript awareness. Mega bonus points if this goes into the codemod.
   - `build` running `astro build` and then building the `server/` if necessary

**Comment by ElianCodes** [comment]
1. I noticed the required `mode` error as well! So put that in your PR for sure
2. The file where this code is lives is entirely up to the developer, but I would think the root of the project makes more sense.
3. Never experienced this myself, so 🤷‍♂️
4. I don't think this addition is in the scope of Astro, this is more of a developer choice (in my opinion), but maybe it's a good addition if people are not used to setting this up themselves.

**Comment by Jutanium** [comment]
Point 1 was fixed https://github.com/withastro/astro/pull/6333

**Comment by ElianCodes** [comment]
Yeah @Jutanium, this is difficult to document, but the happy path or recommended way to do this in "Astro's' eyes, can be interesting for sure!

**Comment by delucis** [comment]
I’d say at least for point 2 we can add example filenames to the Node integration README. That would at least hint at where you might put those — even if it’s up to developer preference in the end.

3 sounds like a bit of an edge case that would also be solved by a recipe addressing 4.

**Comment by Jutanium** [comment]
Hey @jamesarosen - if you're still interested in tackling this, we'd love that!
- The Node integration README can be found [here](https://github.com/withastro/astro/tree/main/packages/integrations/node).
- You can add a recipe (e.g., How to build a Node app with Astro) by following our [Recipes guide](https://github.com/withastro/docs/blob/main/RECIPES.md#more-recipes-page).

**Comment by jamesarosen** [comment]
Thanks for the tips, folks! I opened withastro/astro#6660 with the changes that would have helped me get going with the node integration.

**Comment by Jutanium** [comment]
Pinging for freshness - we'd be happy for anyone to write a _recipe_ and make _small_ changes to the Node integration README as needed

**Comment by delucis** [comment]
Noticed https://github.com/withastro/astro/pull/6660 was closed and there hasn’t been much activity on this issue recently, so closing for now, but still happy to look at improving this guide if there’s still interest!
