### ISSUE TITLE
Copy to clipboard feature for CodeSnippets

### ISSUE THREAD

**Issue by kyonlee** [withastro/docs#2643]
I've recently gone through the tutorial and believe it will benefit to have a copy to clipboard feature for the `CodeSnippet` component.

e.g. On the [Write your first Markdown blog post](https://docs.astro.build/en/tutorial/2-pages/2/) part you have to copy 3 .md snippets.

I'm willing to create a PR for this feature! 😄

**Comment by ElianCodes** [comment]
This would be an awesome feature indeed! 👍

Big thumbs up for me! Let me know if you need any help implementing!

**Comment by delucis** [comment]
Absolutely, this is something we’ve wanted for a long time. We are hoping to replace all our code snippets with an [upcoming npm package](https://github.com/hippotastic/expressive-code) when it’s ready, but in the meantime this would absolutely be super helpful.

One thing we’ve wondered about is how to treat deleted lines in our code snippets, but happy to look at a PR for sure!

**Comment by kyonlee** [comment]
Sorry, that it told a while to get a PR in. 😅

Please have a look and let me know what else would be needed.
The alerts currently in place were just for testing and will be removed.

Things to consider:
* The icon of the button
* Have code blocks to opt into the copy feature - like how it's currently done for code markings

**Comment by Stratis-Dermanoutsos** [comment]
I don't know how good my solution would be for this issue, however, I embed my own snippets using GitHub Gists.

I have made a custom component that gets a file from a Gist, embeds it to the docs page and even adds a copy-to-clipboard button to it.

It is applicable here as we're talking about only 3 snippets and they become much easier to maintain.

My component's code can be found [here](https://gist.github.com/Stratis-Dermanoutsos/abe2f9f8b3f952233dcea7916946886d). (It is more generalised for any plain HTML or framework, I just made it work for Astro)

For a live example, you can visit <https://notes.stratisdermanoutsos.com/en/frameworks/astro#basic-structure-of-a-component>.
