### ISSUE TITLE
Docs guide for Passing children to slot

### ISSUE THREAD

**Issue by RehkMansa** [withastro/docs#2649]
I was looking at the docs on prop patterns, and I came across this line

> If your component must be passed children to its default slot, you can enforce this by using type Props = { children: any; };.

I think the statement is a bit confusing and would be better phrased as:
>If your must pass children to your component's default slot, you can enforce this by using ```type Props = { children: any; };.```

Here is the [link](https://docs.astro.build/en/guides/typescript/#common-prop-type-patterns) to the section, also, if there were an example, it would be really helpful.

**Comment by Jutanium** [comment]
Thanks for the suggestion - we're reworking this page and will take it into consideration!
