### ISSUE TITLE
Document how to extend `window`

### ISSUE THREAD

**Issue by Princesseuh** [withastro/docs#2662]
Sometimes, you want to add a property to the `window` interface. TypeScript doesn't really document how to do this properly, and this situation is more likely to arise in Astro since we support TypeScript directly in script tags.

The solution is to add to `env.d.ts` (or any other `.d.ts` that's in the project scope) a Window interface, like such:

```ts
interface Window {
  helloChris: string;
}
```

The property will then appear in completions and by type-checked with no issues:

<img width="297" alt="image" src="https://user-images.githubusercontent.com/3019731/219025183-d9a9c013-8ba2-4a7a-b5b6-7b1e5e9ac39b.png">

### Side note

A similar situation happens for `globalThis`, but the way to add property to it is completely different, as you need to do the following:

```ts
export {}
declare global {
  function myFunction(): boolean;
  var myVariable: number;
}
```

<img width="305" alt="image" src="https://user-images.githubusercontent.com/3019731/219025697-31e7a291-ac30-491b-a334-e43a5b3bc4ed.png">

**Comment by Jutanium** [comment]
For the second example, exporting the declaration seems to work, too, rather than exporting an empty object:
```ts
export declare global {
  var testing: string;
  function myFunction(): boolean;
}
```

**Comment by Jutanium** [comment]
Additionally, it seems like declaring global sets those properties on both `globalThis` and `window`
