### ISSUE TITLE
Remove Netlify CMS From CMS Page

### ISSUE THREAD

**Issue by feraleyebrows** [withastro/docs#2678]
Possibly a touchy subject considering Netlify are a project sponsor but it seems accepted that Netlify CMS is officially dead after the main developer behind the project left the company. See here:

https://answers.netlify.com/t/is-this-project-dead/70988

Personally I would recommend Tina as the best alternative:

https://tina.io

But there is also this fork of netlify-cms that is being actively developed:

https://www.staticcms.org

**Comment by delucis** [comment]
Although Netlify CMS is unmaintained, we still get questions from people who want to use it with Astro, so at least in the short-term we'll probably keep that page.

Would love a PR adding a stub guide for tina.io if you have experience with it!

**Comment by feraleyebrows** [comment]
Can we at least add a warning message to the page alerting people to the fact that it is unmaintained?

**Comment by Jutanium** [comment]
@feraleyebrows - we definitely hear your concern, but our stance is that our docs aren't meant to maintain _recommendations_ - our guides are meant to explain how to integrate with a service, but not to instruct you on which service to use.
