### ISSUE TITLE
Move FeedbackFish to an island

### ISSUE THREAD

**Issue by FredKSchott** [withastro/docs#2683]
<img width="493" alt="Screen Shot 2023-02-18 at 10 06 32 AM" src="https://user-images.githubusercontent.com/622227/219881513-491d736d-026e-4ba4-8624-9c2a087115ce.png">

https://pagespeed.web.dev/report?url=https%3A%2F%2Fdocs.astro.build%2Fen%2Fguides%2Fupgrade-to%2Fv2%2F

We're seeing lower-than-expected performance on the docs site. I believe that Feedback Fish is the largest contributor to this. 

Moving the current `FeedbackButton` to an island will allow us to use `client:visible` and only load this JS if the button comes into view (most importantly, this will help with mobile perf). Most importantly, this will improve perf on mobile where that button script doesn't actually need to load until the "give feedback" button scrolls into view.

**Comment by delucis** [comment]
We should try using their React component: https://feedback.fish/help/react

We have the docs set up to use Preact’s [compat mode](https://preactjs.com/guide/v10/switching-to-preact/#setting-up-compat), so in theory we should be able to use that, reduce bundle size by avoiding the pre-bundled React I’m guessing is in the plain JS we currently use, and delay loading that JS with the hydration directive.

**Comment by Jutanium** [comment]
No luck getting their React component to work: https://github.com/withastro/docs/tree/feedback-fish-react
