### ISSUE TITLE
The Tutorial Tracker and the unit index on the right are incorrect until all the units have been translated.

### ISSUE THREAD

**Issue by liruifengv** [withastro/docs#2710]
I found a bug, maybe a feature.

![image](https://user-images.githubusercontent.com/25167721/220556395-ac307ddc-f146-49ef-9464-ef0706c25ee1.png)

The Tutorial Tracker and the unit index on the right are incorrect until all the units have been translated.

See:https://github.com/withastro/docs/pull/2704

**Comment by sarah11918** [comment]
Just triaging issues. Even though we're not yet ready to translate the tutorial, it would still be good to figure out what's going on, and when we eventuallty *do* want the tutorial translated, whether there's work we need to do first.
