### ISSUE TITLE
[Little UI issue] Markdown-page has a bad rendering of the code block

### ISSUE THREAD

**Issue by pioupia** [withastro/docs#2713]
### Describe the problem :
The problem is on [this page](https://docs.astro.build/en/guides/markdown-content/#using-components-in-mdx). You can see a block of code where the color is not correctly applied. As a result, the code loses readability.

This is where the problem is on : https://docs.astro.build/en/guides/markdown-content/#using-components-in-mdx

### What this issue changes for users :
Users will find it more difficult to read the code.

### Screenshots :

You can see the problem in image : 
<img alt="Ugly presentation" width="300px" src="https://user-images.githubusercontent.com/49518790/220689661-dde95f68-fc44-4b8e-93e7-6a6ad20f92b8.png" />

### A proposed but not optimal solution :
This can be solve by changing the language to `mdx` instead of `astro`, but I don't think it's a good way to solve the problem.
<img alt="Better presentation" width="300px" src="https://user-images.githubusercontent.com/49518790/220690383-0225f044-5331-4fca-99cb-b1b4a8252916.png" />

And with this technique, you also lose the style of the button code: `<Button title="Contact me" />`.

**Comment by delucis** [comment]
I wonder if changing the language to `md` works well? In general MDX lags behind a bit in terms of editor tooling/syntax highlighting but with `md` at least frontmatter and HTML tags should be highlighted ok.
