### ISSUE TITLE
Add documentation for `class:list`

### ISSUE THREAD

**Issue by Princesseuh** [withastro/docs#272]
Astro has an utility called `class:list` to allow to conditionally add classes to something, it was added in 0.21 but has never been documented

It'd be cool to have documentation for it because the VS Code extension does provide a completion for it, which will inevitably leads users to use it (and wonder how to use it)

For info on usage, see [this fixture](https://github.com/withastro/astro/blob/d84bfe719a546ad855640338d5ed49ad3aa4ccb4/packages/astro/test/fixtures/astro-class-list/src/pages/component.astro) and the [PR for it](https://github.com/withastro/astro/pull/1612)

**Comment by sarah11918** [comment]
@zadeviggers Is this something you'd be interested in looking into, with the directives you've been documenting?

**Comment by zadeviggers** [comment]
Yep, I'll add it in #282
