### ISSUE TITLE
Flicking issue while scrolling on some pages

### ISSUE THREAD

**Issue by ansidev** [withastro/docs#2726]
Steps to reproduce:
1. Prerequisites:
- Chrome (110.0.5481.177 (Official Build) (x86_64)) on macOS (13.2.1 (22D68)).
- No extension is enabled (recommended).
2. Open an example test URL: https://docs.astro.build/en/guides/content-collections/ (I guess this issue occurs on long pages)
3. Scroll up and down.

The address bar or bookmark bar (if enabled) will be flicking.

**Comment by delucis** [comment]
Thanks for the report @ansidev! Any chance you could share a screen capture of this behaviour? [Kap](https://getkap.co/) or QuickTime Player are both good options for this on macOS.

I’m testing on the same Chrome 110.0.5481.177 and macOS 13.2.1 combo but don’t see anything wrong 🤔

**Comment by ansidev** [comment]
Other browsers (macOS Ventura 13.2.1 (22D68))
- MS Edge Stable 110.0.1587.50 (Official build) (x86_64): OK.
- Firefox 110.0 64-bit: OK.

**Comment by delucis** [comment]
Hi @ansidev! Would you be able to test if this deploy preview is any better for you?

https://deploy-preview-2769--astro-docs-2.netlify.app/en/guides/content-collections

**Comment by ansidev** [comment]
> https://deploy-preview-2769--astro-docs-2.netlify.app/en/guides/content-collections

@delucis LGTM!

**Comment by delucis** [comment]
Hooray! Happy that fixed it 🥳

Thanks again for the issue.
