### ISSUE TITLE
Suggested change to docs to improve onboarding

### ISSUE THREAD

**Issue by jamiecarter7** [withastro/docs#2739]
This is a suggestion to improve the TS type checking for users just starting out with Astro (this includes myself).

I found that I was having hidden name referencing issue when trying to rename some of the props in a component.

It was specifically around forgetting the update the name inside the destructured Astro.props object.

I was using this snippet as my base

```
export interface Props {
  to: string;
  bodyText: string;
  class?: string;
}

const { to, bodyText, class: className } = Astro.props as Props;
```

But during changes I was forgetting to update the destructured object - and was only updating the interface object.

After scratching my head as to why no errors were throwing I realised the interface was never attached to the Astro.prop in the tutorial.

Tutorial link: https://docs.astro.build/en/core-concepts/astro-components/

Current code example:
```
---
// src/components/GreetingHeadline.astro
interface Props {
  name: string;
  greeting?: string;
}

const { greeting = "Hello", name } = Astro.props;
---
<h2>{greeting}, {name}!</h2>
```

Suggested code example:
```
---
// src/components/GreetingHeadline.astro
interface Props {
  name: string;
  greeting?: string;
}

const { greeting = "Hello", name } = Astro.props as Props;
---
<h2>{greeting}, {name}!</h2>
```
Saving new users the headache of missing TS errors.

**Comment by delucis** [comment]
Thanks for opening an issue @jamiecarter7! Astro's language server should be automatically using `Props` to type `Astro.props`, avoiding the need to use `as`. Could you share what editor you were using to work on this code?

**Comment by jamiecarter7** [comment]
I am using VS code

**Comment by jamiecarter7** [comment]
Another issue I've spotted is that if I change a file name or location I dont seem get a warning in the console that the file directory does not exist

**Comment by delucis** [comment]
Thanks @jamiecarter7. To double check, do you have our VS Code extension installed? We have some details in our [Editor Setup guide] (https://docs.astro.build/en/editor-setup/).

**Comment by delucis** [comment]
Closing this as I think the docs are correct on this topic. Still curious to hear more though, in case this is uncovering a bug in our tooling.
