### ISSUE TITLE
Content Collection SSR code snippet has type errors + fix

### ISSUE THREAD

**Issue by 60fov** [withastro/docs#2760]
https://docs.astro.build/en/guides/content-collections/#building-for-server-output-ssr

the suggested code snippet has type errors as `slug` and `entry` can be undefined and the guide doesn't mention handling them or if this expected behavior. The resulting ergo feels a bit off since typescript seems to be a significant part of the Content Collection Guide yet is completely neglected here. (assuming I didn't miss anything, or course)

```js
---
import { getEntryBySlug } from 'astro:content';
// 1. Get the slug from the incoming server request
const { slug } = Astro.params;
// 2. Query for the entry directly using the request slug
const entry = await getEntryBySlug('blog', slug);
// 3. (Optional) render the entry to HTML in the template
const { Content } = await entry.render();
---
<h1>{entry.data.title}</h1>
<Content />
```

### note/warning
the simplest solution would be to add a note or warning below the snippet, letting devs know to handle the type errors accordingly assuming Astro has no opinions on how to handle the errors themselves.

e.g.
> ⚠️ if you're using Typescript `slug` can be undefined if ..., and `entry` can undefined if ..., so handle with care. 

### improved code snippet
this is the better solution imo.
```js
---
import { getEntryBySlug } from 'astro:content';
// 1. Get the slug from the incoming server request
const { slug } = Astro.params;
// 2. check if the slug identifier matches the filename
if (slug === undefined) {
    throw new Error("slug/filename mismatch");
}
// 3. Query for the entry directly using the request slug
const entry = await getEntryBySlug('blog', slug);
// 4. redirect if the entry does not exist
if (entry === undefined) {
    return Astro.redirect("/404");
}
// 5. (Optional) render the entry to HTML in the template
const { Content } = await entry.render();
---
<h1>{entry.data.title}</h1>
<Content />
```

**Comment by delucis** [comment]
I agree we’d want to go the improved code snippet route on this one! We can nitpick what should be inside the `if` blocks when something is `undefined` but would you want to create a PR to get the ball rolling?
