### ISSUE TITLE
Should we add docs on using Bun as runtime?

### ISSUE THREAD

**Issue by ElianCodes** [withastro/docs#2768]
As you know, [Bun](<https://bun.sh/>) has existed for quite a while now.
I tested it recently with Astro and it works fine. Should we document this somewhere?

Willing to pick this up for sure!

![Screenshot 2023-03-01 at 22 01 19](https://user-images.githubusercontent.com/15145918/222264096-6489438d-5dc6-42c0-8d0b-748781d3ce13.png)

But I did notice that the `@astrojs/image` integration does not work!

**Comment by delucis** [comment]
Interesting. How would you imagine documenting it? Is it effectively a replacement for npm/pnpm/Yarn so e.g. we’d add `bun i astro` anywhere we show  `npm i astro` or is it more complicated than that?

**Comment by ElianCodes** [comment]
At this moment, I feel like it's indeed something like 'bun install' and 'bun run ...'. But maybe there's more here then we see at first sight, for example, what with 'npx create-astro' and such. 

I'll take a deeper look into this tomorrow and gather some more thoughts!

I'll update this issue sometime tomorrow!

**Comment by delucis** [comment]
Thanks! If that were the case, that’s a pretty big change to go through updating all our package manager prompts to also include `bun` — especially if it turns out to still be a bit experimental and not support everything (like the image integration). So definitely something to chat through and figure out what’s best.

**Comment by sarah11918** [comment]
Just pinging this for freshness... and wondering whether this could be a good recipe as an experiment, until we figure out whether it seems like something stable enough for more general purpose?

**Comment by ElianCodes** [comment]
Yes, I definitely think this would fit better in the recipes section than an overall page! Want me to write this out?

In the meantime, I verified that Bun is very usable with astro, except for the creation of a project, but we can mention that in docs for sure!

**Comment by sarah11918** [comment]
@ElianCodes Would be happy to have this in docs if you're up for writing it out!  🙌
