### ISSUE TITLE
GraphQL data fetching example is broken

### ISSUE THREAD

**Issue by delucis** [withastro/docs#2775]
Got this report via Feedback Fish:

> Hey, just to let you know that the code example in the GraphQL queries section of the docs here: https://docs.astro.build/en/guides/data-fetching/#graphql-queries does not work.
>
> I wanted to reference it to play with GraphQL in Astro, but when I copy/pasted the code to test locally, it failed telling me the response wasn't valid json. So I went to the URL of the sample data at https://graphql-weather-api.herokuapp.com and it seems that's the problem. The app is down, I daresay because Heroku has axed all those lovely hobby tier apps and maybe this was a victim of that?

We should probably find an alternative dummy API we can use instead.

**Comment by ElianCodes** [comment]
What about this Space API? https://spacex-production.up.railway.app/

**Comment by delucis** [comment]
Wondering if this Star Wars API hosted on graphql.org might be more stable?

Example query:
https://graphql.org/swapi-graphql?query=%7B%0A%20%20allFilms(first%3A%203)%20%7B%0A%20%20%20%20films%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20title%0A%20%20%20%20%20%20episodeID%0A%20%20%20%20%20%20releaseDate%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D
