### ISSUE TITLE
SSR docs / guide doesn't really highlight streaming feature

### ISSUE THREAD

**Issue by chrisdmacrae** [withastro/docs#2786]
Streaming is an extremely powerful feature of Astro SSR, but it's not highlighted in any real way in the docs.

Let's do that! Happy to submit a PR with an addition.

https://docs.astro.build/en/guides/server-side-rendering/

**Comment by chrisdmacrae** [comment]
SORRY, will do today!

**Comment by Jutanium** [comment]
Linking! https://github.com/withastro/docs/pull/2851
