### ISSUE TITLE
SSR docs should highlight difference from static for dynamic routing

### ISSUE THREAD

**Issue by snide** [withastro/docs#2792]
I got tripped up for a couple hours today when trying to figure out how SSR works. I'd started from the tutorial flows and started with simple routes, then followed the guide for content collections, migrationing my content to `[...slug]` files. When it came to SSR the guidelines seemed to suggest that all that was needed was a config change and an adapter, but in reality, you'll also need to convert any static routing to dynamic routing when you make that switch. This is made more confusing by getting somewhat vague, silent fails in Astro when running SSR with static routes (pages will hang, but not really tell you why, giving you type errors).

My suggestion to improve the docs would be to link to the content collection docs that describe SSR needs directly in the SSR docs. A subsection of "Dynamic routing" as a feature on that page should do the trick. This is the content it should link to:

https://docs.astro.build/en/guides/content-collections/#building-for-server-output-ssr

I'm happy to set up a PR for this work, I just want to make sure it makes sense to others before setting it up. I think it makes sense seeing as most people will graduate to SSR, and assume all the information they need is on that page.

**Comment by sarah11918** [comment]
Hi @snide, thanks for this observation! We have wanted to update our routing page in general, now that SSR, hybrid rendering are now established features since that page was first designed.

I'd be happy to see what you come up with in a PR, as I think this is a great idea, and happy to work through details there!  :raised_hands:

**Comment by snide** [comment]
Cool. I'll give it a shot sometime this week. Thanks for the response.

**Comment by imjb87** [comment]
@sarah11918 I was actually coming here to raise this too! 

I got tripped up myself earlier on this, and in particular the use of dynamic routes with Storyblok in SSR mode. I would be happy to offer some time to improving the Storyblok recipe to include how to set up SSR mode for the editor and handling dynamic routes.

**Comment by sarah11918** [comment]
Amazing, @imjb87 ! The more the merrier! 👐

**Comment by Jutanium** [comment]
Noting that our main problem is that the [SSR Guide](https://docs.astro.build/en/guides/server-side-rendering/) is incomplete if you're migrating from SSG.

**Comment by sarah11918** [comment]
Copying from https://github.com/withastro/docs/pull/2826/

```
When migrating from a static site to a server-rendered site, make sure you make all the proper adjustments based on the type of Astro site you are building. There are bits of configuration sprinkled around the documentation worth checking, but it's not limited to:

- [Dynamic routes for SSR](https://docs.astro.build/en/core-concepts/routing/#server-ssr-mode)
- [Modifying the `[...slug]` example for SSR](https://docs.astro.build/en/core-concepts/routing/#modifying-the-slug-example-for-ssr)
- [Building the content collections for SSR](https://docs.astro.build/en/guides/content-collections/#building-for-server-output-ssr)
```

**Comment by delucis** [comment]
@sarah11918 will be working on a revamp of our SSR docs in the coming months, so closing this as it will be tackled then. Thank you again for the issue!
