### ISSUE TITLE
[Templates / frameworks/ integrations] listing the associated names 

### ISSUE THREAD

**Issue by ampmonteiro** [withastro/docs#2793]
Hi,

![image](https://user-images.githubusercontent.com/31895754/223145644-a3e9fba4-0e44-4c4f-a441-b03a35498d35.png)

i  recommend that the list of templates / frameworks / integration (that exist in astro.new, with associate name for the command `npm create astro@latest -- --template <example-name>`   should be in the docs for two reasons:

- the list is not in astro v2 cli (where in v1 that list existed),  i create discussion about it  [here](https://github.com/withastro/roadmap/discussions/513)

- the names are not direct association, for example: for lit the name when start new app with flag `--template`  is  `--template framework-lit` , i would expect the name to be just lit or for tailwind is `--template with-tailwindcss`, i would expect just tailwindcss.
 To me, since is not clear / direct, it should be documented and with this do not exist the need to go to  [astro.new page](https://astro.new/)  or  [official examples github repo](https://github.com/withastro/astro/tree/main/examples)

Where this info should be?

In my opinion should be in `Getting Started` page and  `installation` page.

**Comment by delucis** [comment]
Does give me an astro.new feature idea: what if it let you copy the create astro command for each framework? 🤔
