### ISSUE TITLE
Translation not possible on some elements

### ISSUE THREAD

**Issue by Chrissdroid** [withastro/docs#280]
Translation is not possible on theses elements :

- `Top navigation` title
- `Site navigation` title
- `Table of content` title
- Search input in the top bar
  - `Press '/' to search`
- The entire search modal component
- The `<sponsor/>` component 
  - the text "Sponsored by"
  - the aria-label on the sponsor
- The sidebar content placeholder when no translation found
  - "No Translations Found"
  - "View in English"
- "Skip to Content" text
- Avatar list component
  - Contributor image alt & title
  - Additionnal contributor text
- config.ts `SITE` and `OPEN_GRAPH` constants for defaults values in each languages

> ### Edit: more found !
> - `InstallLayout` layout component
>   - `title` & `description` is overwriten
>   - the entire content is static on this layout
> - the `configuration-reference` is auto-generated in english but no options si available for i18n's translations

It's all i got when searching in the code, may be more hidden in corners that i didn't found !

**Comment by sarah11918** [comment]
Wonderful! Even if there's more to find, this is a great start!

I can't promise when we'll get to it, but now we have a record of what to look for... 😄

**Comment by delucis** [comment]
@sarah11918 Feel free to assign this to me and I can go through addressing these where possible.

Thanks for this thorough list @Chrissdroid!

**Comment by sarah11918** [comment]
@delucis I'm not sure you need my assignment, and I'm certainly not going to stop you.. this would be great! It's difficult to plan i18n work right now that won't just need to be done all over again, but this is content-independent, and absoulutely worth doing!  😄

**Comment by delucis** [comment]
@Chrissdroid We just merged #307. Is there anything important left from this issue we should tackle?

**Comment by Chrissdroid** [comment]
I think everything is done with what i mentioned, nice work ! We can close this in prior of #359 and put new issues on there if some components need rework in regard of the docs refactor 😄 (as i said on the pull, I'm not worried about the “sponsored by” text so for now let it be like that and ajust whenever new issues happens)
