### ISSUE TITLE
[Traslations] Add spanish traslation to Mark Doc documentation

### ISSUE THREAD

**Issue by nujovich** [withastro/docs#2824]
Mark doc documentation supports English only at the moment

**Comment by sarah11918** [comment]
Thanks for the request, @nujovich! We do have a system in place for tracking translated pages, and we do have dedicated Spanish translators who work on the site as they are available! They are very active, so I'm sure they'll get to this page when they can!

**Comment by delucis** [comment]
Sharing our i18n dashboard for visibility: https://i18n.docs.astro.build/

We actually mark all our integration guides as `i18nReady: false`. Do we want to revisit that?
