### ISSUE TITLE
Broken starter template instructions

### ISSUE THREAD

**Issue by ohansemmanuel** [withastro/docs#2831]
Hi there! 

In #2372 , @delucis and I discussed a (now fixed) issue with templates. 

In the latest version of create-astro, some other issue seems to be back. For example: 

✅ This worked before 
```bash 
npm create astro@latest -- --template ohansemmanuel/
astrojs-ditch-the-runtime-react
```

❌ Right now, the exact same command fails 

<img width="1157" alt="CleanShot 2023-03-11 at 13 22 47@2x" src="https://user-images.githubusercontent.com/10930234/224484200-c9d66099-aeac-4539-8c92-67045fed7903.png">

Any ideas why? 

The documentation remained the same. I wonder if there's a change in functionality that should be documented?

**Comment by rishi-raj-jain** [comment]
@ohansemmanuel because there's a break in your repo name, 
```
npm create astro@latest -- --template ohansemmanuel/astrojs-ditch-the-runtime-react
```
would work
