### ISSUE TITLE
Add note about the image integration altering image imports, in the image integration page itself

### ISSUE THREAD

**Issue by MoustaphaDev** [withastro/docs#2837]
Although it's already documented in [this page](https://docs.astro.build/en/guides/images/#using-img-with-the-image-integration), I think it would be a good addition to add a note about this in the image integration page itself

**Comment by Jutanium** [comment]
Just linking to [the file to edit](https://github.com/withastro/astro/blob/main/packages/integrations/image/README.md)!

**Comment by delucis** [comment]
Closing as the image integration will be deprecated in 3.0 and we’re currently working on a revamp of our image documentation generally in #3739.
