### ISSUE TITLE
Add note about baseurl in Images guide

### ISSUE THREAD

**Issue by Mitsunee** [withastro/docs#2840]
Currently the [Images](https://docs.astro.build/en/guides/images/) contains this example:

```html
<!-- Local image stored at public/assets/stars.png -->
<img src="/assets/stars.png" alt="A starry night sky.">
```

This could be confusing for users making use of the [`"base"`](https://docs.astro.build/en/reference/configuration-reference/#base) config option, as the url will from the example will be invalid in combination with this config option. The correct src attribute path would be `"/myBaseUrl/assets/stars.png"`.

**Comment by Jutanium** [comment]
Thanks for this - our approach is to document this in the [`base` reference](https://docs.astro.build/en/reference/configuration-reference/#base)!

We'll be planning a recipe on working with `base`.
