### ISSUE TITLE
Nuxt 3: Update Performance Report

### ISSUE THREAD

**Issue by HelloAlexPan** [withastro/docs#2847]
Hey guys at Astro! First off, awesome project — we're big fans over here!

Recently, you guys published the [2023 Web Framework Performance Report](https://astro.build/blog/2023-web-framework-performance-report/) with a comparison to Nuxt. 

Given how the links in the page were to Nuxt 2, I thought it was highly likely that this performance report was generated using **Nuxt 2** as opposed to **Nuxt 3**, which offers far better performance.

Given Nuxt 3 is now the official build (and has been for the past year), I think a fairer comparison would be between Astro and Nuxt 3 as opposed to Nuxt 2. 

What are the communities thoughts?

**Comment by delucis** [comment]
Hi @HelloAlexPan!

From what I’ve understood, this report was compiled based on third-party data which isn’t able to detect which version of a tool was used, so it wasn’t possible to break down framework analysis by version number. This is covered in [the final section of the blog post](https://astro.build/blog/2023-web-framework-performance-report/#methodology--limitations) and also discussed a bit in @FredKSchott’s [Twitter thread about the post](https://twitter.com/FredKSchott/status/1633193631246057472).

As this is the issue tracker for Astro’s docs site, I’ll close this issue as our docs maintainers aren’t involved in the performance report.
