### ISSUE TITLE
Pull out Markdown plugin examples into a recipe

### ISSUE THREAD

**Issue by Jutanium** [withastro/docs#2864]
[This section](https://docs.astro.build/en/guides/markdown-content/#modifying-frontmatter-programmatically) should be a recipe!

**Comment by sarah11918** [comment]
Bumping this one, since it could be a good chance for someone to try to turn some existing content into a recipe!  :partying_face:

**Comment by Jothsa** [comment]
I can try to tackle this. Should the section be removed from the Markdown & MDX page since it's a recipe? Should it be linked on the page?

**Comment by sarah11918** [comment]
@Jothsa Yes to the above! It should be removed from the page it is on, written as its own file under `content/docs/en/recipes/` and replaced by our "Related Recipes" component that takes the new link as props. 

You can see an example of that component being used here: https://docs.astro.build/en/guides/imports/#extending-file-type-support.
