### ISSUE TITLE
Avoid hydration mismatch error in tutorial

### ISSUE THREAD

**Issue by delucis** [withastro/docs#2871]
Our [`Greeting.jsx` component in the tutorial](https://docs.astro.build/en/tutorial/6-islands/1/#include-a-preact-greeting-banner) randomises its initially displayed greeting opening the door to a hydration mismatch on the client. We should avoid this by making the initially displayed greeting predictable, e.g.
```diff
-  const [greeting, setGreeting] = useState(randomMessage());
+  const [greeting, setGreeting] = useState(messages[0]);
```

Discord report: https://discord.com/channels/830184174198718474/830184175176122389/1086023239723130971

**Comment by sarah11918** [comment]
Fixed by @BryceRussell ! Not the first time I've written that today! :partying_face:
