### ISSUE TITLE
Configuring Algolia in the Astro framework?

### ISSUE THREAD

**Issue by nyhxiaoning** [withastro/docs#2874]
After configuring the current Algolia as follows, the results cannot search the currently deployed page, and an error appears as shown in Figure 1 below.

![image](https://user-images.githubusercontent.com/34833782/225844906-c3705c90-4efe-404e-8b1b-dbcd8a4686a5.png)

I would like to inquire about implementing the search configuration in the Astro framework. Apart from the following three fields: indexName, appId, and apiKey, are there any other content that must be configured?
export const ALGOLIA = {
	indexName: 'henry-git-master-nyhxiaoning',//这个名字的来源，可以新建New API Key后，找到更新查看indices
	appId: ' F55Q6IXQJ6',
	apiKey: 'a90a2ba0ae3064e4cc5550f8cfbb0754',
};

thanks!

**Comment by nyhxiaoning** [comment]
The following is the URL of my complete request:

https://l77ql0k6kc-dsn.algolia.net/1/indexes/*/queries?x-algolia-agent=Algolia%20for%20JavaScript%20(4.15.0)%3B%20Browser%20(lite)%3B%20docsearch%20(3.3.3)%3B%20docsearch-react%20(3.3.3)&x-algolia-api-key=bb4b5ccc6005a8b219b1781eed1f68cd&x-algolia-application-id=L77QL0K6KC

**Comment by delucis** [comment]
Hi @nyhxiaoning! Is this using the docs starter template? I’m seeing an “indexName is not valid” error for your request so I’m guessing `henry-git-master-nyhxiaoning` is not how it’s configured with Algolia?

**Comment by nyhxiaoning** [comment]
@delucis thank you.
I did use the official template from Astro, a document center for my resume. At the same time, I have applied for the configuration of the relevant Algolia, as shown in the following figure. After deployment, the search does not take effect.
![image](https://user-images.githubusercontent.com/34833782/226087804-c490675b-3e86-4a4a-afb0-672ed3c93100.png)

**Comment by nyhxiaoning** [comment]
@delucis It has already taken effect, thank you
