### ISSUE TITLE
Should we remove the Docker examples from GCP deploy guide?

### ISSUE THREAD

**Issue by ElianCodes** [withastro/docs#2881]
We've written and rewritten the GCP deploy guide a couple of times, before recipes were a thing.

Now that we've also added Docker as a recipe, should we remove the Docker examples in the GCP guide and refer to the recipe to remove duplicate content? Or keep it the way as it is to offer a full and complete guide for Google Cloud deploys?

I think this should be discussed!

**Comment by Yan-Thomas** [comment]
I'm +1 in removing the content from the Google Cloud Deploy page, I'd possibly just keep the final instructions on how to push to GCP, or replace them with a link from GCP docs with these instructions. Though first, would love to hear @sarah11918's & @Jutanium's opinions on this.

**Comment by ElianCodes** [comment]
@sarah11918 & @Jutanium, if you guys agree, I can make work of this quite quickly! Just give me the word!
