### ISSUE TITLE
Headless WordPress & Astro incorrect code

### ISSUE THREAD

**Issue by jamesli2021** [withastro/docs#2887]
In https://docs.astro.build/en/guides/cms/wordpress/

Found it should be JSX curly bracket, and many instance of Astro code in this page are shown incorrectly.
```
<h2 set:html="post.title.rendered" />
<p set:html="post.content.rendered" />
```

to

```
<h2 set:html={post.title.rendered} />
<p set:html={post.content.rendered} />
```

**Comment by Yan-Thomas** [comment]
You're right, thanks for catching this @jamesli2021. Would you be interested in making a PR fixing this? We can help you out through the process if you need 🙌

**Comment by jamesli2021** [comment]
@Yan-Thomas I hope the PR is good. https://github.com/withastro/docs/commit/579c8361cb98c20af38052366d5ee476cd84fa1a
