### ISSUE TITLE
Building Draft Pages

### ISSUE THREAD

**Issue by matthewmercuri** [withastro/docs#2896]
# Issue/Discussion
As someone who looked to the blog template as guidance to get started, I found the "draft" behaviour a little confusing. Based on the documentation, one might expect that setting a frontmatter property of `draft: true` would mean it is excluded from the build.

I think the confusion lies with using `getCollection` instead of `Astro.glob` **in** `getStaticPaths`. The blog template has the user use `getCollection` in `[...slug].astro`. As such, it is up to the dev to write their own draft filtering logic. For instance, I wrote `getStaticPaths` in `[...slug].astro` like this:
```typescript
export async function getStaticPaths() {
  const posts = await getCollection("blog", ({ data }) =>
    isDev ? true : !data.isDraft
  );
  return posts.map((post) => ({
    params: { slug: post.slug },
    props: post,
  }));
}
```
**NB** `isDev` is just a constant set to true if utilizing a dev environment.

Of course, this also meant that I had a `isDev: z.boolean().optional()` addition to blog collection schema.

I think it would go a long way to update the docs in a manner that would explain something analogous to the above must be done if you do not want to include "draft" pages in builds. I can PR if the maintainers provide some direction in how to proceed.

**Comment by ElianCodes** [comment]
Hey there! Thanks for raising the question and opening an issue!

While I do get your confusion, the `draft: true` feature in frontmatter is a somewhat dated feature. I'll take a look into this!

I'm going to be so bold to self-assign this and work something out in the docs, but feel free to step up!

**Comment by sarah11918** [comment]
Checking in here with @bholmesdev that our guidance for using `draft: true` on MD/MDX pages *located within `src/pages/`* is not appropriate for content collections. This property is not "special" in content collections?

From https://docs.astro.build/en/guides/markdown-content/#draft-pages :

> draft: true is an optional frontmatter value that will mark an individual Markdown or MDX page or post as “unpublished.” By default, this page will be:
> 
> - excluded from the site build (no page will be built)
> - returned by [Astro.glob()](https://docs.astro.build/en/reference/api-reference/#astroglob) (visible in lists of posts)

From https://docs.astro.build/en/guides/content-collections/#filtering-collection-queries :

> You can use this to filter by any content criteria you like. For example, you can filter by frontmatter properties like draft to prevent any draft blog posts from publishing to your blog:

```
// Example: Filter content entries with `draft: true` frontmatter
import { getCollection } from 'astro:content';
const draftBlogEntries = await getCollection('blog', ({ data }) => {
  return data.draft !== true;
});
```

**Comment by bholmesdev** [comment]
@sarah11918 Correct! No magic handling for drafts in content collections right now. Hasn't been requested as a feature surprisingly, so we've kept it to a manual filter.

**Comment by delucis** [comment]
Sounds like we won’t make any changes to the Astro API and we do show an example of the filter function in docs, even if not quite the same function as shown in this issue, so will close for now.
