### ISSUE TITLE
Add an alternative “Create a GitHub issue” button to feedback modal

### ISSUE THREAD

**Issue by delucis** [withastro/docs#2901]
Our feedback modal currently submits all feedback to Feedback Fish but if people have GitHub accounts it would be cool to funnel them to our issues as an alternative path (also to hint at people that this is where a lot of work happens!)

Bonus points if we can pre-fill the GitHub issue with any message a site visitor has already started authoring in the message box!

Example: here’s the form in [the AsyncAPI docs](https://www.asyncapi.com/docs/concepts)

![Feedback modal that includes a “Create an issue” option](https://user-images.githubusercontent.com/357379/226721447-a738163c-2c2b-4a21-8879-da3486c2b1fb.png)

Feedback modal source code: https://github.com/withastro/docs/blob/main/src/components/tutorial/FeedbackButton.astro

**Comment by Aperezpe** [comment]
@delucis I would like to work on this issue.

**Comment by ElianCodes** [comment]
Super awesome Idea @delucis ! This would decrease the work of core / docs to check which feedback came in and prepare them into issues!
