### ISSUE TITLE
Document that Markdoc wraps things in an `<article>` tag

### ISSUE THREAD

**Issue by sarah11918** [withastro/docs#2904]
Look into this, and if necessary, document this as it could have CSS implications for peeps.

> I notice that @astrojs/markdoc surrounds content with `<article>…</article>` whereas when @astrojs/mdx doesn’t. Is that just how markdoc behaves out of the box, or is it something from the Astro integration? The difference means having to adjust my css to accommodate the `<article>` 
>
> Dug a little into the code, looks like that’s just how markdoc works 🤷🏼‍♂️

Discord comment: https://discord.com/channels/830184174198718474/830184175176122389/1087979888734130256

**Comment by Yan-Thomas** [comment]
Adding Ben's comment here for visibility:
> Ah yep, that’s just a Markdoc-ism! I could see that being restrictive for certain use cases though. I’ll check with the team about a config option

Ideally I think it's best to wait if we end up having a config added or this detail removed as a whole before taking action.

**Comment by sarah11918** [comment]
And more context from Markdoc themselves: https://github.com/markdoc/markdoc/discussions/347

We chose this as the default behavior because we wanted the top-level transform to return a single render tree node. It can easily be changed by overriding the document node in your Markdoc configuration. If you want Markdoc.transform to return an array that isn't wrapped in a tag (which Markdoc's React renderer will turn into a Fragment), you can use the following configuration:

```
import Markdoc from '@markdoc/markdoc';

const config = {
  nodes: {
    document: {...Markdoc.nodes.document, render: null}
  }
};

const doc = Markdoc.parse(example);
const output = Markdoc.transform(doc, config);
```

**Comment by ancaemcken** [comment]
Hello there, 

I've just tried this, and the solution above won't play nice in Astro because it returns an array of items instead of a single tree, as the `<Content>` component appears to expect.

What worked was this customized `document` node. 

```
    document: { ...Markdoc.nodes.document, render: 'div' },
```
Without the `div`, the content area was blank.

If folks prefer, they can create a custom element/Markdoc node and use that instead.

**Comment by louiss0** [comment]
I'm pro-removal this being the default.  
``` 
 nodes: {
    document: {...Markdoc.nodes.document, render: null}
  }
```
I did not know  Markdoc did this and I don't think anyone wants this either. The article tag is commonly used in the dynamic paths pages along with the content component.

**Comment by sarah11918** [comment]
Closing this one, since per the linked attempt to document this, there are workarounds. And, Ben may be working on the Markdoc integration itself which could affect what we document.
