### ISSUE TITLE
⚠️ Issue Why tutorial recommends the usage of global styling?

### ISSUE THREAD

**Issue by marcinjahn** [withastro/docs#2929]
These two pages recommend to use global styles:
- https://docs.astro.build/en/tutorial/3-components/3/
- https://docs.astro.build/en/tutorial/3-components/4/

It contradicts a piece of advice given on one of the previous pages - use global styling only when it's necessary. In the linked cases, I don't think it really is necessary.

**Comment by jacobthesheep** [comment]
Issue can be closed.
