### ISSUE TITLE
Don't use Glob with content collections

### ISSUE THREAD

**Issue by Jutanium** [withastro/docs#2945]
Document that `Astro.glob` doesn't work with content collections, and you should use `getCollection` instead.

**Comment by CBID2** [comment]
I can help with this issue @Jutanium

**Comment by donovangomez** [comment]
Hi @Jutanium and @CBID2 ! Was wondering if it was alright if I can contribute if this wasn't done already. I didn't see any mention of it in the [Astro.glob()](https://docs.astro.build/en/guides/imports/#astroglob) section.

Just to make sure I understand the issue before a PR:
- With Astro 2.0 you can now create a folder in the <code>src/</code> directory called <code>content</code>
  e.g. <code>src/content/blog</code>
- It opens the use of [Content collections](https://docs.astro.build/en/guides/content-collections/) where you can now
  use <code>getCollection()</code>  to query the folder for any MD and MDX files in the directory. Blog in this case
- This should point to people like me who is still on Astro 1.0 using Astro.glob to get my blog posts in MD lol.

Also appreciate the work on the docs and Solid @Jutanium . I think Astro is pretty dank.

**Comment by CBID2** [comment]
> Hi @Jutanium and @CBID2 ! Was wondering if it was alright if I can contribute if this wasn't done already. I didn't see any mention of it in the [Astro.glob()](https://docs.astro.build/en/guides/imports/#astroglob) section.
> 
> 
> 
> Just to make sure I understand the issue before a PR:
> 
> - With Astro 2.0 you can now create a folder in the <code>src/</code> directory called <code>content</code>
> 
>   e.g. <code>src/content/blog</code>
> 
> - It opens the use of [Content collections](https://docs.astro.build/en/guides/content-collections/) where you can now
> 
>   use <code>getCollection()</code>  to query the folder for any MD and MDX files in the directory. Blog in this case
> 
> - This should point to people like me who is still on Astro 1.0 using Astro.glob to get my blog posts in MD lol.
> 
> 
> 
> Also appreciate the work on the docs and Solid @Jutanium . I think Astro is pretty dank.

You can work on it. I stil need time with Astro
