### ISSUE TITLE
Error message not properly displayed in Tailwind integration page

### ISSUE THREAD

**Issue by DjebbZ** [withastro/docs#2957]
In https://docs.astro.build/en/guides/integrations-guide/tailwind/#class-does-not-exist-with-apply-directives, the error message looks fine in the markdown code and in the markdown preview on Github, but doesn't look correct I think in the rendered website https://docs.astro.build/en/guides/integrations-guide/tailwind/#class-does-not-exist-with-apply-directives.

**Comment by sarah11918** [comment]
Thanks for pointing this out @DjebbZ! @BryceRussell tackled this for us!  :partying_face:
