### ISSUE TITLE
"Content-focused" excludes many websites you can build with Astro

### ISSUE THREAD

**Issue by Jutanium** [withastro/docs#2959]
Folks get confused when they read [Why Astro](https://docs.astro.build/en/concepts/why-astro/#content-focused). Can I build my site with Astro even if it isn't content-heavy?

It's not the content-focus that's the limit - it's whether your site makes use of shared client-side state across routes.

> Is astro good for only content heavy websites?
> Like would astro be a bad choice if I wanted to create something like Google forms

**Comment by CBID2** [comment]
> Folks get confused when they read [Why Astro](https://docs.astro.build/en/concepts/why-astro/#content-focused). Can I build my site with Astro even if it isn't content-heavy?
> 
> 
> 
> It's not the content-focus that's the limit - it's whether your site makes use of shared client-side state across routes.
> 
> 
> 
> > Is astro good for only content heavy websites?
> 
> > Like would astro be a bad choice if I wanted to create something like Google forms

As a newbie to Astro,I feel this way too @Jutanium. Maybe there can be a paragraph or a section that explains other projects that this product can build? It would lessen the prespective 
tone that the first paragraph has.

**Comment by Jothsa** [comment]
I agree this should be done and am happy to make a pr. Maybe say something like 

> Astro sites can have interactivity, but Astro was not designed to share client-side state across routes.

And then give an example of something that can be done with Astro and something that shouldn't be done. Maybe to use the Google forms example, say Astro can include an interactive multi step form on one page, but if the user closes the page, the form won't load exactly where the user left off with the users entries saved? I don't know if that's the best example though. Any thoughts, anyone?
