### ISSUE TITLE
Update `reactjs.org` links to newer `react.dev` site

### ISSUE THREAD

**Issue by Yan-Thomas** [withastro/docs#2988]
We link to the old https://reactjs.org site a few times in docs, and now we need to update these with their new docs site at https://react.dev. Looking through the `withastro/docs` and `withastro/astro` repos using your code editor's search/find feature should be enough to find most of them.

The old and new docs pages are not 1:1, so you also need to find the corresponding page in the new docs so there's no information being missed out on.

**Comment by sarah11918** [comment]
Quick reminder that some of these pages only mirror content from the main Astro repo! So make sure you're PRing the correct repo/file!

It's mostly the integration docs you'll need to worry about. If you find a link that needs updating on any of the integration docs listed here: https://docs.astro.build/en/guides/integrations-guide/

 Then you'll need to PR the package README somewhere here: https://github.com/withastro/astro/tree/main/packages/integrations
 
 To help you remember, at the VERY TOP in the frontmatter of any of those files, there's a comment telling you exactly where the original file is stored. So when making a PR, always check the top of the page! (A good rule all the time!)
 
 Happy hunting, peeps!

**Comment by Susmita-Dey** [comment]
I'd like to help

**Comment by Yan-Thomas** [comment]
> I'd like to help

Awesome @Susmita-Dey! No need to ask permission, feel free to jump on it. I'd love to give guidance if you need, ping me @Yan (he/him) on Discord or here.

As pointed out above, might be helpful to clone our docs and astro repositories and use the "search and find" feature of your code editor to find references to reactjs.org. Then, it's just a matter of looking through the new react.dev docs and finding a page that has the relevant information for that link and updating it.

**Comment by dreyfus92** [comment]
@Yan-Thomas There's a PR open https://github.com/withastro/docs/pull/2991 already.

**Comment by Susmita-Dey** [comment]
Hello @Yan-Thomas Which repositories are left to complete the same tasks?

**Comment by Yan-Thomas** [comment]
> Hello @Yan-Thomas Which repositories are left to complete the same tasks?

Hi @Susmita-Dey, I believe the already existing PRs cover all the references in both `withastro/docs` and `withastro/astro`, there might be some old links in the `withastro/astro.build` (astro.build site) in one of the blog posts, perhaps. Good hunting! 🙌

**Comment by Susmita-Dey** [comment]
@Yan-Thomas I just checked and there's nothing like that

**Comment by Yan-Thomas** [comment]
> @Yan-Thomas I just checked and there's nothing like that

Right, I think we might have updated all the references then! Thanks for the help and willingness 🙌
