### ISSUE TITLE
adding a new flag --mode for dev and pro 

### ISSUE THREAD

**Issue by wulinsheng123** [withastro/docs#3024]
https://github.com/withastro/astro/pull/6735
this is related to this PR.
I developed a new flag --mode  for dev and pro

**Comment by Yan-Thomas** [comment]
Thanks @wulinsheng123, we'd need to have this documented on our CLI reference page, each command has a "Flags" heading where you can add these commands. For example https://docs.astro.build/en/reference/cli-reference/#astro-dev (you can click the "Edit this page" button to see the file in GitHub and quickly iterate over it). 

Let me know if there's any way we can help you!

**Comment by sarah11918** [comment]
I'm going to close this issue for now, since the original Astro PR is on hold. All this issue does is remind us that we will need some documentation, and I have blocked the other PR anyway to not be released without documentation. So, I don't think we need this issue here right now!
