### ISSUE TITLE
Remark recipes

### ISSUE THREAD

**Issue by louiss0** [withastro/docs#3037]
I'm asking for a remark recipe for Astro. I know the blog template exists but it does not use lots of remark plugins at all. 
It would be nice to get a recipe that has the most used remark plugins. One could be for writers another could be for software engineers.  
I hope this is not too much. To help here is the website for each of the plugins [Plugin Site](https://github.com/remarkjs/remark/blob/main/doc/plugins.md)

**Comment by delucis** [comment]
Hi @louiss0! We do have fairly detailed docs on remark (and rehype) plugins here: https://docs.astro.build/en/guides/markdown-content/#markdown-plugins

Does that cover the kinds of things you were thinking of?

**Comment by louiss0** [comment]
> Hi @louiss0! We do have fairly detailed docs on remark (and rehype) plugins here: https://docs.astro.build/en/guides/markdown-content/#markdown-plugins
> 
> Does that cover the kinds of things you were thinking of?

The point of a recipe is to point out a way of doing things not to introduce a concept. That page introduces the concept of remark plugins not how best to use them.

**Comment by delucis** [comment]
Gotcha. Yes, I agree we kind of mix these things in the Markdown page at the moment. In fact, it sounds like this is what we’re planning in this issue here I just noticed! https://github.com/withastro/docs/issues/2864

**Comment by louiss0** [comment]
> Gotcha. Yes, I agree we kind of mix these things in the Markdown page at the moment. In fact, it sounds like this is what we’re planning in this issue here I just noticed! #2864

Can you please do some research on the most common ones. I just want good starters.

**Comment by sarah11918** [comment]
Hi @louiss0 - We have a discussion here for requests for particular recipes. You are welcome to add to the discussion here:  https://github.com/withastro/docs/discussions/2894

I'm closing this Issue since discussion about future recipes is happening over in Discussions!
