### ISSUE TITLE
No mention to not install Astro globally 

### ISSUE THREAD

**Issue by Princesseuh** [withastro/docs#3045]
Installing Astro globally is not recommended or supported, and often leads to weird issues that can be hard to debug. 

I think it would be judicious to add a section somewhere perhaps in the installation or getting started area to avoid this situation. 

Oftentimes, people install Astro globally by accident because they see a command being "astro dev" instead of "npm run dev", run that, see an error and Google tell them to install the package globally

**Comment by delucis** [comment]
Interesting. There’s no way for a package to detect whether it’s a local or global install right?
