### ISSUE TITLE
No `define:vars` warning exists in styling guide

### ISSUE THREAD

**Issue by TheOtterlord** [withastro/docs#3047]
The define:vars warning only exists in the reference documentation. Is it worth adding something (even if it's smaller) to the styling guide?

(Opening an issue to discuss before I PR)

<details><summary>Preview</summary><br/>
<img src="https://user-images.githubusercontent.com/64310361/231991261-2455bca0-fc0d-485d-8485-e98f7e7b1e08.png" alt="caution note about define:vars"/>
<details>

**Comment by ElianCodes** [comment]
+1 on adding it to the style guide!

**Comment by Yan-Thomas** [comment]
> The define:vars warning only exists in the reference documentation. Is it worth adding something (even if it's smaller) to the styling guide?

Interesting, I'm not sure to be honest! On the Styling page, we link to this heading with the warning, and I generally don't like to repeat warnings like this, let's see what the rest of the team thinks! Thanks for pointing this out 🙌

**Comment by sarah11918** [comment]
I agree with Yan here. On the styling page, it's really only meant to surface that the pattern exists. I think especially with how short that existing section is, and the link to learn more about it, it makes it obvious that "there's more to know that's not on this page."

We have had discussions about whether that entire template directives page belongs in reference, and is the best way to have all that information stored there away from where people are actually learning about it, but I don't think adding to the styling page addresses that problem. If the info is in the wrong place, then it needs to be moved, not duplicated. 

So, I'm closing this one for now!
