### ISSUE TITLE
Explain how environment variables work in SSR apps

### ISSUE THREAD

**Issue by matthewp** [withastro/docs#3049]
This is how environment variables are resolved in import.meta.env. Given a variable FOO what happens during the build is:

1. If `FOO` exists in the environment `import.meta.env.FOO` is replaced with `process.env.FOO`.
    - All of the adapters replace this code with the native environment calls (for ex. `Deno.env.get('FOO')`
2. If `FOO` does not exist in the environment `import.meta.env.FOO` is replaced statically. If it is in a `.env` file for example, that will be used as the static value.
    - If `FOO` is not in the environment and not in a `.env` file then it essentially will always be undefined at runtime.

**Comment by Susmita-Dey** [comment]
So, basically we have to iport and then use native adapters. Am I right?

**Comment by delucis** [comment]
@sasoria is going to take a look and see if we can come up with a nice way to explain this!
