### ISSUE TITLE
misspelling issues in zh-cn doc

### ISSUE THREAD

**Issue by hanxiao790** [withastro/docs#3061]
[https://docs.astro.build/zh-cn/core-concepts/astro-components/#%E7%BB%84%E4%BB%B6%E5%8F%82%E6%95%B0](url)

In this paragraph:
> Astro 组件可以定义和接受参数。 然后，这些参数可用于组件模板以呈现 HTML。 可以在 frontmatter scsipt 中的 Astro.props 中使用。

`frontmatter scsipt` should be `frontmatter script`

**Comment by Yan-Thomas** [comment]
Thanks for pointing this out @hanxiao790, would you like to make a PR making this change? It's a way for us to acknowledge your contribution since GitHub will pick up your profile picture and add it to our Getting Started page's Face PIle. 🙌 

If not, let me know and I'll work on it!

**Comment by hanxiao790** [comment]
@Yan-Thomas Thanks! This is just a minor spelling error, you fix it is OK.
