### ISSUE TITLE
Astro Middleware documentation

### ISSUE THREAD

**Issue by ematipico** [withastro/docs#3069]
The platform team is about the add a new feature in `astro`. The feature is called "Astro middleware".

Few useful links:
- [RFC Stage 2](https://github.com/withastro/roadmap/issues/531), here's a [relevant commen](https://github.com/withastro/roadmap/issues/531#issuecomment-1508933254)t from @matthewp that highlights possible use cases;
- [RFC Stage 3](https://github.com/withastro/roadmap/blob/rfc/stage-3-middleware/proposals/0032-middleware-api.md)
- Relevant [PR](https://github.com/withastro/astro/pull/6721), the description of the PR has instructions of how to install the preview release;

A middleware unlocks two major things:
- do various operations based on the `Request` and `Response`, and also **modify** the `Response` before being rendered; a user can also return **a new** `Response`;
- store contextual information inside a new global called `Astro.locals`/`context.locals` (they're the same object), and then render something based on this `Astro.locals`;

**Comment by ematipico** [comment]
cc @withastro/maintainers-docs

**Comment by sarah11918** [comment]
Closing as initial documentation has been released!  :partying_face: 

Now, updates can be done by referencing the existing docs page!
