### ISSUE TITLE
💡 Idea - show how to detect locale and redirect on the client in i18n recipe

### ISSUE THREAD

**Issue by patmuk** [withastro/docs#3073]
In the second step of "Set up pages for each language" -> "2. Set up src/pages/index.astro to redirect to your default language."

instead of the proposed meta tag, you can use the following client site script: 

---
---

<astro>
  <script>
    import { languages, defaultLang } from '~/utils/i18n/translations';

    const supportedLanguages = Object.keys(languages);
    console.log(`supported languages: ${supportedLanguages}`);

    function getPreferredLanguage() {
      const languageCodes = navigator.languages || [navigator.language];

      for (const code of languageCodes) {
        const language = code.toLowerCase().split(/[_-]+/)[0];
        if (supportedLanguages.includes(language)) {
          console.log(`user prefered language is: ${language}`);
          return language;
        }
      }
      console.log(`none of the user's languages are supported, defaulting to: ${defaultLang}`);
      return defaultLang;
    }

    const preferredLanguage = getPreferredLanguage();

    const url = `/${preferredLanguage}`;
    console.log(`redirecting to ${url}`);
    window.location.replace(url);

  </script>
</astro>

**Comment by patmuk** [comment]
I refactored and debugged the proposed code. The following is a more generic utility function, which can be called from any other page:


`
function getPreferredLanguage() {
    const supportedLanguages = Object.keys(languages);
    console.log(`supported languages: ${supportedLanguages}`);
    const languageCodes = navigator.languages || [navigator.language];

    for (const code of languageCodes) {
        const language = code.toLowerCase().split(/[_-]+/)[0];
        if (supportedLanguages.includes(language)) {
            console.log(`user prefered supported language is: ${language}`);
            return language;
        }
    }
    console.log(`none of the user's languages are supported, defaulting to: ${defaultLang}`);
    return defaultLang;
}

// redirects to the language identifyer URL, e.g. http://www.mypa.ge/page.html -> http://www.mypa.ge/en/page.html
// to be used in the <script> tag for client site execution, e.g.
// pages/404.astro:
// ---
//
// ---
// <astro>
//   <script>
//     import { redirect_to_i18n } from '~/utils/i18n/i18n_utils';
//     redirect_to_i18n();
//   </script>
// < /astro>
//
export function redirect_to_i18n() {
    const url = window.location;

    console.log(`in ${url}`)

    const supportedLanguages = Object.keys(languages);
    for (const languageCode of supportedLanguages) {
        if (url.pathname.includes(languageCode)) {
            console.log(`not redirecting, already i18n page`);
            return url;
        }
    }
    let redirect_url;
    // remove trailing '/'
    if (url.pathname == "/") {
        redirect_url = `${url.origin}/${getPreferredLanguage()}`
    }
    else {
        redirect_url = `${url.origin}/${getPreferredLanguage()}${url.pathname}`;
    }
    console.log(`redirecting to ${redirect_url}`);
    window.location.replace(redirect_url);
}`

**Comment by sarah11918** [comment]
Thanks for this idea! This looks like something that would make a great blog post, and if you'd like to publish your own recipe on your site, we can add a link to it as a related "community recipe."

There are lots of features that can be incorporated with i18n, and our existing recipe was designed to show a simple use case of defaulting to the language of your choice. (As we do in docs, where English is the canonical language of our site and the one that is guaranteed to be up to date.) There may be reasons why you want to choose the default language (as in our case, where English is the full version of the site) and also reasons why you may not wish to automatically redirect someone based on locale (for example, they are located in a particular country but want to view the site in another.)  

So for our recipe, we have chosen what we want to demonstrate. But there are obviously many more things one could do, and we are happy to link to examples of more specialized cases. If you do write something, then please make a PR to the recipes page and we can take a look at it!
