### ISSUE TITLE
⚠️ Issue

### ISSUE THREAD

**Issue by brnkgabriel** [withastro/docs#3080]
It appears that the answer to question #1 on this page is A based on the question and code sample. If the stated answer is actually B, then the question may not be clear enough. Nevertheless, from the information provided, the answer seems to be A

**Comment by brnkgabriel** [comment]
I understand now that question #1 is actually correct. However, having the code above the question caused confusion for me. Can you please merge the code and the question number together to create a more cohesive whole?

**Comment by sarah11918** [comment]
Hi! The code sample for the exercise and the question are contained in a box with a shaded background. They are grouped together.
