### ISSUE TITLE
Installing css-preprocessors as Dev dependency instead of project dependency

### ISSUE THREAD

**Issue by AadityaJain-Dev** [withastro/docs#3085]
Currently in our docs we are suggesting user to install CSS pre-processors as project dependency, shouldn't it be a dev dependency?

I might be wrong since I don't have much experience with these stuff, but please let me know if I am correct, would love to create a PR & contribute :)

![Capture](https://user-images.githubusercontent.com/61523512/233588608-b9a1196e-8e92-437b-a3d5-4c8743bd39ec.PNG)

**Comment by sarah11918** [comment]
Hi @AadityaJain-Dev ! We actually have a line of guidance about dependencies here: https://docs.astro.build/en/core-concepts/project-structure/#packagejson

> There are [two kinds of dependencies](https://docs.npmjs.com/specifying-dependencies-and-devdependencies-in-a-package-json-file) you can specify in a package.json: dependencies and devDependencies. In most cases, these work the same: Astro needs all dependencies at build time, and your package manager will install both. We recommend putting all of your dependencies in dependencies to start, and only use devDependencies if you find a specific need to do so.

For the majority of dependencies in Astro, it doesn't matter whether you install as a project or dev dependency. So, for the sake of simplicity, many of our examples show installing as project dependencies. In other non-Astro projects, the difference often matters more and you do get some benefit from installing some dependencies as dev. But, you can absolutely install many of them as either and keen observation on your part that you might be used to doing that from other projects!

We have had internal discussions about whether it's worth specifying different types of dependencies, but this is our current guidance. So, I'll close this issue as it doesn't require a PR with our current guidance. But I'm ready for the next thing you find to fix, and I'm sure you'll find another contribution to make!  :raised_hands:
