### ISSUE TITLE
Missing results for query "<CTA />"

### ISSUE THREAD

**Issue by grq79** [withastro/docs#3107]
I would like to know how to either comment out the references to newsletter section where it seems to be passed through `<CTA />`, or simply remove the string in all files that serve it up without creating an error.

I've tried commenting them out like this `<!-- <CTA /> -->`

```
---
import type { IFrontmatter } from 'astro-boilerplate-components';

import { CTA } from '@/partials/CTA';
import { Hero } from '@/partials/Hero';
import { ProjectList } from '@/partials/ProjectList';
import { RecentPosts } from '@/partials/RecentPosts';
import Base from '@/templates/Base.astro';
import { AppConfig } from '@/utils/AppConfig';
import { sortByDate } from '@/utils/Posts';

const allPosts = await Astro.glob<IFrontmatter>('./posts/*.md');
const sortedPosts = sortByDate(allPosts);
const lastThreePosts = sortedPosts.slice(0, 3);

const { title } = AppConfig;
const { description } = AppConfig;
---

<Base head={{ title, description }}>
  <Hero />
  <ProjectList />
  <RecentPosts postList={lastThreePosts} />
 <!-- <CTA /> -->
</Base>

```
But I still see it in the footers off all files where I can find the import statement.

**Comment by delucis** [comment]
Hi @grq79! This is the repository for the Astro documentation website but it looks like your question is about a specific Astro library or template maybe? I'd suggest asking the template creator this question, maybe at https://github.com/ixartz/astro-boilerplate-components ?
