### ISSUE TITLE
Why are the CSS files placed in the public directory instead of the styles directory as mentioned in the Project Structure page?

### ISSUE THREAD

**Issue by MrHBS** [withastro/docs#3122]
The Project Structure page describes a directory called styles where you place your CSS files. However I have noticed in this repo the CSS files are placed in the public directory instead. Is there a reason for this?

**Comment by delucis** [comment]
Files in `public/` are not processed by Astro so when setting up this repo, someone decided that our CSS should be shipped as written and is included manually with `<link>` tags. Adding CSS files in `src/` is instead some by adding a JavaScript style `import` in an Astro components.

In general I'd recommend the latter approach unless you need extremely specific control of CSS output. In fact, I am currently working on rebuilding the design for the docs and the new version won't use `public/` for styles.

Hope that answers your question!
