### ISSUE TITLE
⚠️ Typo in Markdown plugins sample code

### ISSUE THREAD

**Issue by thdoan** [withastro/docs#3128]
There's a typo on https://docs.astro.build/en/guides/markdown-content/#markdown-plugins that would result in broken emojis.

Incorrect:
```
export default defineConfig({
  markdown: {
    // Applied to .md and .mdx files
    remarkPlugins: [remarkToc, rehypeAccessibleEmojis],
  },
});
```

Correct:
```
export default defineConfig({
  markdown: {
    // Applied to .md and .mdx files
    rehypePlugins: [rehypeAccessibleEmojis],
    remarkPlugins: [remarkToc],
  },
});
```

**Comment by Yan-Thomas** [comment]
You're right @thdoan! Would you like to open a PR applying this change? You can click "Edit this page" in the docs to make a PR fast, let me know if not, I'd be happy to do it for you.
