### ISSUE TITLE
Astro documentation `partytown.mdx`

### ISSUE THREAD

**Issue by Waxer59** [withastro/docs#3161]
In the partytown integration guide there is an example of code that is not well closed, I don't know if it is a mistake or if you want it to be like that.

Currently this is the code example: 
```js
export default defineConfig({
  integrations: [partytown({
    // Example: Disable debug mode.
    config: { debug: false },
  
})
```
[This is the link to the file](https://github.com/withastro/docs/blob/main/src/content/docs/en/guides/integrations-guide/partytown.mdx), is in line 111

**Comment by delucis** [comment]
I think we should fix it. That’s an integration README, so it actually lives in the `astro` repo here: https://github.com/withastro/astro/tree/main/packages/integrations/partytown#configdebug

Happy for a PR fixing that if you’d like to make one — looks like it would be your first `astro` repo PR! https://astro.badg.es/v1/contributor/Waxer59/

**Comment by Waxer59** [comment]
Ok, when I can I send the PR

**Comment by Waxer59** [comment]
I have already sent the [PR](https://github.com/withastro/astro/pull/7001)

**Comment by delucis** [comment]
Thanks again! Just merged so I'll close this issue. The fix will be pulled into docs in a few hours when the CI runs.
