### ISSUE TITLE
Code swap💡 Idea!

### ISSUE THREAD

**Issue by rachelnabors** [withastro/docs#3177]
What about adding CodeHike to these pages to swap out the lines of code instead of the +/- lines? see step 2-3 here :https://codehike.org/demo/scrollycoding

Happy to submit a PR if you're up for it!

**Comment by sarah11918** [comment]
Thanks for this, @rachelnabors ! We've been watching CodeHike lately, but our Astro maintainer who has done most of the work on our own code snippet formatting has been working on a separate package [Expressive Code](https://github.com/expressive-code/expressive-code/tree/main) that we have been waiting for release (just released this week!) to incorporate into our docs first, before considering additions like this.

We are currently in the process of updating our docs site with this package, and then we'll be ready to look at other additions, too! So all this is to say that we are currently in the middle of updating our code snippets and need to get that all in place before we look at this!

**Comment by delucis** [comment]
Thanks for the idea! We recently migrated to use the new [Expressive Code](https://github.com/expressive-code/expressive-code) package for our code snippets and are planning to use that and some cool future features it will bring around code annotation.

We are hoping to unblock CodeHike usage with Astro and MDX soon though so sharing that link here for anyone who finds this issue: https://github.com/withastro/roadmap/discussions/465
