### ISSUE TITLE
Entity code copied from tutorial snippets instead of `<` HTML symbol

### ISSUE THREAD

**Issue by marcinukleja** [withastro/docs#3186]
In the first few units of tutorial, if you try to copy the snippet, it pastes to VS Code with entity code for `<` symbols.

Here is example site: [https://docs.astro.build/en/tutorial/1-setup/3/](https://docs.astro.build/en/tutorial/1-setup/3/)

Copied and pasted code looks like this:
```
---
---

&#x3C;html lang="en">
  &#x3C;head>
    &#x3C;meta charset="utf-8" />
    &#x3C;link rel="icon" type ="image/svg+xml" href="/favicon.ico" />
    &#x3C;meta name="viewport" content="width=device-width" />
    &#x3C;meta name="generator" content = {Astro.generator} >
    &#x3C;title>Astro&#x3C;/title>
  &#x3C;/head>
  &#x3C;body>
    &#x3C;h1>Astro&#x3C;/h1>
  &#x3C;/body>
&#x3C;/html>
```

**Comment by sarah11918** [comment]
Thanks for letting us know! We very recently added this copy code button to our code samples, and it looks like you've found a case where it's not working properly!

**Comment by marcinukleja** [comment]
After selecting part of the code, the result is the same. However, in unit 2 and 3 I haven't experienced such behavior – even using this _copy code_ button.

**Comment by marcinukleja** [comment]
I've just found a new unexpected case: https://docs.astro.build/en/tutorial/3-components/2/

**Comment by marcinukleja** [comment]
OK, I finished tutorial, and I couldn't reproduce unexpected behavior using copy command (not a button). It seems that problem is only with this new copy button, and looks like the _only_ problematic character is `<`.

Tutorial was great, btw! :)

**Comment by sarah11918** [comment]
Thanks for leaving such detailed feedback! Yeah, I'm thinking it's probably the new button.  :sweat_smile: We'll get on that.

Glad you liked the tutorial!  :raised_hands:
