### ISSUE TITLE
Environment variables

### ISSUE THREAD

**Issue by dreyfus92** [withastro/docs#3191]
In the docs is mentioned that you can load environment variables with a helper function from vite package. This is the [link](https://docs.astro.build/en/guides/configuring-astro/#environment-variables) to the part where the docs explain how Astro evaluates config files.

This should be placed in the `astro.config.mjs`

```js 
import { loadEnv } from "vite";
const { SECRET_PASSWORD } = loadEnv(import.meta.env.MODE, process.cwd(), "");
```

But for some reason, when you import the helper funcion you get an error that can't find the `vite` package.

What I was trying to accomplish was to load env vars directly in the `astro.config.mjs` file but apparently it won't work.

**Comment by delucis** [comment]
Thanks for the issue — and for your patience waiting for a reply @dreyfus92 😄 

Do you remember if you were using `pnpm` for this project? PNPM usually requires anything you import to be a direct project dependency, so I wonder if that was the issue here.

**Comment by TheOtterlord** [comment]
I can confirm `pnpm` is the issue here. Assigning this to myself to keep track, but I should have a PR today.

**Comment by dreyfus92** [comment]
Sorry for the delay, indeed I was using `pnpm`
