### ISSUE TITLE
Some code highlighting ranges are incorrect

### ISSUE THREAD

**Issue by morinokami** [withastro/docs#3215]
I found that some code highlighting ranges are incorrect, for example:

* https://docs.astro.build/en/guides/aliases/
  ![image](https://user-images.githubusercontent.com/7889778/237022457-11462fe1-57f2-490a-8ad7-7b4e944cf454.png)
  ![image](https://user-images.githubusercontent.com/7889778/237022571-a6fe101e-686d-420c-abfb-7bc879c3e3cc.png)
* https://docs.astro.build/en/guides/styling/#frameworks-and-libraries
  ![image](https://user-images.githubusercontent.com/7889778/237022823-34228e20-8019-44a1-834f-631368156597.png)
* https://docs.astro.build/en/guides/testing/#create-your-first-playwright-test
  ![image](https://user-images.githubusercontent.com/7889778/237023010-1b5d768b-5509-479d-9b86-238c6bef3027.png)
* https://docs.astro.build/en/guides/typescript/#import-aliases
  ![image](https://user-images.githubusercontent.com/7889778/237023135-082040ca-ffe4-45ac-9afc-8baedfb3c4a1.png)
* https://docs.astro.build/en/guides/typescript/#type-checking
  ![image](https://user-images.githubusercontent.com/7889778/237023275-814c1cfa-6740-4def-8fa8-c517f70f3ad5.png)

To find the cause I checked the source code like

https://github.com/withastro/docs/blob/496517384b52ed6265ed319e641d26034ee2cfbb/src/content/docs/en/guides/aliases.mdx?plain=1#L11
https://github.com/withastro/docs/blob/496517384b52ed6265ed319e641d26034ee2cfbb/src/content/docs/en/guides/typescript.mdx?plain=1#L274

but the code itself that specifies the highlighting target seems to be correct 🤔

After that, since I could confirm that the same code working fine in a slightly earlier version, I searched for the commit where the problem occurred by bisection search and found that the code highlighting was shifted after the merge of the following PR:

https://github.com/withastro/docs/pull/3184 (b4532a9b)

Unfortunately, it was not clear to me why the PR above caused the problem, but I hope this information will help to resolve the issue.

**Comment by delucis** [comment]
Thanks for the report @morinokami — I also tried reverting #3184 locally and can confirm it fixes this. We’ll need to figure out why, but it may make sense to revert that PR for now as it was only a build speed optimization and it’s probably more important to keep the highlighting correct.

cc @bluwy in case he has any ideas.
