### ISSUE TITLE
Check for Firebase Hosting updates needed after Google I/O

### ISSUE THREAD

**Issue by sarah11918** [withastro/docs#3236]
Firebase Hosting shipped new experimental support for deploying with Astro and announced it at Google I/O!  :rocket:

Now, we need to figure out whether [our own Firebase Hosting deploy docs](https://docs.astro.build/en/guides/deploy/google-firebase/ ) need to change at all. (ACK: the link to Firebase Hosting from our page has changed since that page was made! At the very least, the link needs to update to `https://firebase.google.com/`)

Please read the ["What's New" announcement from Google](https://firebase.blog/posts/2023/05/whats-new-at-google-io/#deploy-astro-nuxt-sveltekit-with-firebase-hosting) and check for anything releated in the [Firebase Hosting Docs](https://firebase.google.com/docs) that differs from our own docs.

If necessary, please open a PR so that our docs are (still) correct!

**Comment by saurabhp75** [comment]
Can I take this issue?

**Comment by sarah11918** [comment]
Sure thing! Just please be sure to come back and comment if you are no longer working on it, so that others can pick it up!

**Comment by Susmita-Dey** [comment]
Hey @sarah11918 Is the issue resolved?

I see a PR linked to this issue which has been merged already.

**Comment by sarah11918** [comment]
Hi @Susmita-Dey !  No this issue is not resolved. The issue you see linked was someone translating the existing page. But, we have not yet had someone tackle this issue as described here.

**Comment by saurabhp75** [comment]
> Sure thing! Just please be sure to come back and comment if you are no longer working on it, so that others can pick it up!

Something urgent came up, I am no longer working on this issue. @Sushmita, you can take this up.

**Comment by Susmita-Dey** [comment]
![image](https://github.com/withastro/docs/assets/79099734/6f7dd7b6-e357-4d43-9e4d-6b551fda82c5)
The link here needs to be updated ig as it's redirecting to the same page where it exists.

**Comment by Susmita-Dey** [comment]
@sarah11918 I wanna take it up. Guide me what to be done.

**Comment by sarah11918** [comment]
Hi @Susmita-Dey ! Great, good catch! You can start by updating that broken link. Please make a PR so that the link actually points to the Firebase page in the Recipes section for backend services.

**Comment by Susmita-Dey** [comment]
> Hi @Susmita-Dey ! Great, good catch! You can start by updating that broken link. Please make a PR so that the link actually points to the Firebase page in the Recipes section for backend services.

Okay, will shoot a PR tomorrow morning!

**Comment by delucis** [comment]
Looks like these links are working now, so we can close this!
