### ISSUE TITLE
Add Typing Information for Dynamically Created HTML Tags

### ISSUE THREAD

**Issue by Jothsa** [withastro/docs#3256]
When creating a dynamic element, I received a typescript error when trying to add an id attribute. Thanks to the Discord support, I was able to fix it by casting the dynamic tag as an HTMLTag. I think this should be mentioned in the docs somewhere. I would be happy to make a PR, but I am not sure where the new content should be placed. I think that it should be in a new section on the Typescript page right after the Built-in HTML Attributes section and there should be a tip on the Astro Syntax page in the Dynamic Tags section linking to the new section of the Typescript page. I'll try to work on a PR later if that sounds good unless someone more knowledgeable than me about Typescript wants to do it/beef up my PR.

```astro
---
import type { HTMLTag } from 'astro/types';

interface Props {
  headingLevel: 1 | 2 | 3 | 4 | 5 | 6;
}

const { headingLevel = 2 } = Astro.props;
const HeadingTag = `h${headingLevel}` as HTMLTag;
---

<HeadingTag id={`panel${i + 1}-heading`} class="panel-heading">
```

**Comment by delucis** [comment]
Closing as we have those docs Erika mentioned that sound like they should do the trick.
