### ISSUE TITLE
astro:build:done hook missing parameter

### ISSUE THREAD

**Issue by ZebraFlesh** [withastro/docs#3257]
The docs for the `astro:build:done` hook do not describe the `pages` parameter: https://docs.astro.build/en/reference/integrations-reference/#astrobuilddone This seems to be the only place to access a list of built pages (where values for static route params have been realized into values), so it seems important.

**Comment by TheOtterlord** [comment]
Aha, I had noticed this recently but completely forgot about it. I'll check whether the reference is generated from anywhere specific then look at fixing it and checking it's all up to date
