### ISSUE TITLE
Potential update to rendering multiple elements 

### ISSUE THREAD

**Issue by ohansemmanuel** [withastro/docs#3269]
## what? 
> ... you should wrap these elements inside a fragment as you would in JavaScript or JSX.

![CleanShot 2023-05-17 at 16 29 40](https://github.com/withastro/docs/assets/10930234/ec8328b2-1bd4-4759-9df2-71de4d319457)

## why? 
It's worth asking, why's this important? 

For example, not doing this in JSX throws an error. However, it works just fine in the latest versions of Astro. 

See https://stackblitz.com/edit/github-o8fjnb?file=src/pages/index.astro 

If we're telling people they **should** do this, it's worth mentioning "why" as this seems to work just fine i.e., without error as in the JSX comparison. 

[See docs.](https://docs.astro.build/en/core-concepts/astro-syntax/#fragments--multiple-elements)

**Comment by sarah11918** [comment]
Hi @ohansemmanuel - I can tell you that when these docs were written, wrapping the elements was required. It would not work otherwise.

I'm checking in with the dev team to see whether something has changed and we can update this advice!  :raised_hands:

**Comment by dreyfus92** [comment]
@sarah11918 I just verified that there's no need to have a fragment to perform this action. I can handle the update if you want me to.

**Comment by ohansemmanuel** [comment]
Thanks @sarah11918
