### ISSUE TITLE
Suggestion: github issues template form

### ISSUE THREAD

**Issue by Waxer59** [withastro/docs#3277]
I suggest adding the issue templates to make the issues more uniform and clearer using [github issues template form](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms), I could work on them if you agree with me.

**Comment by sarah11918** [comment]
I can't find a good label for this one :sweat_smile:  but @Waxer59 let's start the discussion here! 

Propose in this issue what you're thinking of and others are welcome to add to the discussion here!

**Comment by Waxer59** [comment]
What I propose would be to add something similar to what we have in the Starlight project when opening an issue, make use of the issue forms of GitHub, to classify them better and that the user knows what to contribute to receive

**Comment by delucis** [comment]
Nice idea @Waxer59! Can also help guide people away from using docs issues as a place for support questions.

One of the nice things you get with this set-up is also _extra_ stuff on the new issue screen — https://github.com/withastro/starlight/issues/new/choose — for example in the Starlight repo:

<img width="818" alt="screenshot of the new issue page showing options to get support and report security issues separately from creating a new issue" src="https://github.com/withastro/docs/assets/357379/5d2f496b-966d-470c-a965-9e2f6c1d72e3">

One thing we should double check is if we would need to change how our “Give us feedback” component works on the docs site: currently if you choose “Create GitHub Issue” there, it takes the text in the text field and automatically prefills the new issue with it using a query parameter, e.g. `https://github.com/withastro/docs/issues/new?title=Example+Issue&body=Example+body`. (A quick test replacing `docs` with `starlight` in that URL suggests that that lets you bypass the template entirely!)

**Comment by Waxer59** [comment]
But the behavior of the github issue form could be replicated in the component

**Comment by Waxer59** [comment]
What do you mean by bypassing the issue form? for example if I make a url that is `https://github.com/withastro/starlight/issues/new?title=Example+Issue&body=Example+body` instead of creating an issue with these parameters it redirects me to the page where it asks me to create an issue with the forms.

**Comment by delucis** [comment]
Ohhh, interesting! When I follow that link I get a standard new issue form:

<img width="888" alt="Screenshot of the standard GitHub new issue form" src="https://github.com/withastro/docs/assets/357379/9ae95103-7997-4652-850e-ab3c4dab57d8">

I guess that’s something they only allow for admins on the repo. Thank you for double checking!

It looks like we can still prefill data like you suggest though. This URL uses the template, and sets some of the fields: https://github.com/withastro/starlight/issues/new?template=---01-bug-report.yml&title=Example+Issue&bug-description=Example+body&starlight-version=9.9.9&astro-version=9.9.9&package-manager=Santa+Claus

So yup, we can pre-fill some stuff. We’d still need to figure out what questions to ask — I don’t think we want so much diagnostic information though. Someone could create a docs issue about some content and then browser version etc. is not relevant. Would you like to suggest some things that you think would be important to ask? We can also use a template that is just a title and body but lets us show people more context while they create the issue.

**Comment by ElianCodes** [comment]
I'm totally for this! I actually thought we already integrated this a while ago 🤔

**Comment by sarah11918** [comment]
Agreed! I think one for site bugs, one for content, and one "other" is def better than what we had before!

Since you've covered the other ones, for content here are some thoughts:

- Content subject area/topic
- Docs page affected (or suggested, for new content)
- If proposing new content: a general description or bullet points of what should be added
- If reporting incorrect content or code samples, a reproduction in StackBlitz showing it doesn't work/what does work 
- Reminder: If reporting a minor correction (e.g. typo), feel free to submit a PR directly!

**Comment by Waxer59** [comment]
I consider that the following fields would be suitable for the "content" form. Subsequently, the aforementioned forms for "support" and "chat" could be added, which should function similarly to the Starlight project, in order to prevent people from using the issues in this repository as support. Once added, it will be necessary to modify the "Give us feedback" component.

**Comment by sarah11918** [comment]
(The closest label I had was "site improvement"  :smile: )

**Comment by Waxer59** [comment]
I have sent a PR adding these changes https://github.com/withastro/docs/pull/3497 , although changes still need to be made in the "Give us feedback" component.

**Comment by CBID2** [comment]
Maybe there can be an issue form for topic requests too @delucis(e.g., a tutorial that Astro users want to see more off)?
