### ISSUE TITLE
Consider updating ResponseInit link

### ISSUE THREAD

**Issue by ohansemmanuel** [withastro/docs#3313]
# What? 

The ResponseInit link in https://docs.astro.build/en/reference/api-reference/#astroresponse is dead. 

![CleanShot 2023-05-22 at 17 33 02@2x](https://github.com/withastro/docs/assets/10930234/ea278948-412f-4c56-b006-7c36a004e5b2)

It points to MDN, but the hash link no longer exists. 

## Potential solution 
We could potentially point to the actual spec https://fetch.spec.whatwg.org/#responseinit

**Comment by ElianCodes** [comment]
Hmm, the link seems to work on my end; navigates to: https://developer.mozilla.org/en-US/docs/Web/API/Response/Response#init

**Comment by ohansemmanuel** [comment]
Hi @sarah11918 @ElianCodes : 

- The link works, but that's not the problem 
- The actual init object, i.e., the hash this link is supposed to redirect to, I suspect, has been removed from MDN (If it once existed) 
- There's no longer an "init" heading on the MDN page
- The link points you to the standard Response constructor (i.e., the main heading)
-  **Important:** Astro.response is **NOT** the same as the Response constructor.  It's specifically the init object of the constructor, i.e., https://fetch.spec.whatwg.org/#responseinit 

I suggest this one may need to be reopened 😅

**Comment by delucis** [comment]
Yup this does look like the page content changed making the link unhelpful. Thanks for pointing it out @ohansemmanuel!

The spec link is not _great_ (not sure everyone would know what `unsigned short` and `ByteString` mean for example 😅). It may be better just to document the interface ourselves. That’s what Deno Deploy do for example: https://deno.com/deploy/docs/runtime-response#responseinit

**Comment by delucis** [comment]
As a reference, here is what the MDN page _used_ to look like: https://web.archive.org/web/20211207020008/https://developer.mozilla.org/en-US/docs/Web/API/Response/Response#init

> `init`
An options object containing any custom settings that you want to apply to the response, or an empty object (which is the default value). The possible options are:
>
> - `status`: The status code for the response, e.g., `200`.
> - `statusText`: The status message associated with the status code, e.g., `OK`.
> - `headers`: Any headers you want to add to your response, contained within a [`Headers`](https://web.archive.org/web/20211207020008mp_/https://developer.mozilla.org/en-US/docs/Web/API/Headers) object or object literal of [`String`](https://web.archive.org/web/20211207020008mp_/https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String) key/value pairs (see [HTTP headers](https://web.archive.org/web/20211207020008mp_/https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers) for a reference).

**Comment by ohansemmanuel** [comment]
For an arguably simple change, this has been open for far too long. I opened https://github.com/withastro/docs/pull/3966 to address the proposed change. Please take a look cc @delucis @sarah11918 

Cheers folks.
