### ISSUE TITLE
Underscore `_` convention for content collections

### ISSUE THREAD

**Issue by bholmesdev** [withastro/docs#3320]
We've received support threads and issues (see https://github.com/withastro/astro/issues/7063) surprised to find that content collection entries with an underscore in the file name are _ignored._ This deserves a dedicated space in our [content collections guide.](https://docs.astro.build/en/guides/content-collections/)

I would consider a new subheading below the ["organizing with subdirectories" section.](https://docs.astro.build/en/guides/content-collections/#organizing-with-subdirectories)

**Comment by sarah11918** [comment]
Thanks, Ben! Yes, right now there's only one place we really mention files starting with an underscore are treated differently, in the context of excluding pages to be built here: https://docs.astro.build/en/core-concepts/routing/#excluding-pages

I'll take a look at this and we'll either add something more extensive to content collections itself, and/or link to the routing page as a reminder that, even if you're NOT using content collections, files will be ignored and won't create pages/routes.
