### ISSUE TITLE
Update streaming docs to reflect Parallelized rendering 

### ISSUE THREAD

**Issue by ohansemmanuel** [withastro/docs#3333]
## What?
With Astro 2.5 [Parallelized rendering](https://astro.build/blog/astro-250/#parallelized-rendering), it's worth adding some more info here: 

![CleanShot 2023-05-25 at 13 21 11@2x](https://github.com/withastro/docs/assets/10930234/085816bd-da03-4ce7-8cc3-1213111e22b0)

![CleanShot 2023-05-25 at 13 21 55@2x](https://github.com/withastro/docs/assets/10930234/63b93d87-13f5-45bf-9885-8c2c6f529c98)

See https://docs.astro.build/en/guides/server-side-rendering/#streaming

## Why? 
Data-loading components higher in the tree (siblings) will no longer block other components also loading data ...

**Comment by sarah11918** [comment]
This sounds like a great update! Happy to have someone run with it!  :raised_hands:
