### ISSUE TITLE
Provide Examples for Interacting with Raw Local Image Files

### ISSUE THREAD

**Issue by joe-bell** [withastro/docs#3339]
Somewhat related to https://github.com/withastro/roadmap/discussions/578

---

I recently [shipped an example for `plaiceholder`](https://github.com/joe-bell/plaiceholder/blob/main/examples/astro/src/pages/color/multiple.astro#L18), but found myself unable to import the _actual_ (buffer) image via `getImage()`.

I tried fetching the file in the [same vein as @vercel/og](https://vercel.com/docs/concepts/functions/edge-functions/og-image-generation/og-image-examples#using-a-local-image) but this resulted in an error that "fetch wasn't implemented yet". 

For now, I've resorted to using `fs`, but the [the documentation currently reads](https://docs.astro.build/en/guides/imports/#node-builtins):

> We encourage Astro users to avoid Node.js builtins (fs, path, etc.) whenever possible. Astro is compatible with multiple runtimes using [adapters](https://docs.astro.build/en/guides/server-side-rendering/#adding-an-adapter). This includes [Deno](https://docs.astro.build/en/guides/integrations-guide/deno/) and [Cloudflare Workers](https://docs.astro.build/en/guides/integrations-guide/cloudflare/) which do not support Node builtin modules such as fs.

Is there a recommended approach for such a strategy, or is this something that would need to be continued as a feature request?

Thank you 🙏

**Comment by delucis** [comment]
Ah, I maybe wrong, but I believe @Princesseuh said it could be possible to return the buffer there potentially. I’d say we hold on documenting just yet until there’s a clear path for what we want to recommend.

Thanks for the issue!

**Comment by Princesseuh** [comment]
At the moment, the best way to achieve this is to use `?raw` imports if you know the filepath, but yes I do think that we could return it from normal imports as well, as there's occasions where you can't use those imports (ex: content collections)

However it's not possible to return a buffer from `getImage`, as the image is ultimately generated separately from the call to it (through a endpoint)

**Comment by delucis** [comment]
Closing this as there’s nothing to document at the moment but hopefully we can add something in the future once assets has this feature. Thanks again for raising this as something that would be nice to have @joe-bell!
