### ISSUE TITLE
Default Behavior of ${import.meta.env.BASE_URL} documentation

### ISSUE THREAD

**Issue by r-southworth** [withastro/docs#3348]
https://docs.astro.build/en/reference/configuration-reference/#base

Example says to use the import statement like this: <img src=`${import.meta.env.BASE_URL}/image.png`>

In most cases this results in a output URL of /base//image.png

Will open a pull request to update the example to <img src=`${import.meta.env.BASE_URL}image.png`> With a note that if you have trailing slash set to 'never' then you need to add the slash yourself.

**Comment by r-southworth** [comment]
#3349

**Comment by sarah11918** [comment]
Thanks for this @r-southworth! This seems like more helpful advice in the docs!  :partying_face:

**Comment by delucis** [comment]
Looks like this was done in https://github.com/withastro/astro/pull/7392

Thanks again @r-southworth!
