### ISSUE TITLE
Provide examples on how to add admonitions & call-outs

### ISSUE THREAD

**Issue by dreyfus92** [withastro/docs#3365]
What do you guys think about adding a recipe on how to properly add admonitions or call-outs?

**Comment by sarah11918** [comment]
Hey @dreyfus92! I'm not sure I'd make this a recipe, and we do now include these and document how to use them in Starlight, where we expect this component to be most useful. For our own docs, it seems more appropriate for people writing our docs themselves.

I think maybe a good strategy is just to point them to Starlight if they want super fancy admonitions, lol ! :sweat_smile:
