### ISSUE TITLE
⚠️ Issue [vercel] after running cmd  "npx astro add vercel"

### ISSUE THREAD

**Issue by antoniods** [withastro/docs#3430]
We get blank blog posts locally and on vercel after running this command.

**Comment by ElianCodes** [comment]
Hey there! This is working for me. Could you provide us with a minimal example, reproduce steps or a repo?

**Comment by delucis** [comment]
The Vercel adapter you're using enables SSR which changes how Astro handles routing.

Looks like the Paper theme you're using doesn't support this. It uses `getStaticPaths()` to generate a list of post pages to generate and match them to the correct content: https://github.com/antoniods/astro/blob/1538913a3ad285eab9808555a2932c6ee5819c78/src/pages/posts/%5Bslug%5D.astro#L14

`getStaticPaths` is not used in SSR so the props on that page are not configured as the template expects.

I'd ask the theme authors what they think about supporting SSR or jump into the Astro Discord at https://astro.build/chat and ask for help converting a static site to SSR in the #support channel.

**Comment by antoniods** [comment]
Thanks a lot,

I'll try to contact them through discord  ...
