### ISSUE TITLE
Can I add a site to the production websites?

### ISSUE THREAD

**Issue by kireerik** [withastro/docs#3455]
- https://docs.astro.build/en/integrations/integrations/#production-sites

> If yes, I will create a pull request.

**Comment by sarah11918** [comment]
Hi @kireerik!  You found one of our "secret" pages!  :smile: 

This page will eventually be removed in favour of showing sites at https://astro.build/showcase where you are welcome to add your site! You can add your site directly at this link: https://astro.build/showcase/submit

So, we are not updating this page at the moment, and it probably won't exist much longer! I'll close this issue, but please do submit your production site to our showcase! We'd love to see it there!

**Comment by kireerik** [comment]
Yes, I find lots of Astro "sectrets". :D
