### ISSUE TITLE
When are ENV variables or secrets shared with the client / how to wrap external API calls so keys are never exposed to client

### ISSUE THREAD

**Issue by braco** [withastro/docs#3464]
Something I'm not clear about is when secrets are exposed to the client.

Let's say we have a SSR or server-based astro instance that might have live React components.

This might include code that fetches from an external API, and the URLs and keys for this API are stored in .env. 

In what cases would astro be surfacing those API keys to the client? There's a lot of magic happening so it's not totally obvious how to keep those API keys secret, or how those API calls should be wrapped so the API key is never exposed to the client.

There's the PUBLIC_ idiom as defined here:
https://docs.astro.build/en/guides/environment-variables/

but I seem to be able to build live React components around any ENV vars. I'm assuming those aren't routed through astro in production.

**Comment by dreyfus92** [comment]
API keys should not be exposed to the client in a client-server architecture, regardless of whether the app is using SSR (Server-Side Rendering) or not. API keys are sensitive information that should be kept private and protected.

**Comment by delucis** [comment]
Thank you for the issue @braco! As stated in the Environment Variables guide:

> Note that while all environment variables are available in server-side code, **only environment variables prefixed with `PUBLIC_` are available in client-side code** for security purposes.

If you are seeing behaviour different from that, that would be a bug, and it would be great if you could open an issue with a reproduction in the main astro repo: https://github.com/withastro/astro
