### ISSUE TITLE
Found a typo in the Maintainer's Contributing Guide

### ISSUE THREAD

**Issue by CBID2** [withastro/docs#3496]
I was inspired by @sarah11918's speech in the current Discord community call, so I revised a typo.

**Comment by ElianCodes** [comment]
If you find a small typo like this, feel free to open a PR without opening an issue first!

Thank you!

**Comment by CBID2** [comment]
> If you find a small typo like this (even though this is not a real typo, but more like an addition), feel free to open a PR without opening an issue first!
> 
> Thank you!

Oh thanks @ElianCodes. I added an issue partly because I wanted to be in the contributor's section and it's an etiquette thing lol 😆
