### ISSUE TITLE
Document how to redirect from middleware

### ISSUE THREAD

**Issue by sasoria** [withastro/docs#3523]
It was not easy to figure out the best way to redirect from middlware. Others have used the `Response.redirect` function which only supports full URLs. 

`context.redirect` is an easier approach since it supports relative paths and its also used in the middleware [example](https://github.com/withastro/astro/blob/main/examples/middleware/src/middleware.ts) found in withastro/astro.

Maybe we could document this, either in plain text or in a code example? Here's how I did it.

```ts
export const onRequest = defineMiddleware(async (context, next) => {
  if(shouldRedirect) {
   return context.redirect(`/relative/path`);
  }

  return next();
});
```

**Comment by sarah11918** [comment]
Thansk for this suggestion @sasoria! I'm going to ask @ematipico to take a look at this to see what he thinks about documenting this, and whether it's intended to be supported, and part of the stable feature set!

**Comment by ematipico** [comment]
Yes, it makes sense. In the documentation of the middleware, we talk about [`context`](https://docs.astro.build/en/guides/middleware/#context), but we fail to address that `context` has the same APIs of the [endpoint context](https://docs.astro.build/en/reference/api-reference/#endpoint-context) + the `locals`.

Maybe we can add a link to that page.

**Comment by sarah11918** [comment]
Looks like you've got yourself a PR to make, if you want it @sasoria!  :partying_face: 

I've added the label "help wanted" here and a PR is welcome!

**Comment by sasoria** [comment]
Awesome, I'll try to get it done tomorrow.
