### ISSUE TITLE
Minor issue in the documentation related to port customization

### ISSUE THREAD

**Issue by kossidts** [withastro/docs#3532]
In the [configuration reference](https://docs.astro.build/en/reference/configuration-reference/#server-options) section, there is an example provided for customizing the port based on the command. However, I believe there's a small error in the code snippet provided.

Currently, the documentation states: 

```
{
  // Example: Use the function syntax to customize based on command
  server: (command) => ({ port: command === 'dev' ? 3000 : 4000 })
}
```

I believe it should be the following, which works for me:

```
{
  // Example: Use the function syntax to customize based on command
  server: ({command}) => ({ port: command === 'dev' ? 3000 : 4000 })
}
```

It' s a small detail, but I believe it's worth addressing to ensure clarity and accuracy in the documentation.

**Comment by Yan-Thomas** [comment]
Thanks @kossidts, I believe you're right. Would you like to make a PR changing this? The Configuration Reference docs are generated from our types page, here's the exact line you need to change:
https://github.com/withastro/astro/blob/main/packages/astro/src/%40types/astro.ts#L846

**Comment by kossidts** [comment]
Thank you for asking @Yan-Thomas. I have addressed the issue and created a PR https://github.com/withastro/astro/pull/7436. However some tests have failed. I have also encounter test failure immediately after forking and cloning the repo locally. 

I would appreciate your guidance on how to proceed to ensure the tests pass successfully. Please let me know if there are any additional steps or adjustments I can make to resolve the test failures and ensure the smooth integration of the fix.

**Comment by sarah11918** [comment]
Yay! This was fixed and merged in the core repo docs, so I'm closing this issue. Thank you, @kossidts! :partying_face:
