### ISSUE TITLE
Document Content component returned by `Astro.glob`

### ISSUE THREAD

**Issue by Princesseuh** [withastro/docs#358]
Currently the only documentation for `Content` we have is [this inside the API reference](https://docs.astro.build/en/reference/api-reference/#markdown-files) which doesn't tell us much unfortunately about how to use the component

This being undocumented is especially annoying for users as it's the only way to properly render Markdown with working components, which was particularly relevant before the Markdown changes (Now it's the only way to render Markdown from Astro.glob :sweat_smile:)

**Comment by sarah11918** [comment]
Closed by PR #405
