### ISSUE TITLE
[CONTENT] - Contentful guide is out of date

### ISSUE THREAD

**Issue by deeprobin** [withastro/docs#3646]
### 📚 Subject area/topic

Contentful

### 📋 Page(s) affected (or suggested, for new content)

https://docs.astro.build/en/guides/cms/contentful/
https://docs.astro.build/de/guides/cms/contentful/

### 📋 General description or bullet points (if proposing new content)

Update Contentful docs to v10. They reworked their types.

See https://github.com/contentful/contentful.js/blob/master/MIGRATION.md#migration-to-contentfuljs-10x
See https://github.com/contentful/contentful.js/blob/master/TYPESCRIPT.md

### 🖥️ Reproduction in StackBlitz (if reporting incorrect content or code samples)

```ts
export interface ContentPage {
    title: string;
    metaTitle: string;
    openGraphTitle: string;
    metaDescription: string;
    openGraphDescription: string;
    openGraphImage: AssetLink;
    content: Document;
}

export const contentfulClient = contentful.createClient({
    space: import.meta.env.CONTENTFUL_SPACE_ID,
    accessToken: import.meta.env.DEV
        ? import.meta.env.CONTENTFUL_PREVIEW_TOKEN
        : import.meta.env.CONTENTFUL_DELIVERY_TOKEN,
    host: import.meta.env.DEV ? "preview.contentful.com" : "cdn.contentful.com",
});
```

```ts
let entries = await contentfulClient.getEntries<ContentPage>({
/*                                              ^^^^^^^^^^^
Type 'ContentPage' does not satisfy the constraint 'EntrySkeletonType'.
  Type 'ContentPage' is missing the following properties from type 'EntrySkeletonType': fields, contentTypeId
*/
    content_type: "contentPage",
});
```

**Comment by delucis** [comment]
Thanks for the issue @deeprobin! Sounds like @TheOtterlord will get to this soon.
