### ISSUE TITLE
💡 Idea: explain is:inline in ThemeToggle

### ISSUE THREAD

**Issue by 6abotage** [withastro/docs#3679]
Add a note that explain why is:inline is used in the script tag in this example
https://docs.astro.build/en/tutorial/6-islands/2/#add-client-side-interactivity

From what I unterstand up until now, there should be no difference in how the code works in production, wheter you use is:inline or not.
If you dismiss the is:inline instruction astro minifies the script and declares it as module. But it is still inlined in every html file in the output, therefore the behaviour doesn't change. 

Generally we wan't the code to block the rendering of the html with the script tag so no flicker occurs when the prefferred theme is not equal the current theme. I get that and that's why we probably got to write the is:inline, or am I wrong with this point?

Greetings
Dino

**Comment by delucis** [comment]
Thank you for the issue @6abotage — I hope you have been enjoying the tutorial!

> Generally we wan't the code to block the rendering of the html with the script tag so no flicker occurs when the preferred theme is not equal the current theme. I get that and that's why we probably got to write the is:inline, or am I wrong with this point?

Yes, that’s correct! We want the script to run early to avoid styles flickering (and bundled modules are liable to run later after the page has been displayed). While for smaller resources, Astro may inline them, this behaviour changes as they get larger, so it’s best to specify `is:inline` for reliable behaviour.

In the context of a tutorial, we want people to focus on building and trying things out, without necessarily worrying about technical details, so this is why we don’t take time here to explain this in depth. However, we do link to the relevant documentation that provides more context at the bottom of this page, so hopefully that is enough for people who do want to explore and learn more.
