### ISSUE TITLE
Can't modify Markdown frontmatter from remark plugin

### ISSUE THREAD

**Issue by rgov** [withastro/docs#3737]
### What version of `astro` are you using?

2.8.3

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

nom

### What operating system are you using?

macOS Ventura

### What browser are you using?

Safari

### Describe the Bug

The example given for [modifying Markdown frontmatter programmatically](https://docs.astro.build/en/guides/markdown-content/#modifying-frontmatter-programmatically) doesn't seem to work.

Following exactly that example, I can see (with `console.log()`) that my plugin is being called. But in one of my `.astro` files I inspect the `data` objects for each post, and the inserted field is not present.

(Question: Is there any difference between the `markdown` and `mdx` sections of the config file? The documentation seems ambivalent about which to use. I've tried both.)

### What's the expected result?

The example should add the `customProperty` to the front matter.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-klm8sa?file=example-remark-plugin.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Transferring to docs since it seems like this was mostly a misunderstanding of the docs regarding when remark plugins affect the frontmatter

**Comment by delucis** [comment]
Thanks for transferring @Princesseuh.

The [guidance in the Markdown guide](https://docs.astro.build/en/guides/markdown-content/#modifying-frontmatter-programmatically) works well when NOT using content collections, but we should add a link to the [content collections version](https://docs.astro.build/en/guides/content-collections/#modifying-frontmatter-with-remark) to make the difference clearer.

**Comment by TheOtterlord** [comment]
Fixed in https://github.com/withastro/docs/pull/3988
