### ISSUE TITLE
Typo: "directly" to "directory"

### ISSUE THREAD

**Issue by a-trost** [withastro/docs#374]
One line in the [Static Assets page](https://docs.astro.build/en/guides/imports/#supported-file-types) says

> Remember that you can also place any static asset in the [`public/` directory](/en/core-concepts/project-structure/#public) of your project, and Astro will copy the _directly_ into your final build.
(emphasis mine)

I assume this is supposed to say "copy the _directory_ into your final build."

Opening a pull request with this change.

**Comment by sarah11918** [comment]
Thanks for this! I'm closing the issue because I'm handling the pr now.  :)

**Comment by sarah11918** [comment]
Thanks for this! It has been fixed by another pr so I'm closing this one. (The intended original wording was "copy them directly" by the way!)
