### ISSUE TITLE
 [OTHER] - Redirects out of experimental

### ISSUE THREAD

**Issue by matthewp** [withastro/docs#3743]
### 📋 Explain your issue

Redirects RFC was merged and we hope to move it out of experimental. The original PR where it was added is: https://github.com/withastro/docs/pull/3395

Things to do:

- Remove *experimental* references
- Updated *Added in* state to reflect when it became stable

**Comment by sarah11918** [comment]
Thanks, @matthewp !

If nothing in the feature has changed requiring a docs update re: how to use, then I think what we need is:

https://docs.astro.build/en/core-concepts/routing/#configured-redirects-experimental
- remove Experimental
- remove showing the experimental flag in the code sample

In a separate Astro PR to the types file:
https://docs.astro.build/en/reference/configuration-reference/#redirects-experimental
- remove experimental from the header
https://docs.astro.build/en/reference/configuration-reference/#experimentalassets
- remove entirely this experimental flag
