### ISSUE TITLE
[CONTENT] - confusion in FR glossary

### ISSUE THREAD

**Issue by jamesarosen** [withastro/docs#3767]
### 📚 Subject area/topic

glossary

### 📋 Page(s) affected (or suggested, for new content)

https://github.com/withastro/docs/blob/main/src/i18n/fr/README.md

### 📋 General description or bullet points (if proposing new content)

The section titled "🔄️ Mots ne nécessitant pas de traductions" is a bit confusing. The section title translates to

> Words not requiring a translation

It has the following explanatory text:

> 💡 Ces mots sont considérés comme des noms propres dû à leurs origines anglaises, prenant toujours une majuscule :

which translates to

> 💡 These words are considered proper nouns due to their English origins; always use an upper-case:

The table has two kinds of terms:

1. "Template", "Slot", "Framework", etc. These words are not translated in the glossary or in the docs.
2. "Composant Layout", "Composant Page". These are translations of "Layout Component" and "Page Component" respectively. They are translated in the glossary and in the docs.

If the docs are to use _Composant Layout_ and _Composant Page_, I think they belong in a different section in the glossary, possibly in the _Traductions courantes_ below.

### 🖥️ Reproduction in StackBlitz (if reporting incorrect content or code samples)

n/a

**Comment by jamesarosen** [comment]
Compare the [German glossary](https://github.com/withastro/docs/blob/main/src/i18n/de/README.md), which has a single table with English, German, and explanatory notes.

**Comment by delucis** [comment]
Thanks for the issue @jamesarosen! We don’t actively maintain these glossaries in general, and leave them to the individual translation crews to decide on, so happy to handle any PRs or changes our French translators think appropriate!

Feel free to discuss here or in the `#i18n-crew-fr` thread on Discord.
