### ISSUE TITLE
[CONTENT] - Clarify `build.inlineStylesheets` exceptions

### ISSUE THREAD

**Issue by natemoo-re** [withastro/docs#3769]
### 📚 Subject area/topic

Configuration Reference

### 📋 Page(s) affected (or suggested, for new content)

https://docs.astro.build/en/reference/configuration-reference/#buildinlinestylesheets

### 📋 General description or bullet points (if proposing new content)

When using a component with the `client:*` directive, Astro always injects an inline style.

```html
<style>
  astro-island, astro-slot {
    display: contents
  }
</style>
```

The documentation for the `build.inlineStylesheets` option states that a value of `"never"` means "all styles are sent in external stylesheets".

This is technically incorrect, since Astro inlines Island-related styles and scripts for performance reasons.

### 🖥️ Reproduction in StackBlitz (if reporting incorrect content or code samples)

https://stackblitz.com/edit/github-ryrabv?file=package.json,dist%2Findex.html%3AL12

**Comment by delucis** [comment]
I think we can get away with a relatively easy fix here, by updating the configuration reference to say something more like “Control whether **project** styles are sent to the browser” and similarly replace “all styles” in the bullet points with “project styles”.

This will need updating in the Astro repo here: https://github.com/withastro/astro/blob/73eb4dfe2f1ed8bceeba6fb57d60c583f61d78b3/packages/astro/src/%40types/astro.ts#L835-L848
