### ISSUE TITLE
[CONTENT] - Clarify that <ViewTransitions /> intercepts navigation client-side

### ISSUE THREAD

**Issue by kisaragi-hiu** [withastro/docs#3780]
### 📚 Subject area/topic

View Transitions

### 📋 Page(s) affected (or suggested, for new content)

https://docs.astro.build/en/guides/view-transitions/

### 📋 General description or bullet points (if proposing new content)

The second opening paragraph of the View Transitions page can appear to imply that the `ViewTransitions` component isn't in fact intercepting the browser's navigation, as the term "client-side routing" is often used to describe intercepting and doing navigation in JS, bypassing the browser's navigation.

> Astro provides a <ViewTransitions /> routing component that can be added to a single page’s <head> to control page transitions as you navigate away to another page, **an effect traditionally only possible with client-side routing.** *(emphasis added)*

This sentence then becomes confusing because the ViewTransitions component in fact does intercept navigation on the page, even though there isn't a full on router à la react-router being provided. Under this alternative but popular definition of client-side router, this sentence would appear to contradict what the component actually provides.

I propose removing the "only possible" phrase, or replacing it with something like "it provides a lightweight router" or "it does this by intercepting navigation".

### 🖥️ Reproduction in StackBlitz (if reporting incorrect content or code samples)

N/A

**Comment by USKhokhar** [comment]
I did try making it somewhat better with respect to your suggestions, and it can be rephrased to something like this:

---
Astro provides a `<ViewTransitions />` routing component that can be added to a single page's <head> to control page transitions as you navigate away to another page. It provides a lightweight router that intercepts navigation and allows you to customize the transition between pages. Add this component to a reusable .astro component, such as a common head or layout, for animated page transitions across your entire site (SPA mode).
---
