### ISSUE TITLE
Typo in AstroDocs Under CSS Integration Section 

### ISSUE THREAD

**Issue by FriendlyLifeguard** [withastro/docs#3812]
### 📋 Explain your issue

Misspelled Tailwind. 

<img width="785" alt="Screenshot 2023-07-24 at 8 54 08 PM" src="https://github.com/withastro/docs/assets/55970530/e09a244b-a62a-4b58-921e-4ea3e25db8bb">

**Comment by Yan-Thomas** [comment]
Thanks for finding this @FriendlyLifeguard! I've made a PR fixing this typo and others close to it 🙌
