### ISSUE TITLE
[CONTENT] - Dead link in the Node adapter section

### ISSUE THREAD

**Issue by sasoria** [withastro/docs#3831]
### 📚 Subject area/topic

Node adapter (@astrojs/node)

### 📋 Page(s) affected (or suggested, for new content)

https://docs.astro.build/en/guides/integrations-guide/node/#troubleshooting

### 📋 General description or bullet points (if proposing new content)

The Node adapter section links to a [known issue](https://github.com/withastro/astro/issues/4974) that does not exist (it returns 404 on GitHub). I've tried searching for it with no luck. Is the original problem solved by any chance? If we're not sure, then maybe we should just remove the link?

### Screenshot
![Screenshot 2023-07-26 at 14 01 59](https://github.com/withastro/docs/assets/7903076/bf39530a-bb74-4909-a0e5-ccc809c85825)

### 🖥️ Reproduction in StackBlitz (if reporting incorrect content or code samples)

-

**Comment by sdp971** [comment]
Hi ! Could you assign me this issue please 😊 ?

**Comment by sasoria** [comment]
Thank you for wanting to pick this up @sdp971 🙌 You can apply the suggested changes [here](https://github.com/withastro/astro/blob/365701f4915b0a7d99e43b04f4a946d9fa317d04/packages/integrations/node/README.md?plain=1#L191).

**Comment by sdp971** [comment]
Thank you so much  @sasoria 🙏

**Comment by sarah11918** [comment]
Thank you for making the PR to the Astro repo, @sdp971 ! It was exactly what was needed, so I'm closing this issue!  :partying_face:
