### ISSUE TITLE
💡 Idea Can we add a function to output Markdown documents

### ISSUE THREAD

**Issue by xiyuvi** [withastro/docs#3847]
I want to use Astro to create a web blog and create a static JSON data from the article list and Markdown document, which can be used by other external programs

**Comment by delucis** [comment]
Hi @xiyuvi — thank you for the issue! This is the issue tracker for the Astro documentation website. We have a dedicated discussions forum in our `roadmap` repo for feature requests — https://github.com/withastro/roadmap/discussions — and you’re also welcome to give feedback [on Discord](https://astro.build/chat) in our `#feedback-ideas` channel and where we also a friendly support team who can help with any questions you may have.
