### ISSUE TITLE
Theme Switcher a11y and i18n concerns

### ISSUE THREAD

**Issue by Yan-Thomas** [withastro/docs#399]
The [theme switcher component](https://github.com/withastro/docs/blob/main/src/components/RightSidebar/ThemeToggleButton.tsx) uses `aria-label` with template strings to clarify to screen readers the current theme you're using. The problem with this is that it makes harder for translators to just translate it as part of [`ui.ts`](https://github.com/withastro/docs/blob/main/src/i18n/en/ui.ts).

If we can simplify the current component to work without template strings in a way that allow us to translate "Use dark/light theme" would be great. If not, I suggest we change the solution to Heydon Pickering's [Theme Switcher component on Inclusive Components' blog](https://inclusive-components.design/a-theme-switcher/)

**Comment by delucis** [comment]
Great catch! That pesky English text gets everywhere.

I'd suggest adding two new entries to the UI dictionary:

```js
  'themeToggle.useLight': 'Use light theme',
  'themeToggle.useDark': 'Use dark theme',
```

Then we can use the same approach as for other Preact components: add a `labels` prop and pass the correct translations to it from the Astro component that includes it.

**Comment by delucis** [comment]
Here's the table of contents component for example: https://github.com/withastro/docs/blob/main/src/components/RightSidebar/TableOfContents.tsx

And now we pass the translated strings: https://github.com/withastro/docs/blob/4c33018ac3f57db3a1537a40e314b80e6b595553/src/components/RightSidebar/RightSidebar.astro#L19

**Comment by sarah11918** [comment]
Sounds great, and thanks for discovering this @Yan-Thomas !

**Comment by sarah11918** [comment]
While you look into this, can you take Issue #106 into account? Can we address that in this solution?

**Comment by Yan-Thomas** [comment]
Thanks @sarah11918 !

About #106, I think I can also solve this in the same PR. I'm not sure about the UI/UX of it though, but since we want to support the system preference, I could add a third state to the toggle (this way, well, it won't be a toggle anymore so I don't like it that much) or change it, as Fred suggested in the issue, to a button who changes state and icon between dark/light/system, which I prefer.

As a disclaimer, I only use screen readers for testing, so I can't really say what is best or not, but for me atleast, the button approach sounds more intuitive than the toggle. I need to further research on what most users prefer before commiting to one of these approaches, if anyone has more knowledge on this, I would love to know!

**Comment by sarah11918** [comment]
Excellent, @Yan-Thomas !

If I understand the older issue correctly, it's maybe less about whether it's toggle or buttons and more about the functionality of being able to clear/reset the state. So, I personally don't have a preference about the specific UI element as long as it effectively does the job.  :)

**Comment by Yan-Thomas** [comment]
I think I found a solution without changing the UI at all! Credits to my shower thoughts 😅! 

Just to validate it (and remember it) before trying to implement it tomorrow: 

If the current theme matches the system's preference, it removes the data from local storage, so it syncs up with your system. But when you change through the toggle and then the current theme is different from the system, it saves to local storage. I don't think many people change the system's color scheme often, so there isn't a problem from it doesn't saving your current theme to local storage always. 

Sure there isn't clear indication this is happening to the user, but I guess this cover all the use cases that I can think of. Like changing the system's scheme based on day/night cycle automatically.

**Comment by sarah11918** [comment]
I should "send you to the showers" more often, @Yan-Thomas !  😄 

I commented on the PR there, and mentioned the older issue and Caleb there as well.
