### ISSUE TITLE
"On this page" doesn't indicate which part you're currently reading

### ISSUE THREAD

**Issue by Yan-Thomas** [withastro/docs#400]
Something that I feel is missing on the current "On this page" component is the dynamic focus on headings based on where you're on the page, like what React.js Tutorial does in the image below:
![EXDlhQP](https://user-images.githubusercontent.com/61414485/165864998-55be262d-a3e3-4c15-855f-f88d217c4794.gif)

This can be achieved using [Intersection Observer API](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API), the downside is that it means adding more JS to the docs of a framework that has "Ship Less JavaScript" as catchprase😅.

Some pages are big and this functionality helps me keep track of where I am as I read, but the million dollar question is: Is this really valuable to most of us and the extra JavaScript sprinkles are worth it?

**Comment by sarah11918** [comment]
So I took a look and NuxtJS docs do have this. In mobile mode, they don't even have "on this page" at all.

We have to re-do all the comparisons for Astro vs X page anyway... would you be up for looking at e.g. https://nuxtjs.org/docs/get-started/installation as a first step and seeing whether their "on this page" that shows where you are in the page seems to affect performance very much, @Yan-Thomas ? How much work would it be to try adding it to our docs and examining the difference in performance?

**Comment by Yan-Thomas** [comment]
Hey @sarah11918 !

About Nuxt.js docs, they add this "Table of Contents" dropdown that sticks to the page as you scroll on mobile:

![Screenshot_20220430-185543_Samsung Internet.jpg](https://user-images.githubusercontent.com/61414485/166123973-14ed3a73-74af-4c49-806f-63e8b0edaa01.jpg)

I think I can easily PR this tomorrow and show how it affects page load through Lighthouse. Also, since we have preview deploys, anyone can use other metrics to test the performance impact as well!
