### ISSUE TITLE
Astro does not refresh with Docker

### ISSUE THREAD

**Issue by SaulR07** [withastro/docs#4003]
### What version of `astro` are you using?

1.2.6

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

I create my astro image in docker

```
FROM node:18-alpine3.15
RUN mkdir app
WORKDIR /app
COPY . .
RUN npm install
EXPOSE 3000
CMD ["npm","run","dev","--","--host"]
```

I build my image with the following command

` docker build . -t astro-image
`

I run my container with this command

` docker run --name astro-container -p 3000:3000 -v C:\Workspace\Docker\docker-astro:/app -v /app/node_modules/ astro-image`

So far without problems but when I make a change in the index.astro it does not refresh the page.

But the index.astro inside the container does change.

### Link to Minimal Reproducible Example

https://github.com/SaulR07/docker-astro-example

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ElianCodes** [comment]
I'll take this up in the Docker recipe next week!

**Comment by ElianCodes** [comment]
Should be documented now!

**Comment by DerpyDinosaur** [comment]
@ElianCodes I am having trouble finding a Recipe within the docs for a development container. Did it get written somewhere else? 

These docs only seem to show how to deploy and build it.
https://docs.astro.build/en/recipes/docker/

**Comment by daqm3d** [comment]
Verify in the **"Astro.config.mjs"** **Astro** configuration file that has this configuration for recharge with the **"NPM RUN DEV"** command within a Docker container.

```
      export default defineConfig({
       server: {
                     host: true 
                     hmr: {
                               //     This is if the Docker server is in another machine
                              //host: 'IP SERVER HERE'
                     }
         }
     });  
```

**Comment by und-miller** [comment]
> I was stuck on this for a long time. I used the `Vite` config in Astro's `astro.config.mjs` file to enable hot reloading within a docker container.
> 
> ```js
> // https://astro.build/config
> export default defineConfig({
>   integrations: [tailwind(), vue()],
>   vite: {
>     server:{
>       host: "0.0.0.0",
>       hmr: { clientPort: 3000 },
>       port: 3000, 
>       watch: { usePolling: true }
>     }
>   }
> });
> ```
> 
> You do also have to make sure you have a shared volume with your Docker Compose too.
> 
> ```
> web-dev:
>     build:
>         context: web
>         target: develop
>     volumes:
>         - ./web:/web
>         - /web/node_modules
>     ports:
>         - 3000:3000
> ```

Thank you for the solution. I would buy you a beer if I could.

**Comment by SanditZZ** [comment]
> I was stuck on this for a long time. I used the `Vite` config in Astro's `astro.config.mjs` file to enable hot reloading within a docker container.
> 
> ```js
> // https://astro.build/config
> export default defineConfig({
>   integrations: [tailwind(), vue()],
>   vite: {
>     server:{
>       host: "0.0.0.0",
>       hmr: { clientPort: 3000 },
>       port: 3000, 
>       watch: { usePolling: true }
>     }
>   }
> });
> ```
> 
> You do also have to make sure you have a shared volume with your Docker Compose too.
> 
> ```
> web-dev:
>     build:
>         context: web
>         target: develop
>     volumes:
>         - ./web:/web
>         - /web/node_modules
>     ports:
>         - 3000:3000
> ```

Took me a while until this fixed it! Thank you!
