### ISSUE TITLE
Starter Kit installer doesn't enable correct framework

### ISSUE THREAD

**Issue by davedbase** [withastro/docs#402]
**Note**: I clicked the GitHub button on the Astro docs install page and blindly posted this bug here in docs. It should probably be moved to the correct place. Sorry.

## Description

It seems like the installer isn't actually adding the correct JS framework for the generic starter.

## Versions

astro@1.0.0-beta.19
Node v17.3.0
pnpm 6.32.9

## Steps to Reproduce

1. `pnpm create astro@latest`
2. Create app directory: `./test`
3. Select `Starter Kit (Generic)`
4. Select `Solid.js`
5. Install pnpm: `Y`
6. Run `pnpm dev`

Observe that Solid isn't installed in package.json nore is the astro.config.mjs file setup with the correct package.

I'm able to reproduce the same issue for React and the other frameworks.

**Comment by davedbase** [comment]
Maybe it's because you're using npm and I'm using pnpm?

**Comment by davedbase** [comment]
Once I pass that step and setup Solid integration manually I get a further error (which I could post separately but seems related):

```
Failed to resolve force included dependency: solid-js
9:42:19 p.m. [vite] Error when evaluating SSR module @astrojs/solid-js/server.js:
Error: Cannot find module 'solid-js/web' imported from 
```

**Comment by sarah11918** [comment]
pnpm still seems to work for me? Do you see anything here?

![Screenshot 2022-04-28 22 47 43](https://user-images.githubusercontent.com/5098874/165873504-908416b1-e80d-4c33-be32-34d47cff8653.png)
![Screenshot 2022-04-28 22 47 29](https://user-images.githubusercontent.com/5098874/165873506-53c55801-5c7d-4553-9356-c8bc65b3585d.png)

**Comment by davedbase** [comment]
Nope, you know what this is a none issue. This is what happens when we don't *read* instructions. lol.

So I was installing with NO frameworks to begin with and didn't even realise it.

Can I suggest a step be added after selecting the framework? If a user doesn't specify from the list perhaps catch them before they continue? ie. `We noticed you didn't add a framework, would you like to continue? (If you selected a framework make sure you use space bar to actually selected it)`.

I think this is the type of interaction where the user feels confident enough to just pick and go without actually reading the copy. It tripped me up a bit and could be easily resolved.

**Comment by sarah11918** [comment]
I'll make a note! It's already on my list to update the instructions re: the create-astro walk through because this wizard has changed a little since the current docs were written. So, I'll be SURE to make it clear what to do in docs... and I'll ping engineering about the wizard itself.

**Comment by sarah11918** [comment]
I'm closing this issue because the next page on my list to rewrite is the instructions following create-astro, since the wizard has just been updated with new steps! So, I will keep this in mind as I document the process. Thanks again for your suggestions!
