### ISSUE TITLE
Add an example on how to use default environment variables

### ISSUE THREAD

**Issue by TheOtterlord** [withastro/docs#4030]
Our section on [Default Environment Variables](https://docs.astro.build/en/guides/environment-variables/#default-environment-variables) is missing an example of how environment variables are used. 

### Task
Add an example that shows some usage of one of these default environment variables.

#### Page to edit
- [Using environment variables](https://github.com/withastro/docs/blob/ac487d80cb596a64a4295bb4c7478297bd9c459d/src/content/docs/en/guides/environment-variables.mdx#L23)

**Comment by ElianCodes** [comment]
@sasoria, I know you've added some docs to this page a couple of days ago. Is this something you're interested in to pick up?

(Saying no is totally fine!)

**Comment by sasoria** [comment]
Yes, I can pick this up. I'll try to get it done within this week.
