### ISSUE TITLE
Check the RSS feed section of the tutorial works

### ISSUE THREAD

**Issue by TheOtterlord** [withastro/docs#4035]
### 📋 Explain your issue

Run through this section and confirm this works with the current versions of Astro & the RSS package

#### Page

- [Add an RSS feed - Astro Blog Tutorial](https://docs.astro.build/en/tutorial/5-astro-api/4/)

**Comment by sarah11918** [comment]
We had confirmation of the code in the blog-tutorial repo issue https://github.com/withastro/blog-tutorial-demo/issues/12 , so I think we can close this one for now!
