### ISSUE TITLE
Find and fix instances of trailing commas in tsconfig.json

### ISSUE THREAD

**Issue by TheOtterlord** [withastro/docs#4037]
### 📋 Page(s) affected (or suggested, for new content)

https://docs.astro.build/en/install/manual/#6-add-typescript-support

### 📋 General description or bullet points (if proposing new content)

There are some `tsconfig.json` examples which have a trailing comma, which is invalid JSON. Find and replace instances of this in the docs.

**Comment by anubhav1206** [comment]
Can I work on this?

**Comment by ElianCodes** [comment]
Hey @anubhav1206 ! We would love to see you work on this! Go ahead and open a PR!

Hit me up if you need any help!

**Comment by anubhav1206** [comment]
I can't seem to find any unnecessary commas, looks good to me.

**Comment by ElianCodes** [comment]
Hey @anubhav1206! There still are some trailing commas to be found! I gave a little push in #4059.
