### ISSUE TITLE
Audit Routing & Pagination Page

### ISSUE THREAD

**Issue by TheOtterlord** [withastro/docs#4039]
### 📚 Subject area/topic

Routing

### 📋 Page(s) affected (or suggested, for new content)

- https://docs.astro.build/en/core-concepts/routing/
- https://docs.astro.build/en/core-concepts/routing/#pagination

### 📋 General description or bullet points (if proposing new content)

Audit this page, and raise any concerns about existing or lack of content. Pagination specifically is a section that needs rewriting.

### 🖥️ Reproduction in StackBlitz (if reporting incorrect content or code samples)

N/A

**Comment by sarah11918** [comment]
On my list! Doesn't need to be here! Thanks Otterlord!
