### ISSUE TITLE
Update Heroku CMS guide

### ISSUE THREAD

**Issue by ElianCodes** [withastro/docs#4042]
### 📚 Subject area/topic

Deploy guide (Heroku)

### 📋 Page(s) affected (or suggested, for new content)

https://docs.astro.build/en/guides/deploy/heroku/

### 📋 General description or bullet points (if proposing new content)

in https://docs.astro.build/en/guides/deploy/heroku/ we recommend heroku-buildpack-static, but it is deprecated.

```
# set buildpack for static sites
$ heroku buildpacks:set https://github.com/heroku/heroku-buildpack-static.git
```

Check if we can update this to a more recent and maintained package

### 🖥️ Reproduction in StackBlitz (if reporting incorrect content or code samples)

/

**Comment by sarah11918** [comment]
Will wait until someone complains!  ;)  It's here for the record.
