### ISSUE TITLE
Share links at end of tutorial

### ISSUE THREAD

**Issue by TheOtterlord** [withastro/docs#4044]
### 📋 Explain your issue

Add some links at the end of the tutorial, allowing people to share their achievements! Sites like Twitter, Reddit, Mastadon might be some good options.

**Comment by threehymns** [comment]
How about a suggested Github topic tag to use like "astro-blog-project".

**Comment by newtoallofthis123** [comment]
Cool idea! I'll try some things out :)

**Comment by newtoallofthis123** [comment]
Hey I tried to do this and it looks like this now 
![Astro.js](https://github.com/withastro/docs/assets/78465651/a54549fa-ad76-4bb3-8e54-31201b3ccdfd)

Although, I don't think you can add the mastodon links since they are not standardized 😅
