### ISSUE TITLE
There might be a section on using Content Collections in Endpoints

### ISSUE THREAD

**Issue by jrencz** [withastro/docs#4051]
### 📚 Subject area/topic

Guides, Core concepts

### 📋 Page(s) affected (or suggested, for new content)

Page I suggest editing: https://docs.astro.build/en/core-concepts/endpoints/

### 📋 General description or bullet points (if proposing new content)

I re-approached Astro after a longer period of not being up to date with latest new things and I was pleased to see since 2.0.x where I reviewed the docs a log of new things appeared. Kudos!

Among the useful things I will definitely use in following days there are static endpoints. They work like a charm, but after exploring them along yesterday I ended up in having something done, but I got stuck at "where to hold my data". I don't have a headless CMS and I wanted to keep the data as static JSON files.

I was a bit surprised that I can't use `Astro.glob` in Endpoint. Today I approached the problem again and I discovered Content Collections. They do **exactly** what I wanted and what I needed, but they're not mentioned at all on Endpoints page today. **I propose to introduce a section on using Content Collections in Endpoints**. Especially the `type: 'data'` and especially with mentioning that if one was accustomed to `Astro.glob` for expressing "I want all that…" then `getCollection` and `getEntry` are the replacements

### 🖥️ Reproduction in StackBlitz (if reporting incorrect content or code samples)

n/a

**Comment by sarah11918** [comment]
Thanks, this sounds like a very helpful addition indeed, @jrencz !

Is this something you'd be interested in making a PR for? Maybe something on the Endpoints page directly, then a link to it on the Content Collections page where appropriate? What do you think?

**Comment by sarah11918** [comment]
Closed due to inactivity
