### ISSUE TITLE
`import.meta.env` incorrectly rendered in Asides

### ISSUE THREAD

**Issue by liruifengv** [withastro/docs#4110]
### 📝 Issue Description

`import.meta.env` incorrectly rendered in Asides

### 📋 On which page(s) it occurs

- https://docs.astro.build/en/guides/environment-variables/
- https://docs.astro.build/en/guides/configuring-astro/

### 🤔 Expected Behavior

Correctly rendered

### 👀 Current Behavior

`import.meta.env` render as `import\u002Emeta.env`

### 🖥️ Browser

Chrome

### 📄 Additional Information

![image](https://github.com/withastro/docs/assets/25167721/2bfaa3fe-6cbf-4e98-a206-7db7d16ecd40)

**Comment by 100gle** [comment]
it seems that this issue is due to the `escapeViteEnvReferences()` function in [#4858](https://github.com/withastro/astro/pull/4858) when MDX plugin was set up.

```ts
// astro/packages/integrations/mdx/src/index.ts

function escapeViteEnvReferences(code: string) {
	return code.replace(/import\.meta\.env/g, 'import\\u002Emeta.env');
}
```

**Comment by TheOtterlord** [comment]
We're in the process of migrating our docs to Starlight. I checked the preview branch for some of the migration work, and it looks like it's rendering fine.
- https://astro-docs-migration-preview.netlify.app/en/guides/environment-variables/
- https://astro-docs-migration-preview.netlify.app/en/guides/configuring-astro/

Making a note in case this issue outlives the current docs site. This is not to say we're closed to fixes! It could be some time before this migration is complete, and in the meantime it would be great to find a fix for this and **PRs are welcome!**
