### ISSUE TITLE
Integrations API — Dev Setup for Testing Locally Example

### ISSUE THREAD

**Issue by roblevintennis** [withastro/docs#414]
Capturing the idea that we should show instructions for setting up a local dev env and testing a non-internal integration (see [this comment](https://github.com/withastro/docs/pull/388#issuecomment-1112041968)) per @bholmesdev request. One will need to configure their own `tsconfig` as `astro-scripts` which is typically used within astro's main monorepo is not available. Also, many folks new to npm publishing won't be aware of tooling like `npm pack` etc., so a hello world example of all this will help them get to a place where they can contribute.

Here's a small readme [showing how I did it](https://github.com/AgnosticUI/agnosticui/tree/master/integrations/agnosticui-astro#getting-started) (and the integration seems to be working in this repo link too if you follow those instructions); but I believe Ben wants to investigate if there's a cleaner `pnpm` way to approach to this :)

**Comment by sarah11918** [comment]
Just because this is getting a little stale, I'm pinging @bholmesdev again to see if he has a fresh take on this one!

**Comment by bholmesdev** [comment]
My thoughts haven't changed on this too much! I've sadly had to deprioritize this in favor of other bug and documentation work. Happy to pick this up in the next couple weeks.

**Comment by delucis** [comment]
Hey sorry, this issue got a little neglected. We’re not going to be able to prioritise this for a little while. If anyone does want to pick it up and provide a guide — maybe adding to our NPM Package guide — would be happy to see it!

**Comment by delucis** [comment]
Going to close this in favour of #1969!
