### ISSUE TITLE
View Transitions page not visible in Italian sidebar

### ISSUE THREAD

**Issue by TheOtterlord** [withastro/docs#4141]
### 📝 Issue Description

The [View Transitions](https://docs.astro.build/it/guides/view-transitions/) page isn't available in the Italian navigation.

### 📋 On which page(s) it occurs

https://docs.astro.build/it/getting-started/

### 🤔 Expected Behavior

The page should be visible in the sidebar

### 👀 Current Behavior

The page is missing from the navigation

### 🖥️ Browser

Firefox

### 📄 Additional Information

This seems to come from the Italian navigation translation not using `NavDictionary`, and therefore not being provided the correct fallbacks.

Edit: Additional context, while the nav isn't broken for Spanish, that also doesn't currently use `NavDictionary`

**Comment by delucis** [comment]
Agree this is almost certainly related to not using `NavDictionary`. I’d guess Spanish would have the same issue if they weren’t so darn fast at adding each page we add 😄 

I’d suggest we standardise both to use `NavDictionary` to avoid getting tripped up.

Thanks for the detailed issue @TheOtterlord!
