### ISSUE TITLE
[meta] Improve contributor guides 

### ISSUE THREAD

**Issue by tsxoxo** [withastro/docs#4183]
### 📚 Subject area/topic

contributor guides -- recipe style guide

### 📋 Page(s) affected (or suggested, for new content)

up for discussion -- possibly:

* The [Writing Guide](https://github.com/withastro/docs/blob/main/contributor-guides/writing-and-style-guide.md)
* [Recipe Guide](https://github.com/withastro/docs/blob/main/contributor-guides/submitting-a-recipe.md)
* The [Contributing to Docs section](https://docs.astro.build/en/contribute/#contributing-to-docs) on the docs website

### 📋 General description or bullet points (if proposing new content)

I see some things to improve in our writing guides. Happy to submit a PR or 3!

## State implicit guidelines more clearly
While we were working on the CMS recipe for `Builder.io`, some additional writing guidelines came out in [the PR](https://github.com/withastro/docs/pull/3357). I think it might save future contributors (and our brave reviewers) some time if these guidelines were stated clearly somewhere in the writing guides:

1. [*“we typically like to avoid getting into too many of the third-party's instructions."*](https://github.com/withastro/docs/pull/3357#discussion_r1224434946)
 
This is a quote from @sarah11918 that we could almost put in the docs as is :o). I'd add smth like: *"You can give some, but keep it simple. For more complex procedures, you can link to a relevant page in the official documentation instead"*. 

2. *Don't attach screenshots.* 

### Possible space for these instructions

- in the section [Recipe writing](https://github.com/withastro/docs/blob/main/contributor-guides/writing-and-style-guide.md#recipe-writing) within [`writing-and-style-guide.md`](https://github.com/withastro/docs/blob/main/contributor-guides/[writing-and-style-guide.md)

## Improve instructions for text highlighting in our [section on code samples](https://github.com/withastro/docs/blob/main/contributor-guides/writing-and-style-guide.md#code-samples)

I’ve had trouble applying some of the regex examples in that section to my own snippets.

After doing some tests (see reproduction) I think I found the thing that really threw me off:

[Example 2](https://github.com/withastro/docs/blob/main/contributor-guides/writing-and-style-guide.md#example-2) says *"- highlight any occurrence of `{props.title}` and `{props.social}`"*,
but the following regex -- `/{props.(title|socialLinks)}/` (sic!) -- only highlights the words `title` and `social` -- whatever is in the round brackets. I thought for a long time there was something wrong on my side. 

I think it should be made clear this only highlights the words in the round brackets. And possibly give another example highlighting the whole `{props.title}`, including the wavy brackets. 

Also, the regex in the example saying `socialLinks` instead `social` seems to be an oversight. 

💜

### 🖥️ Reproduction in StackBlitz (if reporting incorrect content or code samples)

Ran some quick in a Gitpod workspace. They're at the top in the Builder CMS recipe.  

https://gitpod.io#snapshot/2c8fcfdb-aa29-4ba2-b9ad-5adb316bf012

**Comment by sarah11918** [comment]
We are so backed up, I'm just getting around to some older issues now... it looks like this one should have been closed with the merged PR!

Thanks for this, for contributing, and hope to see you around the docs again! (And I have a lot of behind-the-scenes contributor guide improvements happening... so I hope these docs will continue to get better!)
