### ISSUE TITLE
Improve `locals` documentation on Middleware

### ISSUE THREAD

**Issue by Fryuni** [withastro/docs#4207]
### 📚 Subject area/topic

Middleware

### 📋 Page(s) affected (or suggested, for new content)

https://docs.astro.build/en/guides/middleware/

### 📋 General description or bullet points (if proposing new content)

Some code snippets, like the one below, include a comment about intercepting the response data from a request. No data is being intercepted in such snippets and the comments are placed before populating the `locals` object, where one might intercept _the request_. Intercepting _the response_ would be done by modifying the return value of `next()`.

```js
export function onRequest ({ locals, request }, next) {
    // intercept response data from a request
    // optionally, transform the response by modifying `locals`
    locals.title = "New title";

    // return a Response or the result of calling `next()`
    return next();
};
```

I think this snippet would be clearer with the following comments:

```js
export function onRequest ({ locals, request }, next) {
    // intercept data from a request
    // optionally, share data with the rendering process by modifying `locals`
    locals.title = "New title";

    // return a Response or the result of calling `next()`
    // optionally, transform the response by modifying the result
    return next();
};
```

The reference for `locals` also causes the same confusion, it says:

> An object containing data from a `Response` that can be manipulated inside middleware.

From what I understand, the `locals` is used by the routes and pages to create the response, so it contains data _for_ the response, possibly _from the request_.

Is my interpretation correct?

**Comment by sarah11918** [comment]
Thank you for this comment! I am referring this discussion to @ematipico to help us decide the best action for the documentation!
