### ISSUE TITLE
[v3 checks] Remove references of returning simple objects from endpoints

### ISSUE THREAD

**Issue by bluwy** [withastro/docs#4296]
### 📚 Subject area/topic

Endpoints

### 📋 Page(s) affected (or suggested, for new content)

https://docs.astro.build/en/core-concepts/endpoints/

I don't see any other pages that needs updating, but could worth checking if I miss something.

### 📋 General description or bullet points (if proposing new content)

Endpoints should return with a `Response` instead of a simple object in Astro 3.0.

Note: While the migration guide has the `ResponseWithEncoding` API to ease the change, I don't think we want to recommend it as most setup can use `Response` with a little refactoring. For example, an image can be served like this too:

```ts
export async function get({ params, request }) {
  const response = await fetch("https://docs.astro.build/assets/full-logo-light.png");
  return new Response(await response.arrayBuffer());
}
```

So the docs should not use `ResponseWithEncoding` if possible.

### 🖥️ Reproduction in StackBlitz (if reporting incorrect content or code samples)

N/A. Original core PR: https://github.com/withastro/astro/pull/8132

**Comment by fflaten** [comment]
> I don't see any other pages that needs updating, but could worth checking if I miss something.

RSS should also be updated with `Response`. New users are more likely to hit that than custom endpoints. 🙂

**Comment by bluwy** [comment]
Wow thanks for flagging that. I miss that part for sure, I'll see if we can make that return a `Response` or simply a string instead.

**Comment by ElianCodes** [comment]
Hey @bluwy, I updated the page here: https://github.com/withastro/docs/pull/4166/files#diff-59d57ceac4a4eb8bfdbf48874466f48ff6ba866c6168bce159cdd832012a5d5b

Could you dubble check for me?

**Comment by bluwy** [comment]
Thanks @ElianCodes left a [comment](https://github.com/withastro/docs/pull/4166/files#r1305642945) mostly about formatting, but I think you caught the rest of the changes!

**Comment by ElianCodes** [comment]
Awesome! In that case I'm closing this issue!
