### ISSUE TITLE
Subtle bug in AWS CI/CD with Github actions.

### ISSUE THREAD

**Issue by ErikKaum** [withastro/docs#4298]
### 📚 Subject area/topic

Deployment docs

### 📋 Page(s) affected (or suggested, for new content)

https://docs.astro.build/en/guides/deploy/aws/#continuous-deployment-with-github-actions

### 📋 General description or bullet points (if proposing new content)

When deploying through Github actions, copy + pasting the code examples, static assets aren't deleted from the S3 bucket even if they don't appear in the `/dist` directory.

An example. I have some blog pages under `/blog/[slug]`. And under `/pages/blog/[...slug].astro` I have the pretty much the standard template:
```
export async function getStaticPaths() {
	const mode = import.meta.env.MODE
	let posts = await getCollection('blog');
	
	if (mode === 'production') {
		posts = posts.filter((post) => post.data.draft !== true)
	}

	return posts.map((post) => ({
		params: { slug: post.slug },
		props: post,
	}));
}
type Props = CollectionEntry<'blog'>;

const post = Astro.props;
const { Content } = await post.render();
---

<BlogPost {...post.data}>
	<Content />
</BlogPost>
```
now if I delete a blog post and run `aws s3 sync ./dist/ s3://${{ secrets.BUCKET_ID }}` it wont delete that route from the S3 bucket.

The suggested fix would be to use:
`aws s3 sync --delete ./dist/ s3://${{ secrets.BUCKET_ID }}`
and add IAM permissions to delete objects:
`"s3:DeleteObject"`

### 🖥️ Reproduction in StackBlitz (if reporting incorrect content or code samples)

I tired to describe above how to reproduce. Not really possible with stackblitz since it's a CI/CD thing.

**Comment by delucis** [comment]
Thanks for the issue @ErikKaum! Would you be interested in updating the guide with these additional steps in a PR? We’d be happy for the improvement.

**Comment by ErikKaum** [comment]
Thank you 👍 I'll make a PR!

**Comment by ErikKaum** [comment]
Ah seem like I need permission to push + PR to the repo @delucis. Something you could help me with?

**Comment by delucis** [comment]
You shouldn’t need to push directly — most of our contributors use a fork to PR from. The contributing guide might be helpful. For example, this section on maintaining a fork: https://github.com/withastro/docs/blob/main/CONTRIBUTING.md#helpful-information-about-forks

The simplest can be to edit the page directly in GitHub’s web UI, but happy to provide any guidance you might need!

**Comment by ErikKaum** [comment]
Ouh yes, sorry didn't read the guidelines properly. Got the PR going. Thanks for the help 👍
