### ISSUE TITLE
Problem with Spanish tutorial

### ISSUE THREAD

**Issue by jramma** [withastro/docs#4303]
You have this example for post-4.md:

---
layout: ../../layouts/MarkdownPostLayout.astro
title: Mi cuarta entrada en el blog
author: Astro alumno
description: "Esta entrada aparecerá sola!"
image:
  url: "https://docs.astro.build/default-og-image.png"
  alt: "La palabra "astro" contra una ilustración de planetas y estrellas."
pubDate: 2022-08-08
tags: ["astro", "éxitos"]
---
Esta entrada debería aparecer con las demás entradas de mi blog, porque `Astro.glob()` está devolviendo una lista de todas mis entradas para crear mi lista.

In this snippet, the double quotes around the alt value should be single quotes to avoid conflicts with the double quotes surrounding the entire value.

**Comment by delucis** [comment]
Thanks for the report @jramma! Would you be interested in making a PR to fix this? You should be able to click the “Edit this page” link in the right sidebar.

**Comment by jramma** [comment]
I'm sorry, but I don't find the text in GitHub, you can see this error right here https://docs.astro.build/es/tutorial/5-astro-api/1/ is the example of the third step

**Comment by jramma** [comment]
Thank you for all! I did the PR
