### ISSUE TITLE
[Content collections] Documentation should maybe specify that the `z.object` wrapper is needed?

### ISSUE THREAD

**Issue by Acccent** [withastro/docs#4306]
### 📚 Subject area/topic

Content Collections guide – specifically, defining schemas.

### 📋 Page(s) affected (or suggested, for new content)

https://docs.astro.build/en/guides/content-collections/#defining-a-collection-schema

### 📋 Explain your issue

Following [this change](https://github.com/withastro/astro/pull/5770), collection schemas require a `z.object` wrapper; the examples in the docs [have already been changed accordingly](https://github.com/withastro/docs/pull/2335).

Personally when reading the docs, it wasn't clear that the examples were demonstrating the _required_ structure – I thought `z.object` was used as, well, an example.

I would suggest something like this in the documentation for defining schemas (changes in italics):

> To define your first collection, create a `src/content/config.ts` file if one does not already exist (`.js` and `.mjs` extensions are also supported.) This file should:
> 
> 1. **Import the proper utilities** from `astro:content`. 
> 2. **Define each collection that you'd like to validate. _Collections must include:_** 
>  \- A `type` (introduced in Astro v2.5.0) specifying whether the collection contains content authoring formats like Markdown (`type: 'content'`) or data formats like JSON or YAML (`type: 'data'`);
>  \- A `schema` that defines the shape of your frontmatter or entry data, _using a Zod object as a base (`z.object({...})`)._ 
> 3. **Export a single `collections` object** to register your collections.

**Comment by Acccent** [comment]
Note that I suppose the schema actually does accept a few other things besides `z.object` (https://github.com/withastro/astro/pull/8163), but I don't know how to explain this in a way that wouldn't just add confusion. I guess anyone using the more advanced types that are valid would know that they will be accepted.

**Comment by TheOtterlord** [comment]
Thanks for the feedback!

We clarify usage of Zod in a later section ([Defining datatypes with Zod](https://docs.astro.build/en/guides/content-collections/#defining-datatypes-with-zod)). We could maybe append "using Zod" to clarify what we're using to define a schema?

> **Define each collection that you’d like to validate.** This includes a `type` (introduced in Astro v2.5.0) specifying whether the collection contains content authoring formats like Markdown (`type: 'content'`) or data formats like JSON or YAML (`type: 'data'`). It also includes a `schema` that defines the shape of your frontmatter or entry data, _using Zod_.

**Comment by Acccent** [comment]
I think (again this is just me) the problem isn't so much about clarifying the use of Zod (which is fairly well documented), but the use of Zod _objects_. I set up several schemas using `z.array()` or even `z.string()` for data collections and I couldn't figure out for the longest time where all the issues were coming from, because I was using Zod in a presumably correct way and it was all getting compiled normally.

**Comment by delucis** [comment]
I'd expect arrays to be valid in data collections, so if they're not, it might be a bug.

**Comment by Acccent** [comment]
Honestly same, and if arrays could be supported in data collections that would indeed make my life a lot easier! but since you specified in issue 8163 (linked above) that they aren't, I figured there must be some reason 😝

**Comment by TheOtterlord** [comment]
@Acccent  I've created an example on the latest version, which seems to work fine: [Stackblitz](https://stackblitz.com/edit/github-t8gznk?file=src%2Fcontent%2Fconfig.ts,src%2Fcontent%2Fauthors%2Ftest.json,src%2Fpages%2Findex.astro&on=stackblitz)

We could probably use an example somewhere on the page, to make it clear this is a supported use-case.

**Comment by delucis** [comment]
> since you specified in issue 8163 (linked above) that they aren't, I figured there must be some reason 😝

Yeah in withastro/astro#8163 I was specifically solving a content collection schema issue and had not considered data collections. We should probably make the supported types for content and data collections different to support a wider range in data collections.

**Comment by Acccent** [comment]
Okay, it looks like it was fixed in the last few releases :) Sorry about the false alarm and thanks for checking it!

**Comment by Acccent** [comment]
Okay, it looks like it was fixed in the last few releases :) Sorry about the false alarm and thanks for checking it!
