### ISSUE TITLE
Add `coc-astro` to Editor Setup page

### ISSUE THREAD

**Issue by Princesseuh** [withastro/docs#4319]
### 📋 Explain your issue

[coc-astro](https://github.com/yaegassy/coc-astro) is one of the nicest way to use the Astro language-server in Neovim, for coc.nvim users. We should link to it, it'd be cool.

Probably something like

> [coc-astro](https://github.com/yaegassy/coc-astro) provides support for our language server in Neovim for [`coc.nvim`](https://github.com/neoclide/coc.nvim) users

would be enough?

**Comment by JayRKyd** [comment]
I would like to be assigned to this if possible please
