### ISSUE TITLE
clarify how dates work in frontmatter

### ISSUE THREAD

**Issue by mayank99** [withastro/docs#4348]
### 📋 Explain your issue

i'm a little confused about how dates work in the frontmatter, when combined with content collections.

this seems to be the only recognized format (i've tried a bunch of variations):
```
---
date: 2023-08-23
---
```
and it's not ideal because it creates the wrong date depending on the time zone.
```
Tue Aug 22 2023 20:00:00 GMT -0400 (Eastern Daylight Time)
```

currently [this](https://docs.astro.build/en/guides/content-collections/#defining-datatypes-with-zod) is the only reference i can find in the documentation site, and it's buried inside a code block.
```js
// In frontmatter, dates written without quotes around them are interpreted as Date objects
publishDate: z.date(),
// You can also transform a date string (e.g. "2022-07-08") to a Date object
// publishDate: z.string().transform((str) => new Date(str)),
```

more documentation on this would be quite useful!

**Comment by Princesseuh** [comment]
This is actually a YAML thing I'm pretty sure: https://yaml.org/type/timestamp.html
