### ISSUE TITLE
Add documentation for styling rendered markdown using Tailwind

### ISSUE THREAD

**Issue by jocchong** [withastro/docs#4367]
## Problem
For those using Tailwind, it's not obvious how to style markdown rendered via Astro because Tailwind uses utility classes as its main way to style HTML.

## Solution
Adding a section in `src/content/docs/en/guides/integrations-guide/tailwind.mdx` for this referencing the official [`@tailwind/typography`](https://tailwindcss.com/docs/typography-plugin) under the `Usage` section makes the most sense to me.

**Comment by sarah11918** [comment]
See support thread here: https://discord.com/channels/830184174198718474/1144654109924917258

**Comment by lloydjatkinson** [comment]
I think a generic page/recipe might be useful here that can cover, at least, Tailwind (with it's typography plugin) and some plain CSS. This should cover all "how do I style my content separately and differently from my main site" questions. 😀

**Comment by VoxelMC** [comment]
@sarah11918 is anyone working on this at the moment?

**Comment by newtoallofthis123** [comment]
I always just use `<Fragment />` or make a custom component. Here for the recommendations :)

**Comment by sarah11918** [comment]
@VoxelMC I don't believe anyone is working on this! Happy if you'd like to read through the suggestions here and come up with a plan. I'm not a Tailwind user personally, so the more community members working our our Tailwind guidance the better!  :raised_hands:

**Comment by VoxelMC** [comment]
> @VoxelMC I don't believe anyone is working on this! Happy if you'd like to read through the suggestions here and come up with a plan. I'm not a Tailwind user personally, so the more community members working our our Tailwind guidance the better!  :raised_hands: 

Will do!

**Comment by VoxelMC** [comment]
> @VoxelMC I don't believe anyone is working on this! Happy if you'd like to read through the suggestions here and come up with a plan. I'm not a Tailwind user personally, so the more community members working our our Tailwind guidance the better! 🙌

Quick question for you: shall I add this under a heading in the Tailwind integration files [here](https://github.com/withastro/astro/blob/main/packages/integrations/tailwind/README.md)? 

Here's my plan
- Styling Rendered Markdown
  - Add @tailwindcss/typography
  - Make a component called `<Prose>`
  - Use `<Prose>` with rendered Markdown
  - Show a before/after

Should I provide before and after photos or a video like the one that is already there?
