### ISSUE TITLE
Isomorphic AstroCookies/AstroCookie

### ISSUE THREAD

**Issue by btakita** [withastro/docs#4420]
### 📝 Issue Description

When sharing isomorphic code between the server & browser in Astro, it would be beneficial to have a single API to access & modify cookie values. The `AstroBrowserCookies` would be driven from `document.cookie` instead of a `Request` object.

`AstroBrowserCookies` would implement `AstroCookiesInterface` & not implement `headers()`.

`AstroCookie` can remain the same.

### 📋 On which page(s) it occurs

Any page using browser cookies.

### 🤔 Expected Behavior

A single API to access & mutate cookies.

### 👀 Current Behavior

A bespoke browser API to access & manipulate cookies.

### 🖥️ Browser

All

**Comment by sarah11918** [comment]
Hi! This repo is only for issues related to the Astro documentation site. Feature requests can be made in the #feedback-ideas channel on our Discord server, or proposals can be made on the Astro Roadmap repo.
