### ISSUE TITLE
💡 Idea: Dynamic Routes passed as variable into Astro file

### ISSUE THREAD

**Issue by Dmitriyx** [withastro/docs#4434]
https://docs.astro.build/en/core-concepts/routing/#dynamic-routes

It shows here that we need to generate all paths on build time.

I would it would be cool if we could pass value on runtime to the astro file.

file structure:
src/pages/dogs/[dog].astro

Could we have it work in a way without having the need to specify all paths on build time?

currently, the workout I do is redirecting users with a query param attached and I grab the value from the URL that way.

however, it would be better if I did not have to do that because the URL would look much nicer without the use of query params.

**Comment by delucis** [comment]
Thanks for the issue @Dmitriyx! This issue tracker is for Astro’s docs website not Astro’s core functionality. You can suggest new features in our Roadmap Discussions: https://github.com/withastro/roadmap/discussions/
