### ISSUE TITLE
Nested pagination example code broken?

### ISSUE THREAD

**Issue by tadyjp** [withastro/docs#4440]
In Nested Pagination example code, should `allTags.map` be `allTags.flatMap`?
https://docs.astro.build/en/core-concepts/routing/#nested-pagination

related: https://github.com/withastro/docs/issues/3756#issuecomment-1654216966

**Comment by ElianCodes** [comment]
You are correct indeed! Are you willing to open up a PR and fix this yourself?

**Comment by tadyjp** [comment]
@ElianCodes Yes, I will try to fix it myself within the next few days!
