### ISSUE TITLE
Built-in Components reference is outdated

### ISSUE THREAD

**Issue by natemoo-re** [withastro/docs#4442]
### 📚 Subject area/topic

astro:components

### 📋 Page(s) affected (or suggested, for new content)

https://docs.astro.build/en/reference/api-reference/#built-in-components

### 📋 General description or bullet points (if proposing new content)

The reference for built-in components is outdated for v3.0. 

The section should probably include at least a reference for the `ViewTransitions` component, potentially linking back to https://docs.astro.build/en/guides/view-transitions/

```js
import { ViewTransitions } from 'astro:transitions'
```

### 🖥️ Reproduction in StackBlitz (if reporting incorrect content or code samples)

n/a

**Comment by sarah11918** [comment]
Adding this one to my tasks!

**Comment by sarah11918** [comment]
Other components we mention in docs:

`<Image />`
`<Fragment />`
`<Content />`
`<ViewTransitions />`
`< Astro.self />`

**Comment by newtoallofthis123** [comment]
Um...just for some clarity, Reference to `<Image />` `<Fragment />` etc must be added briefly, linking back to their respective docs?
