### ISSUE TITLE
View Transitions docs: make clear that only transition:animate will result in fallback animation

### ISSUE THREAD

**Issue by ElianCodes** [withastro/docs#4445]
### 📚 Subject area/topic

View Transitions

### 📋 Page(s) affected (or suggested, for new content)

https://docs.astro.build/en/guides/view-transitions/#fallback-control

### 📋 General description or bullet points (if proposing new content)

Our View Transitions docs could use some updates on the fallback, and mention that only using transition:animate results in fallback animations.

### 🖥️ Reproduction in StackBlitz (if reporting incorrect content or code samples)

N/A

**Comment by manthan-jsharma** [comment]
Hi @ElianCodes, I'm interested in picking this up. Could you please provide more detailed information about the specific revisions needed for the document?

**Comment by sarah11918** [comment]
@ElianCodes do you still think we need this? View Transitions is changing all the time. Do you have something in mind to go here, or would you close this now?

**Comment by ElianCodes** [comment]
I actually think we can close this now!

Closing for now, but can always be re-opened if we decide so.
