### ISSUE TITLE
Since Astro includes SSR, I think it's worth mentioning in the getting started page

### ISSUE THREAD

**Issue by omerp-explorium** [withastro/docs#4524]
### 📚 Subject area/topic

SSR

### 📋 Page(s) affected (or suggested, for new content)

https://docs.astro.build/en/concepts/why-astro/

### 📋 General description or bullet points (if proposing new content)

I believe it is possible to create application-focused sites now, Or am I at the wrong here? 🤔 

### 🖥️ Reproduction in StackBlitz (if reporting incorrect content or code samples)

-

**Comment by sarah11918** [comment]
Thank you for this note @omerp-explorium ! We are currently rewriting our getting started and conceptual pages and improving some other areas of documentation to better address SSR and highlight that yes, we now do have the features that make web apps a great option in Astro!  🙌  Hope to have some of this done soon!
