### ISSUE TITLE
Clarify `Your repository is named <YOUR_USERNAME>.github.io. `

### ISSUE THREAD

**Issue by tordans** [withastro/docs#4569]
### 📚 Subject area/topic

Deployment

### 📋 Page(s) affected (or suggested, for new content)

https://docs.astro.build/en/guides/deploy/github/

### 📋 General description or bullet points (if proposing new content)

The docs say …
> Don’t set a base parameter if:
> - Your repository is named <YOUR_USERNAME>.github.io.`
> - …

This wording is in place since the first commit of this document (but in different places; according gut Github blame).

It think this is wrong.

The default Github pattern is that `https://github.com/tordans` has github pages at `tordans.github.io`. The same for organisations. So every regular repo is located at `<YOUR_USERNAME>.github.io/<NAME_OF_REPO>`, so for every repo the given exception is true. Which results in a broken build…

### 🖥️ Reproduction in StackBlitz (if reporting incorrect content or code samples)

I tested it in https://github.com/tordans/berlin-bikenetwork-monitoring/commit/349a5c7f4c515da80da3aa840c7b5f1ffc93b050

**Comment by ElianCodes** [comment]
Hey! Good catch! Do you want to make a PR for this?

**Comment by delucis** [comment]
Ah, I think there could be a misunderstanding here. GitHub special cases a repository at `https://github.com/USERNAME/USERNAME.github.io` serving it at `USERNAME.github.io` with no subpath.

So when we say you can omit `base` when “Your repository is named `<YOUR_USERNAME>.github.io`.” I think that should be true, but maybe isn’t clear enough exactly what that means?

**Comment by tordans** [comment]
@delucis your are right. I was wondering if that is what was meant, but right now it matches all github pages, not just the User or organization site.

Maybe something like this:

>Don’t set a base parameter if your page is served from the root folder:
>-Your repository `https://github.com/<USERNAME>/<USERNAME>.github.io`
>-…

The part about the root folder would be a good hint.
And using the repo github path instead of the github pages URL makes it clear. This is taken from https://pages.github.com/

**Comment by sarah11918** [comment]
If that extra clarification would be helpful, then docs would accept a PR to show that!
