### ISSUE TITLE
⚠️ Issue with apostrophe following docs.astro.build/en/tutorial/2-pages/2/

### ISSUE THREAD

**Issue by king8fisher** [withastro/docs#4575]
Markdown transformer apparently changes `'` to `’` in cases like "I've accomplished", but without proper `<meta charset="utf-8">`, these characters look like garbage in the browser.

**Comment by itsmatteomanf** [comment]
I see the `'` character everywhere and, in the live site, see a normal `<meta charset="utf-8">`.

https://github.com/withastro/docs/blob/0b2ebea9fa080c30bd1b0308326fbc025b4e9073/src/content/docs/en/tutorial/2-pages/2.mdx#L60

https://github.com/withastro/docs/blob/0b2ebea9fa080c30bd1b0308326fbc025b4e9073/src/components/HeadCommon.astro#L7

**Comment by king8fisher** [comment]
I mean if you follow and run the example, that's where the transformation happens.

**Comment by sarah11918** [comment]
Thank you for this. We have updated the tutorial instructions to warn that when you create your first Markdown page, before creating a Markdown layout, this page will not yet be formatted.

The intention at this point in the tutorial is only to demonstrate that a route is created, but the rendering will not be fully proper until later in the tutorial when layouts are introduced. (You do not have the option of defining meta tags in a Markdown page, so this route cannot yet take advantage of an Astro layout component until one is created and specified on the page.)

**Comment by king8fisher** [comment]
I agree the warning with explanation is enough. Thank you!
