### ISSUE TITLE
'sanitize-html' need more actions than the tutorial of adding RSS

### ISSUE THREAD

**Issue by LeenHawk** [withastro/docs#4582]
### 📋 Explain your issue

In the [tutorial](https://docs.astro.build/en/guides/rss) of adding RSS, it use `sanitize-html` but it show:
```shell
[vite]: Rollup failed to resolve import "sanitize-html" from "C:/Users/leen/Documents/workspace/astro-fafabear/src/pages/rss.xml.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
```
I have tried configure the `astro.config.mjs`:
```
export default defineConfig({
  site: 'https://example.com',
  .....
  build: {
    rollupOptions: {
      external: ["sanitize-html"]
    }
  }
});
```
But it doesn't work. Could someone give a help and fix the doc?

**Comment by sarah11918** [comment]
Hi @LeenHawk! We have work in progress to update the tutorial RSS example for v3! In the mean time, you can consult the updated docs page on adding RSS to an Astro site for more up-to-date information!  🙌 

If you encounter more problems with your own code, then please ask in our Discord https://astro.build/chat which is where people will be happy to help you with your project! We cannot answer support questions here. These issues are only for working on the documentation site. But, we have support people in Discord ready to help answer questions and troubleshoot code with you! 🚀
