### ISSUE TITLE
Manual install guide of Tailwind doesn't explain how to set up Tailwind's config for Astro

### ISSUE THREAD

**Issue by Princesseuh** [withastro/docs#4587]
### 📚 Subject area/topic

Tailwind Integration

### 📋 Page(s) affected (or suggested, for new content)

https://docs.astro.build/en/guides/integrations-guide/tailwind/#manual-install

### 📋 General description or bullet points (if proposing new content)

There should be a paragraph explaining that you need a Tailwind config with at least `content: ["./src/**/*.{astro,js,ts,tsx,md,mdx}"],` in it. FWIW, Tailwind will warn you that your `content` is empty if you don't have a config, but it's not obvious what you should do to fix it

### 🖥️ Reproduction in StackBlitz (if reporting incorrect content or code samples)

N/A

**Comment by dreyfus92** [comment]
@sarah11918 I would like to work on this issue 💼

**Comment by ElianCodes** [comment]
Hey @dreyfus92! Feel free to open up a PR! I'll assign this issue to you!

**Comment by Kritika30032002** [comment]
I would like to work on this issue

**Comment by sarah11918** [comment]
Indeed! This has been written thanks to some wonderful contributors, so we can close this issue! 🚀
