### ISSUE TITLE
`<Tabs client:visible>` in Docs code doesn't sync tabs anymore

### ISSUE THREAD

**Issue by ElianCodes** [withastro/docs#4588]
### 📝 Issue Description

We had to change `<Tabs client:visible>` to `<Tabs client:idle>` in the docs code {Astro v3 PR](https://github.com/withastro/docs/pull/4461).

This is simply an issue to track that we changed it and probably need to change it back sometime in the future!

### 📋 On which page(s) it occurs

all pages where the `<Tabs>` Preact component is used

### 🤔 Expected Behavior

🤷‍♂️

### 👀 Current Behavior

🙅‍♂️

### 🖥️ Browser

All of 'em

**Comment by dreyfus92** [comment]
Hey @ElianCodes I was testing the website on my end and tabs seem to be syncing for me on chrome & safari. I'm curious about which browser are you using.

**Comment by sarah11918** [comment]
@ElianCodes can you confirm whether this is still something to be concerned about with the migration to Starlight?

**Comment by TheOtterlord** [comment]
This is fixed in the Starlight migration with the replacement of the Preact component

**Comment by ElianCodes** [comment]
Right! I kinda forgot about this! Thanks @TheOtterlord !
