### ISSUE TITLE
Light mode on Docs site is flashing black for a brief moment on page navigation

### ISSUE THREAD

**Issue by ElianCodes** [withastro/docs#4599]
### 📝 Issue Description

When the docs site is set on light mode, the page briefly flashes black before entering light mode.

### 📋 On which page(s) it occurs

All pages using light mode.

### 🤔 Expected Behavior

No flashing

### 👀 Current Behavior

it does flash

### 🖥️ Browser

only tested in Chromium based browsers

### 📄 Additional Information

Happens since Astro v3 upgrade

**Comment by jacobthesheep** [comment]
Yeah, it occurs even on Safari and Firefox
