### ISSUE TITLE
Inconsistent sub headings in SSR adapters

### ISSUE THREAD

**Issue by sasoria** [withastro/docs#4629]
### 📚 Subject area/topic

SSR adapters

### 📋 Page(s) affected (or suggested, for new content)

https://docs.astro.build/en/guides/integrations-guide/node/

### 📋 General description or bullet points (if proposing new content)

The integrations guide for Node seems to have a sub heading that is inconsistent with the other adapters.

Most adapters seem to use the following pattern, _Why Astro [adapter]_, i.e:

> Why Astro Deno
> Why Astro Netlify

The Node adapter uses this:
> Why @astrojs/node

Do we want to change this in order to introduce consistency or leave it as it is?

### 🖥️ Reproduction in StackBlitz (if reporting incorrect content or code samples)

...

**Comment by sarah11918** [comment]
@sasoria Sure! Would you like to make a PR for this, or anyone? Adding the Help Wanted tag, and anyone is welcome to change `@astrojs/node` to `Astro Node.js` 🙌

**Comment by dreyfus92** [comment]
I would like to work on this @sarah11918

**Comment by sarah11918** [comment]
Amazing @dreyfus92 :rocket:

**Comment by dreyfus92** [comment]
@sarah11918 there are some integrations guides that just have `Why Astro Sitemap` without the question mark, should I add the question mark to all of them or just fix this issue?

**Comment by sarah11918** [comment]
@dreyfus92 I'll approve the fix of this issue as is, but in general, yes I'd say question marks for all!

**Comment by jacobthesheep** [comment]
@sarah11918 is this issue resolved?

**Comment by sarah11918** [comment]
Closed as done!
