### ISSUE TITLE
Need of a Versioning of old documentation

### ISSUE THREAD

**Issue by antoninadert** [withastro/docs#4649]
### 📋 Explain your issue

I need to access the old documentation since I didn't migrate to v3 yet. 

Is this an option ?

**Comment by sarah11918** [comment]
Hi @antoninadert ! We do not maintain on our live, published site information for older versions as that code for earlier versions will be unsupported.

But, you can use a deploy preview from any older PR before the site was upgraded to v3 to navigate an older version of the site. Here is one from just before the site was upgraded: https://deploy-preview-4250--astro-docs-2.netlify.app/en/getting-started/ 🙌
