### ISSUE TITLE
How to skip prompts during install

### ISSUE THREAD

**Issue by totalhack** [withastro/docs#4651]
### 📚 Subject area/topic

Install

### 📋 Page(s) affected (or suggested, for new content)

https://docs.astro.build/en/install/auto/

### 📋 General description or bullet points (if proposing new content)

Note: it's unclear to me if this is a documentation issue or a feature issue so I decided to file it here assuming there is already a way to do this and I just can't find it in the docs.

There doesn't appear to be a way to utilize `npm create astro` but have it just use all recommended defaults and not prompt for any information. Using something like `npm create astro newdir -- --skip-houston` still prompts for information. Passing `--yes` also has no effect, seems like that should be the one to get it done. Am I misunderstanding the docs or should this be a bug/feature request?

```
 create-astro   v4.0.2 Scaffold Astro projects.

create-astro [dir] [...flags]

             --help (-h)  See all available flags.
       --template <name>  Specify your template.
--install / --no-install  Install dependencies (or not).
        --git / --no-git  Initialize git repo (or not).
              --yes (-y)  Skip all prompt by accepting defaults.
               --no (-n)  Skip all prompt by declining defaults.
               --dry-run  Walk through steps without executing.
          --skip-houston  Skip Houston animation.
                   --ref  Choose astro branch (default: latest).
                 --fancy  Enable full unicode support for Windows.
   --typescript <option>  TypeScript option: strict | strictest | relaxed.
```

### 🖥️ Reproduction in StackBlitz (if reporting incorrect content or code samples)

N/A

**Comment by jacobthesheep** [comment]
This would be new feature but I believe there is a way to do this with CLI commands depending on what shell you're using.

**Comment by totalhack** [comment]
@jacobthesheep i think the `--yes` option is what is supposed to get it done, but it doesn't work. I'll leave it up to you whether you want to close this or if you agree some more documentation around this would be useful, as it seems to only be documented in the `--help` output of the command I think. I'll open a bug on the main astro repo for `--yes` not functioning as expected.

**Comment by jacobthesheep** [comment]
Well I'm not sure where you got 
```
 create-astro   v4.0.2 Scaffold Astro projects.

create-astro [dir] [...flags]

             --help (-h)  See all available flags.
       --template <name>  Specify your template.
--install / --no-install  Install dependencies (or not).
        --git / --no-git  Initialize git repo (or not).
              --yes (-y)  Skip all prompt by accepting defaults.
               --no (-n)  Skip all prompt by declining defaults.
               --dry-run  Walk through steps without executing.
          --skip-houston  Skip Houston animation.
                   --ref  Choose astro branch (default: latest).
                 --fancy  Enable full unicode support for Windows.
   --typescript <option>  TypeScript option: strict | strictest | relaxed.
```
but these are the [official cli commands](https://docs.astro.build/en/reference/cli-reference/).

**Comment by totalhack** [comment]
It's the `--help` output of the `npm create astro` command -- think its a different tool and set of commands than what you referenced.

**Comment by sarah11918** [comment]
Hi @totalhack! You are reading correct, that is what the `yes` flag is supposed to do! So, if you'd like to make an issue on the `/withastro/astro` repo then you can file a bug report there for unexpected behaviour. Thanks!

**Comment by totalhack** [comment]
I did, seems split on whether they think this is intended behavior. At any rate IMO the install docs could use an example of how to accept all defaults.
