### ISSUE TITLE
Formatting is not working

### ISSUE THREAD

**Issue by ragokan** [withastro/docs#472]
Hello, I am using *Prettier* in my VSCode editor. Sadly formatting is not working.

![image](https://user-images.githubusercontent.com/63511519/167248501-6a45a200-4816-48b7-abb6-da52f811cf51.png)
Lets say I did it look like this, whenever I try to format, it does do nothing.

`"[astro]": { "editor.defaultFormatter": "astro-build.astro-vscode" }` I also added this to the config.json which did affect nothing. I also tried prettier astro plugin which also did not work.

**Comment by ragokan** [comment]
![image](https://user-images.githubusercontent.com/63511519/167249020-e404a40f-431e-404d-b09f-a99ab1826b3c.png)
This is what I get when I say format manually

**Comment by delucis** [comment]
Hi @ragokan 👋 

Looks like the Prettier plugin isn’t being picked up by VS Code for some reason. This repo is specifically for the Astro documentation website and it is on our to-do list to document setting up Prettier (#425).

You might want to see if there are any issues on the prettier plugin repo that can help: https://github.com/withastro/prettier-plugin-astro

I know for sure you need a Prettier config file. Here’s an example of one: https://github.com/astro-community/astro-embed/blob/3320f68c0ff30327a2c303024993c54ad6a3d36e/.prettierrc.cjs

OK if I close this issue for now as we’re already tracking improved documentation in #425. If necessary, you could open an issue on the plugin repo.

**Comment by ragokan** [comment]
Hey

> Hi @ragokan 👋
> 
> Looks like the Prettier plugin isn’t being picked up by VS Code for some reason. This repo is specifically for the Astro documentation website and it is on our to-do list to document setting up Prettier (#425).
> 
> You might want to see if there are any issues on the prettier plugin repo that can help: https://github.com/withastro/prettier-plugin-astro
> 
> I know for sure you need a Prettier config file. Here’s an example of one: https://github.com/astro-community/astro-embed/blob/3320f68c0ff30327a2c303024993c54ad6a3d36e/.prettierrc.cjs
> 
> OK if I close this issue for now as we’re already tracking improved documentation in #425? If necessary, you could open an issue on the plugin repo.

Hello, thank you for your fast reply. It did work when I follow your config file but only when I switched from pnpm to npm. Probably it can not detect pnpm directory. I will search about it, have a great day!

**Comment by delucis** [comment]
Oh, yeah, I think difficulties with `pnpm` are one of the most common problems. I think this is the most relevant issue: https://github.com/withastro/prettier-plugin-astro/issues/97
