### ISSUE TITLE
Nested CSS was detected, but CSS nesting has not been configured correctly. 

### ISSUE THREAD

**Issue by xexiu** [withastro/docs#4746]
### 📚 Subject area/topic

PostCSS with Tailwind Plugin

### 📋 Page(s) affected (or suggested, for new content)

https://docs.astro.build/es/guides/styling/#postcss

### 📋 General description or bullet points (if proposing new content)

Hello,

After following the steps from the Docs, I get the error on the console (check screenshots).
Seems that somehow PostCSS config has some conflicts with Tailwind, following the Astro Doc.

- MacOSX Ventura 13.5.1
- VSCode
- "astro": "^3.1.0",
- package.json:

```
{
  "name": "sm_astro",
  "type": "module",
  "version": "0.0.1",
  "browserslist": [
    "defaults"
  ],
  "scripts": {
    "dev": "bun --bun astro dev",
    "start": "astro dev",
    "build": "astro build",
    "preview": "astro preview",
    "astro": "astro"
  },
  "dependencies": {
    "@astrojs/partytown": "^2.0.0",
    "@astrojs/sitemap": "^3.0.0",
    "@astrojs/tailwind": "^5.0.0",
    "@typescript-eslint/parser": "^6.7.0",
    "astro": "^3.1.0",
    "astro-icon": "^0.8.1",
    "autoprefixer": "^10.4.15",
    "eslint-plugin-astro": "^0.29.0",
    "eslint-plugin-jsx-a11y": "^6.7.1",
    "tailwindcss": "^3.3.3"
  },
  "devDependencies": {
    "bun-types": "^1.0.2",
    "eslint": "^8.49.0"
  }
}
```

Changed from:

```js
const autoprefixer = require('autoprefixer');

module.exports = {
   plugins: [
      autoprefixer(),
   ]
};
```

To:

```js
module.exports = {
   plugins: {
      'tailwindcss/nesting': {}, <--- Needs this
      tailwindcss: {},
      autoprefixer: {},
   }
};
```

After that, the error from the console goes away :).

![Captura de pantalla 2023-09-19 a las 7 16 43](https://github.com/withastro/docs/assets/7423607/39af6984-ccc1-471b-9cc4-82caa0aafd90)
![Captura de pantalla 2023-09-19 a las 8 10 04](https://github.com/withastro/docs/assets/7423607/12cc31fc-7230-457b-8075-644922f7ccfe)

### 🖥️ Reproduction in StackBlitz (if reporting incorrect content or code samples)

https://stackblitz.com/edit/github-elgzfe-pwwt3m?file=src%2Flayouts%2FLayout.astro,postcss.config.cjs,package.json

**Comment by piratey7007** [comment]
Hey there @xexiu. After looking at this issue and the documentation, my understanding is that Astro does not enable the `tailwindcss/nesting` plugin by default. The TailwindCSS documentation covers this [here](https://tailwindcss.com/docs/using-with-preprocessors#nesting), but you can use the other syntax as well like so:

```cjs
const autoprefixer = require('autoprefixer');
const tailwindNesting = require('tailwindcss/nesting');

module.exports = {
  plugins: [tailwindNesting(), autoprefixer()],
};
```

The Vite/Tailwind error message also seems fairly user-friendly, at least from my point of view, explaining the source of the error, how to fix it, and a corresponding link to documentation.

```md
[vite:css] Nested CSS was detected, but CSS nesting has not been configured correctly.
Please enable a CSS nesting plugin *before* Tailwind in your configuration. 
See how here: https://tailwindcss.ocm/docs/using-with-preprocessors#nesting
```

If there's anything that I may have missed, I'm open to discussion about it, these are just my thoughts.

And I guess I'd more like to open this up to others to see if this implementation detail is something out of the norm for either Vite or Astro, or something that should be covered more in depth in the Astro documentation specifically (either via a link or a small section).

**Comment by sarah11918** [comment]
Closing this as not something for us to document when an error message with explanation exists for this case.
