### ISSUE TITLE
⚠️ Issue

### ISSUE THREAD

**Issue by amaimus** [withastro/docs#4752]
![image](https://github.com/withastro/docs/assets/35699916/4288fd54-e035-4b79-b918-cb67367b0c4b)
 In this tutorial
 
https://docs.astro.build/en/recipes/i18n/#hide-default-language-in-the-url
In section 4, useTranslatedPath should be imported

**Comment by dreyfus92** [comment]
Hello @amaimus, nice catch! Would you be willing to open a PR to fix this issue?

**Comment by amaimus** [comment]
Sure!

**Comment by amaimus** [comment]
Done! https://github.com/withastro/docs/pull/4771 
Let me know if i did something wrong in the process.

Pd: thank you for encouraging me to make my first open source project contribution 🚀

**Comment by sarah11918** [comment]
Closed by PR #4771 :tada:
