### ISSUE TITLE
Docs on How to pass parameter when calling endpoints from the server

### ISSUE THREAD

**Issue by agungsb** [withastro/docs#4767]
## INTRO ##

Hi,

I'm new to Astro and I'm using it to build my latest website. I'm so in love with this awesome framework. While the docs is so useful, I stumbled upon an issue. A particular example in the docs didn't work as expected. I did find the workaround, but I don't think it's the elegant solution.

## CASE ##

I have a case like mentioned in https://docs.astro.build/en/recipes/call-endpoints/

The example didn't even work:

```
---
import { GET } from './api/hello.ts'

let response = await GET(Astro)
const data = await response.json()
---

<h1>{data.greeting} world!</h1>
```

Typescript complains:

```
Argument of type 'Readonly<AstroGlobal<Record<string, any>, AstroComponentFactory, Record<string, string | undefined>>>' is not assignable to parameter of type 'APIContext<Record<string, any>, Record<string, string | undefined>>'.
  Property 'ResponseWithEncoding' is missing in type 'Readonly<AstroGlobal<Record<string, any>, AstroComponentFactory, Record<string, string | undefined>>>' but required in type 'APIContext<Record<string, any>, Record<string, string | undefined>>'.ts(2345)
  ```
  
 I played around and did the following workaround:
 
 ```
 import { GET } from './api/hello.ts'

let response = await GET(Astro as any)
const data = await response.json()
---

<h1>{data.greeting} world!</h1>
```

Notice that I define `any` type. It worked fine. But then I wanted to pass a 'custom parameter' to the GET:

```
import { GET } from './api/hello.ts'

let response = await GET({
    ...Astro,
    params: { id: '1' },
} as any)
const data = await response.json()
---

<h1>{data.greeting} world!</h1>
```

Above codes triggered error when building:

```
ClientAddressNotAvailable: `Astro.clientAddress` is not available in the `@astrojs/node` adapter. File an issue with the adapter to add support.
```

I didn't want to remove or change the adapter. So I tried to omit `clientAddress` from `Astro`:

```
import { GET } from './api/hello.ts'
import { omit } from 'lodash';

let response = await GET({
    ...omit(Astro, ['clientAddress']),
    params: { id: '1' },
} as any)
const data = await response.json()
---

<h1>{data.greeting} world!</h1>
```

But the same error still occurred. I tried to find another way around and surprisingly found that the following code works:

```
import { GET } from './api/hello.ts'

let response = await GET({
    params: { id: '1' },
} as any)
const data = await response.json()
---

<h1>{data.greeting} world!</h1>
```

I believe that the usage of the `any` type is an ugly workaround because if I use `APIContext<Props>` it would make Typescript complain:

```
Conversion of type '{ params: { code: string; }; }' to type 'APIContext<Props, Record<string, string | undefined>>' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  Type '{ params: { code: string; }; }' is missing the following properties from type 'APIContext<Props, Record<string, string | undefined>>': site, generator, url, props, and 6 more.
  ```
  
I'm thinking about making the parameter to be optional. Because currently, it would be troublesome to always implement all properties in the argument:

```
import { GET } from './api/hello.ts'

let response = await GET({
    params: { id: '1' },
    site: Astro.site,
    generator: Astro.generator,
    url: Astro.url,
    props: Astro.props,
    redirect: Astro.redirect,
    locals: Astro.locals,
    ResponseWithEncoding: {
      error: function (): Response {
        throw new Error("Function not implemented.");
      },
      redirect: function (
        url: string | URL,
        status?: number | undefined,
      ): Response {
        throw new Error("Function not implemented.");
      },
    },
    clientAddress: "",
    cookies: Astro.cookies
    request: Astro.request,
} as any)
const data = await response.json()
---

<h1>{data.greeting} world!</h1>
```

Plus, the Typescript complains about `ResponseWithEncoding` property:

```
Type '{ error: () => Response; redirect: (url: string | URL, status?: number | undefined) => Response; }' is not assignable to type '{ new (body: BodyInit | null | undefined, init: ResponseInit | undefined, encoding?: BufferEncoding | undefined): { readonly headers: Headers; ... 13 more ...; text(): Promise<...>; }; error(): Response; redirect(url: string | URL, status?: number | undefined): Response; }'.
  Type '{ error: () => Response; redirect: (url: string | URL, status?: number | undefined) => Response; }' provides no match for the signature 'new (body: BodyInit | null | undefined, init: ResponseInit | undefined, encoding?: BufferEncoding | undefined): { readonly headers: Headers; ... 13 more ...; text(): Promise<...>; }'
```

I don't know if you can, at least, make `ResponseWithEncoding` to be optional. I edited `node_modules/astro/dist/@types/astro.d.ts` file and made that property to be optional, and it worked. But I don't know the side effect of that change to the entire framework.
  
 ## THOUGHTS ##
  Can you please add a proper solution to my case in your docs? I believe this is a simple case that would be used often in the real application.
  
  Thank you.

**Comment by agungsb** [comment]
I found a little bit 'better' workaround.

```
---
import { GET } from './api/hello.ts'

const context = createContext({
  request: Astro.request,
  params: { code: DEFAULT_COUNTRY_CODE },
//  params: Astro.params,
});

let response = await GET(context)
const data = await response.json()
---

<h1>{data.greeting} world!</h1>
```

Do you think it's the proper solution?

**Comment by sarah11918** [comment]
Thank you for this comment! I will ask @delucis to triage this and comment on your proposal!

**Comment by TheOtterlord** [comment]
Thanks for the workaround!

[Astro 4.0 removes the `ResponseWithEncoding` type](https://docs.astro.build/en/guides/upgrade-to/v4/#removed-returning-simple-objects-from-endpoints) causing this issue. After upgrading to 4.0, the workaround should no longer be needed :tada:

**Comment by EddyVinck** [comment]
FYI I had the old workaround in my code

```
let response = await GET({
      ...Astro,
      params: { id: Astro.params.id },
    });
```

And this was causing some weird isues. I logged the `Astro` object and noticed the parameters weren't aligned with my `[id].ts` file name, so I had to rename that.

The result was me getting this error on both [Netlify](https://github.com/withastro/adapters/issues/142) and Vercel:

```
ClientAddressNotAvailable: `Astro.clientAddress` is not available in the `@astrojs/netlify` adapter.
```

Here is my commit that fixed it:
https://github.com/EddyVinck/astro-engineering-blog/commit/747b2ca0eca0fd7efe3abd10324bb2aa90f465ae
