### ISSUE TITLE
Remove `h` imports from preact snippets

### ISSUE THREAD

**Issue by TheOtterlord** [withastro/docs#4772]
### 📚 Subject area/topic

Preact

### 📋 Page(s) affected (or suggested, for new content)

https://docs.astro.build/en/tutorial/6-islands/1/#include-a-preact-greeting-banner

### 📋 General description or bullet points (if proposing new content)

Confirm that we can remove `h` from preact code snippets, and make a PR to remove them

### 🖥️ Reproduction in StackBlitz (if reporting incorrect content or code samples)

N/A

**Comment by ElianCodes** [comment]
I think they're mostly removed by now!
