### ISSUE TITLE
Typings cannot be resolved for `markdown.rehypePlugins` in `astro.config.ts` file

### ISSUE THREAD

**Issue by idlist** [withastro/docs#4779]
### Astro Info

```block
Astro                    v3.0.10
Node                     v20.5.1
System                   Windows (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/vue
                         @astrojs/mdx
                         @astrojs/sitemap
```

### Describe the Bug

I'm trying to follow the [Add icons to external links](https://docs.astro.build/en/recipes/external-links/) recipe, and I ran into this problem:

![image](https://github.com/withastro/astro/assets/29368226/a5fe1d8f-ad5c-428b-b423-b7f6ec989eb7)

The error says:

![image](https://github.com/withastro/astro/assets/29368226/0952ae63-36ca-4cb9-bd08-19ca1f6b3a62)

a workaround would be (or actually it might be the only practical solution for now):

![image](https://github.com/withastro/astro/assets/29368226/55772d2d-d216-40e2-96f5-98b25fb14d83)

### What's the expected result?

No errors are reported.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-pxea2u?file=astro.config.ts&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by kevinzunigacuellar** [comment]
It looks like the file might be missing a title. Additionally, there seems to be a conflict between the file name and the code block extension. The text references a .mjs document, but the code block is marked as TypeScript.

**Comment by idlist** [comment]
I don't know why but updating to newer Astro version (still in v3) fixes this issue.
And it seems like Astro v4 does not have this issue, so I'm closing this issue for now.
