### ISSUE TITLE
New major version of unified. Should we mention that in the plugins section until it incorporated into Astro?

### ISSUE THREAD

**Issue by kelvinsjk** [withastro/docs#4788]
### 📋 Explain your issue

I was running into some issues bugs with markdown remark/rehype plugins (in particular remark-math that was crashing on trying to render displayed equations).

After trying to debug the issue I realized the unified/remark/rehype ecosystem just dropped a new major version (v11) a few days ago, while the Astro internals are running v10 and their associated plugins. When I reinstalled a older version of remark-math (dropping from v6 to v5) things worked as expected.

So I was wondering if this is a PSA we might want to add to the [plugins section](https://docs.astro.build/en/guides/markdown-content/#markdown-plugins) of the docs.

Pros:
- users who may be encountering bugs via markdown plugins are alerted to this issue in the docs

Cons: 
- explanation might be lengthy and confusing because of a lack of a common version  numbering system in the plugins so it may be hard to point someone to exactly which version they should install
- will need to update the documentation once unified v11 gets incorporated into Astro

**Comment by sarah11918** [comment]
Hi there! We don't typically document workarounds in docs, and we will be releasing Astro 4 shortly which will be updating internals, so thank you for bringing this to our attention, but as you wrote, this isn't something we'll document vs just update in core itself!  🙌
