### ISSUE TITLE
⚠️ Issue Doble quotation marks in spanish lesson.

### ISSUE THREAD

**Issue by MiguelDecode** [withastro/docs#4800]
Inside the tutorial area, part 5 , lesson "Create a blog post archive". When you give us the code for the post-4.md.
In spanish version you give a code with a problem in the doble quotation marks of property alt of the image.
`image:
  url: "https://docs.astro.build/default-og-image.png"
  alt: "La palabra "astro" contra una ilustración de planetas y estrellas."`
The word astro is surrounded by doble quotation marks and broke the sentence. This generate a problem when i try to display links in the blog page and with dynamic tags after.

I only change this doble quotation marks for single like this and all works perfectly.
`image:
  url: "https://docs.astro.build/default-og-image.png"
  alt: "La palabra 'astro' contra una ilustración de planetas y estrellas."`

**Comment by Waxer59** [comment]
Hello! In this case, it is a typo. If you feel like it, you can submit a PR to correct it. If you open a PR, be sure to link this issue in the description of the PR. 🤠

**Comment by ElianCodes** [comment]
Since #4877 has been merged, I think this issue is safe to close now!

**Comment by MiguelDecode** [comment]
Thanks to all for the help. I hope to collaborate again in the future.
