### ISSUE TITLE
Multiple Initialization of Firebase App Without Unique Name

### ISSUE THREAD

**Issue by davidochoadev** [withastro/docs#4803]
### 📚 Subject area/topic

Firebase & Astro

### 📋 Page(s) affected (or suggested, for new content)

https://docs.astro.build/en/guides/backend/google-firebase/#installing-dependencies

### 📋 General description or bullet points (if proposing new content)

I've encountered a small issue with Astro while I was recreating the guide for implementing [Firebase with Astro](https://docs.astro.build/en/guides/backend/google-firebase/#installing-dependencies). I noticed a small problem regarding the `initializeApp` on the `export const app`inside `server.ts`. I tried to check if the same issue arose in client.ts as well, but it seems not. - 
- The problem is as follows:
<img width="1256" alt="Schermata 2023-09-25 alle 01 21 47" src="https://github.com/withastro/docs/assets/105085603/96797a4d-f994-4319-a025-b8b67018dcf4">

### 🖥️ Reproduction in StackBlitz (if reporting incorrect content or code samples)

I think it's appropriate to update the documentation with the most suitable approach to avoid this error. At the moment, i solved it by simply adding a check, this is my server.ts:

```javascript
import type { ServiceAccount } from "firebase-admin";
import { initializeApp, cert, getApps } from "firebase-admin/app";

const alreadyCreatedApps = getApps();
const serviceAccount = {
  type: "service_account",
  project_id: import.meta.env.FIREBASE_PROJECT_ID,
  private_key_id: import.meta.env.FIREBASE_PRIVATE_KEY_ID,
  private_key: import.meta.env.FIREBASE_PRIVATE_KEY,
  client_email: import.meta.env.FIREBASE_CLIENT_EMAIL,
  client_id: import.meta.env.FIREBASE_CLIENT_ID,
  auth_uri: import.meta.env.FIREBASE_AUTH_URI,
  token_uri: import.meta.env.FIREBASE_TOKEN_URI,
  auth_provider_x509_cert_url: import.meta.env.FIREBASE_AUTH_CERT_URL,
  client_x509_cert_url: import.meta.env.FIREBASE_CLIENT_CERT_URL,
};

export const app = alreadyCreatedApps.length === 0
? initializeApp({
  credential: cert(serviceAccount as ServiceAccount),
},"astro-firebase-vercel"):alreadyCreatedApps[0];
```

**Comment by VoxelMC** [comment]
Hello, I can probably do this!
I had the exact same problem when building and reloading my Firebase+Astro project.

How does this look?

```ts
import type { ServiceAccount } from "firebase-admin";
import { initializeApp, cert, getApps } from "firebase-admin/app";

const activeApps = getApps();
const serviceAccount = {
  type: "service_account",
  project_id: import.meta.env.FIREBASE_PROJECT_ID,
  private_key_id: import.meta.env.FIREBASE_PRIVATE_KEY_ID,
  private_key: import.meta.env.FIREBASE_PRIVATE_KEY,
  client_email: import.meta.env.FIREBASE_CLIENT_EMAIL,
  client_id: import.meta.env.FIREBASE_CLIENT_ID,
  auth_uri: import.meta.env.FIREBASE_AUTH_URI,
  token_uri: import.meta.env.FIREBASE_TOKEN_URI,
  auth_provider_x509_cert_url: import.meta.env.FIREBASE_AUTH_CERT_URL,
  client_x509_cert_url: import.meta.env.FIREBASE_CLIENT_CERT_URL,
};

export const app = activeApps.length === 0 ? initializeApp({
  credential: cert(serviceAccount as ServiceAccount),
}) : activeApps[0];
```

**Comment by davidochoadev** [comment]
> Hello, I can probably do this!
> I had the exact same problem when building and reloading my Firebase+Astro project.
> 
> How does this look?
> 
> ```ts
> import type { ServiceAccount } from "firebase-admin";
> import { initializeApp, cert, getApps } from "firebase-admin/app";
> 
> const activeApps = getApps();
> const serviceAccount = {
>   type: "service_account",
>   project_id: import.meta.env.FIREBASE_PROJECT_ID,
>   private_key_id: import.meta.env.FIREBASE_PRIVATE_KEY_ID,
>   private_key: import.meta.env.FIREBASE_PRIVATE_KEY,
>   client_email: import.meta.env.FIREBASE_CLIENT_EMAIL,
>   client_id: import.meta.env.FIREBASE_CLIENT_ID,
>   auth_uri: import.meta.env.FIREBASE_AUTH_URI,
>   token_uri: import.meta.env.FIREBASE_TOKEN_URI,
>   auth_provider_x509_cert_url: import.meta.env.FIREBASE_AUTH_CERT_URL,
>   client_x509_cert_url: import.meta.env.FIREBASE_CLIENT_CERT_URL,
> };
> 
> export const app = activeApps.length === 0 ? initializeApp({
>   credential: cert(serviceAccount as ServiceAccount),
> }) : activeApps[0];
> ```

@VoxelMC  Yes, in the end, I think it's the most optimal solution. I was checking if there were any best practices from Firebase to avoid the issue, but at the moment, I can't find anything.
