### ISSUE TITLE
RIAPI implementations

### ISSUE THREAD

**Issue by rafalkrupinski** [withastro/docs#4806]
### 📚 Subject area/topic

Hard to find RIAPI implementations

### 📋 Page(s) affected (or suggested, for new content)

https://docs.astro.build/en/reference/image-service-reference/#what-is-an-image-service

### 📋 General description or bullet points (if proposing new content)

The section about external image services mentions two commercial image services "or any [RIAPI](https://github.com/riapi/riapi)-compliant server".

The linked project (RIAPI) hasn't been updated since 2013, doesn't link to any implementations, it's websites domain has expired, its google group is empty, and generally the Internet hasn't heard about it.

Would it be possible to link some open-source implementations or provide a better source of links?

### 🖥️ Reproduction in StackBlitz (if reporting incorrect content or code samples)

this section is both conditional and required...

**Comment by lilith** [comment]
That's my bad, ImageResizer (since 2009) and Imageflow (since 2016) have been the reference implementations, and the spec is pretty loosely followed by other tools. I've updated it a bit https://github.com/riapi/riapi/blob/master/readme.md

**Comment by sarah11918** [comment]
Closed as not something to change in documentation! 🙌

**Comment by rafalkrupinski** [comment]
What would you change instead? The documentation refers to a specification without a list of implementations and is not searchable. That's not helpful.
