### ISSUE TITLE
Warn users that an adapter may overwrite the build.format config

### ISSUE THREAD

**Issue by th0rgall** [withastro/docs#4807]
### 📝 Issue Description

The [Vercel Static Adapter](https://github.com/withastro/astro/tree/211bfe3b00c2e77e3647a6e1f1644ddc1ab7fda8/packages/integrations/vercel) overwrites the user-supplied Astro config with `format: directory` (as well as `redirects: false`).
```js
updateConfig({
	outDir,
	build: {
		format: 'directory',
		redirects: false,
	},
```
https://github.com/withastro/astro/blob/211bfe3b00c2e77e3647a6e1f1644ddc1ab7fda8/packages/integrations/vercel/src/static/adapter.ts#L87-L92

The dev server works fine with the `'file'` format, but Vercel's adapter doesn't. This thus leads to an unexpected divergence between the dev & production environments.

I'm not sure if `format: 'directory',` is forced by the adapter because of a technical limitation that prevents `format: 'file'` from working, but assuming it is, the docs could be clearer.

### 📋 On which page(s) it occurs

https://docs.astro.build/en/reference/configuration-reference/#buildformat

Also https://docs.astro.build/en/reference/configuration-reference/#buildredirects (but the line `This option is mostly meant to be used by adapters` there already serves as a kind of warning).

### 🤔 Expected Behavior

Ideally, https://docs.astro.build/en/reference/configuration-reference/#buildformat would have warned me that an adapter may overwrite this setting (I'm not sure if Vercel Static is the only adapter that does this).

### 👀 Current Behavior

https://docs.astro.build/en/reference/configuration-reference/#buildformat is the documentation I looked up first. There is no warning there that adapters can influence these settings.

The [adapter readme](https://github.com/withastro/astro/tree/main/packages/integrations/vercel) mentions:
> This will install the adapter and make the appropriate changes to your astro.config.mjs file in one step [..]

However, I only found that while writing this report.

### 🖥️ Browser

Chrome 116.0.5845.187

### 📄 Additional Information

As a precedent, https://docs.astro.build/en/reference/configuration-reference/#buildserverentry mentions:

> Specifies the file name of the server entrypoint when building to SSR. This entrypoint is usually dependent on which host you are deploying to and **will be set by your adapter for you.**

**Comment by sarah11918** [comment]
Thanks for this comment! I have marked this for exploration with our platform devs to confirm whether this is in fact expected behaviour that should be documented, or whether this might be a bug and this is not in fact supposed to happen. We'll need to explore before we know whether this is something to document!

**Comment by matthewp** [comment]
An adapter, or any integration for that matter, can override any particular config. That's often a primary purpose of an integration, to bundle a bunch of configuration changes together rather than doing them all individually. So if I was going to document this, that's what I would document.

As far as what the Vercel adapter is doing in this case, I'm not sure if it was an intentional decision based on a limitation or if was incidental. If some one is willing to try making the change in a PR and confirming that it still works, we could possibly change it.

**Comment by sarah11918** [comment]
I've addressed this in the config reference docs! https://github.com/withastro/astro/pull/9502 Thank you for your comment!

**Comment by th0rgall** [comment]
Thank you @sarah11918! That note surely would have helped me understand my issue more quickly (or even prevented it).

> An adapter, or any integration for that matter, can override any particular config. That's often a primary purpose of an integration, to bundle a bunch of configuration changes together rather than doing them all individually.

@matthewp reconsidering my issue with this in mind, it would perhaps be helpful if it's the adapter's responsibility to warn/error at build time when it overrides a particular config.

Like:
```
WARN: You have set `build.format` to "file" in astro.config.mjs, but this output format isn't supported by the Vercel Static adapter. It will be set to "directory".
```

Additionally, the limitations of the adapter could be pointed out in its documentation.

My main issue here was that my Vercel production deployment behaved differently from my local development server (I had broken links/404s), and I had to dive into the adapter code to figure out why exactly.
