### ISSUE TITLE
Remove "experimental" from SSR page

### ISSUE THREAD

**Issue by sarah11918** [withastro/docs#481]
This page needs updating now that SSR is no longer behind an experimental flag. It is the "new normal" but, it is still undergoing changes and in development. So, the text should at the very least remove reference to the experimental flag. But, perhaps keeping a note about it being in current development and subject to change is still helpful?

I suggest:

- Remove "(experimental)" from the SSR page heading at https://docs.astro.build/en/guides/server-side-rendering/
- remove "behind an experimental flag" to reflect that it is now enabled by default
- Maybe change "SSR is marked as experimental in Astro..." to something more like "SSR is new in Astro and changes will occur. before v1.0 stable release. Please keep up to date with API changes here."  ?

**Comment by SaumyaBhushan** [comment]
I would like to work on this issue. can you please assign it to me?

**Comment by SaumyaBhushan** [comment]
https://github.com/withastro/docs/pull/489

**Comment by SaumyaBhushan** [comment]
@sarah11918 Please review it.

**Comment by Pukimaa** [comment]
This seems resolved, yay! @sarah11918 could you please close the issue?
