### ISSUE TITLE
Unable to deploy SSR build.

### ISSUE THREAD

**Issue by CovertCode** [withastro/docs#4811]
### 📋 Explain your issue

I tried to build in `standalone` mode.
Config:
```
import { defineConfig } from 'astro/config';

import node from "@astrojs/node";

// https://astro.build/config
export default defineConfig({
  output: "server",
  adapter: node({
    mode: "middleware"
  })
});```

Build was success.
I was having some client side js files in `src/libs/` folder. In development version everything was working fine. But after build these are not loaded.
I tried `node ./dist/server/entry.mjs`
CSS, js files in public did got loaded but js files ins `src/lib` were not loaded. I have a `login.js` file which had listener to login button. Now in build version if I click that button I get error in node server console:
```
ReferenceError: document is not defined
    at file:///home/xxx/xxx/hy-as/dist/server/chunks/pages/login_6b94d670.mjs:2:21
```

There's some issue with `dist/client` folder.

Can someone help me in deployment?

**Comment by jacobthesheep** [comment]
Please move this issue to the main astro repo.

**Comment by sarah11918** [comment]
Hi there! This is the repo for issues to our documentation site only so I am closing this issue. For support, please ask in our Discord at https://astro.build/chat where we have people who would be happy to answer questions and help you troubleshoot!

If you think you have discovered a bug in Astro itself, you will need to file a bug at https://github.com/withastro/astro/issues/ and fill out their bug template, which will also ask you to provide a reproduction. I suggest asking on Discord first if you are able to, as people will try to help you there!
