### ISSUE TITLE
Outdated info: edge adapter was removed from `@astrojs/netlify`

### ISSUE THREAD

**Issue by lilnasy** [withastro/docs#4812]
### 📚 Subject area/topic

Deploy recipe

### 📋 Page(s) affected (or suggested, for new content)

https://docs.astro.build/en/guides/deploy/netlify
https://github.com/withastro/docs/blob/main/src/content/docs/en/guides/deploy/netlify.mdx

### 📋 General description or bullet points (if proposing new content)

It makes references to the edge adapter which was removed in `@astrojs/netlify`3.0 ([Changelog](https://github.com/withastro/astro/blob/main/packages/integrations/netlify/CHANGELOG.md#300).)

<img width="500" alt="image" src="https://github-production-user-asset-6210df.s3.amazonaws.com/69170106/270680402-ac0b72c9-0152-4c92-ab9f-a80097b9649b.png">
<img width="500" alt="image" src="https://github-production-user-asset-6210df.s3.amazonaws.com/69170106/270680486-042288b7-74f1-4074-9f1a-f0d169fa0c92.png">

### 🖥️ Reproduction in StackBlitz (if reporting incorrect content or code samples)

Not applicable

**Comment by RUDRAcode** [comment]
I would like to contribute to this . Can anyone please guide me ?

**Comment by lilnasy** [comment]
Hi @RUDRAcode, thanks for offering help! It's really appreciated but this issue already has a pull request. However, we have other issues we could use your help with. I would recommend looking at the issues tagged "good first issue". 

https://github.com/withastro/docs/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22

**Comment by sarah11918** [comment]
Hi! It looks like this issue was fixed, so I'm closing this issue. Thank you for pointing this out, and we hope you'll look through for other issues to fix!
