### ISSUE TITLE
recommendation about docs.astro.build, part what is astro? and try your first project

### ISSUE THREAD

**Issue by GiovannisBV** [withastro/docs#4826]
### 📋 Explain your issue

Hello dear Astro community, 
guys you are doing a wonderful job!! Appreciate what you are busy with!!
As well, we want to contribute to documentation of the project, lets say non code contribution, we give you the following recommendation: 

In part What is Astro? we are missing a little bit more information about the project, we think one sentence is not enough to show us the whole meaning of Astro. In part Try your first project, we are missing more information about the steps of installation. Yes, its said that all steps are included in the installation package, but we think it will be nice to have more details. 

We stay in touch!!

**Comment by sarah11918** [comment]
Thank you for your comment here! We are happy you are enjoying Astro!

We are currently revising both the Why Astro and Getting started page in the docs, and adding some more of the information you describe, so we think this will be covered in those new pages when we release them.

Thank you again, and see you around the project and the Discord!  🙌
