### ISSUE TITLE
fix: broken links in contributor guides

### ISSUE THREAD

**Issue by BekahHW** [withastro/docs#4828]
### 📚 Subject area/topic

contributor guides

### 📋 Page(s) affected (or suggested, for new content)

- submitting a recipe
- astro maintainers guides to docs

### 📋 General description or bullet points (if proposing new content)

n/a

### 🖥️ Reproduction in StackBlitz (if reporting incorrect content or code samples)

n/a

**Comment by jacobthesheep** [comment]
So this can be closed?

**Comment by BekahHW** [comment]
@jacobthesheep sorry about that! I thought I had closes #4828 in the PR, but I must've accidentally deleted it.
