### ISSUE TITLE
⚠️ Issue with Azure Deployment Instructions

### ISSUE THREAD

**Issue by blueboxes** [withastro/docs#4891]
On https://docs.astro.build/en/guides/deploy/microsoft-azure/

You must also set the engine in your `packages.json` as the static website build defaults to node 16 which is not compatible with astro

```
  "engines": {
    "node": ">=18.0.0"
  },
```

https://edi.wang/post/2022/1/27/how-to-specify-nodejs-version-when-building-azure-static-web-app

**Comment by VoxelMC** [comment]
@sarah11918 I was thinking about trying out the Azure deployment method, could you assign this to me and I can test it out while I'm at it?

**Comment by blueboxes** [comment]
I have a few other bits I found that may improve the docs as well. 

I plan to write a blog post, once done I will share here. I would be happy for any of the points to be incorporated into the official docs.

**Comment by blueboxes** [comment]
Here is my post feel free to use as much of it as you wish. 

https://www.blueboxes.co.uk/deploying-an-astro-website-to-azure-static-web-apps

I ran through both using vscode and the azure portal. The current astro guide in this GitHub issue covers everything except the need to set the engine in the package.json though in some places could be a bit clearer.

**Comment by TheOtterlord** [comment]
@VoxelMC we don't typically assign issues to people, but if an issue is open, that's your sign it's free to take! I've tagged this with `help-wanted` so people know it's available. If you're interested in making a PR, we'd love that!

**Comment by TheOtterlord** [comment]
@blueboxes this looks really useful! We have a community resource section at the end of some CMS guides ([example](https://docs.astro.build/en/guides/cms/storyblok/#community-resources)), and I think this would be a good opportunity to add one to our Azure deploy guide. We'd be open to a PR if you want to add your guide! Along with anything other feedback you might have!
