### ISSUE TITLE
Update PR template so issues are properly closed after being merged

### ISSUE THREAD

**Issue by jdwilkin4** [withastro/docs#4897]
In your [PR template](https://github.com/withastro/docs/blob/main/.github/PULL_REQUEST_TEMPLATE.md), it mentions adding the issue number here

[Related Issue / Implementation PR](https://github.com/withastro/docs/blob/main/.github/PULL_REQUEST_TEMPLATE.md#related-issue--implementation-pr)
Closes Issue #

However, when PR's are merged the issue remains open and maintainers are left to close them manually.
An example of this can be seen with this recently [merged PR](https://github.com/withastro/docs/pull/4870) that resolves the issue but the [issue](https://github.com/withastro/docs/issues/4869) remains open. 

To automate this, we can remove the word Issue.

Here is my proposed change

[Related Issue / Implementation PR](https://github.com/withastro/docs/blob/main/.github/PULL_REQUEST_TEMPLATE.md#related-issue--implementation-pr)
Closes  #

With this proposed change, now when PR's are merged the issue associated with it will be closed automatically.
https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

This will also help contributors see which open issues already have a PR in review for them.

**Comment by at-the-vr** [comment]
That makes sense, I did faced this Issue in last year Hacktoberfest as well.

**Comment by jdwilkin4** [comment]
closing this issue since it has already been resolved
