### ISSUE TITLE
`@astrojs/sitemap` does not always output sitemaps to `dist/`

### ISSUE THREAD

**Issue by evadecker** [withastro/docs#4919]
### 📚 Subject area/topic

Integrations

### 📋 Page(s) affected (or suggested, for new content)

https://docs.astro.build/en/guides/integrations-guide/sitemap/

### 📋 General description or bullet points (if proposing new content)

The `@astrojs/sitemap` docs currently state (emphasis mine):

> Now, [build your site for production](https://docs.astro.build/en/reference/cli-reference/#astro-build) via the astro build command. **You should find your sitemap under dist/ for both sitemap-index.xml and sitemap-0.xml!**

However, this is not always true. When using the Vercel adapter, files are output to `.vercel/output/static/` instead of `dist/`. I'm not sure if other adapters also have output directories which diverge from `dist/`.

It took me awhile to understand why the CLI was saying `@astrojs/sitemap: "sitemap-index.xml" is created.` but nothing was displaying in `/dist` as the docs said they should.

### 🖥️ Reproduction in StackBlitz (if reporting incorrect content or code samples)

https://stackblitz.com/edit/github-fuztr3?file=src%2Fpages%2Findex.astro

**Comment by evadecker** [comment]
As a followup, it would be excellent to improve the command line output for `@astrojs/sitemap` to specify **where** the sitemap was output.

Currently, this is all you get:

<img width="469" alt="image" src="https://github.com/withastro/docs/assets/4117920/af019252-2312-49fb-b090-3ca6d5dac7cc">

**Comment by Suraj-kumar00** [comment]
Hi @evadecker, How are you doing?
Can I work on this issue? Can you please assign it to me?

**Comment by evadecker** [comment]
Quality of life update to the CLI tracked here: https://github.com/withastro/astro/pull/8824
