### ISSUE TITLE
Making A toggle button instead of 2 buttons

### ISSUE THREAD

**Issue by Kritika30032002** [withastro/docs#5048]
### Astro Info

```block
UI/UX Issue
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome

### Describe the Bug

The toggle button can be made to toggle between light mode and dark mode instead of using 2 buttons which will increase the user experience.

### What's the expected result?

The toggle button can be made to toggle between light mode and dark mode

### Link to Minimal Reproducible Example

NA

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
Hi @Kritika30032002 — I’m not sure exactly what you’re referring to. Could you provide some more information please?

In the Astro docs we use an `<input type="radio">` for the theme toggle and in [the blog tutorial](https://docs.astro.build/en/tutorial/6-islands/2/) we use a single `<button>`, so I haven’t been able to find somewhere where we use 2 buttons as you describe.

**Comment by Kritika30032002** [comment]
Assign this to me. 

![image](https://github.com/withastro/docs/assets/83400697/b3785428-f52d-4876-ba2f-b035a3c4681e)

**Comment by at-the-vr** [comment]
Hey Kritika, this is a topic to [discuss about](https://github.com/withastro/docs/discussions) but I would rather stick with current implementation for theme toggling as it provides smooth accessibility and generally lets user know which theme they would prefer to use. If you bring this to the Discussions, maintainers there will let you know how this Issue can be proceeded

**Comment by Kritika30032002** [comment]
okay

**Comment by sarah11918** [comment]
Closing this issue now as we are keeping the current site as is, and migrating to Starlight soon and using its theme toggle implementation!
