### ISSUE TITLE
Code as headings, or not?

### ISSUE THREAD

**Issue by sarah11918** [withastro/docs#509]
We're trying to determine a consistent style to use.

Currently, and (explicitly by request), the CLI page does NOT use formatted code for the various `--` headings. 

However, on Project Struture, the directories DO use formatted code directories.

Do we have a preference? Are we concerned with consistency? (And sorry, more of these issues will come up as more translators are actively in the docs wanting explicit instructions, and finding these inconsistencies.) 😅 

![Screenshot 2022-05-09 18 45 12](https://user-images.githubusercontent.com/5098874/167503886-3c55beb2-5589-4b0f-874e-4ee00eb79c2a.png)
![Screenshot 2022-05-09 18 44 43](https://user-images.githubusercontent.com/5098874/167503889-32c0587b-2604-4044-b4c9-3c6a851dccd5.png)

**Comment by delucis** [comment]
I’m +1 on `code` in headings (or wherever else it appears).

**Comment by hippotastic** [comment]
> I’m +1 on `code` in headings (or wherever else it appears).

I agree and also want to point out that there can be headings where only a part of the heading text is a code reference. The screenshots could be a bit misleading in that regard because they only show headings that fully consist of a code block.

**Comment by sarah11918** [comment]
It's not misleading if the point is to show that we're not consistent, @hippotastic ! 😅 

But yes, there could be other options that might affect our decision about which we prefer visually.  :)

**Comment by sarah11918** [comment]
OK, if we're Team Code In Headings, then I'll put out a call for someone (as if I don't already know I have @Chrissdroid in mind...) to make a PR going through EVERY page and re-adding inline code into all appropriate headings.

Then, we can look at every single page and confirm that nothing looks too weird to keep!
