### ISSUE TITLE
Adapter API - remove experimental before v1

### ISSUE THREAD

**Issue by sarah11918** [withastro/docs#513]
The Adapter API page in the docs ( https://docs.astro.build/en/reference/adapter-reference/ ) will need updating when the Adapter API is no longer considered to be "experimental"

- [ ] Remove (experimental) from the page title _<-- is this still experimental?_
- [ ] remove the call out that SSR is experimental in Astro _<-- Can this be done NOW?_

**Comment by tony-sull** [comment]
@matthewp is it safe to call the Adapters API stable at this point?

**Comment by Yan-Thomas** [comment]
The adapters API is also called experimental [here on the integrations reference page](https://docs.astro.build/pt-br/reference/integrations-reference/#astrobuildstart).

**Comment by sarah11918** [comment]
I believe this change has been made, in both places. 🥳
