### ISSUE TITLE
Lit not listed in client:only docs

### ISSUE THREAD

**Issue by boyatbeebee** [withastro/docs#5135]
It seems Lit is missing in the example list.

https://docs.astro.build/en/reference/directives-reference/#clientonly

client:only="lit"

Is this a mistake? Or is Lit no longer supported?

**Comment by sarah11918** [comment]
I think these are just examples, not meant to be a comprehensive list! So I'll close this issue, but if you discover that you try to use Lit and it does not work, you can file an issue with the core astro repo!
