### ISSUE TITLE
CLI refence - anything missing to doc here?

### ISSUE THREAD

**Issue by sarah11918** [withastro/docs#516]
The CLI reference page has not been significantly updated (other than adding Telemetry, only minor typo/formatting fixes) for about 4 months. (`-- host` was added 2 months ago.)

Is there anything missing from this page that should be included for v1?

**Comment by delucis** [comment]
Fred mentioned automating the CLI docs in https://github.com/withastro/docs/issues/209

Regardless of whether we do that, checking the `@cli` tags in the types file might be a good measure of if this is up to date: https://github.com/withastro/astro/blob/main/packages/astro/src/%40types/astro.ts

**Comment by sarah11918** [comment]
Changing this as a task for Core to review for a final once-over. Otherwise, this page can be considered "polished" and ready for translation.
