### ISSUE TITLE
Community in Sidebar?

### ISSUE THREAD

**Issue by sarah11918** [withastro/docs#517]
Just throwing this out there for discussion, since I saw it on [11ty's doc site](https://www.11ty.dev/docs/) when I was running audits. What do we think of something like this?

![Screenshot 2022-05-05 12 27 53](https://user-images.githubusercontent.com/5098874/167640146-ad6b9efd-e3b0-49f5-8de0-bafa9643acc0.png)

**Comment by Yan-Thomas** [comment]
Hi, sidebar expert here.

I love the idea of a community section, maybe we can even change the placement of some other stuff? We just have to be sure of what we would want to be linked in this section.

I have been working on this in a local branch, what do you guys think if the placement was something like this?
![image](https://user-images.githubusercontent.com/61414485/168449098-6b8bcf83-853e-4c07-a6d5-a2012991c1a6.png)

**Comment by delucis** [comment]
Looks fantastic @Yan-Thomas! I wonder if having **More** above **Community** would make sense as that keeps all the page-specific stuff together?

**Comment by Yan-Thomas** [comment]
> I wonder if having More above Community would make sense as that keeps all the page-specific stuff together?
Hi @delucis!

It would bug me that "More" is not the final section, like in a sentence, but maybe that's just me? Since "More" in my print only has "Edit/translate this page", maybe we should rename it to "Contribute"?

**Comment by delucis** [comment]
Yeah, in this scenario "Contribute" is fantastic here.
