### ISSUE TITLE
Adapter implementation documentation

### ISSUE THREAD

**Issue by bhainesva** [withastro/docs#5181]
### 📚 Subject area/topic

Integration API, Adapter API

### 📋 Page(s) affected (or suggested, for new content)

https://docs.astro.build/en/reference/integrations-reference/
https://docs.astro.build/en/reference/adapter-reference/

### 📋 General description or bullet points (if proposing new content)

Hello, I've noticed some small inconsistencies in the documentation about implementing adapters.

1. The [Quick API Reference](https://docs.astro.build/en/reference/integrations-reference/#quick-api-reference) doesn't include the `setAdapter` option for the `astro:config:done` hook that is mentioned in the [Adapter API](https://docs.astro.build/en/reference/adapter-reference/#building-an-adapter) page.
2. The definition for the AstroAdapter interface that is passed into the `setAdapter` call [here](https://docs.astro.build/en/reference/adapter-reference/#building-an-adapter) is slightly different than its typing in the code [here](https://github.com/withastro/astro/blob/d5dc5ce04acd19d9c9b7a29c2519408f6bdc3b83/packages/astro/src/%40types/astro.ts#L1828).
    1.  `previewEntrypoint` and `args` are missing
    2. There are a few differences in which properties are optional, but that might be intentional
    3. In the code `args` is typed as `any`, but in practice it seems like trying to pass a function or an object with a function value won't work. It might be helpful to note any restrictions (if args has to be serializable for example). 

One other small question I ran into was about the `serverEntrypoint` option. The documentation describes it as "The entrypoint for server-side rendering." The example value given is `"@matthewp/my-adapter/server.js"`. It wasn't obvious to me how the string should be structured in general. The example appears to be pointing to a node module, so it might be nice to mention you can also use a relative path from the root of your Astro project. This question came up in the discord [here](https://discord.com/channels/830184174198718474/830184175176122389/1150936602118459482) and the asker concluded it wasn't possible, but it has been working for me. 

### 🖥️ Reproduction in StackBlitz (if reporting incorrect content or code samples)

n/a

**Comment by matthewp** [comment]
Using relative from the root of your project is probably not wise to document as most people building adapters are going to share them, not just use them in local projects, where relative won't work. Instead I'd suggest using this pattern: `fileURLToPath(new URL('./adapter.js', import.meta.url))`. You should also be able to use a specifier like `@matthewp/my-adapter/server.js` as long as `server.js` (in this example) is part of your package.json exports.

**Comment by sarah11918** [comment]
Thank you, @bhainesva ! I finally had a moment to make the corrections to the API documentation you mentioned, and you can see it in #5955 . If you would like to leave a review comment there, then you can get co-author credit for the PR, since it was your discovery!
