### ISSUE TITLE
💡 Idea: Adopt the recommended practise of one sentence per line

### ISSUE THREAD

**Issue by rdwz** [withastro/docs#5192]
This is from AsciiDoc's recommended practices, but works as well for Markdown documents and does even more sense in the context of collaborative work and version controlled files. 

I think this is generally a very useful approach and could be a good addition to our contribution guides. 
What do you think? 🧑‍🚀

> ## One Sentence Per Line
>
> Don’t wrap text at a fixed column width. Instead, put each sentence on its own line, a technique called sentence per line.
> This technique is similar to how you write and organize source code.
> The result can be spectacular.
> 
> Here are some of the advantages of using the sentence per line style:
> 
> - It prevents reflows (meaning a change early in the paragraph won’t cause the remaining lines in the paragraph to reposition).
> - You can easily swap sentences.
> - You can easily separate or join paragraphs.
> - You can comment out sentences or add commentary to them.
> - You can spot sentences which are too long or sentences that vary widely in length.
> - You can spot redundant (and thus mundane) patterns in your writing.
> 
> We picked up this idea from the writing guide in the [Neo4j documentation](https://neo4j.com/docs/2.2.8/community-docs.html#_writing).
> However, it seems like the idea dates back a discovery by Buckminster Fuller in the 1930s, who called it [ventilated prose](https://vanemden.wordpress.com/2009/01/01/ventilated-prose/).
> The technique was also recommended in 2009 by Brandon Rhodes in a blog post about [Semantic Linefeeds](https://rhodesmill.org/brandon/2012/one-sentence-per-line/).
> 
> It’s important to note that this technique works because AsciiDoc doesn’t treat wrapped lines in prose as hard line breaks.
> At least, it doesn’t show up that way to the reader.
> The line breaks between contiguous lines of prose will not be visible in the rendered document (i.e., as the reader sees it).

source: https://asciidoctor.org/docs/asciidoc-recommended-practices/#one-sentence-per-line

**Comment by sarah11918** [comment]
We are not adopting this practice, thanks!
