### ISSUE TITLE
`Missing alt property.` error should contain the image without `alt`

### ISSUE THREAD

**Issue by Akxe** [withastro/docs#5218]
This error could be more helpful... What image is missing the Alt?

On a side note... some images might be better without an alt. Imagine if the user does not give me the description or enters a very bad one (ex. `image`, `Cover image for a project`, `Project visualization n.12`...). An AI would have done better to describe the image in that case...

**Comment by Akxe** [comment]
This should be in the code part of astro... I was redirected here without realising it...

**Comment by kik-o** [comment]
> This should be in the code part of astro... I was redirected here without realising it...

Should probably close this out and link to your new issue @Akxe
