### ISSUE TITLE
SSR benchmark

### ISSUE THREAD

**Issue by cdtut** [withastro/docs#5226]
Astro can substitute node framework like express, hapi, koa and fastify. Please add benchmark comparing common feature to them like hello world, file upload, validation and some more to compare requests, CPU and memory. Can show astro as valid framework to use for SSR and discover slow areas that need to be speed up.

**Comment by sarah11918** [comment]
Hi! We're not considering adding these benchmarks as they will be subject to change and would need updating, and this is not documentation on how to use Astro. We do publish such snapshot comparisons on our blog in articles and on social media.
