### ISSUE TITLE
Discuss type restrictions in content that result in UnsupportedConfigTransformError

### ISSUE THREAD

**Issue by jyasskin** [withastro/docs#5227]
### 📚 Subject area/topic

Content Collections

### 📋 Page(s) affected (or suggested, for new content)

https://docs.astro.build/en/guides/content-collections/#defining-datatypes-with-zod

### 📋 General description or bullet points (if proposing new content)

https://docs.astro.build/en/guides/content-collections/#defining-datatypes-with-zod doesn't say there are any restrictions on the types of data that we can return from [`transform`](https://zod.dev/?id=transform), but if we return something that's not supported by the [devalue](https://github.com/rich-harris/devalue) library, we get the https://docs.astro.build/en/reference/errors/unsupported-config-transform-error/ error.

### 🖥️ Reproduction in StackBlitz (if reporting incorrect content or code samples)

https://stackblitz.com/edit/github-s54fgs?file=src%2Fcontent%2Fconfig.ts

**Comment by sarah11918** [comment]
Hi there! Thanks for raising this. At this time, we are comfortable with a very clear error message and link to appropriate documentation as the way we are choosing to document this!
