### ISSUE TITLE
Modifying the [...slug] example for SSR

### ISSUE THREAD

**Issue by sherleyoz** [withastro/docs#5231]
### 📚 Subject area/topic

SSR

### 📋 Page(s) affected (or suggested, for new content)

https://docs.astro.build/en/core-concepts/routing/#example-dynamic-pages-at-multiple-levels

### 📋 General description or bullet points (if proposing new content)

Please provide a full tutorial for modifying [...slug] for Astro SSR, for e.g. if slug property is defined in the individual md/ mdx files 

### 🖥️ Reproduction in StackBlitz (if reporting incorrect content or code samples)

NA

**Comment by VoxelMC** [comment]
Just to see if I understand correctly, a tutorial that will retrieve an entry from a markdown/mdx file (probably from a content collection) using a frontmatter-defined `slug:` property - specifically for SSR?

Would this constitute an official recipe, @sarah11918? If so, I would love to write it sometime soon.

**Comment by sarah11918** [comment]
Hi @VoxelMC ! I think the issue here is that our examples only show defining a static array for `pages`, but most people will want to use both `getStaticPaths()` as well as the SSR method based on generating the `pages` array itself.

I think these are common enough use cases that these examples could go right into the routing page here! Would you be up for trying to make examples for these?

**Comment by VoxelMC** [comment]
> Hi @VoxelMC ! I think the issue here is that our examples only show defining a static array for `pages`, but most people will want to use both `getStaticPaths()` as well as the SSR method based on generating the `pages` array itself.
> 
> I think these are common enough use cases that these examples could go right into the routing page here! Would you be up for trying to make examples for these?

Ahh, I see. Yes, I would love to. I will draft something up this weekend :)

**Comment by VoxelMC** [comment]
> Hi @VoxelMC ! I think the issue here is that our examples only show defining a static array for `pages`, but most people will want to use both `getStaticPaths()` as well as the SSR method based on generating the `pages` array itself.
> 
> I think these are common enough use cases that these examples could go right into the routing page here! Would you be up for trying to make examples for these?

I believe I clearly dropped the ball on "`weekend`" here, but I should have time to take a crack at this soon!

Before I do that, I want to clear everything up. So, when you say 

> the SSR method based on generating the pages array itself.

Do you mean mapping over a content collection and matching the slug (and responding 404 if it's not there)? 

For example, 
```jsx
---
import { getEntries } from 'astro:content';

const blogPosts = await getEntries('blog');
const { slug } = Astro.params;

const post = blogPosts.find((post) => post.slug === slug);

if (!post) return Astro.redirect("/404");
const { title, text } = post;
---
<h1>{title}</h1>
<p>{text}</p>
```
Or something like that? Or am I not following...

**Comment by sarah11918** [comment]
Hi @VoxelMC -i might have misinterpreted the original request, but what *I* mean is:

1. our current `getStaticPaths()` example shows the paths all listed out in an array:

```
export function getStaticPaths() {
  return [
    {params: {dog: 'clifford'}},
    {params: {dog: 'rover'}},
    {params: {dog: 'spot'}},
  ];
}
```

But most people aren't going to do that. :smile: They'll do something more like e.g. returning a mapping over a bunch of routes. with e.g.  `params: {tag}`. This is from the Add Content Collections to the blog tutorial where we make a `[tags]` page, for example:

```
export async function getStaticPaths() {
  const allPosts = await getCollection("posts");
  const uniqueTags = [...new Set(allPosts.map((post) => post.data.tags).flat())];

  return uniqueTags.map((tag) => {
    const filteredPosts = allPosts.filter((post) =>
      post.data.tags.includes(tag)
    );
    return {
      params: { tag },
      props: { posts: filteredPosts },
    };
  });
}
```

2. The place we *do* show how to create routes using `[...slug]` for SSR *also* lists out all the routes in advance, and doesn't generate them: https://docs.astro.build/en/core-concepts/routing/#modifying-the-slug-example-for-ssr

```
---
// src/pages/[...slug].astro
const pages = [
  {
    slug: undefined,
    title: 'Astro Store',
    text: 'Welcome to the Astro store!',
  },
  {
    slug: 'products',
    title: 'Astro products',
    text: 'We have lots of products for you',
  },
  {
    slug: 'products/astro-handbook',
    title: 'The ultimate Astro handbook',
    text: 'If you want to learn Astro, you must read this book.',
  }
];

const { slug } = Astro.params;
const page = pages.find((page) => page.slug === slug);
if (!page) return Astro.redirect("/404");
const { title, text } = page;
---
<html>
<head>
  <title>{title}</title>
</head>
<body>
  <h1>{title}</h1>
  <p>{text}</p>
</body>
</html>
```

I had thought it would be helpful to have examples the way people are likely to use them there. 


I suspect perhaps the OP was asking for something more like this example: https://docs.astro.build/en/guides/content-collections/#building-for-server-output-ssr but not using the passed `slug` default property in content collections, but instead if you've defined your own frontmatter "slugOverride" property or something. It would seem the difference would be that frontmatter properties are available on `data` (e.g. `post.data.property`) whereas the slug is available just from the returned entry (`post.data`), so I think the content collections example probably doesn't need reproducing?

At any rate, I'm going to close this issue but my above note still stands about what I perceive as missing in docs right now, and something I have on my radar that I'd like to eventually address! (and wouldn't turn down help.)  ;)
