### ISSUE TITLE
Discord Link Invalid

### ISSUE THREAD

**Issue by kik-o** [withastro/docs#5241]
### 📚 Subject area/topic

Discord

### 📋 Page(s) affected (or suggested, for new content)

* https://discord.com/invite/grF4GTXXYm
* https://astro.build/chat

### 📋 General description or bullet points (if proposing new content)

Site and docs should be updated to use new Discord chat links

### 🖥️ Reproduction in StackBlitz (if reporting incorrect content or code samples)

Click on the Discord icon found at the top right of [marketing site](https://astro.build/) which links https://astro.build/chat ->  https://discord.com/invite/grF4GTXXYm and you'll see the following error message:
![chrome_ujZSd1825f](https://github.com/withastro/docs/assets/22601829/a177c56b-e7af-4e87-a717-c4f4a969ed4e)

Same link can be found anywhere in the docs where Discord or "Chat with us" is mentioned.

**Comment by TheOtterlord** [comment]
Both these links work fine for me. Does this invite work for you?
https://discord.gg/astro-lounge-830184174198718474

**Comment by kik-o** [comment]
Huh.. weird. It's working fine for me now.
