### ISSUE TITLE
⚠️ Update StoryblokComponent import path

### ISSUE THREAD

**Issue by eacardenase** [withastro/docs#5281]
Using @storyblock/astro v3.0.1 the correct path to the following [doc](https://docs.astro.build/en/guides/cms/storyblok/#connecting-bloks-to-components) should be the following:

import StoryblokComponent from '@storyblok/astro/components/StoryblokComponent';

Previous one: 
import StoryblokComponent from '@storyblok/astro/StoryblokComponent.astro';

**Comment by delucis** [comment]
Thanks for the issue @eacardenase! Would you be interested in submitting a PR to fix this?

**Comment by dreyfus92** [comment]
@sarah11918 can you assign it to me?
