### ISSUE TITLE
No mention of lack of support for dynamically named slots

### ISSUE THREAD

**Issue by Alex-S-Davies** [withastro/docs#5297]
Although the docs mention astro has support for named slots, and that these slots can be used in UI framework components, it doesn't mention anywhere that there are severe limitations when it comes to dynamically named slots.

This is a known limitation of the astro compiler (https://github.com/withastro/astro/issues/5066) and looks like it is unlikely to be supported any time soon.

Not documenting known limitations can be frustrating as it often leads to many wasted hours.

I will submit a PR shortly to amend this.

**Comment by matthewp** [comment]
Great suggestion! I'm surprised we didn't have this.
