### ISSUE TITLE
The "Add an RSS feed" documentation's sample code leads to deprecation warning for users about returning a simple object

### ISSUE THREAD

**Issue by phd20** [withastro/docs#5333]
This [documentation](https://docs.astro.build/en/guides/rss/) still provides working sample code but results in a build warning:

`[yourXmlPage] returns a simple object which is deprecated. Please return an instance of Response. See https://docs.astro.build/en/core-concepts/endpoints/#server-endpoints-api-routes for more information.`

![rss_xml_ts_—_phd20_github_io](https://github.com/withastro/docs/assets/33853403/884ac7bf-5d15-4c62-ad9c-17c0f768a72b)

## Expected Outcome
The documentation is updated with sample code that no longer results in a deprecation warning (which presumably includes a response object).

**Comment by delucis** [comment]
Thanks for the report @phd20! Could you check which version of the `@astrojs/rss` you have installed? Should be fixed if you have v3 of `@astrojs/rss` installed.

**Comment by phd20** [comment]
Thanks, @delucis. I was apparently on v2. Updating `@astrojs/rss` to v3 got rid of the warning. I'll close this out.
