### ISSUE TITLE
Incorrect information in "Using environment variables"

### ISSUE THREAD

**Issue by Genteure** [withastro/docs#5413]
### 📚 Subject area/topic

Environment variables

### 📋 Page(s) affected (or suggested, for new content)

https://docs.astro.build/en/guides/environment-variables/#using-the-cli

### 📋 General description or bullet points (if proposing new content)

> CAUTION
>
> Variables set this way will be available everywhere within your project, including on the client.

This doesn't seems correct. Environment variables passed in from CLI are also filtered based on the same rules applied to `.env` files.

### 🖥️ Reproduction in StackBlitz (if reporting incorrect content or code samples)

https://stackblitz.com/edit/github-azezsp?file=src%2Fpages%2Findex.astro,.env

**Comment by at-the-vr** [comment]
Hey @Genteure How about this suggestion ?
```js
<PackageManagerTabs>
 <Fragment slot="yarn">
    ```shell
    yarn run dev && POKEAPI=https://pokeapi.co/api/v2
    ```
 </Fragment>
 <Fragment slot="npm">
    ```shell
     npm run dev && POKEAPI=https://pokeapi.co/api/v2
    ```
 </Fragment>
 <Fragment slot="pnpm">
    ```shell
    pnpm run dev && POKEAPI=https://pokeapi.co/api/v2
    ```
 </Fragment>
</PackageManagerTabs>

:::note
Variables set this way will be available everywhere within your project, and not on the client.
:::
```
![image](https://github.com/withastro/docs/assets/88548999/81329ef8-fb4a-4c60-926c-08ef7a0efab6)

**Comment by Genteure** [comment]
I think we can just remove this aside because their behavior regarding visibility to processed client side code is the same (unless there's a difference I'm not aware of).
