### ISSUE TITLE
Route Priority Order

### ISSUE THREAD

**Issue by cdtut** [withastro/docs#5431]
### 📋 Explain your issue

https://docs.astro.build/en/core-concepts/routing/#route-priority-order can explain how it works with paths at different levels in tree. It only show cases when all templates are same level.

>    pages/posts/create.astro - Will build /posts/create
>    pages/posts/[pid].astro - Will build /posts/1, /posts/abc, etc. But not /posts/create
>    pages/posts/[...slug].astro - Will build /posts/1/2, /posts/a/b/c, etc. But not /posts/create, /posts/1, /posts/abc

It should explain with templates at more levels to cover more cases. Maybe first 2 lines not necessary but 3 and 4 will help explain the concept with more levels.

> pages/create.astro
> pages/[pid].astro
> pages/[...slug].astro
> pages/posts.astro
> pages/posts/create.astro
> pages/posts/[pid].astro
> pages/posts/[...slug].astro

**Comment by sarah11918** [comment]
Thanks for your comment! We will be looking at updating our routing page in the new year, and I have made a note of this feedback!  :raised_hands:
