### ISSUE TITLE
Disable telemetry

### ISSUE THREAD

**Issue by cdtut** [withastro/docs#5432]
### 📋 Explain your issue

What files `npx astro telemetry disable` touches on my computer?

Unethical to make it opt out but at least please document what exactly this command changes.

**Comment by sarah11918** [comment]
Thanks @cdtut , I think this would be great information to add to the docs!

The Astro `telemetry` package is here: https://github.com/withastro/astro/tree/main/packages/telemetry/src

There are anonymous IDs set per project, but mostly the information we collect and analyze is the version of Astro used and which integrations you are using. This helps us know what are users are actually using, and helps us plan our development roadmap accordingly. 

For example, if only 2% of our users are using one particular integration, but it results in 50% of our bugs and issues filed... maybe we decide that integration just isn't worth it!  :sweat_smile: 

Similarly, knowing which version of Astro people are running lets us know how disruptive breaking changes might be, and might tell us we should wait longer before a next major release.

I do think you're right, though, that we could describe this in the CLI guide where we mention the command. It will have no effect on your project, so it is safe to have it either enabled or disabled and it will not affect how Astro works.

Thank you again for mentioning it! I will keep this issue open and label it as "help wanted" in case anyone from the community would like to explore the code for the telemetry package and suggest a helpful comment to add to the docs!

**Comment by Jothsa** [comment]
I can try to do this

**Comment by vchirikov** [comment]
It also will be nice to have an option to disable telemetry with env variable.

**Comment by TheOtterlord** [comment]
@vchirikov You can set `ASTRO_TELEMETRY_DISABLED=1` to disable telemetry via environment variables. You can find out more about telemetry here: https://astro.build/telemetry/

**Comment by vchirikov** [comment]
@TheOtterlord missed that, big thanks!
