### ISSUE TITLE
Consider updating the docgen.mjs script that updates configuration-reference

### ISSUE THREAD

**Issue by Chrissdroid** [withastro/docs#544]
Opening this issue about the `docgen.mjs` script to be able to auto-update `configuration-reference.md` as a scheduled github action.

Ideas mentioned with this:

- Schedule it as 1 time per day / two days ( to avoid the complexity of listening on changes from `withastro/astro` types )
- Updating the current `docgen.mjs` to be compatible with github CI
- Converting automatically `https://docs.astro.build/` to relatives links
- Automatically merge changes on the repo ( and be sure it trigger the i18n CI loop )

**Comment by sarah11918** [comment]
We have a live test-case available:

"The configuration documentation says the default value of trailingSlash is always. But it's wrong, the default value is ignore https://docs.astro.build/en/reference/configuration-reference/#trailingslash"

**Comment by Chrissdroid** [comment]
"The link inside the config ref is absolute, can cause issues with dev environnements and redirecting when unnecessary https://github.com/withastro/docs/blob/main/src/pages/en/reference/configuration-reference.md?plain=1#L266"

**Comment by sarah11918** [comment]
Wait, is this the same as #209 @Chrissdroid ? or related? If so, maybe you can add info there.

**Comment by Chrissdroid** [comment]
we could merge this here for the first case but i think it's more suitable to make a separate thing for the "CLI Flag" automatisation

( which could be pushed toward with changes from this )

**Comment by delucis** [comment]
Good catch, @sarah11918. Do we prefer moving this to #209 to keep all docgen-related ideas in one place? I can copy this over to that issue in that case.

**Comment by sarah11918** [comment]
I'll leave it to you to decide what makes your life easier @delucis ! 

If it's easier together because it's targeting the same script, perfectly fine to copy over stuff from here and just keep going ahead in #209 . If you want to keep the specific ideas separate, I have no problems having two different issues.

**Comment by delucis** [comment]
OK! I’ve moved this over there. That way if someone’s looking at one of these they might pick up the others if it makes sense to tackle more than one at once. Thanks so much for collating the different thoughts here @Chrissdroid 💜
