### ISSUE TITLE
Precise where to create the .astro folder

### ISSUE THREAD

**Issue by Canfry** [withastro/docs#5460]
### 📋 Explain your issue

Reading the documentation about content collections, you have a section talking about the .astro folder that automatically updates running dev or build commands. It would be nice to precise where exactly to create the folder (root directory or src?). Just a little opinion, hope it helps. Thanks for your amazing product.

**Comment by sarah11918** [comment]
Thank you for your comment, @Canfry ! Our documentation does say:

> No action is needed on your part to maintain or update this directory. You are encouraged to ignore it entirely while working in your project.

So, it's not something you have to create, nor worry about at all!  :raised_hands: You can just go right ahead and enjoy Astro. :smile:

**Comment by Canfry** [comment]
Thank you so much for your reply @sarah11918 . I feel stupid I didn't get it that way when I read it for the first time. No worries I'm enjoying a lot Astro.
