### ISSUE TITLE
Document how to dynamically create/add/download files to public folder during the build process

### ISSUE THREAD

**Issue by pReya** [withastro/docs#5464]
### 📚 Subject area/topic

Bundling

### 📋 Page(s) affected (or suggested, for new content)

https://docs.astro.build/en/guides/imports/#files-in-public

### 📋 General description or bullet points (if proposing new content)

In multiple locations, the Astro docs state that any files in the `public` folder will be copied to the output bundle, without any modification.

However the docs are missing one big caveat: This is only true, if the files are already existing before the build process starts. It's not possible to add files to `public` during the build process (e.g. downloading images via API) and have them copied/bundled to the output. It seems that Astro is indexing the public folder BEFORE the build process, and will only copy/bundle all the files that have been there before the build process started.

This should be mentioned in the docs, and maybe there could maybe even be a mention of possible workarounds (e.g. use a shell script to copy the files after the `npm run build` call).

### 🖥️ Reproduction in StackBlitz (if reporting incorrect content or code samples)

https://stackblitz.com/edit/github-aqszdy?file=src%2Fpages%2Findex.astro

**Comment by sarah11918** [comment]
Thanks for this comment @pReya ! We're going to check with our platform devs re: the exact behaviour that occurs, and the exact guidance they would like documented here.

**Comment by Jothsa** [comment]
I would also like to see this documented!

**Comment by Princesseuh** [comment]
Creating files in `public` during build doesn't actually work. The files gets copied *before* the build and you'll end up missing files. See this old issue: https://github.com/withastro/astro/issues/5669

**Comment by sarah11918** [comment]
I've added a brief note on our project structure page in the above mentioned PR. You're welcome to leave comments there, but this page is not for going into details like workarounds.

If you'd like to create a recipe that demonstrates a workaround like a shell script, you can create one for docs, or make a blog post and we would happily link to it from the More Recipes page!
