### ISSUE TITLE
Update widths example to match attribute description

### ISSUE THREAD

**Issue by hfournier** [withastro/docs#5473]
### 📚 Subject area/topic

Images

### 📋 Page(s) affected (or suggested, for new content)

https://docs.astro.build/en/guides/images/#image--astroassets

### 📋 General description or bullet points (if proposing new content)

The `widths` attribute description states:
```
If provided, this value will be used to generate a srcset attribute on the <img> tag. A [sizes property](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/sizes) must also be provided.
```
but the example that follows does not include a `sizes` attribute.

### 🖥️ Reproduction in StackBlitz (if reporting incorrect content or code samples)

n/a

**Comment by sarah11918** [comment]
Great catch! I'll keep this issue open and add "help wanted" to it as we would gladly accept a PR to correct this!  :raised_hands:

**Comment by mingjunlu** [comment]
[Pull request](#5485) incoming 🫡
