### ISSUE TITLE
Add `biome` to "Other Tools" section

### ISSUE THREAD

**Issue by jacobthesheep** [withastro/docs#5476]
### 📚 Subject area/topic

Editor Setup / Other Tools

### 📋 Page(s) affected (or suggested, for new content)

https://docs.astro.build/en/editor-setup/#other-tools

### 📋 General description or bullet points (if proposing new content)

As [Biome](https://biomejs.dev/) is close to 100% [Prettier](https://prettier.io/) compatibility, it would be a great addition to this page.

Also [knip](https://knip.dev/) is a neat package that extends linters. Up to discussion if it should be added as well.

### 🖥️ Reproduction in StackBlitz (if reporting incorrect content or code samples)

none

**Comment by delucis** [comment]
Biome isn’t able to run on `.astro` files is it?
