### ISSUE TITLE
⚠️ Issue Getting error in: Building a Blog  - Generate tag pages

### ISSUE THREAD

**Issue by 4rc0s** [withastro/docs#5486]
I'm getting an error on the file created from [Generate tag pages](https://docs.astro.build/en/tutorial/5-astro-api/2/).

`Cannot read properties of undefined (reading 'filter')` for the line 

```const filteredPosts = posts.filter((post) =>
    post.frontmatter.tags?.includes(tag),
);
```

Here's the complete file as created from the tutorial:

```
---
import BaseLayout from "../../layouts/BaseLayout.astro";

export async function getStaticPaths() {
    const allPosts = await Astro.glob("../posts/*.md");

    return [
        { params: { tag: "astro" } },
        { params: { tag: "successes" } },
        { params: { tag: "community" } },
        { params: { tag: "blogging" } },
        { params: { tag: "setbacks" } },
        { params: { tag: "learning in public" } },
    ];
}

const { tag } = Astro.params;
const { posts } = Astro.props;
const filteredPosts = posts.filter((post) =>
    post.frontmatter.tags?.includes(tag),
);
---

<BaseLayout pageTitle={tag}>
    <p>Posts tagged with {tag}</p>
    <ul>
        {
            filteredPosts.map((post) => (
                <BlogPost url={post.url} title={post.frontmatter.title} />
            ))
        }
    </ul>
</BaseLayout>
```

I also see an error with undefined `BlogPost`.

**Comment by sarah11918** [comment]
Hi! There's a note in Step 4 about also importing the `<BlogPost />` component at the top of the file that you might have missed:

![image](https://github.com/withastro/docs/assets/5098874/924d27c0-d91c-49b7-b400-f30d14c65ec1)

This might be the cause of both errors!

You can see the completed version of the code here: https://github.com/withastro/blog-tutorial-demo to compare your code, if that helps!

If you have any more issues or questions working through the tutorial, people would be happy to help you in the Astro Discord! https://astro.build/chat :raised_hands:
