### ISSUE TITLE
No Navigation below minimum screen width, app unusable

### ISSUE THREAD

**Issue by Steve-Ast24** [withastro/docs#5498]
as defined, the Navigation vanishes below the minimum screen width. This can be seen by sizing browser window & is the default on phone in portrait mode (Pixel 6Pro, so not small). As such, the app is unusable. How can this be good design?
*edit: maybe just a documentation change to call out this issue & say it's addressed in later modules

 @media screen and (min-width: 636px) {

**Comment by sarah11918** [comment]
Thank for your comment! As you noticed, the hamberger menu with the script is introduced just after the header component, but we can look into a "warning" when creating the responsiveness of the header!
