### ISSUE TITLE
i can not use react and preact together

### ISSUE THREAD

**Issue by Rangocold** [withastro/docs#5531]
i can not use react and preact together

when i set react and preact in integrations together,they can not work, and component also display exception

https://stackblitz.com/edit/github-bkcbcd?file=src%2Fcomponents%2FTestComponent.tsx

**Comment by Rangocold** [comment]
i fina an error in page(i do not create the var named prevRefreshReg ): 

Uncaught (in promise) SyntaxError: Identifier 'prevRefreshReg' has already been declared (at TestComponent.tsx:6:5)

**Comment by Rangocold** [comment]
and i find the 'prevRefreshReg' is declared twice in compiled TestComponent.tsx
![image](https://github.com/withastro/docs/assets/16416092/d937cbd6-7eef-43fe-91ec-4300268e3169)
![image](https://github.com/withastro/docs/assets/16416092/d4e63cad-768f-47f1-bd97-1617a0a4b614)

**Comment by Jothsa** [comment]
I don't know much about React and Preact, so I can't offer any help. This Github is for issues about the Astro docs specifically. For your type of issue, I suggest opening a thread in the #support channel of the [official Astro Discord](https://astro.build/chat). The folks there are super helpful!

**Comment by lilnasy** [comment]
Thanks for reporting it, @Rangocold!

What I notice missing in your stackblitz is this:
```
/** @jsxImportSource preact */
```
We document this in `Troubleshooting` [here](https://docs.astro.build/en/guides/typescript/#errors-typing-multiple-jsx-frameworks-at-the-same-time).

You might find it helpful to build upon our starter template for multiple frameworks: https://astro.new/latest/frameworks.

**Comment by fasiha** [comment]
> We document this in `Troubleshooting` [here](https://docs.astro.build/en/guides/typescript/#errors-typing-multiple-jsx-frameworks-at-the-same-time).

Thanks for this this tip @lilnasy! Could we include a link to this very useful suggestion at the bottom of the "[Combining multiple JSX frameworks](https://docs.astro.build/en/guides/integrations-guide/solid-js/#combining-multiple-jsx-frameworks)" section? I thought all I had to do was provide `include` paths in `astro.config.mjs` but was at a loss as to why VS Code was angry about types until I saw this (also [Solid docs](https://docs.solidjs.com/configuration/typescript#configuring-typescript) mention this `jsxImportSource` tip) 😁
