### ISSUE TITLE
Form Handling in Docs

### ISSUE THREAD

**Issue by ThePaulMcBride** [withastro/docs#5656]
Right now, the examples on how to use API endpoints and forms shows a method which requires JavaScript and breaks without it.

Given the heritage of Astro, it might make sense to give examples that do not require client side JavaScript and instead uses the native HTML behaviour with the api endpoint redirecting.

**Comment by lilnasy** [comment]
Thanks for opening this issue, @ThePaulMcBride!

We have an excellent recipe showing how you can write a form and a form handler in the same astro file!
https://docs.astro.build/en/recipes/build-forms

Feel free to reopen if you think something could be improved in it.
