### ISSUE TITLE
Cannot Deploy to Heroku

### ISSUE THREAD

**Issue by Mooskopf** [withastro/docs#5657]
### 📋 Explain your issue

[https://github.com/heroku/heroku-buildpack-static.git](https://github.com/heroku/heroku-buildpack-static.git) is deprecated and cant be used in Heroku Build
I tried deploying it with the [nginx Buildpack](https://github.com/heroku/heroku-buildpack-nginx/blob/main/static.md#document-root) and followed the instructions but it didnt work. Anybody has an idea how I could deploy my astro project to heroku?

**Comment by lilnasy** [comment]
Thanks for flagging this, @Mooskopf!

Looks like our [heroku deployment guide](https://docs.astro.build/en/guides/deploy/heroku) needs to be updated, and the heroku's instructions for using the nginx buildpack instead are here: https://github.com/heroku/heroku-buildpack-static#warning-heroku-buildpack-static-is-deprecated
