### ISSUE TITLE
Missing results for query "addPageExtension" and "addContentEntryType"

### ISSUE THREAD

**Issue by kdheepak** [withastro/docs#5669]
I'm trying to build an integration with jupyter notebooks, and this is the function I have so far:

```
export default function ipynb() {
  return {
    name: "ipynb",
    hooks: {
      "astro:config:setup": (options) => {
        console.log(options);
        options.addPageExtension(".ipynb");
        options.addContentEntryType({
          extensions: [".ipynb"],
          getEntryInfo({ fileUrl, contents }) {
            return {
              data: {
                ...
              },
              slug,
            };
          },
          handlePropagation: false,
        });
        options.updateConfig({
          vite: { plugins: [vitePlugin()] },
        });
      },
    },
  };
}
```

I don't see `addPageExtension` and `addContentEntryType` in the reference documentation anywhere, and even when I run `console.log(options)` I don't see `addPageExtension` or `addContentEntryType`. But I'm able to retrieve `.ipynb` notebooks as part of `getCollections` if and only if I add these functions. 

Can you point me to the documentation for these functions?

**Comment by lilnasy** [comment]
Thanks for the report @kdheepak!

The functions you mentioned are not documented because they are not part of _public_ integration API. They exist to power the internal MDX integration.

However, we do not officially support their usage elsewhere so it  would be misleading to document them.
