### ISSUE TITLE
Inconsistent scroll behavior between tabs and sidebar

### ISSUE THREAD

**Issue by Fryuni** [withastro/docs#5678]
### 📝 Issue Description

The links on the sidebar jump directly to the header, without any scroll animation.

The links for the tabs are scrolling smoothly to the tabs.

### 📋 On which page(s) it occurs

Every page with tabs

### 🤔 Expected Behavior

Either neither should have a smooth scroll or both should.

But I don't think the tabs should have any scroll at all, Starlight's [own docs](https://jam.dev/c/60a16be9-b177-4d66-adbc-1a51e3e6dfb1) don't have that.

### 👀 Current Behavior

https://jam.dev/c/3c56e87d-407c-42c4-a216-ec46ebe063ae

### 🖥️ Browser

Chrome and Firefox on Linux

**Comment by Fryuni** [comment]
So the decision was to scroll to the tab without smooth scrolling?

I don't get why there even is a scrolling there. Starlight doesn't. Although I listed it as one of the expected behaviors it is the least user-friendly of the 3 IMHO.

**Comment by delucis** [comment]
See Otterlord’s comment: https://github.com/withastro/docs/pull/5711#pullrequestreview-1780183160

Starlight doesn’t currently include synced tabs, which is what introduces the need for scroll management (because toggling multiple different heighted tabs on the page can cause weird jumps). We currently have a very simple approach that just always scrolls to the top of the page, but @TheOtterlord is working on an improvement so they don’t scroll!

**Comment by Fryuni** [comment]
Huum, I see. Now it makes sense why there is the jump. It was clearly an intentional addition, just not clear why. Go TheOtterlord!!

**Comment by yasnbouz** [comment]
Preventing the tabs from scrolling, results in a bad user experience on this page: [astro-docs-sharing-state](https://docs.astro.build/en/core-concepts/sharing-state/#using-atoms), The same problem occurred with the smooth scrolling feature. 

## Examples
tabs with no scrolling

[no-scroll.webm](https://github.com/withastro/docs/assets/45861586/c8838f13-7aec-44ec-a6e4-0717ee61371a)

tabs with smooth scrolling (current)

[smooth-scroll.webm](https://github.com/withastro/docs/assets/45861586/cf390058-086f-4595-8fce-60fa648f86b3)

tabs without smooth scrolling

[without-smooth.webm](https://github.com/withastro/docs/assets/45861586/03e1c06c-7213-448e-a760-9e39f7353c77)
