### ISSUE TITLE
Add a page for CSS-in-JS

### ISSUE THREAD

**Issue by jacobdalamb** [withastro/docs#5681]
### 📚 Subject area/topic

Add-ons

### 📋 Page(s) affected (or suggested, for new content)

suggested page for new content https://docs.astro.build/en/guides/css-in-js/

### 📋 General description or bullet points (if proposing new content)

What CSS-in-JS libraries are fully compatible and those with workarounds

### 🖥️ Reproduction in StackBlitz (if reporting incorrect content or code samples)

none

**Comment by lilnasy** [comment]
Hmm, I am not sure there is much to document other than "Use the library's astro integration. If it doesn't have one, it is not going to work".

And an overview of the various efforts and possibilities for integrations is meticulously put together by `mayank99` is here:
- https://github.com/withastro/roadmap/discussions/778

**Comment by sarah11918** [comment]
Since CSS-in-JS isn't super well supported in general and it's therefore not a pattern we really encourage, as Arsh says, it's not something we can really document, and there's not much worth documenting. This probably isn't something we'll add to docs anytime soon.
