### ISSUE TITLE
Change HTTP method for hx directive in partials section

### ISSUE THREAD

**Issue by eliasvelazquezdev** [withastro/docs#5696]
### 📋 Explain your issue

The [partials section of the docs](https://docs.astro.build/en/core-concepts/astro-pages/#using-with-a-library) suggests that the POST method should be used in the hx directive (when using HTMX) to retrieve content from a partial page.

In my case, this worked fine locally but not on production. I deployed my site on Netlify and kept getting 400 (Bad Request) errors when trying to navigate the site.

I switched the method to GET and everything worked fine, both locally and production.

I suggest to add this change to the docs.

**Comment by jacobthesheep** [comment]
Odd. It works for me on both dev and production using Vercel

**Comment by eliasvelazquezdev** [comment]
> Odd. It works for me on both dev and production using Vercel.

Thank you for replying. I thought the same, since on dev works just fine. I was surprised to see the hx-post directive not working on the deployed version of my site.

**Comment by lilnasy** [comment]
There is nothing about the example that should prevent a POST request from functioning. It is possible you are running into a bug and you might want to discuss this in support.

Feel free to reopen if you think this is not the case.

And either way, you are welcome to directly open a PR to switch `hx-post` to `hx-get`. The method is not relevant in explaining the partials feature.
