### ISSUE TITLE
Astro:self example does not work

### ISSUE THREAD

**Issue by ekafyi** [withastro/docs#577]
The current example in https://docs.astro.build/en/reference/api-reference/#astroself does not work.

Reproduction: https://codesandbox.io/s/astro-self-example-3qv8f2?file=/src/components/NestedList.astro

This causes an error _"unexpected return"_.

```astro
---
const { items } = Astro.props;
---
<ul class="nested-list">
  <li>{items.map((item) => {
    if (Array.isArray(item)) {
      // If there is a nested data-structure we render `<Astro.self>`
      // and can pass props through with the recursive call
      return <Astro.self items={item} />;
    } else {
      return item;
    }
  })}</li>
</ul>
```

The only way I got it to work was by returning a fragment/element directly from the mapping and do the recursive breaking conditional check _inside_ the fragment/element.

```astro
---
const { items } = Astro.props;
---
<ul class="nested-list">
  {items.map((item) => (
    <li>
      {Array.isArray(item) ? (
        <Astro.self items={item} />
      ) : (
        item
      )}
    </li>
  ))}
</ul>
```

**Comment by sarah11918** [comment]
Thanks @ekafyi ! This is a great reproduction, and perfect timing for me to go over some PRs/Issues with @tony-sull tomorrow! 💜 

We'll follow up here, and once I confirm what *should* work, and what *should* go in the docs, then I'm happy if you want to make a PR for the docs based on your findings!

**Comment by ekafyi** [comment]
on a side note, if anyone has a proper explanation on _why_ the original example does not work (is it a JSX thing? Vite? Astro?) i'll be keen to hear! it's a pattern that works in React-JSX.

**Comment by delucis** [comment]
Might be related to https://github.com/withastro/compiler/issues/394

**Comment by ekafyi** [comment]
Makes sense @delucis , once the compiler bug is fixed, if the original example works then no change to the docs necessary.

**Comment by sarah11918** [comment]
I need to make a new label for PRs like this... "Waiting until the problem magically fixes itself?"  😅

**Comment by ekafyi** [comment]
> Let’s use your example for now @ekafyi! Would you be up for creating a PR?

Sure.

Question: should I only modify the `en` file or other languages that has the `api-reference` page as well?

**Comment by sarah11918** [comment]
Yay! @ekafyi ! Thanks!

Please modify only the `/en/` page, and our automated system will kick in, the translators will be notified if there is an existing page already translated that needs updating.

I know it's just a code sample in this case and you *could* make the change, even without knowing Portuguese, but the process works, so we'll stick with it!  :)
