### ISSUE TITLE
Verify Code in Build Forms recipe

### ISSUE THREAD

**Issue by sarah11918** [withastro/docs#5777]
### 📚 Subject area/topic

Building forms recipe

### 📋 Page(s) affected (or suggested, for new content)

https://docs.astro.build/en/recipes/build-forms-api/

### 📋 Description of content that is out-of-date or incorrect

We had two people leave feedback regarding this recipe. Would be great if someone would review it, try it fresh and see if it needs updating or correcting!

Comment 1:
Following the code from https://docs.astro.build/en/recipes/build-forms-api/ and having a project with SSR enabled, the code for the submit function that does prevent default cant be reached

Comment 2:
Suggest pointing out the Vue component for the "build-forms-api" page needs "client:*" within the Astro page.

**Comment by VoxelMC** [comment]
Hello! I tested the code in the React, Svelte, and Vue code examples. I used the `node` SSR adapter.

#### Comment 1: **Tested by removing the `e.preventDefault()` and testing behaviour in presence or absence.**
- React code reached `e.preventDefault()`
- Same with Svelte
- Same with Vue
As far as I can see, this is working as is intended. A possible reason for misinterpretation is that a `client` directive was not used. This would make the form act like a normal form anyways, as though the default was not prevented!

#### Comment 2: **Same as above, but with a `client:load` directive.**
- All of the components definitely need a `client` directive to function as is intended in the recipe!

I have not tested Solid or Preact. I can, in the future, if no one else has!

Hope this helps!

**Comment by sarah11918** [comment]
@VoxelMC Would you be interested in seeing if you can improve this, maybe by reordering the sequence of the steps, and maybe adding showing the components being used with client directives?

**Comment by VoxelMC** [comment]
> @VoxelMC Would you be interested in seeing if you can improve this, maybe by reordering the sequence of the steps, and maybe adding showing the components being used with client directives?

Yes, definitely! I'll get on that :)
