### ISSUE TITLE
Low Contrast Favicon in Safari

### ISSUE THREAD

**Issue by mingjunlu** [withastro/docs#5792]
### 📋 Explain your issue

Hi there 👋

I noticed that the contrast of the favicon is kind of low in Safari. I think that the team might want to know 🙂

![截圖 2023-12-15 上午10 42 37](https://github.com/withastro/docs/assets/40516784/04bc011d-717c-48c3-ba31-c4aa5e1f5daa)

**Comment by delucis** [comment]
Thanks for reporting @mingjunlu! Which version of Safari is this? The docs use an SVG favicon that uses a `@media` query to adapt to the user’s current colour scheme, but Safari doesn’t [support SVG favicons](https://caniuse.com/link-icon-svg), so we fall back to a static `.ico` icon in these cases.

We could probably work around this with a dark border around the fallback icon, so users of Safari in light mode get a better experience.

**Comment by mingjunlu** [comment]
Hi @delucis, sorry for not mentioning the version. I'm using Safari 17.2 (light mode).

Adding the border sounds good! 👍
