### ISSUE TITLE
left scroll bar issue.

### ISSUE THREAD

**Issue by Hunnnn77** [withastro/docs#5877]
### 📝 Issue Description

![캡처](https://github.com/withastro/docs/assets/134451251/4b86603b-e322-4f6c-9234-c4739b5de20b)

### 📋 On which page(s) it occurs

entire page, seems it's default behavior.

### 🤔 Expected Behavior

stay position of scrollbar beside selected article.

### 👀 Current Behavior

whenever i clicked each new articles, scrollbar has positioned at the top(initialized scroll position). that's annoying!

### 🖥️ Browser

firefox

**Comment by TheOtterlord** [comment]
Thanks for the report! We have an [existing open issue (#5771)](https://github.com/withastro/docs/issues/5771) for this, so I'll close this as duplicate, but it's good to know there's a strong want for this. I'll try to find some time over the next week or so to look at this further.
