### ISSUE TITLE
⚠️ Issue Reading Time 

### ISSUE THREAD

**Issue by sahillangoo** [withastro/docs#5896]
I used reading time as per the [documentation](https://docs.astro.build/en/recipes/reading-time/) but got this error,
Im using the markdown layout!

1. Install Helper Packages ✅
2. Create a remark plugin. ✅
3. Add the plugin to your config.✅
4. Display Reading Time. ❌

```
Cannot destructure property 'minutesRead' of 'Astro2.props.frontmatter' as it is undefined.
```

**Comment by VoxelMC** [comment]
If you are able, can you see if this works?

```jsx
---
const { frontmatter } = Astro.props;
---

<html>
  <head>...</head>
  <body>
    <p>{frontmatter.minutesRead}</p>
    <slot />
  </body>
</html>
```

There is probably no reason for this to work any differently, but maybe we can start here?

**Comment by sahillangoo** [comment]
Not working , Link to [repo](https://github.com/sahillangoo/sahillangoo.github.io):
![image](https://github.com/withastro/docs/assets/40671195/832f9faa-4609-41e3-a357-e1544b73cdb0)

**Comment by TheOtterlord** [comment]
Hey @sahillangoo! Looks like your repo is empty, but looking at the screenshot I see a `CollectionEntry` type. The `frontmatter` Astro prop only exists if you're using [markdown templating](https://docs.astro.build/en/guides/markdown-content/#frontmatter-layout) instead of content collections. If your markdown is coming from content collections (like it looks to be here), you can instead use the example from the previous snippet in the recipe:

```astro
---
import { CollectionEntry, getCollection } from 'astro:content';

export async function getStaticPaths() {
  const blog = await getCollection('blog');
  return blog.map(entry => ({
    params: { slug: entry.slug },
    props: { entry },
  }));
}

const { entry } = Astro.props;
const { Content, remarkPluginFrontmatter } = await entry.render();
---

<html>
  <head>...</head>
  <body>
    ...
    <p>{remarkPluginFrontmatter.minutesRead}</p>
    ...
  </body>
</html>
```

Let me know if this helps!

**Comment by sahillangoo** [comment]
My Bad i was troubleshooting deployment had to reinitiate the [repo](https://github.com/sahillangoo/sahillangoo.github.io) 
Yeah I have the content collection and the above snippet works as already mention in the recipe but i want it in the layout!
So used the other one but now i have add it as a prop and it works like a charm!
Thanks for helping!
```
<BlogPost {...data} timetoread={remarkPluginFrontmatter.minutesRead}>
	<Content />
</BlogPost>
```

**Comment by TheOtterlord** [comment]
Glad we could help!
