### ISSUE TITLE
Handle errors in dynamic image import recipe

### ISSUE THREAD

**Issue by TheOtterlord** [withastro/docs#5905]
Handle errors to avoid an obscure not a function error.

see: https://github.com/withastro/docs/pull/5898#issuecomment-1868329451

**Comment by VoxelMC** [comment]
I can add this shortly!

**Comment by VoxelMC** [comment]
@Princesseuh Sorry to bother you, but I just want to ensure this is correct!
About your comment here: https://github.com/withastro/docs/pull/5898#issuecomment-1868329451

So, as the `import.meta.glob` function returns an object with `path: Function` pairs, if you access a path that isn't there, the function can't be called. Here are the three strategies ***I*** would use to tackle this, and let me know which makes more sense for Astro.

### 1. Nullish Coalesce the function, then call it later:
This makes more sense if you can use a default image.
```tsx
---
const { imagePath, ... } = Astro.props;
const images = import.meta.glob<{ default: ImageMetadata }>('src/assets/*.{jpeg,jpg,png,gif}');
const loadImage = images[imagePath] ?? images['src/assets/default-image.png'];
---
<Image src={ loadImage() } alt={...} />
```

### 2. Conditionally Render the image:
If it's better not to have the image at all.
```tsx
---
const { imagePath, ... } = Astro.props;
const images = import.meta.glob<{ default: ImageMetadata }>('src/assets/*.{jpeg,jpg,png,gif}');
const loadImage = images[imagePath];
---
{ loadImage && <Image src={ loadImage() } alt={...} /> }
```

### 3. Just throw an error:
```tsx
---
const { imagePath, ... } = Astro.props;
const images = import.meta.glob<{ default: ImageMetadata }>('src/assets/*.{jpeg,jpg,png,gif}');
if (!images[imagePath]) throw new Error("Image not found in glob pattern: src/assets/*.{jpeg,jpg,png,gif}");
---
<Image src={ images[imagePath]() } alt={...} />
```

#### Alternatively, I could just leave it to the reader and put this in a `:::warning` block:

```tsx
---
const { imagePath, ... } = Astro.props;
const images = import.meta.glob<{ default: ImageMetadata }>('src/assets/*.{jpeg,jpg,png,gif}');
// if imagePath is not a valid file in the glob, images[imagePath]() will log an error.
---
<Image src={ images[imagePath]() } alt={...} />
```
@sarah11918 I would also greatly appreciate your opinion on this :)

**Comment by sarah11918** [comment]
I think I like including the built-in logic for the error with the `if` statement. I say go with that! @VoxelMC

**Comment by kaishin** [comment]
As someone who's new to Astro and who came across this today, I'd vote for 3 as well as it would give me the choice to decide how I want to handle it.

**Comment by VoxelMC** [comment]
> As someone who's new to Astro and who came across this today, I'd vote for 3 as well as it would give me the choice to decide how I want to handle it.

Perfect - I will make that PR now for review! Please feel free to have a look
