### ISSUE TITLE
Incorrect code in "Build a blog" tutorial

### ISSUE THREAD

**Issue by Haimantika** [withastro/docs#5952]
### 📚 Subject area/topic

Build a blog tutorial

### 📋 Page(s) affected (or suggested, for new content)

https://docs.astro.build/en/tutorial/4-layouts/1/

### 📋 Description of content that is out-of-date or incorrect

The code in the file `BaseLayout.astro` mentions to import the header from `Header.astro` file, but in the previous steps, we added the header in the `Navigation.astro` file.

### 🖥️ Reproduction in StackBlitz (if reporting incorrect content or code samples)

<img width="1512" alt="Screenshot 2023-12-26 at 7 49 35 PM" src="https://github.com/withastro/docs/assets/32809211/dfec9373-c4b3-4cdc-aeef-54a5f0f99611">

**Comment by Haimantika** [comment]
I am interested to contribute and solve the issue. Please assign it to me :)

**Comment by sarah11918** [comment]
Hi @Haimantika This is not an error with the tutorial, but means that the import statement for the Header component that you built at this step is incorrect: https://docs.astro.build/en/tutorial/3-components/3/#try-it-yourself---build-a-new-header-component

At this point in the tutorial, the Navigation component should now be inside the Header component.
