### ISSUE TITLE
Slots can also be Fragments besides HTML elements, but it's not explained

### ISSUE THREAD

**Issue by mauriciabad** [withastro/docs#5959]
On the [Components page > Named slots section](https://docs.astro.build/en/core-concepts/astro-components/#named-slots), it is not explained that on the parent component, a slot can be declared as a `<Fragment>` if the developer doesn't want to declare it in an HTML element. This pattern is useful for adding classes to the slot from the child component.

For example:

```astro
---
// Wrapper.astro
import CustomTable from './CustomTable.astro';
---
<CustomTable>
  <Fragment slot="header"/>
    <tr><th>Column 1</th><th>Column 2</th></tr>
  </Fragment>
  <Fragment slot="body"/>
    <tr><td>A1</td><td>A2</td></tr>
    <tr><td>B1</td><td>B2</td></tr>
    <tr><td>C1</td><td class="font-bold">C2</td></tr>
  </Fragment>
</CustomTable>
```

```astro
---
// CustomTable.astro
---
<table class="bg-white">
  <thead class="sticky top-0 bg-white"><slot name="header"/></thead>
  <tbody class="[&_td:nth-child(odd)]:bg-gray-100"><slot name="body"/></tbody>
</table>
```

I had exactly this use case, and couldn't find another way to add classes to `thead` and `tbody` on the child component. But using Fragments was not obvious to me, since it's not explained in the slots documentation.

**Comment by sarah11918** [comment]
I think maybe where the docs could be clearer is that when we describe that a name attribute can be used on any "child element", that refers to any templating element (not just HTML elements, but also components) defining content to be passed to a slot. Yes, our examples do only show HTML elements, but it's also how Astro components are passed as children to framework components as children on the UI Frameworks guide page.

I know I've seen others use the `<Fragment slot="name" >` pattern as well, so if it would be helpful to include this pattern, then I think that makes sense! I'll make a quick addition to docs today!
