### ISSUE TITLE
`compilerOptions.paths` in `tsconfig` isn't respected for TypeScript Astro configs (`astro.config.ts`)

### ISSUE THREAD

**Issue by romannurik** [withastro/docs#6003]
### Astro Info

```block
(Note, this command only worked once I temporarily removed changes to `astro.config.ts`)

Astro                    v4.0.8
Node                     v18.16.0
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

According to [the docs](https://docs.astro.build/en/guides/configuring-astro/#:~:text=TypeScript%20config%20file%20loading%20is%20handled%20using%20tsm%20and%20will%20respect%20your%20project%20tsconfig%20options.):

> TypeScript config file loading is handled using tsm and will respect your project tsconfig options.

However, the following setup doesn't actually compile:

**tsconfig.json**
```json
{
  "extends": "astro/tsconfigs/strict",
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@/util/*": ["./src/util/*"],
    }
  },
}
```

**astro.config.ts**
```ts
import { defineConfig } from 'astro/config';
import { helloWorld } from '@/util/hello-world';
helloWorld();
export default defineConfig({});
```

**src/util/hello-world.ts**
```ts
export function helloWorld() { console.log('it worked!'); }
```

The error you get varies by environment but it's essentially something similar to:
> Cannot find module '@/util/hello-world' imported from '/absolute/path/to/astro.config.ts'

As soon as you stop using the alias in `astro.config.ts`, it works as expected:
```diff
 import { defineConfig } from 'astro/config';
-import { helloWorld } from '@/util/hello-world';
+import { helloWorld } from './src/util/hello-world'; 
 helloWorld();
 export default defineConfig({});
```

This is obviously a contrived example, but I have a more real world case that this affects more dramatically (wiring up a Socket.io server as a custom vite plugin that uses TS code shared between client / server / vite-plugin).

### What's the expected result?

The aliases defined in `tsconfig.json` should work per the docs.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-u2tsfo?file=astro.config.ts

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by sarah11918** [comment]
Someone please make a PR and add the necessary sentence so we can start the new year with zero issues!!  😉 🍾

**Comment by gsi-kevincarrera** [comment]
I'm on it

**Comment by VoxelMC** [comment]
> Someone please make a PR and add the necessary sentence so we can start the new year with zero issues!!  😉 🍾 

If no one gets to it before I get home and finish my Master's application, I can do it!

**Comment by gsi-kevincarrera** [comment]
@sarah11918 I think we can start the year with zero issues ;)
