### ISSUE TITLE
Unclear, which dependencies needed for node adapter at runtime

### ISSUE THREAD

**Issue by angryziber** [withastro/docs#6019]
### Astro Info

```block
Not relevant
```

### Describe the Bug

It seems that having only @astrojs/node as runtime dependency fails.

Adding the whole "astro" package to runtime dependencies is an overkill, but also not enough.

### What's the expected result?

It should be clearly stated which astro dependencies should be in dev, and which are needed for runtime, possibly a minimal set, not everything that is required for building.

### Link to Minimal Reproducible Example

Not relevant

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by sarah11918** [comment]
Hi! We actually do document a recommendation to put everything in `dependencies` to start, and then use `devDependencies` when you find a specific need to do so. In most cases, for Astro it doesn't make a difference. When it does, you can then use `devDependencies`: https://docs.astro.build/en/core-concepts/project-structure/#packagejson

We have discussed this internally a few times, and we do tend to always come back to this statement, so I don't think we'll be updating it at this time.
