### ISSUE TITLE
Remove wrapping <p> tags around <ImportMetaEnv /> component

### ISSUE THREAD

**Issue by sarah11918** [withastro/docs#612]
When https://github.com/withastro/astro/pull/3410 is merged, we should no longer need to wrap `<ImportMetaEnv />` in `<p>` tags.

- Track down all the places this is used (API config, RSS, ...?) and try removing the `<p>` tags... and see what happens!
- Check for any other components we might be using in Markdown by looking for `setup: ` in the frontmatter and try similarly removing any wrapping html elements.

BONUS: Try seeing whether this merged PR means we can actually render `import.meta.env` directly in Markdown, without the need for a component!

**Comment by natemoo-re** [comment]
I spent about 30 mins trying to get `import.meta.env` working in `.md` files and it's still really difficult. Was hoping for an easy fix, but no luck.

[The Markdown PR](https://github.com/withastro/astro/pull/3410) should still help a lot! But I also opened https://github.com/withastro/astro/issues/3412 to track the larger issue here.
