### ISSUE TITLE
Next JS being called out as `built for client-side rendering of your entire website and include server-side rendering mainly to address performance concerns` might be confusing for new developers

### ISSUE THREAD

**Issue by itsnoa04** [withastro/docs#6175]
I would like to suggest a change in the Core Concepts > Why Astro > Server First paragraph of the astro docs as it calls out Next JS as a Framework built for client-side rendering of your entire website and include server-side rendering mainly to address performance concerns, I would imagine this to be confusing for a new developers in the future given the current direction vercel is taking Next and all the marketing and popularity behind it.

Please correct me if my interpretation is incorrect.

**Comment by sarah11918** [comment]
We are satisfied with our current description, thanks!
