### ISSUE TITLE
Replace terrible tables with headings, bullets etc.

### ISSUE THREAD

**Issue by sarah11918** [withastro/docs#6201]
### 📚 Subject area/topic

API reference

### 📋 Page(s) affected (or suggested, for new content)

https://docs.astro.build/en/reference/api-reference/
(check for more)

### 📋 Description of content that is out-of-date or incorrect

We really can't put up with these tables any longer!  :sweat_smile: 

![image](https://github.com/withastro/docs/assets/5098874/899b6c31-686b-48f1-a350-0c6f6f41b500)

Use other entries on this, and on the configuration reference page, for inspiration to display this content sensibly. (Headings are never bad. Listed as bullet points *may* work, but we'd need to see them in action.)

**Comment by SatanshuMishra** [comment]
Would love to do this if it's alright! 👀

**Comment by VoxelMC** [comment]
### Tables are **OUT**
**Bold:** `'code,'`
- and maybe bullets?

are **IN**

**Comment by sarah11918** [comment]
@SatanshuMishra Would be happy to have you do this! I'm sure @VoxelMC would also be happy to provide an extra pair of eyes to help get something that is consistent with the rest of docs.  Please feel free to make a PR, and I'll take a look at what you come up with and we can all figure out exactly what we want after we see it.Thank you!

**Comment by SatanshuMishra** [comment]
Thank you and Sounds good! I will have a PR up soon :)!
