### ISSUE TITLE
Add a new common problem to the lit integration section

### ISSUE THREAD

**Issue by sanabel-al-firdaws** [withastro/docs#6227]
### 📚 Subject area/topic

DX and LSP

### 📋 Suggested page

https://docs.astro.build/en/guides/integrations-guide/lit/#troubleshooting

### 📋 General description or bullet points (if proposing new content)

https://discord.com/channels/830184174198718474/1166792409301123124

Currently when importing a lit component adding an attribute to it for example :

\<Greet name="Fred" \>
the Astro vs code extension will give error about the attribute

for first time users they might think they are doing something wrong

changing the Lit example to the hello world of Lit will fix this issue 
https://lit.dev/playground/#sample=examples/hello-world

```
---
import { SimpleGreeting } from './simple-greeting';
---

<SimpleGreeting name="Bob" />
```

it would be nice adding "Astro extension dosen't support lit elements intilesene "

**Comment by sarah11918** [comment]
This issue hasn't seen activity recently! 

We would welcome a PR to the `@astrojs/lit` integration page in docs updating the troubleshooting section:

> Common issues are listed below:
>
> Astro does not support IntelliSense for Lit components.

**Comment by sasoria** [comment]
Awesome, I'll pick this up later today!
