### ISSUE TITLE
Astro.props entry in the API Reference page

### ISSUE THREAD

**Issue by delucis** [withastro/docs#632]
### Discussed in https://github.com/withastro/docs/discussions/630

---

<div type='discussions-op-text'>

<sup>Originally posted by **@ekafyi** May 23, 2022</sup>
Would it be a good idea to add an entry for `Astro.props` in https://docs.astro.build/en/reference/api-reference ?

While it has been briefly addressed in https://docs.astro.build/en/reference/api-reference/#data-passing-with-props, people may not know that eg. `Astro.props` contain the HTML element `tag` property, which can be used to render an element polymorphically, as discussed in https://discord.com/channels/830184174198718474/830184175176122389/977974602431086632

</div>

---

<div type='discussions-op-text'>

<sup>Originally posted by **@delucis** May 23, 2022</sup>
Great idea! We should definitely include `Astro.props` on that page.

About dynamic tag rendering: there's nothing “special” about a `tag` prop so I'm not sure this would go there. You could name your prop `is` or `as` for example and it would also work. All that needs to happen is for you to use a variable that is a string, so that could come from a prop or something else:

```astro
---
const El = 'div'
---
<El>Hello!</El>
```

</div>

---

<div type='discussions-op-text'>

<sup>Originally posted by **@sarah11918** May 23, 2022</sup>
This does seem like a huge ommision, since it's something EVERYBODY uses! Great call, @ekafyi !

I think this rises to the level of "Issue", if you'd like to make one so it gets on the task list.

</div>

**Comment by sarah11918** [comment]
Just updating: I have asked in core-docs channel whether someone is willing to provide some content for this.

**Comment by delucis** [comment]
v1 triage call notes:

- We should definitely add `Astro.props` to the API Reference!

- Splitting out the dynamic tag name technique to a separate issue: #1180 (lower priority)

**Comment by FredKSchott** [comment]
Just chatted with @bholmesdev about this and how to balance it with the MDX tasks remaining for v1.0. Any chance that @sarah11918 or @delucis could do the work to create the basic `Astro.props` reference section using the content that already exists here: https://docs.astro.build/en/core-concepts/astro-components/#component-props

And then Ben could come in to fill in any info still missing?

**Comment by sarah11918** [comment]
Closing this, as done. PRs welcome if it needs to change!
