### ISSUE TITLE
Use new ESLint plugin to dogfood it

### ISSUE THREAD

**Issue by delucis** [withastro/docs#634]
@FredKSchott [suggested on Discord](https://discord.com/channels/830184174198718474/830184175176122389/978400069042704464) we add the new ESLint plugin to dogfood it and give feedback to the author. Plugin repo is here: https://github.com/ota-meshi/eslint-plugin-astro

**Comment by delucis** [comment]
@Chrissdroid This issue was more about _using_ the new plugin in the repo, but for sure we could also share that this tool exists. Same for the Prettier plugin which we don‘t mention anywhere. These _could_ go in Editor Setup, although in a way this is all “ecosystem” stuff that maybe we need to think about how best to showcase.

There have been discussions about improving [the integrations showcase](https://astro.build/integrations/) and maybe this is something for there: having a tooling category for Prettier, ESLint, etc.

That way we could share a link in Editor Setup saying “Looking for more tooling like Prettier, ESLint, and more? Check out the showcase”

**Comment by Chrissdroid** [comment]
Ohhh, I see

It could be so cool to expend the integrations list and give more visibility to awesome projects
