### ISSUE TITLE
On mobile browsers, the navigation on the tutorial page, the link colors are saturated and harsh.

### ISSUE THREAD

**Issue by liruifengv** [withastro/docs#6424]
### 📋 Explain your issue

![7c3c38717a45761eae9f445f600c834](https://github.com/withastro/docs/assets/25167721/5ac6a949-99b6-4554-8e78-75f7b23ea835)

On mobile browsers, the navigation on the tutorial page, the link colors are saturated and harsh.

Also chrome and safari.

**Comment by TheOtterlord** [comment]
Thanks for reporting! I'll try to fix this today

**Comment by TheOtterlord** [comment]
@liruifengv could you confirm if this PR fixes your issue? I was unable to replicate this exact screenshot, but I'm 99% sure this should fix it: https://github.com/withastro/docs/pull/6438

**Comment by liruifengv** [comment]
> @liruifengv could you confirm if this PR fixes your issue? I was unable to replicate this exact screenshot, but I'm 99% sure this should fix it: https://github.com/withastro/docs/pull/6438

![image](https://github.com/withastro/docs/assets/25167721/25d1c630-4ae7-4d2d-865b-316b23a28980)

Sure. Looks great now. Thank you!
