### ISSUE TITLE
links to `#anchor` when the target page is not translated

### ISSUE THREAD

**Issue by sarah11918** [withastro/docs#646]
A general comment about links to `#anchor` when the target page is not translated: the user will not see the message "This page hasn't been translated yet". This might surprise the user, because they are not expecting to see English and do not see the warning. Maybe the warning needs to be sticky/absolutely-positioned?

_Originally posted by @jbrains in https://github.com/withastro/docs/pull/463#discussion_r880881262_

**Comment by sarah11918** [comment]
Agreed that @hippotastic had a great idea... just wondering, didn't we discuss this very thing a loooooong time ago? Was @Yan-Thomas involved in that? I can't remember why we didn't go that route?

**Comment by hippotastic** [comment]
I also had a slight déjà-vu moment while suggesting that approach, but couldn't find any prior discussion on Discord. :)

**Comment by delucis** [comment]
There was discussion of this. Don't remember where. The tricky thing is the link looks like `/fr/page-in-english` so we can't do this based on link alone — any plugin would need to be aware of the translated pages.

**Comment by hippotastic** [comment]
As the sidebar can do it, I'm confident the plugin can also achieve this! :)

**Comment by delucis** [comment]
Found the existing discussion: https://github.com/withastro/docs/discussions/590

**Comment by delucis** [comment]
Yeah. An automated solution seems good at this point. So do we by any chance have someone around who has familiarised themselves to a great depth with remark? 🤔

**Comment by hippotastic** [comment]
I can give it a shot tomorrow!

**Comment by delucis** [comment]
Awesome, thanks Hippo!

**Comment by sarah11918** [comment]
Chris: perfects something
Hippo: I will make this redundant tomorrow.

**Comment by hippotastic** [comment]
> Chris: perfects something
> 
> Hippo: I will make this redundant tomorrow.

Oh no, that wasn't my intention at all! 😅 I already felt bad suggesting an alternative approach after all the work Chris put into the notice, now I feel even worse! 🙈

**Comment by sarah11918** [comment]
Not my intention, Hippo! And sorry, that was probably a better comment for Discord! 

I think we all feel good about this direction, and appreciate your ability to tackle problems, or else I wouldn't have been so joking about it.

**Comment by hippotastic** [comment]
I've just had a look at this, and it seems that the tough part is not the Markdown plugin, but the styling! 😄

There are at least 4 different ways on how we could style the `EN` suffix of fallback links. I need your input to select one of them (or come up with an even better one).

Please compare them, especially how they mix with punctuation. Which variant do you prefer?

### Variant 1: In link color, underline ends before
![image](https://user-images.githubusercontent.com/6137925/175285876-c1cf2e01-1c79-4608-9b63-55c67d2c4073.png)

### Variant 2: In link color, underline continues
![image](https://user-images.githubusercontent.com/6137925/175285893-e1498c20-d2ae-4432-91fa-d6763edc4369.png)

### Variant 3: In lighter text color, underline ends before
![image](https://user-images.githubusercontent.com/6137925/175285932-29f3a02d-3c63-4977-bd1e-7b89b9507a32.png)

### Variant 4: In lighter text color, underline continues
![image](https://user-images.githubusercontent.com/6137925/175285939-f958753e-e4ed-4050-8d4d-6cc20cb8f17a.png)

**Comment by hippotastic** [comment]
We can do a quick emote poll maybe.
- Variant 1: 🎉
- Variant 2: ❤
- Variant 3: 🚀
- Variant 4: 👀

**Comment by sarah11918** [comment]
We can do a poll, but variant 1 is the only one I find acceptable. ;)

**Comment by delucis** [comment]
The bit that bugs me is the weird gap around punctuation, so wonder if just:

> Text with [link to fallback (EN)](#).

Could make sense?

**Comment by hippotastic** [comment]
The weird gap next to punctuation is the reason why I found this so difficult, too.

Apparently, @sarah11918 doesn't seem to mind that gap, though 😄

**Comment by sarah11918** [comment]
I am OK with either superscript and slightly off punctuation (I do like the instinct to put it , and would personally be willing to sacrifice Perfect Punctuation Positioning if that were the will of the group) or Chris' suggestion.

I already sort of dislike how code words  inside larger link phrases come out formatted, so PPP isn't that big a deal to me. But, I also don't hate (EN)!

**Comment by hippotastic** [comment]
I like your suggestions with a regular text suffix. Hope it's not an issue in any of our languages to put a fixed suffix like that in the regular text/link flow.

**Comment by sarah11918** [comment]
Correct, @hippotastic ! I am surprisingly tolerant of the gap! But, not attatched to it!

**Comment by delucis** [comment]
Sounds good to me!
