### ISSUE TITLE
Include link to Stackblitz starter in the Incorrect Content Report 📄 template?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [withastro/docs#6550]
I'm filing a new issue with [Issue: Incorrect Content Report 📄](https://github.com/withastro/docs/issues/new?assignees=&labels=improve+documentation&projects=&template=CONTENT.yml). It asks for a Stackblitz reproduction - but doesn't directly provide a link to it. Mind if I add a link to https://astro.new for convenience? 🙂

**Comment by TheOtterlord** [comment]
Sorry for the wait :sweat_smile:
That sounds like a great addition!
