### ISSUE TITLE
⚠️ Issue: githubpages - broken links

### ISSUE THREAD

**Issue by ya-lops** [withastro/docs#6608]
I am following all the instructions to publish the site on github pages. deployment occurs, but absolutely all links are broken. You can check the hosted site based on the official portfolio template at https://ya-lops.github.io/art-i/

**Comment by mingjunlu** [comment]
Hi @ya-lops,

Try these to see if it works:

1. Set `site` and `base` in astro.config.mjs
  ```javascript
  export default defineConfig({
    site: 'https://ya-lops.github.io',
    base: '/art-i',
  });
  ```
2. Prefix internal links with the base `/art-i/`
  ```astro
  // Before
  <CallToAction href="/work/">...</CallToAction>

  // After
  <CallToAction href="/art-i/work/">...</CallToAction>
  ```

Reference: [Deploy your Astro Site to GitHub Pages](https://docs.astro.build/en/guides/deploy/github)

**Comment by ya-lops** [comment]
> Try these to see if it works:
> 
> 1. Set `site` and `base` in your....

I completely forgot about it. Thank you. helped!
