### ISSUE TITLE
📘 DOC:  Installation instructions for lsp-mode / emacs

### ISSUE THREAD

**Issue by komali2** [withastro/docs#6764]
The LSP server for astro is listed incorrectly on the LSP mode documentation as automatically installable: https://emacs-lsp.github.io/lsp-mode/page/lsp-astro/#debugger-not-available

This is not hte case, see: https://github.com/emacs-lsp/lsp-mode/issues/4169

There is some manual "astro mode" with LSP support for astro you can add to your emacs config here: https://github.com/emacs-lsp/lsp-mode/issues/3584#issuecomment-1321204879

However it would be nice to have this documented on the LSP server implementation within this repository.

**Comment by sarah11918** [comment]
Closing this as a docs issue as it is not something that we are actively looking to address ourselves. But we are happy to receive a Docs PR as Erika describes if there is an external resource we could/should be linking to that is not covered there!
