### ISSUE TITLE
Improve alpine documentation on the use of the entrypoint or script

### ISSUE THREAD

**Issue by javadude24** [withastro/docs#6773]
### Astro Info

```block
import { defineConfig } from 'astro/config';
import alpine from '@astrojs/alpinejs';

export default defineConfig({
  // ...
  integrations: [alpine({ entrypoint: '/src/entrypoint' })],
});

/* entrypoint.ts file */
import type { Alpine } from 'alpinejs'
import intersect from '@alpinejs/intersect'

export default (Alpine: Alpine) => {
    Alpine.plugin(intersect)
}
```

### Describe the Bug

I have followed the instructions in documentation here:
https://docs.astro.build/en/guides/integrations-guide/alpinejs/#configuration-options

I tried to add the intersect plugin. However, when i tried an example, it claimed I needed to import the script file. It’s interested that the next section below shows importing the collapse plugin script file.
https://docs.astro.build/en/guides/integrations-guide/alpinejs/#usage

I thought by using the entrypoint method took the place for having to manually add the script file.

### What's the expected result?

Plugin to work without having to manually add script file

### Link to Minimal Reproducible Example

https://docs.astro.build/en/guides/integrations-guide/alpinejs/#usage

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by sarah11918** [comment]
Closing this as this is not an issue that docs intends to address ourselves. But, if someone wants to make a PR specifically suggestion what would be more helpful to have in docs, we would look at it!
