### ISSUE TITLE
Improve documentation around `astro sync`

### ISSUE THREAD

**Issue by florian-lefebvre** [withastro/docs#6780]
### 📋 Explain your issue

Once https://github.com/withastro/astro/pull/9906 lands, types won't be broken by default when using Content Collections. `astro sync` will still be useful (hence needs to be recommended) but we can probably reduce the prominence of the callouts.

**Comment by sarah11918** [comment]
This landed! What would you like to see changed in docs as a result?

**Comment by florian-lefebvre** [comment]
I don't remember exactly but we talked about this with nate. Basically, I think the idea would be to encourage to run `astro sync` to get high fidelity types, but not tell users to run it or your types will be completely broken. Hope that makes sense 😅! An example of place where this could be improved is https://github.com/withastro/docs/pull/6272/files#diff-ec9625e9b89360bd7a29d0d392017cbb704e8890a12534044ca2374dddb9fdb5R181

**Comment by sarah11918** [comment]
@florian-lefebvre , are you still wanting to champion `astro sync` in docs?

If so, can you state clearly what kind of contributions you'd like (e.g. look for all instances where we suggest running `astro check` yourself, and ... don't do that? :smile: ) so we can put a help wanted tag on here and get people contributing?

**Comment by florian-lefebvre** [comment]
To be honest, it would be great to tackle this in #7058 because `astro sync` will change again! Let me know what you think

**Comment by sarah11918** [comment]
Sure thing, @florian-lefebvre ! Makes sense to get all the documentation updated and proper at once!

**Comment by florian-lefebvre** [comment]
Closing for now, I'll end up working on this anyway later on
