### ISSUE TITLE
Mention RSS Autodiscovery in RSS Guide

### ISSUE THREAD

**Issue by tylermercer** [withastro/docs#6802]
### 📚 Subject area/topic

RSS guide

### 📋 Suggested page

https://docs.astro.build/en/guides/rss/

### 📋 General description or bullet points (if proposing new content)

Something like this, as a new section before the `Next Steps` section in the RSS guide.

> ## Enabling auto-discovery of your RSS feed
>
> RSS autodiscovery, [as explained by the RSS Advisory Board](https://www.rssboard.org/rss-autodiscovery), is "a technique that makes it possible for browsers and other software to automatically find a site's RSS feed."
> 
> All you need to do is add a `link` tag to your site's `head` element, like so:
>
> ```html
> <link
>     rel="alternate"
>     type="application/rss+xml"
>     title="Your Site's Title"
>     href={`${Astro.site}rss.xml`}
> />
> ```
> 
> After you've done this, your readers can put your site's base URL into their RSS reader to subscribe to your posts, without having to find the specific URL of your RSS feed!

**Comment by tylermercer** [comment]
I've made this change on [a fork of this repo](https://github.com/tylermercer/docs/tree/mention-rss-autodiscovery), but didn't open a PR since the CONTRIBUTING.md says to start with an issue. 🙂

**Comment by sarah11918** [comment]
Hi @tylermercer ! This sounds like a great addition! We would welcome a PR with this guidance, and a link to the spec. Thank you for your patience as we work through issues, and I appreciate you filing an issue to discuss first!  😄
