### ISSUE TITLE
Sidebar reorganisation proposal

### ISSUE THREAD

**Issue by delucis** [withastro/docs#6845]
Prompted by #6791, I wanted to share a plan for the page sidebar to address a few longstanding issues.

#### **Current sidebar**

<img width="314" alt="docs sidebar featuring table of contents and a contribute section with links to contribute, edit, translate, and give feedback" src="https://github.com/withastro/docs/assets/357379/4efa1c6a-1cb3-4b92-a7c2-50f4e5a9e9a6">

####  **Overall aims**

* Stop using the page sidebar for links other than table of contents. Links here are inaccessible on narrower viewports.
* Create space for new helpful links, notably to[ https://community.astro.build](https://community.astro.build) 

####  **Proposal**

1. Move our edit and translate links down to the bottom of the page content. An edit link is displayed there already currently, we’d add the translation one.
2. Create a new page footer below the pagination arrows for additional links. Initially these would be our current “Contribute” and “Give Feedback” items from the sidebar, plus a new “Community” link.

Overall the result would look something like this:

<img width="837" alt="docs page section showing edit and translate links above the pagination arrows, and a footer below that with contribute, feedback, and community links" src="https://github.com/withastro/docs/assets/357379/8295544c-40dc-4bfc-9310-c4670b94c89c">

**Comment by sarah11918** [comment]
Just adding my approval here! I love this idea because it always bothered me that some links were not available in certain viewport sizes.

Now that we have https://community.astro.build and hope to use it for more, docs doesn't have to be the place that links to absolutely everything! If we link to just the community site, then people can get what they want in the right spot!

**Comment by sarah11918** [comment]
Still happy with this proposal!

**Comment by sarah11918** [comment]
Are we still liking this @delucis ? Is this something that we're happy to have community members attempt?

**Comment by delucis** [comment]
Definitely! Happy to provide any guidance if anyone would like to attempt all or some of this.

**Comment by SatanshuMishra** [comment]
Now that I've some more time, would love to take this on @delucis!

**Comment by sarah11918** [comment]
Bring it, @SatanshuMishra !  😄

**Comment by delucis** [comment]
> should a new component be created? Or do you think adding it to the pagination component is sufficient?

Either is probably fine to start with — we can always move things around. Personally, I'd probably make a dedicated component for the links and then add it to footer.

Thanks @SatanshuMishra!
