### ISSUE TITLE
Add Zed (code editor)

### ISSUE THREAD

**Issue by jacobdalamb** [withastro/docs#6863]
### 📚 Subject area/topic

Editor Setup

### 📋 Suggested page

https://docs.astro.build/en/editor-setup/

### 📋 General description or bullet points (if proposing new content)

- Add [Zed](https://zed.dev/) either as a heading along VSCode and Jet Brains or under "Other Code Editors"

**Comment by ElianCodes** [comment]
AFAIK Zed doesn't support `.astro` files?

**Comment by jacobdalamb** [comment]
> AFAIK Zed doesn't support `.astro` files?

Next release will include [Astro support](https://github.com/zed-industries/zed/commit/2e7db57e16d4940956f7b716d65dbc6675d82f7b)

**Comment by ElianCodes** [comment]
Ah yeah, I just saw the preview here: https://zed.dev/releases/preview.

We'll add it once it's stable and released

**Comment by sasoria** [comment]
It looks like there's support for Astro in the [latest release](https://zed.dev/releases/stable/0.123.2) of Zed.

**Comment by TheOtterlord** [comment]
Closing this w/ the same reason as the PR (see https://github.com/withastro/docs/pull/7225#issuecomment-2037356011)
