### ISSUE TITLE
Add utf8 to the language version of double-byte characters

### ISSUE THREAD

**Issue by ShortArrow** [withastro/docs#6866]
### 📚 Subject area/topic

tutorial

### 📋 Suggested page

https://docs.astro.build/ja/tutorial/2-pages/1/

### 📋 General description or bullet points (if proposing new content)

# Summary

For languages that use double-byte characters, there are cases where you need to specify UTF8.
In the case of Japanese Chrome, the characters are garbled.

Also, this information may be noise that deviates from the purpose of the tutorial. Therefore, if you have intentionally deleted it, I think it is better to keep it as is.

# Actual

```html
<body>
  <a href="/">ホーム</a>
  <a href="/about/">概要</a>
  <h1>私について</h1>
  <h2>... そして私の新しいAstroサイトについて！</h2>

  <p>
    私はAstroの入門チュートリアルを進めています。これは私のウェブサイトの2番目のページで、自分で作った初めてのページです！
  </p>

  <p>
    このサイトはチュートリアルを進めるにつれて更新されていきます。定期的にチェックして、私の旅の様子を見に来てください！
  </p>
</body>
```

![image](https://github.com/withastro/docs/assets/16986253/81ad8d7f-46a9-4b41-869b-69f555acc4f9)

# Expected

```html
<head>
  <meta charset="UTF-8" />
</head>
<body>
　<!-- existing codes -->
</body>
```

**Comment by liruifengv** [comment]
Thanks for your report. Chinese has the same problem. We can specify the encoding format through charset, or set it uniformly in the layout.

In this section, code other than the `body` may be omitted intentionally. Because it's already mentioned in https://docs.astro.build/en/tutorial/1-setup/3/#edit-your-home-page.

**Comment by ShortArrow** [comment]
@liruifengv Sorry, I didn't read ["Copy, or retype the contents of index.astro"](https://docs.astro.build/en/tutorial/2-pages/1/#:~:text=about.astro.-,Copy%2C%20or%20retype%20the%20contents%20of%20index.astro%20into%20your%20new%20about.astro%20file.,-Tip).
I will close this.
