### ISSUE TITLE
⚠️ Issue: installing fonts after installing tailwind, documentation guide seems out of date and following throws an error. 

### ISSUE THREAD

**Issue by mpstaton** [withastro/docs#6880]
I followed along with this instruction set:
https://docs.astro.build/en/guides/fonts/

Installed Inter with Yarn. 

I'm using tailwind so I added the suggested lines of code to the Tailwind config.  

First, the file name isn't tailwind.config.cjs it is now tailwind.config.mjs
Not sure if that's the cause of my error.  

So, this is my tailwind.config.mjs:

```
/** @type {import('tailwindcss').Config} */

const defaultTheme = require("tailwindcss/defaultTheme")

export default {
	content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
	theme: {
		extend: {
			fontFamily: {
				["InterVariable", "Inter", ...defaultTheme.fontFamily.sans],
			}
		},
	},
	plugins: [],
}
```
VSCode is telling me an "expression is expected" here: "...defaultTheme.fontFamily.sans],"
Your handy error visualization says this: [postcss] Unexpected token, expected "]" (10:21)"
pages/index.astro:63

I'm not experienced enough to know if this is a user error or not.  But, I followed your instructions and don't know what to make of what I'm seeing. And, at the very least the tailwind config file has a different extension and is structured differently in the latest version of Astro, so this documentation page is out of date.

**Comment by mpstaton** [comment]
FYI, whoever comes along, I just copy pasted your code and now it works fine.  

However, that's not the config file structure that latest tailwind now generates. So, I have no understanding if this is an issue or not.  However, I would expect you would want places flagged where your documentation is out of sync with the code that's live.

**Comment by TheOtterlord** [comment]
Thanks for raising this! Looks like this is using the old CommonJS format for the config. I'll make sure to update this today.

Looks like you're missing the key in `fontFamily` in your config. `fontFamily` should have the `sans` key, mapping to the array.
```ts
fontFamily: {
	["InterVariable", "Inter", ...defaultTheme.fontFamily.sans],
}
```

Once I've updated the docs, the new version (`tailwind.config.mjs`) should end up looking something like this
```ts
import defaultTheme from 'tailwindcss/defaultTheme'

/** @type {import('tailwindcss').Config} */
export default {
	content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
	theme: {
		extend: {
			fontFamily: {
				sans: ['Inter', ...defaultTheme.fontFamily.sans],
			},
		},
	},
	plugins: [],
}
```

**Comment by mpstaton** [comment]
Thanks @TheOtterlord
