### ISSUE TITLE
Remove Tigris from the Astro Integrations

### ISSUE THREAD

**Issue by RayyanNafees** [withastro/docs#6889]
### 📋 Explain your issue

Astro docs have the [Tigris Integration](https://docs.astro.build/en/guides/backend/tigris/#_top) which says Tigris being a  MongoDB / DynamoDB alternative NoSQLDB

Unfortunately the Project's direction is changed and Tigris is now an S3 compatible storage bucked (like Cloudflare R2) which makes no sense to be integrated with astro
Neither does it's JS SDK support the features any longer

The [Tigris Astro Integration](https://github.com/tigrisdata-archive/tigris-astro?tab=readme-ov-file) repository is also archived by the authors & it's [Get Started](https://www.tigrisdata.com/docs/quickstarts/quickstart-typescript/) page returns a 404

So please remove the integration from the Docs Site

**Comment by sarah11918** [comment]
Thank you for reporting this! I agree, it makes sense to delete this page. Are you interested in making a PR to remove the necessary files? 

To remove the guide, the following files/content will need to be removed:

- https://github.com/withastro/docs/blob/main/src/content/docs/en/guides/backend/tigris.mdx
- https://github.com/withastro/docs/blob/main/public/logos/tigris.svg

And, Tigris should be removed from:
- https://github.com/withastro/docs/blob/766019ef52bf4d6ceb51a6f5b9fb4fbae2ebee17/src/data/logos.ts#L75

**Comment by SatanshuMishra** [comment]
I am happy to take this on sometime soon. However, if @RayyanNafees wants to do it and gets to it before, that is alright!
