### ISSUE TITLE
Doc the solution for using Astro with Yarn 3 (Berry) issue

### ISSUE THREAD

**Issue by sarah11918** [withastro/docs#700]
As per this Bug in Astro: https://github.com/withastro/astro/issues/3450

(The last comment appears to have the solution.)

This probably goes in the Install page, a note or comment, and we should get feedback from core whether this is considered temporary, or a hack, or a more official "how to do it" to get the phrasing/presentation correct.

**Comment by retronav** [comment]
@sarah11918 Yes, let me get some more information on this and I will send a pull request 👍🏻

**Comment by retronav** [comment]
Since #749, #753 have this covered, I think this issue can be closed.

**Comment by delucis** [comment]
Indeed — thanks @retronav!
