### ISSUE TITLE
Outdated caution warning?

### ISSUE THREAD

**Issue by ttmc** [withastro/docs#7032]
In the Astro Docs about "Mixing Frameworks" (at https://docs.astro.build/en/guides/framework-components/#mixing-frameworks ), it says:

![Screenshot from 2024-02-25 12-41-53](https://github.com/withastro/docs/assets/1210951/4168a333-7a52-40db-ab45-0693d3cb2ce0)

I created an MDX page which contains both Astro and Svelte components, and it works fine.

I know MDX came later. Is the above Caution warning outdated? Or maybe it is strictly correct because an Astro component isn't the same as an Astro page? If it is, I don't understand how

**Comment by at-the-vr** [comment]
this might be debatable. [MDX](https://github.com/mdx-js/mdx/) is not a "framework", its a format prohibiting it to be included in [en/guides/framework-components/](https://docs.astro.build/en/guides/framework-components/).

Fortunately 😅 docs do cover MDX features [en/guides/markdown-content/](https://docs.astro.build/en/guides/markdown-content/#using-components-in-mdx)
