### ISSUE TITLE
No yarn version information

### ISSUE THREAD

**Issue by rgilsimoes** [withastro/docs#7134]
### 📚 Subject area/topic

Installation pre-requisites

### 📋 Page(s) affected (or suggested, for new content)

https://docs.astro.build/en/install/auto/
https://docs.astro.build/en/guides/upgrade-to/v4/

### 📋 Description of content that is out-of-date or incorrect

In the Astro installation section the prerequisites do not specify which yarn version is being considered (Classic or v2 aka berry).
Developers may use any version and when they try to follow the upgrade to v4 guide they don't have the "dlx" command if they are using the Classic version.
Following the yarn migrate to v2 guide works fine.

**Comment by sarah11918** [comment]
Hi! Yarn's own page recommends updating from their Classic version. We are not ultimately responsible for maintaining instructions for older versions of other services. It's likely that if you're intentionally on Yarn 1.x and not upgrading despite their own recommendation to do so when possible, then you are aware that you are running an older version, and will need to find/use older commands. 

So, this isn't something we're interested in adding/maintaining in our documentation.
