### ISSUE TITLE
Clarify reference to Astro.currentLocale in guides/internationalization.mdx? 

### ISSUE THREAD

**Issue by Because789** [withastro/docs#7152]
### 📚 Subject area/topic

Internationalization

### 📋 Page(s) affected (or suggested, for new content)

https://docs.astro.build/en/guides/internationalization/#browser-language-detection

### 📋 Description of content that is out-of-date or incorrect

Since I ran into the same issue as https://github.com/withastro/astro/issues/10017, namely taking way too long to find `Astro.currentLocale`, I'd suggest clarifying the reference to it in the internationalization guide. The paragraph starts with _"allow you to access **two** properties"_, which are only available in SSR mode. But then there is a list with **three** items, and one of them, `Astro.currentLocale`, is also available in SSG mode (at least if I understand it right). 

It also would be nice if the properties would get a link to the API reference (like to https://docs.astro.build/en/reference/api-reference/#astrocurrentlocale).

**Comment by sarah11918** [comment]
Ah yes, good call! The two properties were listed here first, and both are available only for SSR mode, and then the 3rd was added later and obviously that paragraph text was not updated to match.  

OK, so looks like what is needed here is:

- each of those three get a link back to the API reference
- the text can be updated to something like:

> Astro’s i18n routing combined with one of Astro’s [on-demand server rendering modes (output:'server' or output:'hybrid')](https://docs.astro.build/en/guides/server-side-rendering/) allow you to access two properties for browser language detection: Astro.preferredLocale and Astro.preferredLocaleList. Static sites and pre-rendered pages have access to `Astro.currentLocale`.

How about a change like that? I'd be happy to receive a PR to update the page!
