### ISSUE TITLE
What is 'serializable' front matter?

### ISSUE THREAD

**Issue by tinymachine** [withastro/docs#717]
I'm not clear on what 'serializable' means here wrt `define:vars`. Maybe there's a way to make this less jargon-y?

> Any *serializable* front matter variable is supported

https://github.com/withastro/docs/blob/c747f02e4420e5f36f3034074b03ac99d1444102/src/pages/en/reference/directives-reference.md?plain=1#L191

**Comment by sarah11918** [comment]
Thanks for this! Do you think linking this term to MDN web docs https://developer.mozilla.org/en-US/docs/Glossary/serialization would be enough help, for this reference page?

I will also raise this for consideration, to see what others think about expanding the detail here. Our Reference pages are intended to be more technical. So, I could see some prefering to keep as little explanation as possible on these pages, and instead linking externally to definitions elsewhere.

But, if the term is unfamiliar to a lot of readers, and if there is very little chance of them making a mistake without that added jargon there at all, then maybe having it there is more confusing than helpful?

**Comment by delucis** [comment]
I think it would be good to check with core exactly what is supported. I would usually understand serialisable to mean literals (string, number, boolean, and objects/arrays only containing the same). A good proxy for this is: what is left after `JSON.stringify` on your values. 

Is anything else supported by Astro? I know with framework component props (which are also serialised for hydration), Astro has or had some support for function serialisation right? Is that also the case here? I the absence of core I could run some tests to figure this out.

**Comment by sarah11918** [comment]
@zadeviggers Is expanding upon this description in your super-awesome directives page something that interests you?

**Comment by tinymachine** [comment]
Sounds good - thanks for the update, @delucis
