### ISSUE TITLE
`@astrojs/db` NPM page links to nonexistent documentation page

### ISSUE THREAD

**Issue by ThatOneCalculator** [withastro/docs#7234]
### 📋 Explain your issue

On https://www.npmjs.com/package/@astrojs/db , clicking on `Read the @astrojs/db docs` leads to https://docs.astro.build/en/guides/integrations-guide/db/ which 404's

**Comment by dreyfus92** [comment]
Hey @ThatOneCalculator, the docs of `astrojs/db` aren't ready for prod that's why it sends you to that `four-oh-four` page. They might be ready for the launch of [Astro Studio](https://studio.astro.build/)

**Comment by mayank99** [comment]
Looks like the docs are live now, this issue should be safe to close.
