### ISSUE TITLE
Meta Docs related repos do not have LICENSE files

### ISSUE THREAD

**Issue by emeraldsquirrel** [withastro/docs#7288]
### 📝 Issue Description

_sarah11918 in discord#feedback-ideas specifically asked me to file this issue on this specific repo._

**WHAT:** Some meta docs related repos do not have LICENSE files and are not copy-left. I would appreciate them to be MIT or CC-BY or equivalent.

**WHY:** When making my astro documentation website, I needed to come up with meta docs like `contributing`, `governance` and `i18n` translation guides for my site. Obviously Astro is a significantly larger project, however a subset of the text would make a great starting point or inspiration for my own meta docs.  In fact some of these documents on the astro repos specifically mention they themselves were inspired by other projects (like governance), but cannot themselves be used due to copyright.

I'd be happy to submit `LICENSE` pull requests if someone empowered/with authority could tell me they agree with applying a copy-left and which one to submit.

### 📋 On which page(s) it occurs

So far when trying to emulate astro's main website `contribute` and `translate this page` sidebar links, I have run into two repos that do not have licenses and are part of the larger meta docs, are linked directly or sub-linked from those pages.
- https://github.com/withastro/contribute.docs.astro.build -- specifically the translation instructions
- https://github.com/withastro/.github -- specifically `GOVERNANCE.md`

### 🤔 Expected Behavior

Being able to use meta-material on the astro and astro docs website through a copy-left license.

### 👀 Current Behavior

Copyrighted, cannot use the material.

### 🖥️ Browser

N/A

**Comment by sarah11918** [comment]
MIT Licenses added to both repos! Thank you for bringing this to our attention!
