### ISSUE TITLE
Unclear and duplicative table configuration reference for astro@db

### ISSUE THREAD

**Issue by goulvenclech** [withastro/docs#7321]
### 📚 Subject area/topic

Astro DB

### 📋 Page(s) affected (or suggested, for new content)

https://docs.astro.build/en/guides/integrations-guide/db/#table-configuration-reference
And
https://docs.astro.build/en/guides/astro-db/#table-references

### 📋 Description of content that is out-of-date or incorrect

<img width="752" alt="image" src="https://github.com/withastro/docs/assets/35667800/d7bd4c33-7333-4bd5-9716-ff2e4a11e453">

I think the content of [the first link](https://docs.astro.build/en/guides/integrations-guide/db/#table-configuration-reference) (see the screen above) is an incomplete/unclear version of the content of [the second link](https://docs.astro.build/en/guides/astro-db/#table-references) (see the screen below). Either the duplication should be removed, or a link to access the second link should be added. 

<img width="511" alt="image" src="https://github.com/withastro/docs/assets/35667800/4f93b401-d9aa-471d-8abf-cebb00c36c33">

I wasted a few minutes trying to "guess" how the references work from the first screen... But the example on the second one is really great!

**Comment by sarah11918** [comment]
Hi! I'm glad the reference section was clear enough for you on the db page itself!

There in fact is a link to that exact section just the line before your screenshot here. Hope that helps! :raised_hands: 

![image](https://github.com/withastro/docs/assets/5098874/68a40be3-32bc-47ad-a3d7-aada9cf7e915)
