### ISSUE TITLE
Other Editors - Neovim Setup

### ISSUE THREAD

**Issue by alcb1310** [withastro/docs#7339]
### 📋 Explain your issue

In the editor setup page, specific to the Neovim section, the configuration does not work properly *unless* you have the `prettier-plugin-astro` installed in the project you are working, the documentation should be specific about it.

**Comment by Princesseuh** [comment]
This issue has been fixed in our language-tooling, it should no longer crash when `prettier` and `prettier-plugin-astro` are not installed.
