### ISSUE TITLE
Add Bun to the Package Manager Tabs across the docs

### ISSUE THREAD

**Issue by Dax911** [withastro/docs#7376]
### 📚 Subject area/topic

Package Managers

### 📋 Suggested page

https://docs.astro.build/en/install/auto/
https://docs.astro.build/en/editor-setup
... most pages tbh

### 📋 General description or bullet points (if proposing new content)

Just adding the bun commands to the documentation.

**Comment by Dax911** [comment]
Working on the changes [here](https://github.com/Dax911/docs.git) if this is something the team is interested in.

**Comment by TheOtterlord** [comment]
Hi @dax911! We know Bun is working on supporting Astro, but Bun is not officially supported by Astro, so we are not including it in our documentation at this time. We do have a user-submitted recipe for [using Bun with Astro](https://docs.astro.build/en/recipes/bun/), and if there is an error on that page you are welcome to PR a correction! But we've decided that for the time being, we will not be adding additional package managers or runtimes to the docs.
