### ISSUE TITLE
Blog posts with broken links

### ISSUE THREAD

**Issue by f33w** [withastro/docs#7390]
### 📚 Subject area/topic

Blog

### 📋 Page(s) affected (or suggested, for new content)

https://astro.build/blog/whats-new-january-2024/
https://astro.build/blog/whats-new-december-2023/
https://astro.build/blog/introducing-content-collections/
https://astro.build/blog/astro-1/
https://astro.build/blog/astro-018/
https://astro.build/blog/astro-019/
https://astro.build/blog/astro-i18n/
https://astro.build/blog/astro-2100/

### 📋 Description of content that is out-of-date or incorrect

**https://astro.build/blog/whats-new-january-2024/**
1. This link https://astro.build/themes/details/astrofy/ **should be changed to this** https://astro.build/themes/details/astrofy-personal-porfolio-website-template/
2. https://starry-lens-test-space.vercel.app/
3. https://12steps.vercel.app/
4. https://sonar-team.github.io/doc/ **(You may want to change it to GitHub of the author https://github.com/Sonar-team)**

**https://astro.build/blog/whats-new-december-2023/**
1. https://birksovskiy.vercel.app/
2. https://hamza127.vercel.app/
3. https://caoutchou.vercel.app/

**https://astro.build/blog/introducing-content-collections/**
https://astro.new/docs

**https://astro.build/blog/astro-1/*
1. https://github.com/Jutanium
2. https://github.com/Yan-Thomas

**https://astro.build/blog/astro-18/**
1. https://github.com/withastro/astro/tree/main/packages/renderers/renderer-solid
2. https://github.com/withastro/astro/tree/main/packages/renderers/renderer-lit
3. https://developers.cloudflare.com/pages/framework-guides/astro

**https://astro.build/blog/astro-019/**
https://github.com/withastro/astro/blob/main/FUNDING.md

**https://astro.build/blog/astro-i18n/**
https://github.com/withastro/docs/blob/main/contributor-guides/translating-astro-docs.md

**https://astro.build/blog/astro-2100/**
https://github.com/withastro/astro/blob/refs/heads/next/packages/astro/CHANGELOG.md

**Comment by at-the-vr** [comment]
I think this Issue can be moved to https://github.com/withastro/astro.build
