### ISSUE TITLE
astro.build/db extremely laggy in mobile Firefox 123.1.0

### ISSUE THREAD

**Issue by aaarichter** [withastro/docs#7411]
### 📝 Issue Description

I just wanted to check the news regarding Astro DB on my mobile phone. But looking at astro.build/db with Firefox 123 causes  the browser to become very laggy (scroll behavior as well as browser functionality / UI)

### 📋 On which page(s) it occurs

https://astro.build/db

### 🤔 Expected Behavior

smooth scroll behavior, no CPU  freeze up

### 👀 Current Behavior

page seems to consume a lot of resources that freeze the browser

### 🖥️ Browser

Mobile Firefox 123.1.0

### 📄 Additional Information

my mobile: Samsung S8 with Android 9, Firefox has uBlock plugin

**Comment by delucis** [comment]
Thanks for reporting! Closing as a duplicate of https://github.com/withastro/astro.build/issues/997

**Comment by aaarichter** [comment]
thanks @delucis -  I opened this issue here, because the main page felt okayish, while the db one was really laggy. I assumed that it might have been a problem of the /db page
