### ISSUE TITLE
Adding an example for `<Content />` - mapping through posts

### ISSUE THREAD

**Issue by sarah11918** [withastro/docs#745]
A common use case is mapping through an array of posts, like from this Discord thread: https://discord.com/channels/830184174198718474/983477899971666012/983495572512206889

(code would need to be be stripped down for our example, as this was someone's very specific code)

```
---
export async function getStaticPaths() {
  const posts = await Astro.glob('../../../../../content/**/*.md')

  return posts.map((post) => {
    const filePath = post.file.split('/')
    const filename = filePath[filePath.length - 1].slice(0, -3)
    const date = new Date(post.frontmatter.date)
    const formattedMonth = ("0" + (date.getMonth() + 1)).slice(-2)
    return {
      params: { 
year: date.getFullYear(), month: formattedMonth, slug: filename },
      props: { post, date: post.frontmatter.date },
    };
  });
}
const { year, month, slug } = Astro.params;
const {post, date} = Astro.props
---
<h1>{year}</h1>
<h1>{month}</h1>
<h1>{slug}</h1>
<p>{date}</p>
<!--This is the wee bit your missing bud-->
<post.Content/> 
```
Here is another proposed example.

```
export async function getStaticPaths() {
  const posts = await Astro.glob('../data/posts/**/index.md')

  return await Promise.all(
    posts.map(async (post) => ({
      params: { slug: post.frontmatter.slug },
      props: {
        metadata: post.frontmatter,
        headers: await post.getHeaders(),
        content: post.Content,
      }
    }))
  )
}

const { metadata, headers, content: PostContent } = Astro.props
---
<PostContent />
```

Since this has come up a couple of times very recently, I lean towards including an expanded example. (I think, at least for now, I'm OK also keeping the one that's there? It can always be removed if we find it redundant later.)

Can we converge here in this issue on one single good, best-practices example that is clear and helpful, and then it can be PR'd to add it to the Markdown page under "Exported Properties" for `Content`?

Can we figure out here what's minimal enough, yet also helpful enough?

_Originally posted by @sarah11918 in https://github.com/withastro/docs/issues/669#issuecomment-1150592256_

**Comment by sarah11918** [comment]
Thanks for this! I have also let (and am letting) @aFuzzyBear know to check in here!

**Comment by aFuzzyBear** [comment]
Ill get on to this guys
