### ISSUE TITLE
Authorized remote images are not optimized in Markdown

### ISSUE THREAD

**Issue by 1574242600** [withastro/docs#7539]
### Astro Info

```block
Astro                    v4.5.8
Node                     v18.18.0
System                   Linux (x64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

> Use standard Markdown`![alt](src)` syntax in your .md files. This syntax works with Astro’s [Image Service API](https://docs.astro.build/en/reference/image-service-reference/) to optimize your local images and authorized remote images.
>[https://docs.astro.build/en/guides/images/#images-in-markdown-files](https://docs.astro.build/en/guides/images/#images-in-markdown-files)

Although the documentation says it will optimise "your local images and authorized remote images", it doesn't actually optimise authorized remote images.

### What's the expected result?

Authorized remote images will be optimized in Markdown.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-pqjmye

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Yeah, processing remote images in Markdown / MDX / Markdoc using the native syntax is currently not supported. It has never been since the feature has been introduced, so the docs is wrong on the matter

**Comment by irumaru** [comment]
Is there any possibility of implementing remote image optimization within markdown in the future?

**Comment by irumaru** [comment]
Is there any possibility of implementing remote image optimization within markdown in the future?

**Comment by OliverSpeir** [comment]
> Is there any possibility of implementing remote image optimization within markdown in the future?

Yeah it's possible the pieces are in place, the important consideration is inferSize makes a network request to get the dimensions of the image and that has some implications for on demand rendered Astro pages
