### ISSUE TITLE
Astro check command missing flags

### ISSUE THREAD

**Issue by lifeisfakenews** [withastro/docs#7542]
### 📚 Subject area/topic

astro cli commands

### 📋 Page(s) affected (or suggested, for new content)

https://docs.astro.build/en/reference/cli-reference/#astro-check

### 📋 Description of content that is out-of-date or incorrect

the only flag listed on the docs website for the astro check command is `--watch`
There are it turns out other flags that can be supplied such as `--minimumSeverity` or `--help`

**Comment by jmayergit** [comment]
Came to make this issue and saw it was already made 👍

In the language tools repository we can see the following flags

https://github.com/withastro/language-tools/blob/main/packages/astro-check/src/options.ts#L21
```
	minimumSeverity: {
		choices: ['error', 'warning', 'hint'] as const,
		description:
			'Minimum diagnostic severity to show. Choosing `warning` will, for example, show both errors and warnings, but not hints. ',
		default: 'hint',
	},
```

Which are not documented at this location in the docs repository, https://github.com/withastro/docs/blob/2f83515ba71f5a2138f1c7e47f74d12b3e0c38fb/src/content/docs/en/reference/cli-reference.mdx#astro-check.

**Comment by sarah11918** [comment]
Thank you both for pointing this out @lifeisfakenews and @jmayer -- especially pointing  ! 

Would love a PR to docs (following the existing format) if someone wants to add the missing flags!

**Comment by lifeisfakenews** [comment]
i can submit a PR with added flags
