### ISSUE TITLE
Incorrect remote markdown example

### ISSUE THREAD

**Issue by tinnamchoi** [withastro/docs#7629]
### 📚 Subject area/topic

Remote markdown

### 📋 Page(s) affected (or suggested, for new content)

https://docs.astro.build/en/guides/markdown-content/#fetching-remote-markdown

### 📋 Description of content that is out-of-date or incorrect

The original code may initially appear to work as `npm run dev` will re-fetch the content every time the page is refreshed, but running `npm run build` will reveal that in the actual behaviour, the content is only fetched at build time and is not in fact dynamically fetched during runtime.

**Comment by TheOtterlord** [comment]
Closing with https://github.com/withastro/docs/pull/7630#pullrequestreview-1971297941
