### ISSUE TITLE
Fixing Data Insertion Type Mismatch in Astro DB Table Definitions

### ISSUE THREAD

**Issue by suzulang** [withastro/docs#7792]
### 📚 Subject area/topic

astro-db

### 📋 Page(s) affected (or suggested, for new content)

https://docs.astro.build/en/guides/astro-db/

### 📋 Description of content that is out-of-date or incorrect

I will try to follow the documentation and configure astro-db.

The field names of the table provided in the documentation do not match the field names of the mock data in seed.ts

### 🖥️ Reproduction in StackBlitz (if reporting incorrect content or code samples)

**Title:**
Issues with Inserting Data into Astro DB using `astro:db`

**Body:**

Hello,

I'm working with Astro DB and encountered an issue while trying to insert data into a table. Below are the details of my setup and the problem I've encountered.

**Setup**
**Database Configuration (db/config.ts):**

```ts
// db/config.ts
import { defineDb, defineTable, column } from 'astro:db';

const Comment = defineTable({
  columns: {
    author: column.text(),
    body: column.text(),
  }
})

export default defineDb({
  tables: { Comment },
})
Data Seeding Script (db/seed.ts):
```
```ts
// db/seed.ts
import { db, Comment } from 'astro:db';

export default async function() {
  await db.insert(Comment).values([
    { authorId: 1, body: 'Hope you like Astro DB!' },
    { authorId: 2, body: 'Enjoy!'},
  ])
}
```
When I run this setup, it produces the following output (as seen in the attached image):

<img width="862" alt="image" src="https://github.com/withastro/docs/assets/155881657/bc9248ba-7fee-440a-8b21-7715af529835">

**Issue**
The compiler throws an error regarding the **authorId** field, which does not match the defined structure in **Comment** table where the field is named **author**.

**Solution Attempt**
I modified the database configuration and the seeding script as follows:

**Modified Database Configuration in db/config.ts:**

Changed `author: column.text(),` to `author: column.number(),`

**Modified Data Seeding Script (db/seed.ts):**

```ts
// db/seed.ts
import { db, Comment } from 'astro:db';

export default async function() {
  await db.insert(Comment).values([
    { author: 1, body: 'Hope you like Astro DB!' },
    { author: 2, body: 'Enjoy!'},
  ])
}
```
After making these changes, the script runs successfully, as shown in the attached image:
<img width="303" alt="image" src="https://github.com/withastro/docs/assets/155881657/bfdcb18f-e586-4542-a063-ba6263fc4b4d">

Questions
Is there a recommended approach for debugging such type-related issues in Astro DB?
Are there best practices for structuring database configurations and seeding scripts to avoid these kinds of issues?
Thank you for your assistance!

**Comment by sarah11918** [comment]
Hi @suzulang! 

As you're aware, Astro DB is a new and developing feature. I can see that you have questions about best practices, and we do not yet have established best practices for debugging. I am going to refer you to asking support questions in our Discord where some of our maintainers and community members may have suggestions as to how they debug, and structure their configurations.

You may also be interested in community resources that we have collected with various content and guides people have created to demonstrate their own process and usage of the feature. While we are still attempting to create comprehensive documentation, we are happy to showcase community content! There may be some content here that is useful or interesting: https://astro.build/blog/whats-new-march-2024/#showcase

I noted that you expressed interest in contributing to the docs in your earlier PR, and one way that helps us is when people create their own content, guides, articles and videos and then we do link to them from docs, for example: https://docs.astro.build/en/community-resources/content/#astro-db 

If you create content of your own, please do submit a PR to this page and we will link to it! I note that we ourselves do not yet have a "top to bottom" continuous example, so these guides people write to demonstrate an actual blog feature they have built are always appreciated, and we love to showcase community content!
