### ISSUE TITLE
Little problem in the `guides/images` file

### ISSUE THREAD

**Issue by pioupia** [withastro/docs#7820]
### 📚 Subject area/topic

guides

### 📋 Page(s) affected (or suggested, for new content)

https://docs.astro.build/en/guides/images/#images-in-public

### 📋 Description of content that is out-of-date or incorrect

Small problem with the `<img>` tag, which is not closed.
```html
<img src="/images/public-cat.jpg" alt="A sleeping cat." />
```
```html
<img src="https://example.com/remote-cat.jpg" alt="A sleeping cat." />
```

**Comment by Princesseuh** [comment]
`img` is a void tag, it does not require to be closed in HTML. Up to docs if they want to show one style or the other, but either way works!

**Comment by TheOtterlord** [comment]
We tend to not be too strict with the styles in our snippets, but also "[self-closing tags (`<tag />`) do not exist in HTML](https://developer.mozilla.org/en-US/docs/Glossary/Void_element#self-closing_tags)" and the trailing slash is ignored by browsers. There's no real difference between the two, so it's fine if there's some inconsistency here.
