### ISSUE TITLE
Minor typo

### ISSUE THREAD

**Issue by he00741098** [withastro/docs#7910]
### 📋 Explain your issue

On the life cycle section of the view-transitions page (https://docs.astro.build/en/guides/view-transitions/#lifecycle-events), there appears to be a small typo: "The <ViewTransition /> router fires a **number events** on the document during navigation".

**Comment by yanthomasdev** [comment]
Nice catch @he00741098, would you like to contribute with a PR fixing the typo? Or would you rather want us to handle it?

**Comment by he00741098** [comment]
I've submitted a pull request
