### ISSUE TITLE
Deploy Astro to Clever Cloud

### ISSUE THREAD

**Issue by juliamrch** [withastro/docs#7937]
### 📚 Subject area/topic

guide

### 📋 Suggested page

https://docs.astro.build/en/guides/deploy/

## New content proposal

At Clever Cloud, we provide [guides](https://developers.clever-cloud.com/guides/) for deploying different stacks on our automation platform. I'm reworking the Astro guide and I propose to adapt the content to include it in Astro docs. Guide would contain the following:

- Create an application (Node.js server or Static)
- Useful environment variables to deploy Astro
- Known issues

If you agree with this new content, fell free to assign me this issue and I'll be glad to open a PR at the start of May.

## Reviewing

If there is no CI/CD for review apps in this repo, I can provide a deployed version of the PR content.

**Comment by sarah11918** [comment]
Hi @juliamrch ! Community members are welcome to submit new deploy guides!

We ask that you use existing guides as a general model for format, structure etc. (Note: some of these guides are quite old and our standards might have changed a little over time. However, we will recognize and appreciate that you followed existing content and thank you in advance for understanding if we suggest editing comments that might contradict an existing guide.)

You can find more information about submitting one of these guides in our [Contributing Guide](https://contribute.docs.astro.build/guides/recipe-writing/#cms-deploy-and-migrate-to-astro-guides) where you can also find our basic writing/style guide.

So, I'm going to close this issue as it's not an "issue" for our docs repo per se! 😄  But, thank you for expressing your interest in submitting a guide here, and consider this an invitation to submit one!

**Comment by juliamrch** [comment]
Thank you for your answer! I wanted to check first if it was ok with you to take new guides. I will submit a PR with a new guide following your guidelines.

Have a great day!
