### ISSUE TITLE
Abount Fontsource package name

### ISSUE THREAD

**Issue by magurotabetai** [withastro/docs#7981]
### 📚 Subject area/topic

Usinc custom fonts

### 📋 Page(s) affected (or suggested, for new content)

https://docs.astro.build/en/guides/fonts/

### 📋 Description of content that is out-of-date or incorrect

Since Variable Fonts in fontsource start with @fontsource-variable/,  I thought it might be better to display "It will start with @fontsource/ or @fontsource-variable/ followed by the name of the font." instead of the tip "It will start with @fontsource/ followed by the name of the font."

**Comment by delucis** [comment]
Thank you for the issue @magurotabetai — would you like to make a PR with this change?

I checked the Fontsource docs and confirmed they are now also using that scope, see for example https://fontsource.org/fonts/inter/install

**Comment by magurotabetai** [comment]
I would like to gain experience contributing to OSS, so I would like to create a PR for sure!
