### ISSUE TITLE
PT-BR pages Google and Algolia Search issues

### ISSUE THREAD

**Issue by Yan-Thomas** [withastro/docs#805]
The Brazilian Portuguese docs are having some weird problems, the first one is that Algolia Search doesn't find any of the pt-BR pages, so any search results in "No results ...", as you can see in the gif below:

![5EnDbvd](https://user-images.githubusercontent.com/61414485/174502795-4c543cd8-46cc-4f0c-b9d0-600c52bccd73.gif)

The second one, Google Search is indexing the Brazilian Portuguese pages, but for some reason, some of them have their title/description in English. The page content itself is in Brazilian Portuguese, and I can see that the meta attributes are properly translated (Astro Components pt-BR page source code):

![image](https://user-images.githubusercontent.com/61414485/174503792-1cdff8ea-1a6e-42ac-9edc-59653604af1b.png)

I'm using Google's "in cache" feature to see when the page was supposedly last crawled, here's a list of pages I tested and the behaviors I found:

### Hidratação Parcial  (Partial Hydration)
- [x] Correct title and description
- [x] Includes pt-BR as part of the link breadcrumb
[Cache](https://webcache.googleusercontent.com/search?q=cache:qlw0utFTggUJ:https://docs.astro.build/pt-BR/core-concepts/partial-hydration/+&cd=1&hl=pt-BR&ct=clnk&gl=br): May 10, 2022

### Solução de Problemas (Troubleshooting)
- [x] Correct title and description
- [ ] Includes pt-BR as part of the link breadcrumb
[Cache](https://webcache.googleusercontent.com/search?q=cache:H7j_XHEvgKUJ:https://docs.astro.build/pt-BR/guides/troubleshooting/+&cd=2&hl=pt-BR&ct=clnk&gl=br): June 10, 2022
![image](https://user-images.githubusercontent.com/61414485/174503471-08fac311-58ee-4966-81c7-634211651b85.png)

### Componentes Astro (Astro Components)
- [ ] Correct title and description
- [x] Includes pt-BR as part of the link breadcrumb
[Cache](https://webcache.googleusercontent.com/search?q=cache:21X7leXNzMMJ:https://docs.astro.build/pt-BR/core-concepts/astro-components/+&cd=1&hl=pt-BR&ct=clnk&gl=br): 19 June, 2022
![image](https://user-images.githubusercontent.com/61414485/174503609-b7bf3416-66b9-4eb2-8f6d-7a8e5cbe10dd.png)

I checked some other pages and I'm pretty sure all of them follow one of the three described behaviors above.

**Comment by hippotastic** [comment]
I‘m pretty sure that the indexing issue has to do with the fact that the URLs for two-part language codes with uppercase characters inside conflict with Netlify‘s unfortunate behavior of auto-redirecting to all-lowercase URLs.

I mentioned this issue earlier when developing my link checker, but back then, we decided not to do anything about it.

Now it seems that we have a new good reason to fix this. 😄

As we unfortunately cannot change Netlify's redirection behavior that makes URLs all lowercase, my recommendation would be to rename all occurrences of `pt-BR` to `pt-br` (folder names, links, language selector targets). The goal is that the canonical URLs as seen in the page source code match the actual URLs hosted on Netlify.

**Comment by hippotastic** [comment]
Oh, and a heads up: If we go that route, we'll also need to update the language code in tools like the translation status script, because they are all case sensitive and will not recognize the new language code anymore otherwise. :)

**Comment by delucis** [comment]
Thanks for flagging this @Yan-Thomas and the helpful tips @hippotastic. I’ll tackle this as high priority this week.

**Comment by delucis** [comment]
Let’s monitor this now that https://github.com/withastro/docs/pull/833 is merged. Fingers crossed that fixes things in a week or so.

**Comment by delucis** [comment]
I just tried the on-site search and a Brazilian Google search and this seems to be working correctly now as far as I can tell! Feel free to re-open if you still see these issues.
