### ISSUE TITLE
Add support for route prefetching

### ISSUE THREAD

**Issue by ctjlewis** [withastro/docs#813]
Rich Harris selected this repo's docs as [an example](https://twitter.com/rich_harris/status/1539084063558062080?s=21&t=RPHzjZ_2MXac-Z2PXAOgNA) of how SSR routing is less performant than CSR, and it's true that the UX for these docs is noticeably worse than the SPA example.

This appears to only be the case because the request upon clicking actually goes down the wire and has not been precached by the page after render. It is possible to prefetch links on a page such that they are cached in advance and will respond 304 on an actual click, reducing the slowdown to only the difference between disk read and memory read (negligible).

See [next/link](https://nextjs.org/docs/api-reference/next/link) for an example of how this should be done.

**Comment by sarah11918** [comment]
I'm going to close this issue, since this appears to have been handled and discussed in the core Astro repo!
