### ISSUE TITLE
Resolve confusion around Astro.site

### ISSUE THREAD

**Issue by FredKSchott** [withastro/docs#814]
### To Tackle:

- `Astro.site` is useful for generating production URLs in your site no matter where you're deploying to (staging, prod) or how you're deploying it (ssg, ssr). BUT, this should be explicit so it should be hardcoded to always be the `site` config provided.
- The docs on the `site` value would be updated to something like this: _"Use site config value to set a consistent (static) production URL for your site. You can access this value via Astro.site or import.meta.env.SITE (outside of Astro). This can be used to generating production URLs in your templates."_
- `Astro.request.url` provides everything else you need as a user to access the current, deployed domain, path, etc. Already set correctly by our SSR adapters. 

We should audit all references to `Astro.site` in the docs site to address the items above. `Astro.request.url` should be used instead, unless you explicitly need the "production-only site domain" for something like a canonical URL.

**Comment by sarah11918** [comment]
Annotating here:

`site` defined in https://docs.astro.build/en/reference/configuration-reference/#site

> Your final, deployed URL. Astro uses this full URL to generate your sitemap and canonical URLs in your final build. It is strongly recommended that you set this configuration to get the most out of Astro.

(File to update this item: https://github.com/withastro/astro/blob/main/packages/astro/src/%40types/astro.ts )

------

`Astro.site` - https://docs.astro.build/en/reference/api-reference/#astrosite
- defined in reference here, but does not appear to be mentioned elsewhere, used in code samples etc.
> Astro.site returns a URL made from .site in your Astro config. If undefined, this will return a URL generated from localhost.

------

`Astro.request` - https://docs.astro.build/en/reference/api-reference/#astrorequest
- the example shown for this is `const url = new URL(Astro.request.url);`
- this seems to be the only reference in docs to `Astro.request.url`

------

Other pages:
Environment Variables - `site` is mentioned here, but only in the context of `import.meta.env.SITE`
RSS -  `site` is mentioned here, but only in the context of `import.meta.env.SITE`

**Comment by delucis** [comment]
Closing as we now have `Astro.url` and updated docs accordingly! 🥳

**Comment by ehassaan** [comment]
Was this never updated in production? The docs still tells `site` is used to generate canonical URLs,
https://docs.astro.build/en/reference/configuration-reference/
