### ISSUE TITLE
Provide a comparison against iles

### ISSUE THREAD

**Issue by dhruvkb** [withastro/docs#817]
[iles](https://github.com/ElMassimo/iles) is another Vite based static site generator with similar features to Astro like
- partial hydration
- support for multiple frameworks
- based on Vite

It's a relatively small and new package (614 stars on GitHub) and credits Astro. On an upcoming project I am trying to decide which to adopt and was hoping that there would be some documentation on how Astro and iles are different.

**Comment by delucis** [comment]
We no longer have a direct comparison page, so I’ll close this for now. Would love to see a blog post or similar on this topic — I’m sure it would be super helpful!
