### ISSUE TITLE
Prettier plugin content is incorrect.

### ISSUE THREAD

**Issue by chun37** [withastro/docs#8249]
### 📚 Subject area/topic

Prettier

### 📋 Page(s) affected (or suggested, for new content)

https://docs.astro.build/en/editor-setup/

### 📋 Description of content that is out-of-date or incorrect

> Prettier will then automatically detect the plugin and use it to process .astro files when you run it:
it is written like this.

However, it seems that automatic detection of plugins has been discontinued since Prettier v3. (https://github.com/withastro/docs/pull/7507)

If the plugin is not automatically detected, I think automatically detect is a lie.
I think this part needs to be deleted.

**Comment by at-the-vr** [comment]
That's a great observation, Fixit🛠️ 😄

**Comment by sarah11918** [comment]
Just bumping this for visibility! Would happily take a PR to delete the inaccurate statement, or to add `<Steps>` like @at-the-vr mentioned!
