### ISSUE TITLE
Middleware: unclear that reading cookies/headers behaviour

### ISSUE THREAD

**Issue by thomasledoux1** [withastro/docs#8264]
### 📚 Subject area/topic

Middleware

### 📋 Page(s) affected (or suggested, for new content)

https://docs.astro.build/en/guides/middleware/

### 📋 Description of content that is out-of-date or incorrect

At the moment in my opinion it is not clear that you can not read cookies/headers from the `context` in middleware when you are request a static page.
I'm not sure where exactly this information could be highlighted, but I couldn't figure this out from the existing docs. 
I first created an issue in the `astro` repo https://github.com/withastro/astro/issues/11023

**Comment by sarah11918** [comment]
Hi @thomasledoux1 ! The documentation that describes Cookies/Headers as an on-demand/SSR rendered feature is here: https://docs.astro.build/en/guides/server-side-rendering/#on-demand-rendering-features

We have actually been discussing internally that we don't have a (any? 😅 ) examples showing use of middleware in a static site, so we also haven't really documented well on that page the *difference*.

What would you think about adding to the original first sentence on the middleware page, something like:

> Middleware allows you to intercept requests and responses and inject behaviors dynamically every time a page or endpoint is about to be rendered. This rendering occurs at build time for all prerendered pages, but occurs when the route is requested for pages rendered on demand, making [additional SSR features like cookies and headers](https://docs.astro.build/en/guides/server-side-rendering/#on-demand-rendering-features) available.

Do you think that addresses the issue? If so, I'd be happy to receive a docs PR to that page!
