### ISSUE TITLE
Script Tag CDNs with View Transitions

### ISSUE THREAD

**Issue by jesseagleboy** [withastro/docs#8354]
### 📋 Explain your issue

After learning from [Simon Grimm about Capacitor](https://www.youtube.com/watch?v=ZFNwTJiDEvU) to turn Astro into a native/web app, I've tried implementing [Ionic](https://ionicframework.com/docs/components) to utilize native styling. The current compromise is that without View Transitions, the styling works fine while with View Transitions on, the CDN doesn't run again and it doesn't appear there is some Astro directive to rerun CDNs. I've reached out for support at Ionic about re-running their scripts to use the Astro "after-swap" directive but wanted to see if Astro had things in place to rerun CDNs that didn't need to be explicitly written out in a new event listener. The current documentation for Ionic's vanilla Javascript is very vague which makes it hard to re-initialize the Ionic scripts (at least as far as I've seen). Hopefully, this also gets Astro to move into PWA or native apps soon.

**Comment by sarah11918** [comment]
Hi @jesseagleboy ! Sorry, we're just catching up after a busy month of releases and offsite etc.

Unfortunately, this isn't the right place to connect about this. This repo is for issues with the documentation website, and we are unable to help with other guidance. But, we would like to direct you to our [Discord](https://astro.build/chat), or the [Roadmap repo](https://github.com/withastro/roadmap/discussions) for questions and discussions about product direction. (And, specifically @martrapp might be a good person to discuss the impact that View Transitions is having in your attempts!)

So, I'll be closing this as it's not an issue with our docs site, but I hope you can connect in one of the above mentioned places to have this discussion!
