### ISSUE TITLE
Tutorial says that the rss.xml can't be seen in development but it actually can be

### ISSUE THREAD

**Issue by Ash882** [withastro/docs#8418]
### 📚 Subject area/topic

Tutorials -> Build a blog

### 📋 Page(s) affected (or suggested, for new content)

https://docs.astro.build/en/tutorial/5-astro-api/4/#create-an-xml-feed-document

### 📋 Description of content that is out-of-date or incorrect

On step 4 (This rss.xml document is only created when your site is built, so you won’t be able to see this page in your browser during development...) of Create an .xml feed document

It says that rss.xml is only created when the site is built, but that isn't true since I can see it in the development server.

I guess that this could be fixed by just removing step 4 or replacing it with a run a development server?

### 🖥️ Reproduction in StackBlitz (if reporting incorrect content or code samples)

![Bildschirmfoto_20240601_211612](https://github.com/withastro/docs/assets/155681028/ff7b3be8-1ee1-4692-9bc7-329329570a1b)

**Comment by at-the-vr** [comment]
Hey @Ash882 you are indeed correct, wanna make a PR for it 😄 ?

**Comment by sarah11918** [comment]
I'm not sure when we changed this, because this for sure WAS how it worked when the tutorial was written! 😅
