### ISSUE TITLE
Missing results for query "rtl"

### ISSUE THREAD

**Issue by arastoonet** [withastro/docs#8488]
Hi, it would be great if you could provide a reference on how to implement the right-to-left feature in the themes.

**Comment by at-the-vr** [comment]
could this be a good recipe to have within https://docs.astro.build/en/recipes/i18n/ @sarah11918 ?

**Comment by arastoonet** [comment]
There's literally no solution about RTL layout in this link.

**Comment by sarah11918** [comment]
I don't think they were suggesting there was a solution there, but saying that might be a good place to ADD something!  

I'm not sure what you mean by "in the themes"? I think we could have a recipe showing how to add RTL support in an Astro site, but I don't know if you mean something different or more specific? But also, this is not something special to Astro, it is usually done by adding CSS. So we often do not document things that are outside of Astro, like normal CSS or JavaScript. I think you can search outside of Astro Docs and see how to get the CSS support you need for RTL.

**Comment by arastoonet** [comment]
I suggest creating a document explaining how to create `rtl.css` for different themes, not for a specific theme, but all of them.
