### ISSUE TITLE
View transitions flicker

### ISSUE THREAD

**Issue by bravo-is** [withastro/docs#8497]
I didn't run into any flicker while navigating between routes. But the theme does flicker if the browser is refreshed. To fix this you can just add this inline script, instead of the suggested after-swap event
`<script is:inline>
  localStorage.theme === 'dark'
  ? document.documentElement.classList.add("dark")
  : document.documentElement.classList.remove("dark");
</script>`

**Comment by sarah11918** [comment]
Hi @bravo-is - I'm not able to replicate any theme flicker based on what you've said above. Can you describe more, or maybe show a screenshot of exactly what steps produce the flicker?

Would also be happy to hear steps to reproduce if anyone else notices this!

**Comment by bravo-is** [comment]
Hi @sarah11918 , to reproduce this I just needed to use all of the suggested code in the [Update scripts](https://docs.astro.build/en/tutorials/add-view-transitions/#update-scripts) section. With the dev server running I switch the theme to dark mode. Now whenever I refresh the browser (F5) I see the light theme flicker before the dark theme is applied (Firefox and Edge). Thanks for looking into this 😄
