### ISSUE TITLE
Docs doesn't specify that `import.meta.env` is evaluated at build time with SSR adapter.

### ISSUE THREAD

**Issue by feelixe** [withastro/docs#8509]
### 📋 Explain your issue

In the [docs](https://docs.astro.build/en/guides/environment-variables/) it's not mentioned that using `import.meta.env` will be evaluated at build time. If you are using static generation, that goes without saying. But with a SSR adapter, I think many will expect this to be evaluated per request at runtime. I at least did until i looked in the transpiled server files.

I believe some clarification would be good.

**Comment by Fryuni** [comment]
It might improve discoverability, but the information is available from that page.

The first line states that Astro uses Vite's built-in handling for environment variables and links to their docs. The linked page starts with:

> Vite exposes env variables on the special `import.meta.env` object, which are statically replaced at build time.

The same could be said for any other Vite details about env vars, like `.env.[mode].local` files also being loaded to allow for untracked `.env` files.

**Comment by sarah11918** [comment]
@feelixe Would it solve your problem if we updated our sentence there to include the content on the linked page to Vite, maybe like:

> Astro uses Vite’s built-in support for environment variables, which are statically replaced at build time, and lets you [use any of its methods](https://vitejs.dev/guide/env-and-mode.html) to work with them.

If so we would happily accept a PR to docs with that update!
