### ISSUE TITLE
Add documentation regarding usage of `style` tags in components containing `html` tags (i.e. layout components)

### ISSUE THREAD

**Issue by Trombach** [withastro/docs#8603]
### 📋 Explain your issue

I'm opening this issue to ask for advice on fixing a gap in the documentation regarding layout components. The issue is that if a layout component contains an `html` tag, any `style` tags (this might also apply to `script` tags?) need to be nested inside the `html` tag. This is different to how astro components normally behave where the `style` tag is usually placed outside of any other tags.

## Example

```astro
// invalid
---
---
<html>
  <head>...</head>
  <body>...</body>
<html>

<style>...</style>

// valid
---
---
<html>
  <head>...</head>
  <body>...</body>
  <style>...</style>
<html>
```

The behaviour and workaround was confirmed in this [issue](https://github.com/withastro/astro/issues/6428).

## Suggestion

I think this would make sense to explain in a callout box on the [layouts page](https://github.com/withastro/docs/blob/07b48047672cd245cc43243d9abdb6545995be8d/src/content/docs/en/basics/layouts.mdx). Something akin to

> [!WARNING]
> A `style` tag in an Astro component containing an `html` tag must be nested inside the `html` tag.

I don't think I have seen this mentioned anywhere else in the docs, but I might have overlooked it. Ideally this should trigger at least a linter warning in the language tools, but getting it documented would be a good start.

More than happy to send a PR!

**Comment by at-the-vr** [comment]
Can confirm the suggestion is valid based off Issue linked & [withastro/astro/blob/main/examples/blog/src/layouts/BlogPost.astro](https://github.com/withastro/astro/blob/main/examples/blog/src/layouts/BlogPost.astro). Hit your PR right away 😉

**Comment by sarah11918** [comment]
I saw the discussion and agree it seems to be something that needs documenting!

I will point out though, that a call out is probably NOT the way to do this.  ;)  Cautions and warnings are for: security risk, might lose data, set your house on fire etc. In general, "how things work" is not a special note, it's just part of regular documentation!

So, I would encourage you to look for where, in normal paragraph text, this content makes sense to add! Then, I'll help edit it and get it over the finish line. 💪

**Comment by Trombach** [comment]
@sarah11918 Thanks, good point regarding the callout. I will write something up later today and send it through. I can also send through a German translation at the same time, I presume I'd do that in a separate PR?

**Comment by sarah11918** [comment]
Yes! The German would be in a 2nd PR, thanks!  Especially since you won't know for sure what the final English version will be until Team Docs is finished reviewing and possibly editing it, it saves work by not doing the translation too early. 🙌
