### ISSUE TITLE
Tip's titles are truncated when using inline code

### ISSUE THREAD

**Issue by ArmandPhilippot** [withastro/docs#8711]
### 📝 Issue Description

Some tips are using inline code in their title (e.g. ``:::tip[Set a `baseUrl`]``). It seems only strings are accepted so the inline code is removed from the title.

### 📋 On which page(s) it occurs

- https://docs.astro.build/en/guides/testing/

**Edit:** After checking manually the documentation website in English, it seems to be the only affected page (including the translations). So I would say that it is the expected behavior and the _Tips_ title on this page should be renamed (not a bug). Most of the tips have `Tip` as title... maybe it's enough here too. What do you think?

### 🤔 Expected Behavior

I expect to see "**Set a `baseUrl`**" while navigating to the tip above [Running your Playwright tests](https://docs.astro.build/en/guides/testing/#running-your-playwright-tests) since in the source file I see ``:::tip[Set a `baseUrl`] `` (without the extra space at the end which I added for formatting).

### 👀 Current Behavior

Instead, I see "**Set a** ".

And this is happening for other tips on the page.

### 🖥️ Browser

Not relevant I think but... Firefox 127.0.1

### 📄 Additional Information

I could update the documentation but I'm not sure if this is a bug or the expected behavior. So I prefer to have a confirmation first.

* In case of expected behavior, the documentation should be updated to replace the inline codes in all the aside's titles with regular strings,
* In case of a Starlight bug, an issue should be opened there about [asides.ts](https://github.com/withastro/starlight/blob/0e72ce5d31c0cfe23c8aedb4090be5f408f5d6dc/packages/starlight/integrations/asides.ts).

**Comment by delucis** [comment]
Ah, I didn’t know we were using this anywhere in docs. We have a discussion for this here in Starlight: https://github.com/withastro/starlight/discussions/1915

I’ll link this issue there, but I think it will need solving upstread.

**Comment by ArmandPhilippot** [comment]
Ah, I checked the issues on the Starlight repository before opening this issue... I didn't think about the discussions.  Thanks for the link!
