### ISSUE TITLE
Feedback Fish: error in Reading Time recipe

### ISSUE THREAD

**Issue by sarah11918** [withastro/docs#8778]
### 📚 Subject area/topic

Recipe - remark plugin

### 📋 Page(s) affected (or suggested, for new content)

https://docs.astro.build/en/recipes/reading-time/#_top

### 📋 Description of content that is out-of-date or incorrect

From Feedback Fish: 

Reading Time did not work and return undefined

**Comment by at-the-vr** [comment]
I could not find any discrepancy in the guide. Everything worked smoothly on my end. Linking the test blog: https://reading-time-test.netlify.app/blog/ && the commit related with it https://github.com/at-the-vr/reading-time-test-repo/commit/6c2120bac8b165c5a6219dc6aa421b02ff18c64d
```js
Astro                    v4.11.5
Node                     v18.17.1
System                   Windows (x64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
                         @astrojs/sitemap
```
Did this issue happened to multiple users?

**Comment by sarah11918** [comment]
Thank you! Happy to close this out! :raised_hands: 

No, anything from Feedback Fish was a single user report, so it's likely this could be a problem with their own code.
