### ISSUE TITLE
Error in Gitlab deploy code?

### ISSUE THREAD

**Issue by sarah11918** [withastro/docs#8780]
### 📚 Subject area/topic

deploy guide

### 📋 Page(s) affected (or suggested, for new content)

https://docs.astro.build/en/guides/deploy/gitlab/

### 📋 Description of content that is out-of-date or incorrect

From Feedback Fish:

the .gitlab-ci.yml on your docs are not valid

**Comment by menghif** [comment]
I can take a look at this.
