### ISSUE TITLE
Code error in recipe Build Forms with APIs?

### ISSUE THREAD

**Issue by sarah11918** [withastro/docs#8783]
### 📚 Subject area/topic

recipe - building forms

### 📋 Page(s) affected (or suggested, for new content)

https://docs.astro.build/en/recipes/build-forms-api/

### 📋 Description of content that is out-of-date or incorrect

From Feedback Fish:

In FeedbackForm.tsx example it gives error on import of type without specifying.

This works:
import { useState } from "react";
import type { FormEvent } from "react";

**Comment by mingjunlu** [comment]
Confirmed. I'll submit a PR 🔜

![截圖 2024-07-15 下午2 47 52](https://github.com/user-attachments/assets/ce0a5cbd-1635-4427-b8a8-877cf11aa386)
