### ISSUE TITLE
Improve Custom Animations code example for View Transitions guide

### ISSUE THREAD

**Issue by sarah11918** [withastro/docs#8787]
### 📚 Subject area/topic

view transitions

### 📋 Page(s) affected (or suggested, for new content)

https://docs.astro.build/en/guides/view-transitions/#customizing-animations

### 📋 Description of content that is out-of-date or incorrect

From Feedback Fish:

Hi Astro team,
I've been adding View Transitions to my site and wanted to add a custom transition to get things just right. A couple of things that tripped me up in the docs that I think you should know in case these are issues other folks are having:

* It wasn't clear to me that the animation names 'fadeIn' and 'fadeOut' in the custom animation example refer to named keyframe sequences that I'd have to define myself in my CSS. It might be worth making this super clear. (I ended up working it out after a bit of a google and reading this post — https://blog.logrocket.com/using-view-transitions-api-astro/#custom-animations)

* Also in that example 'fadeIn' and 'fadeOut' appear to be the wrong way round. It would make more sense for 'fadeOut' to be used in conjunction with the old page and 'fadeIn' to be use in conjunction with the new. 

Hope this helps. And thanks for all you do with Astro. I've been using it since the very early beta and LOVE it.

**Comment by SatanshuMishra** [comment]
I wouldn't mind taking this on :)!

**Comment by sarah11918** [comment]
Hi @SatanshuMishra ! Thank you, yes! The first task is to verify that this is in fact an issue.  :smile: 

I've been transcribing comments from our feedback widget but haven't yet had the time to explore any. Just because one person makes a comment doesn't always mean it's actionable. Whenever you see the `help - confirm behaviour` that means that we need to first confirm what was reported, and only then work on the problem.

I would love it if you'd be up for tackling this! :raised_hands: Even just exploring the issue and reporting back is a helpful first step.

**Comment by Dillonpw** [comment]
About a month ago I helped someone out with this same issue in the support channel on discord.
Someone unfamiliar with View Transitions could get hung up where the wording before the code block reads: "The following example shows **all** the necessary properties to define a custom fade animation"
For added clarity we could add an additional bit of code showing a CSS file with the keyframes defined or define them between style tags in a root layout or something along those lines where the keyframes are defined and could be copied and used as an obvious change from the standard animation.

**Comment by Dillonpw** [comment]
I'll put together a draft of an example this afternoon!
