### ISSUE TITLE
Discoverability of image helper with content collections

### ISSUE THREAD

**Issue by sarah11918** [withastro/docs#8809]
### 📚 Subject area/topic

content collections, images

### 📋 Suggested page

https://docs.astro.build/en/guides/content-collections/#defining-a-collection-schema

### 📋 General description or bullet points (if proposing new content)

We show an example of defining an image in a content collections schema, but don't describe using images at all on this page (only the image page) and don't link there.

**Comment by at-the-vr** [comment]
does that includes **create a `blog` layout** and **define image source in md/mdx files** ? 

Something like [BlogPost.astro](https://github.com/withastro/astro/blob/latest/examples/blog/src/layouts/BlogPost.astro) being used for slugs and [first-post.md](https://github.com/withastro/astro/blob/latest/examples/blog/src/content/blog/first-post.md) from the Blog template

**Comment by sarah11918** [comment]
Now I'm thinking that we don't need specific information on new versions of the content collections page, but rather the image advice should be specific to the file type of the collection entry (which is probably markdown or mdx) so I think it's safe to close this one!
