### ISSUE TITLE
Missing NODE_VERSION environment variable text for Netlify deployment

### ISSUE THREAD

**Issue by jmaeat** [withastro/docs#884]
The page in question: https://docs.astro.build/deploy/netlify/

I noticed while reading through the Netlify deploy guide that there is no longer a mention of the NODE_VERSION environment variable. Cloudflare Pages, for example, has the following under Step 2:
> Environment variables (advanced): Currently, Cloudflare Pages supports NODE_VERSION = 12.18.0 in the Pages build environment by default. Astro requires 14.15.0, v16.0.0, or higher. You can add an environment variable with the Variable name of NODE_VERSION and a Value of a Node version that’s compatible with Astro or by specifying the node version of your project in a .nvmrc or .node-version file.

I double-checked the Netlify docs and the [default Node version for their Xenial image](https://github.com/netlify/build-image/blob/xenial/included_software.md) is still 12.18.0, which will cause Astro builds to fail.

**Comment by sarah11918** [comment]
Great catch, and thanks for this! If you'd like to make a PR to suggest a way to add this back in, feel free.

I think this can be handled either through the dashboard UI (setting an environment variable directly) or through a `netlify.toml` file? So we should document both.
