### ISSUE TITLE
Update View Transitions Docs

### ISSUE THREAD

**Issue by OliverSpeir** [withastro/docs#8904]
### 📋 Suggested page

https://docs.astro.build/en/guides/view-transitions/

### 📋 General description or bullet points (if proposing new content)

Add "Removing `<ViewTransitions/>` Component section
  - "What needs to change?"
  - "What can I keep?"
  - "How do I reuse my custom animations?"

***Maybe*** add tracking of browser support, I personally will volunteer for keeping this updated

As of right now:
- Chrome and Edge support level 2
- Safari added level 1, I haven't found a good issue to track level 2
- Firefox has plans for level 1 in new couple months, [Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1823896)

**Comment by sarah11918** [comment]
Great call out to document removing the component!

As for updating statuses... is there a predictable static link for checking each browser's status? I would prefer if we didn't have to *ourselves* literally say "Browser X, level Y support" but could have one link that never needs updating that is e.g.`[current adoption status of Browser X](link we don't have to update)`

Or, if some other source we trust is updating statuses, I would be OK to link to even a non-official source that we find reliable and have faith will themselves be updating.

**Comment by liruifengv** [comment]
How about [the View Transitions API Docs In MDN](https://developer.mozilla.org/en-US/docs/Web/API/View_Transitions_API#browser_compatibility)?

**Comment by sarah11918** [comment]
That link looks amazing, exactly what I was thinking of! :raised_hands:

**Comment by OliverSpeir** [comment]
That link covers level 1 Astro needs level 2 to be able to replace the <ViewTransition /> component

**Comment by martrapp** [comment]
Granted, npm is currently a bit in transition between level 1 and 2 for the documentation, but liruifengv'a link is fine. The `startViewTransition` table shows level 1 support and the `@viewTransition` table shows level 2 support.

**Comment by sarah11918** [comment]
@martrapp posted his page recently https://events-3bg.pages.dev/jotter/api/references/#w3c-drafts ... would this work? https://events-3bg.pages.dev/jotter/api/references/#w3c-drafts (lol, Martin just commented)

**Comment by OliverSpeir** [comment]
Also worth noting that we need to explain that transition persist won’t be supported by the browsers

**Comment by sarah11918** [comment]
Just checking to see whether anyone is interested in picking this one up! We've got the link mentioned above for browser support, and a section on removing the component would be welcome!

**Comment by sarah11918** [comment]
On Talking and Doc'ing, we decided to close this issue as we couldn't think of a great way to say if you're not using transitions anymore then you can't use anything on this page.

We will wait to see whether there's a specific, recurring issue people seem to need guidance on that is more than "undo what you did to enable it."
