### ISSUE TITLE
Improve `Astro.redirect` doc with static/server differences

### ISSUE THREAD

**Issue by ArmandPhilippot** [withastro/docs#8917]
### 📚 Subject area/topic

API Reference

### 📋 Page(s) affected (or suggested, for new content)

https://docs.astro.build/en/reference/api-reference/#astroredirect

### 📋 Description of content that is out-of-date or incorrect

Until now (see https://github.com/withastro/astro/issues/11544), the inline documentation for `Astro.redirect` was misleading: this method is not SSR only. It can also be used with static output but there are some differences. So I suggest to improve the documentation with some additions.

Currently, `Astro.redirect` is documented in:
* [API reference](https://docs.astro.build/en/reference/api-reference/#astroredirect)
* [Routing](https://docs.astro.build/en/guides/routing/#dynamic-redirects)

I think it makes more sense to update [API reference](https://docs.astro.build/en/reference/api-reference/#astroredirect) (and this is the link I put in my issue/PR on `astro` repository).

#### Document the function signature

Some other functions in the API reference have a `Type` below that shows the function signature. I think we should do the same for `Astro.redirect`:

```md
Type: (path: string, status?: number) => Response
```

And update the link in the sentence below since the value of `ValidRedirectStatus` (the real number type) is `300 | 301 | 302 | 303 | 304 | 307 | 308` (a redirection status only):

```diff
-Allows you to redirect to another page, and optionally provide an [HTTP response status code](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status) as a second parameter.
+Allows you to redirect to another page, and optionally provide an [HTTP response status code](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status#redirection_messages) as a second parameter.
```

#### Clarify differences between SSR and static pages

From my understanding, the second parameter only works with SSR: we cannot use a status code with `http-equiv`. So, it might be useful to clarify the difference in behavior between `output: 'static'` and `output: 'server'`.

In [API reference](https://docs.astro.build/en/reference/api-reference/#astroredirect), we could add something like what is described in [`redirects` in Configuration reference](https://docs.astro.build/en/reference/configuration-reference/#redirects):

```md
For statically-generated sites, this will produce a client redirect using a [<meta http-equiv="refresh"> tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta#http-equiv) and does not support status codes.

When using SSR, status codes are supported. Astro will serve redirected requests with a status of 302 by default unless another code is specified.
```

And reword the sentence above the example because of this difference:

```diff
-The following example redirects a user to a login page, using the default HTTP response status code 302:
+The following example redirects a user to a login page:
```

#### Suggestion with changes

```mdx
### `Astro.redirect()`

**Type:** `(path: string, status?: number) => Response`

Allows you to redirect to another page, and optionally provide an [HTTP response status code](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status) as a second parameter.

A page (and not a child component) must `return` the result of `Astro.redirect()` for the redirect to occur.

For statically-generated sites, this will produce a client redirect using a [<meta http-equiv="refresh"> tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta#http-equiv) and does not support status codes.

When using SSR, status codes are supported. Astro will serve redirected requests with a status of 302 by default unless another code is specified.

The following example redirects a user to a login page:

{/* ... The current example ... */}
```

#### Probably useless

When using `hybrid` or `static`, the status code is applied in dev mode since the dev server does not use `http-equiv` but Vite to serve the pages. So the users might notice this difference. However, I'm not sure it's worth mentioning.

**Comment by sarah11918** [comment]
This looks amazing, @ArmandPhilippot ! I would welcome a PR to the API reference page for this. Bonus points if you can also track down the version of Astro that introduced `Astro.redirect()` and add the `<Since />` component to save me some work! (Otherwise, I will find it for your PR)

There is an open PR right now for `Astro.rewrite()` that will be released in the next minor, and I don't think it currently includes a Type either. Would you be willing to also look at PR #8914 and suggest the proper Type there?

**Comment by ArmandPhilippot** [comment]
@sarah11918 I'm on it! Thanks for your feedback.
