### ISSUE TITLE
Improve title style

### ISSUE THREAD

**Issue by jamesli2021** [withastro/docs#8937]
### 📋 Explain your issue

On this page
https://docs.astro.build/en/concepts/why-astro/

The phrase 'Why Astro' might sometimes imply a persuasive or defensive approach.

I suggest that for documentation, we should begin with 'What is Astro.' This is the first thing readers think about when learning a new concept, and it provides a neutral and informative tone.

**Comment by delucis** [comment]
Thanks for the issue @jamesli2021! That page does aim to answer “Why Astro?” more than “What is Astro”. While most of our documentation does indeed aim to be neutral and informative, we do sometimes need other kinds of content like this, which help people asking themselves whether Astro is right for them. In these situations, some users may be happy with a “what” list, but for others understanding motivations, use cases, and why Astro is well suited for those is helpful.
