### ISSUE TITLE
Mobile nav links aren't showing in tutorial

### ISSUE THREAD

**Issue by 1codingguy** [withastro/docs#9024]
### 📝 Issue Description

Mobile nav links aren't showing because:
```
.nav-links {
  display: none;
}
```

### 📋 On which page(s) it occurs

https://docs.astro.build/en/tutorial/3-components/3/

### 🤔 Expected Behavior

On mobile view the nav links should be showing

### 👀 Current Behavior

On mobile view the nav links aren't showing

### 🖥️ Browser

Chrome

**Comment by 1codingguy** [comment]
Sorry it should be tagged "Incorrect Content Report" instead of bug, but can't change it back.

**Comment by at-the-vr** [comment]
Hey 1codingguy 👋 , mobile nav links are displayed underneath the hamburger menu which is addressed in https://docs.astro.build/en/tutorial/3-components/4/. Safe to say the content is correct
