### ISSUE TITLE
Visual bug: Astro logo is clipped at the bottom

### ISSUE THREAD

**Issue by JusticeMatthew** [withastro/docs#9047]
### 📝 Issue Description

The bottom of the flame on the logo in the header is clipped on the bottom
![image](https://github.com/user-attachments/assets/33f6da63-0072-40cc-813a-31d8d8f06445)

### 📋 On which page(s) it occurs

All pages with the header

### 🤔 Expected Behavior

For the logo to not be clipped as it appears in the press page

### 👀 Current Behavior

The logo is clipped

### 🖥️ Browser

Chrome 127.0.6533.72

**Comment by rogue-marketing-dev** [comment]
I can take a look at this this afternoon if no one else is.
