### ISSUE TITLE
Low font contrast in active item in left sidebar

### ISSUE THREAD

**Issue by kevinzunigacuellar** [withastro/docs#905]
**Description**

The active link inside navbar has a shallow font contrast in light mode

<img width="314" alt="image" src="https://user-images.githubusercontent.com/46791833/176984344-0be0a1c5-e1b3-4e10-a75c-76e11d921640.png">

**Comment by delucis** [comment]
Ouch! This is new. I think it may have been introduced in #849. Would you be interested in investigating and submitting a PR?
