### ISSUE TITLE
Create and pass props to a Social Media component

### ISSUE THREAD

**Issue by zzzh** [withastro/docs#9077]
In this page: https://docs.astro.build/en/tutorial/3-components/2/
There suppose to be a "Create and pass props to a Social Media component" part, but miss the content.

**Comment by ArmandPhilippot** [comment]
Hi @zzzh! I think the confusion comes from the "Get ready" insert: this is used to summarize the purpose of the page and not to match the headings. So the content is indeed on the page:
* you [create a Social Media component](https://docs.astro.build/en/tutorial/3-components/2/#create-a-social-media-component)
* then you [use it, with props, in the previously created footer](https://docs.astro.build/en/tutorial/3-components/2/#import-and-use-socialastro-in-your-footer)
