### ISSUE TITLE
a working navigation menu that is both responsive to screen size and responds to user input on this page

### ISSUE THREAD

**Issue by zzzh** [withastro/docs#9078]
In this page: https://docs.astro.build/en/tutorial/3-components/4/

It's said "Check your browser preview again at various sizes, and verify that you have a working navigation menu that is both responsive to screen size and responds to user input on this page."

Don't work on my Edge browser in Windows 11.

**Comment by sarah11918** [comment]
Hi! If you are having trouble with your code, the place to get help and support is our Discord! You can share code and ask for help at https://astro.build/chat !
