### ISSUE TITLE
Add clearer instructions to experimental content intellisense setup

### ISSUE THREAD

**Issue by JusticeMatthew** [withastro/docs#9122]
### 📚 Subject area/topic

content layer

### 📋 Suggested page

https://docs.astro.build/en/reference/configuration-reference/#experimentalcontentintellisense

### 📋 General description or bullet points (if proposing new content)

Provide clearer instructions for accessing and enabling the setting in VS Code

**Comment by sarah11918** [comment]
Hey @JusticeMatthew - often with experimental features... you're on your own! 😅 This is a very new, and early feature. It's not yet ready for prime time, and it's at the stage where it's really just meant to be played with at your own risk to see how the feature will develop.

So we're not going to document more about using it right now, BUT, if you'd like to hunt down the original Astro implementation PR and update the reference entry with a link to it, so people can check out the code, see the initial discussion/thoughts behind the feature, I think that would be a great addition here! Something like:

`See the [content Intellisense implementation PR](PR link) for more details about this early feature.`

**Comment by sarah11918** [comment]
Just pointing out that this would be a good first issue for someone to add this link!

I think you could add the line mentioned above here and it would be helpful! https://github.com/withastro/astro/blob/7814a6cad15f06931f963580176d9b38aa7819f2/packages/astro/src/%40types/astro.ts#L2148
