### ISSUE TITLE
Self-host deployment docs

### ISSUE THREAD

**Issue by sarah11918** [withastro/docs#9124]
### 📚 Subject area/topic

deployment

### 📋 Suggested page

https://docs.astro.build/en/guides/deploy/

### 📋 General description or bullet points (if proposing new content)

Have a guide to self-hosting/deployment

**Comment by Fryuni** [comment]
The [Docker guide](https://docs.astro.build/en/recipes/docker/#creating-a-dockerfile) is what people should follow for self-hosting. It mentions it can be used for cloud providers at the top. Maybe we should also mention that you can use the image for self-hosting.

Tho, people using Docker would probably know that they can run it locally or wherever they want 🤔 that is kinda of the point of Docker.

**Comment by sarah11918** [comment]
ok, satisfied enough with this for now!
