### ISSUE TITLE
Link to component prop types for getting props of built in components

### ISSUE THREAD

**Issue by sarah11918** [withastro/docs#9125]
### 📚 Subject area/topic

Typing component props

### 📋 Suggested page

https://docs.astro.build/en/reference/api-reference/#built-in-components

### 📋 General description or bullet points (if proposing new content)

Add a link in the API reference section for our built-in components to our documentation about `ComponentProps`. Something like just adding the statement in bold to the existing text.

Built-in Components
Astro includes several built-in components for you to use in your projects. All built-in components are available in .astro files via import {} from 'astro:components';. **You can reference the `Props` of these components using the [`ComponentProps` type](/en/guides/typescript/#componentprops-type)**.

**Comment by ManorSailor** [comment]
How about utilizing a custom components like _tip_ or _note_ instead of a bold statement?

**Comment by sarah11918** [comment]
Sorry, I can see the misunderstanding. I made the statement bold so that it would be obvious what change to make! No, the text should not be bold, and it should not be any kind of tip or note! If it's just regular documentation, it does not belong in a note.

I'll fix that in the PR!
