### ISSUE TITLE
Infinite Loop redirection

### ISSUE THREAD

**Issue by ohrrkan** [withastro/docs#9134]
Those two redirect can lead to an infinite loop redirection

Signin should only redirect on dashboard if the JWT is valid not only because not !

https://github.com/withastro/docs/blob/af56f405f3cfeb67044907c8114543c17f6130c3/src/content/docs/en/guides/backend/supabase.mdx?plain=1#L285

Dashboard should only redirect on signin if no error validating the tokens

https://github.com/withastro/docs/blob/af56f405f3cfeb67044907c8114543c17f6130c3/src/content/docs/en/guides/backend/supabase.mdx?plain=1#L331

setSession can return an error but also throw an error. this is a bad practice (I already report to Supabase team) but it is the case.
This mean that checking return error is not enough and the example should be rewrite like this maybe : 

```
...
const { cookies, redirect } = Astro;

const accessToken = cookies.get("sb-access-token");
const refreshToken = cookies.get("sb-refresh-token");

if (!accessToken || !refreshToken) {
  return redirect("/signin");
}
let setSession: AuthResponse;
try {
  setSession = await supabase.auth.setSession({
    refresh_token: refreshToken.value,
    access_token: accessToken.value,
  });
  if (setSession.error) {
    cookies.delete("sb-access-token", {
      path: "/",
    });
    cookies.delete("sb-refresh-token", {
      path: "/",
    });
    return redirect("/signin");
  }
} catch (error) {
  return redirect("/signin");
}
const email = setSession.data.user?.email;
...
```

You can produce the infinite loop by editing your cookie  with invalid data on sb-access-token for example.
it will create a server error by the way because of the unhandled throw but you have the point.

**Comment by sarah11918** [comment]
Hi @ohrrkan , thanks for reporting this!

Have you tested your solution to see if it works? If that's working code that is preferable to avoid the infinite loop redirection, we'd be happy to receive a PR to the docs page to update the content!

We are quite busy getting our docs together for our launch of 5.0 beta next week, so I'm not sure how quickly someone would be able to get around to reviewing it. Maybe @kevinzunigacuellar who worked on a lot of our third-party guides originally and has experience with Supabase would be able to help verify and guide you through a PR to update the docs!

**Comment by kevinzunigacuellar** [comment]
Hi! Sorry for the delay in getting back to you — I’ve been looking into this. You’re right, Supabase handles errors in two ways: either by returning an object with an error or by throwing an error.

https://github.com/supabase/auth-js/blob/ef3911cd1a082a6825ce25fe326081e096bd55f5/src/lib/helpers.ts#L204-L206

While it’s not ideal, as you pointed out, it seems necessary to wrap the setSession call in a try-catch to manage this edge case. The example you provided should work, with the small addition of deleting the cookies when catching an error. This will prevent an infinite loop between the sign-in page and the dashboard.

```astro
---
import Layout from "../layouts/Layout.astro";
import { supabase } from "../lib/supabase";

const accessToken = Astro.cookies.get("sb-access-token");
const refreshToken = Astro.cookies.get("sb-refresh-token");

if (!accessToken || !refreshToken) {
  return Astro.redirect("/signin");
}

let session;
try {
  session = await supabase.auth.setSession({
    refresh_token: refreshToken.value,
    access_token: accessToken.value,
  });
  if (session.error) {
    Astro.cookies.delete("sb-access-token", {
      path: "/",
    });
    Astro.cookies.delete("sb-refresh-token", {
      path: "/",
    });
    return redirect("/signin");
  }
} catch (error) {
  Astro.cookies.delete("sb-access-token", {
    path: "/",
  });
  Astro.cookies.delete("sb-refresh-token", {
    path: "/",
  });
  return Astro.redirect("/signin");
}

if (session.error) {
  Astro.cookies.delete("sb-access-token", {
    path: "/",
  });
  Astro.cookies.delete("sb-refresh-token", {
    path: "/",
  });

  return Astro.redirect("/signin");
}

const email = session.data.user?.email;
---
<Layout title="dashboard">
  <h1>Welcome {email}</h1>
  <p>We are happy to see you here</p>
  <form action="/api/auth/signout">
    <button type="submit">Sign out</button>
  </form>
</Layout>

```

Thanks for the insight!

**Comment by sarah11918** [comment]
Thanks for looking into this @kevinzunigacuellar 🎉  

Is there a corresponding update to the guide in docs we should make? Would you like to do that, or describe for a contributor what they should do?

**Comment by kevinzunigacuellar** [comment]
I can send a PR for a quick update. 

However, with Astro introducing new stable features like env and actions, this guide might need a more comprehensive update soon.

**Comment by Fryuni** [comment]
I'd suggest this instead of handling error in two places:
```ts
await supabase.auth.setSession({
    refresh_token: refreshToken.value,
    access_token: accessToken.value,
  })
.catch(error => ({error}));
```

Turns the thrown error into a value. But that is only if the thrown error is from a rejection of the promise. If there is a sync path on `setSession` that throws the error then ignore this.
