### ISSUE TITLE
propertiesToHash missing from Image Service API Docs

### ISSUE THREAD

**Issue by amxmln** [withastro/docs#9169]
### 📚 Subject area/topic

Image Service API

### 📋 Page(s) affected (or suggested, for new content)

https://docs.astro.build/en/reference/image-service-reference/

### 📋 Description of content that is out-of-date or incorrect

According to [this PR](https://github.com/withastro/astro/pull/8984), the Image Service API has a property `propertiesToHash` which is used to control which properties are included in the filename hash of an optimised asset.

There doesn’t seem to be a mention on the page in the docs, although I believe there should be, since it’s important information to know when creating a custom image service that supports more options than the standard one.

On a related note, I believe the built-in `sharpService` is not using the `propertiesToHash`? I couldn’t find a mention in the source code. Is that intentional and if so, why?

**Edit:** looking at the patch that introduced the change, it seems like if an image service doesn’t define `propertiesToHash`, Astro will fall back on the default ones defined in `packages/astro/src/assets/consts.ts`. Perhaps this could also be added to the updated documentation.

**Comment by Princesseuh** [comment]
It is missing yes. I said I would add it and never did, oops.

The method optionally returns an array of strings, which represents the keys that should be included to generate the hash of the image. Its default value is everything that counts for the base services, width height format quality etc.

**Comment by amxmln** [comment]
Hi @sarah11918, I have opened a PR for this issue. I wasn’t quite sure where to put the new content in the document, since it isn’t really a hook. So I added the information in the section about local image services.

**Comment by sarah11918** [comment]
Thank you @amxmln ! I will ask @Princesseuh to review it. Really appreciate you jumping in here. :rocket:
