### ISSUE TITLE
⚠️ Issue: Use correct comment style in .env file for Astro / Strapi integration page

### ISSUE THREAD

**Issue by bvold** [withastro/docs#9189]
On the Astro page : https://docs.astro.build/en/guides/cms/strapi/

Currently the content of the .env file is:

```env
STRAPI_URL="http://127.0.0.1:1337" // or use your IP address
```

but if you copy this naively, it will actually append the "// or use your IP address" to your URL, because "//" is not the correct comment starter for .env files.

To fix this, the correct comment starter should be "#"

```env
STRAPI_URL="http://127.0.0.1:1337" # or use your IP address
```

**Comment by TheOtterlord** [comment]
Good catch! Feel free to open a PR to fix this
