### ISSUE TITLE
V5 migration guide and Astro Container API documentation improvement

### ISSUE THREAD

**Issue by xsynaptic** [withastro/docs#9452]
### 📚 Subject area/topic

V5 migration guide and Astro Container API

### 📋 Page(s) affected (or suggested, for new content)

https://5-0-0-beta.docs.astro.build/en/guides/upgrade-to/v5/
https://5-0-0-beta.docs.astro.build/en/reference/container-reference/

### 📋 Description of content that is out-of-date or incorrect

The migration guide mentions that the MDX integration now handles JSX directly but does not cover changes to the Astro Container API that result.
Similarly, the Astro Container API docs are not updated for 5.0.
Additionally, the "edit this" link on the migration guide points to the v4 guide.

I've already submitted a PR with these changes but was asked to open an issue here. For reference:
https://github.com/withastro/docs/pull/9445

**Comment by sarah11918** [comment]
Thank you! This issue didn't automatically close with the mentioned PR as it wasn't linked there, but that should close this issue! Again, thank you for bringing it up and submitting a fix! :raised_hands:
