### ISSUE TITLE
⚠️ Issue

### ISSUE THREAD

**Issue by Geezt435** [withastro/docs#9500]
https://docs.astro.build/en/reference/errors/collection-does-not-exist-error/

Directory already exist but still errors showing The collection "post" does not exist or is empty. Ensure a collection directory with this name exists.

**Comment by sarah11918** [comment]
Hi! If you are having issues with your Astro project, then you can get support in our Discord channel https://astro.build.chat

This repo is only for reporting issues with our documentation, and we can't help with individual projects here. But people are happy to help on Discord!
