### ISSUE TITLE
Package not recognized as official despite being listed in astro integrations

### ISSUE THREAD

**Issue by Celinesco** [withastro/docs#9551]
### 📚 Subject area/topic

Inconsistency between the CLI message and the integrations website.

### 📋 Page(s) affected (or suggested, for new content)

A message in the CLI is inconsistent with the information on the [web site](https://astro.build/integrations/)

### 📋 Description of content that is out-of-date or incorrect

![Screenshot from 2024-10-03 17-08-46](https://github.com/user-attachments/assets/daae6620-c921-4070-a439-13d7e397af47)

I received the following message in the console when trying to use the package `astro-icon` with `npx astro add astro-icon`
_astro-icon is not an officil Astro package._ 
And then the link to check the officil integrations: https://astro.build/integrations

However, when I visit the link provided, `astro-icon` is listed as an official integration. 

I tried to find where the code responsible for this is located so I could contribute, but I got overwhelmed, sorry!

**Comment by ArmandPhilippot** [comment]
I think there is some confusion about the [Integrations](https://astro.build/integrations) page. The integrations listed on this page are not necessarily official. If you want to see only official integrations, you have to use the filters: https://astro.build/integrations/?search=&categories%5B%5D=official Once `Official` is checked, `astro-icon` no longer appears.

So I don't see any inconsistency between the two: `astro-icon` is not an official integration.

That said, whether the integration is official or not, in the case of `astro-icon` I can only recommend it personally!

**Comment by Celinesco** [comment]
AHH I see. Then I'm closing this. Thank you!
