### ISSUE TITLE
Add mention of `mode: 'md'` in astro.config.js docs

### ISSUE THREAD

**Issue by crutchcorn** [withastro/docs#960]
While MDX is the default processor of Markdown files in Astro, there are instances where it interacts with behavior from typical Markdown processing. For example, I want to be able to assign a custom ID to headers using the following syntax:

```
# Header {#id}
```

[Using a custom rehype plugin I wrote](https://github.com/unicorn-utterances/rehype-slug-custom-id), but cannot do so using the default Astro MDX markdown processor.

As such, `astro.config.js` seems to expose a `mode` flag (which is missing a TypeScript definition) that works like so:

```
export default defineConfig({ 
  markdown: {
    mode: 'md',
  }
});
```

Which solves my issues with MDX processing.

I'm happy to make a PR to introduce this into our documentation.

**Comment by delucis** [comment]
Thanks for the issue @crutchcorn! I’ve labelled this “tsc” so we can get some input from the core team on whether this is something we _should_ be documenting. Once we have that, we can decide what to do.

**Comment by sarah11918** [comment]
It looks like this has been added upstream: https://github.com/withastro/docs/pull/977! Yay! Thanks @crutchcorn !
