### ISSUE TITLE
Add an example using Actions to the Insert section in the AstroDB docs

### ISSUE THREAD

**Issue by jwdallas** [withastro/docs#9635]
### 📚 Subject area/topic

AstroDB

### 📋 Suggested page

https://docs.astro.build/en/guides/astro-db/#insert

### 📋 General description or bullet points (if proposing new content)

Please extend or modify the section titled “Insert” in the AstroDB docs to include an example using the new Actions feature.

There is a [brief discussion](https://discord.com/channels/830184174198718474/853350631389265940/1293838226523684906) about this on Discord:
* @JusticeMatthew says "API endpoint" example code under the "INSERT" header shows a DELETE endpoint. ([Link](https://discord.com/channels/830184174198718474/853350631389265940/1293935723384275025))
* @JusticeMatthew provides some rough sample code that they say should be double checked. ([Link](https://discord.com/channels/830184174198718474/853350631389265940/1293939022036471889))

**Comment by casungo** [comment]
The suggested extension was added to the PR #9509.
