### ISSUE TITLE
Integration page asides

### ISSUE THREAD

**Issue by delucis** [withastro/docs#967]
Here’s something that I didn’t get to while working on #954 that would be cool to add to the integration READMEs workflow.

The READMEs currently use a mix of styles for tips and warnings using blockquotes as is common on GitHub. I would like to see these standardised to [GitHub’s new syntax for notes and warnings](https://github.com/github-community/community/discussions/16925):

```md
> **Note**
> This is a note

> **Warning**
> This is a warning
```

> **Note**
> This is a note

> **Warning**
> This is a warning

**THEN** I would like to add a remark plugin to our processing pipeline here:

https://github.com/withastro/docs/blob/2c93d8ff0615ac11a6ddcc0b009636c166530fe0/scripts/generate-integration-pages.ts#L73-L77

That finds that syntax and converts it to:

```md
:::note
This is a note
:::

:::caution
This is a warning
:::
```

**Comment by sarah11918** [comment]
@delucis If we plan to move much content OUT of the READMEs and into Docs itself, then what's the priority on this, do you feel?

**Comment by delucis** [comment]
Depends if we're still using asides in the shorter READMEs or not. I think someone mentioned some things staying README-focused (like Tailwind & Partytown) but if those are the only ones that's one warning instance I can spot currently.

Not _high_ priority I'd say.

**Comment by sarah11918** [comment]
And, if we NO LONGER IMPORT the content from the READMEs (still an "if" at this point), but instead just link to them in Docs... then we just standardize those README.md files with GitHub aside notation as necessary (whatever remains) but wouldn't need a plugin for docs?

**Comment by Lofty-Brambles** [comment]
Was there any consensus on this issue? Standardizing would be quick PR to do :)

**Comment by delucis** [comment]
As it stands currently, we would still need a custom remark plugin that maps GitHub's syntax to our custom aside syntax. Would love a PR for that if you think it's straightforward!
