### ISSUE TITLE
Existing Astro + Lucia integration link now points to a 404 page

### ISSUE THREAD

**Issue by User5842** [withastro/docs#9858]
### 📚 Subject area/topic

Astro Authentication Documentation

### 📋 Page(s) affected (or suggested, for new content)

https://docs.astro.build/en/guides/authentication/

### 📋 Description of content that is out-of-date or incorrect

Lucia is now a learning resource for implementing authentication from scratch, and framework-specific implementations have been removed after version 3.

Underneath the configuration section (https://docs.astro.build/en/guides/authentication/#configuration), the link to Lucia now renders a 404 page and has since been moved to https://v3.lucia-auth.com/getting-started/astro.

**Comment by sarah11918** [comment]
Hi @User5842, thank you for bringing this to our attention! We've actually had this on our list to tackle, and there's a PR ready to merge now. I've updated the PR so that it will close this issue for us. :rocket:
