### ISSUE TITLE
Add “deep dive” guide to how Astro works technically

### ISSUE THREAD

**Issue by delucis** [withastro/docs#986]
- What is the `<astro-island>` element?
- Why do we inline some scripts?
- How does bundling work?
- etc.

Probably fits into the “Explanation” quadrant if we’re thinking with the diátaxis model in mind: provides theoretical background information in a friendly tone (https://diataxis.fr/explanation/).

**Comment by sarah11918** [comment]
I *suspect* this is going to be on @FredKSchott 's (not @fredkbot ! I have to be careful now!) list to tackle, either as part of, or follow up to #893 .

**Comment by FredKSchott** [comment]
Yes!

**Comment by wassfila** [comment]
(-)
* Many hardly get through the external API doc or even use its search feature, they don't care about the internals.
* Now some percentage (gut feeling less than 5%) want to reuse Astro in custom way
* explaining Astro needs to explain Vite, need to explain Rollup, need to explain npm packaging,...

(+)
* I think the Astro team, dev, support, contributors would highly appreciate this
* I took me ages to differenciate build flow from runtime flow
* when does my plugin run ?
* why do I run SSR while my imports are fixed on build step ?
(+)
These non-intuitive points could have some dataflow diagrams that triggers aha on first view. These diagrams have ROI when core team explains Astro in conferences or interviews, also when projecting the future of Astro.

**Comment by delucis** [comment]
We suspect this is not going to happen any time so soon, so will close for now.
