### ISSUE TITLE
astro:env docs should explain which environment variables are captured at build vs runtime

### ISSUE THREAD

**Issue by jyasskin** [withastro/docs#9865]
### 📚 Subject area/topic

environment variables

### 📋 Suggested page

https://5-0-0-beta.docs.astro.build/en/guides/environment-variables/#type-safe-environment-variables

### 📋 General description or bullet points (if proposing new content)

Some values for `context` and `access` result in the environment variable being checked and captured at build time, while other values cause the environment variable to only be read at runtime. The documentation should say which is which.

**Comment by sarah11918** [comment]
@florian-lefebvre  would you be able to comment on this? Is there an improvement we can make to the docs about this?

**Comment by florian-lefebvre** [comment]
In my opinion, we already talk about this [in this section](https://5-0-0-beta.docs.astro.build/en/guides/environment-variables/#variable-types) but maybe we emphasize or clarify it?

**Comment by sarah11918** [comment]
I think that's fine, it's explained! Thank you Florian!
