### ISSUE TITLE
Document how to escape curly braces in Markdown

### ISSUE THREAD

**Issue by hippotastic** [withastro/docs#987]
We currently don't document how to prevent a text like `{some content}` inside a Markdown file from being treated as a JS expression.

It ~~works~~ should work by replacing the opening brace with its HTML entity: `&#123;`

I think we should document this in our Markdown section.

**Comment by delucis** [comment]
Thanks @hippotastic!

I’m adding this section now, but it looks like it doesn’t work 😞 

Adding `&#123;` errors with `ReferenceError: variable$$render is not defined` from the default export of the Markdown file.

**Comment by hippotastic** [comment]
I guess this warrants creating a new bug in the main repo then! I'm gonna head over there and create one. 😅

**Comment by delucis** [comment]
Thanks!

I can write this code block without any problems

````md
```markdown
&#123;curly
```
````

But using the entity in a paragraph or whatever breaks:

```md
Escaped &#123;curly}
```

**Comment by delucis** [comment]
Aaaaand, same goes for `&lt;`:

```
error: Cannot read property 'exports' of undefined
```

**Comment by hippotastic** [comment]
What should work is escaping it like this: `{'&#123;'}`

But of course that doesn't look very pretty and I would advise not documenting this and fixing it instead.

**Comment by sarah11918** [comment]
Given that we are NOT documenting @hippotastic 's LOVELY workaround... 

Do we close this issue? OR do we put an issue in Troubleshooting? I know it came up on Discord recently, but I'm not sure how *much* of an issue this is. And, if we fix it... then we have to go take this out...

Close? What do we think?

**Comment by hippotastic** [comment]
I'd say we wait until it's fixed and *then* document it! 😄

**Comment by delucis** [comment]
Yup! https://github.com/withastro/docs/pull/993 should be good to go once this is fixed.

**Comment by delucis** [comment]
Will merge #993 to close this once we’ve upgraded to the RC release of Astro!
