### ISSUE TITLE
Add note about Netlify Functions

### ISSUE THREAD

**Issue by delucis** [withastro/docs#988]
A Netlify user was confused how "Netlify Background Functions" worked in Astro

The answer was: "just follow the netlify docs" (aka use a `netlify` folder in your repo) but it wasn't clear that this would work natively in Astro. 

It would be nice to add a mention to our integration guide/readme about how the `netlify` folder works, and that you can just use it as expected!

**Comment by FredKSchott** [comment]
@delucis I just realized that Netlify has a blog post about this! 

https://www.netlify.com/blog/deploy-an-astro-site-with-forms-serverless-functions-and-redirects/

I think this is all we'd need to link to in the integration readme. Actually, I bet each integration could have a "links" section at the bottom, that links out to relevant off-site tutorials and guides on how to use the integration!
