### ISSUE TITLE
Mention that navigation uses the standard `a` element in Astro

### ISSUE THREAD

**Issue by delucis** [withastro/docs#992]
**Why?** A user was unclear how to link to another page in Astro

- Usually because React/next.js make this confusing with `<Link>` element
- Could use a small callout that you can use `<a>` elements directly

   SvelteKit has this (https://kit.svelte.dev/docs/routing#pages):

   > Note that SvelteKit uses `<a>` elements to navigate between routes, rather than a framework-specific `<Link>` component.

#### To discuss

Where should this go? SvelteKit mentions this in the “Pages” section of their Routing guide. Our routing guide is much more concerned with the logic behind file-based routing, `getStaticPaths` etc. Maybe on “Pages”? On first glance I don’t see the best spot for it. Maybe we need a separate subheading although it would be a fairly short section.

```md
## Navigating between pages

Astro uses standard HTML [`<a>` elements](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a) to navigate between routes, rather than a framework-specific `<Link>` component.
```

**Comment by kevinzunigacuellar** [comment]
I like the [Next.js](https://nextjs.org/docs/routing/introduction#linking-between-pages) approach to this inside Routing. Maybe a section after dynamic routes and before Route Priority Order?

**Comment by kevinzunigacuellar** [comment]
I don't see why it shouldn't be in both sections. I remember hearing about duplicating content in the tailwindcss docs. It makes sense to duplicate content when users might be drawn to either of these sections to find some information about `<links>`
