### ISSUE TITLE
Mark Lucia Auth as deprecated

### ISSUE THREAD

**Issue by Ladvace** [withastro/docs#9965]
### 📋 Explain your issue

I came across this Lucia auth announcement where the author announces the deprecation of the library by March 2025.

https://github.com/lucia-auth/lucia/discussions/1714

It would be better to either remove the Lucia auth solution section or to mark it as deprecated:

https://docs.astro.build/en/guides/authentication/#lucia

**Comment by sarah11918** [comment]
Hi @Ladvace ! We have updated our Lucia auth on the guide page in keeping with the announcement! Lucia is no longer an auth tool, but *is* still very much an auth resource. They are switching from being a solution to being a resource for implementing auth yourself. That is why our content now links to their available guides, as Lucia can still be helpful for those implementing authentication.

So I'll close this issue as we've handled this. Thanks for coming to make the docs better! 🚀
