### ISSUE TITLE
The example for transition:animate:"none" does not work as advertised

### ISSUE THREAD

**Issue by martrapp** [withastro/docs#9977]
### 📚 Subject area/topic

View Transitions

### 📋 Page(s) affected (or suggested, for new content)

https://docs.astro.build/en/guides/view-transitions/#built-in-animation-directives

### 📋 Description of content that is out-of-date or incorrect

`transition:animate` will only work on the root element if it's used within a component that's shared across all pages.

The simplest solution is to use a common layout, here is the most minimal version:
```
---
// Layout.astro
---
<html transition:animate="none">
  <slot />
</html>
```

https://discord.com/channels/830184174198718474/1305515717101359104

### 🖥️ Reproduction in StackBlitz (if reporting incorrect content or code samples)

here is a Stackblitz for the example from the support thread
https://stackblitz.com/edit/withastro-astro-emfhs5?file=src%2Fpages%2Findex.astro
not been able to turn off transitions in this example is inherent to Astro's approach and can not really be repaired.  

The fix in docs would be to use transition:animate="none" only in a layout, not directly on the `<html>` element of a layout-less `.astro` file. (this adds complexity to the example, but currently it is simply wrong)

**Comment by martrapp** [comment]
This is a complicated edge case: The problem exists only for the toplevel `<html>` element if used directly in a .astro file. Typically we suggest common layout components. Then the problem does not surface. 

Running the stackblitz produces two transition groups on naviagation as Astro auto-generates two different scope names for the two pages:
![image](https://github.com/user-attachments/assets/cef2dd92-e81f-4acd-b08f-31694ebc1c0d)
The CSS rules for the astro... scopes are defined on the old page only and unknown on the new page. Therefore the browser generates a `root` group for the unknown scope. resulting in two groups: The astro group with disabled animations and the root group with default 250ms fade.

Using transition:animate in a component defines the same scope name on the old an new page and thus the required CSS is present on both pages. Now there is only one Astro generated group and the animations are disabled. No browser generated `root` group with default fade.

**Comment by sarah11918** [comment]
Hey @martrapp , thank you for noticing and letting us know!

I mean, normally I'd be asking *you* for advice on how to proceed in this case. 😅 Would you like to make a PR with your best judgement on what to show? This could include:

- updating the existing example to be accurate (hopefully without being extremely complicated)
- choosing an entirely different example to demonstrate whatever concept this was intending to demonstrate (something hopefully kind of simple)
- removing the example entirely so it's at least not wrong

I really would trust your judgement here! What do you think?

**Comment by martrapp** [comment]
Hi @sarah11918, normally I'd just correct the docs 😅

But in this particular case I was quite unsure what would be best for docs, pondering the alternatives you named.

I'll come up with a suggestion and as usual trust that you come to the rescue ;-)
