### ISSUE TITLE
Bug in code example on mdx page

### ISSUE THREAD

**Issue by redexp** [withastro/docs#9985]
### 📝 Issue Description

Good day

There code
```astro
---
const matches = await import.meta.glob('./posts/*.mdx', { eager: true });
const posts = Object.values(posts);
---

{posts.map(post => <p>{post.title}</p>)}
```
As you can see bug in line `const posts = Object.values(posts);`

### 📋 On which page(s) it occurs

https://docs.astro.build/en/guides/integrations-guide/mdx/#using-exported-variables-in-mdx

### 🤔 Expected Behavior

```astro
---
const matches = await import.meta.glob('./posts/*.mdx', { eager: true });
const posts = Object.values(matches);
---

{posts.map(post => <p>{post.title}</p>)}
```

### 👀 Current Behavior

```astro
---
const matches = await import.meta.glob('./posts/*.mdx', { eager: true });
const posts = Object.values(posts);
---

{posts.map(post => <p>{post.title}</p>)}
```

### 🖥️ Browser

Chrome 130

**Comment by apatel369** [comment]
@redexp Nice catch! Thanks for reporting this issue. Would you like to create a PR to fix it? It's a simple fix, and we'd love to have your contribution. Here is the [guide](https://contribute.docs.astro.build/first-time/edit-single-page/) to help you get started. If you have any questions or need assistance, feel free to ask. We're here to help!

**Comment by sarah11918** [comment]
Hi @redexp ! Just also adding another thank you for reporting this!

As we are very close to "closing off" our v4 docs and putting them in maintenance in favour of preparing our v5 docs, we would love to have this fix added soon if you are still available to make a PR! It would be nice to not have to live with this error for ever and ever! 😅 

So just checking in on whether you would still like to make a PR, or whether you would like someone else to fix this! We would love your contribution if you're still willing.

**Comment by apatel369** [comment]
Thank you @sarah11918 for your follow-up. Since I'm not sure if @redexp  is still interested in creating a PR, I will create one.

@redexp , you are still very welcome to contribute to other things in the project. We appreciate your help in identifying this issue!
